### ISSUE TITLE
Can't find backgrounds?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1010]
This one was posted by a teacher to BJC TEACHERS on Piazza: "I click on the Stage sprite, click File, Backgrounds ... and no options appear. Before we were able to get the X,Y grid and others as options. Not sure how to get them back?"

**Comment by maryfries** [comment]
I flush my cache several times a day, and I'm having the same problem.

I just flushed again, and still no backgrounds... Can you reopen this? (I can't.)

**Comment by jmoenig** [comment]
I fixed it just now. Sorry! I was having permission issues yesterday, and somehow that particular new file didn't get transferred. Now it is and everybody should be able to get the backgrounds again, even without flushing the cache.

**Comment by maryfries** [comment]
Yes, working now! Thanks, Jens!!
