### ISSUE TITLE
Snap Sound Tapering

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1015]
It would be nice if Snap would automatically fade out the edges (start and end) of any sounds played so that scripts like this don’t click between each note: for (i) = (50) to (80) [play note (i) for (0.25) beats]

**Comment by brianharvey** [comment]
Good point.  We should get someone, not Jens, to work on sounds altogether.

**Comment by jmoenig** [comment]
done! In Snap5. It only took a couple of years :-)
