### ISSUE TITLE
code can be attached below forever loop

### ISSUE THREAD

**Issue by wortzmanb** [jmoenig/Snap#1029]
When a forever loop has a block preceding it, it becomes possible to attach the forever above another block, producing something like:
![download](https://cloud.githubusercontent.com/assets/8575915/11382204/6f19c1b8-92b5-11e5-8811-663dcec0c926.png)

This only occurs when there is code preceding the forever, and the attachment is only possible one way.  (i.e. you can attach the forever above another block, but cannot attach another block below the forever)

**Comment by jmoenig** [comment]
Good catch!

**Comment by cycomachead** [comment]
Heh, I always just assumed this was a known edge case! :P

**Comment by bromagosa** [comment]
This has been fixed at some point.
