### ISSUE TITLE
Chrome 47 : Moving the mouse while holding the mouse button down keeps Canvas from redrawing

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap#1055]
I'm noticing this in the latest Chrome 47.0.2526.73 (64-bit) on Mac El Capitan 10.11.1 on both of my Mac laptops and on Windows 10 when either dragging anything for a longer time or when drawing something in the paint editor. The World Canvas almost never updates while the mouse button is held down, but it still gets all the events, because after a while - or when the mouse button is released - all the intermediate vertices are drawn in the paint editor.

Before I try to isolate the issue and file a bug report, is anybody else experiencing the same issue? Did anybody check with the latest Chrome Canary nightly build, whether it's still around there?

Thanks!

**Comment by cycomachead** [comment]
I tried a 
```
Pen down
Forever
    Go to (random) (random)
```
Loop, and then held and dragged some scripts around and the stage was still updating.

Would that show the bug? I was using Chrome Canary, so maybe it was fixed?

**Comment by jmoenig** [comment]
Thanks, hmm... yes, that should show the bug.
Here's my little test case:

![script](https://cloud.githubusercontent.com/assets/2596285/11652920/c8753a86-9d9a-11e5-9279-602df56ac1d9.png)

run this script and while it is running, hold down the mouse button and move the mouse around over Snap. For me the sprite stops moving while the mouse button is down and the mouse moves. And this happens in Chrome on either of my laptops and also on Windows 10. It's really irritating. Maybe I should try Canary.

**Comment by jmoenig** [comment]
It's also regardless of any recent changes in Snap. I've tested some really old versions and the same happens there. In current Chrome.

**Comment by cycomachead** [comment]
Nope, can't reproduce it. Chrome 44 and 49

**Comment by jmoenig** [comment]
Strange. I just installed Canary, and everything is okay in there. Seems to be just v47.
Geez, are we really going to trust browser-makers with driving our cars?

**Comment by jmoenig** [comment]
Canary (Chrom 49) doesn't have this issue on my Mac, but on Windows 10 it still has it.
I hate Google!

**Comment by liam4** [comment]
I hate computers! No matter what you do, they always have a problem! We should go back to using tally sticks! :P

**Comment by jmoenig** [comment]
so, this has even been coming up on Chrome Canary 49 lately for me, on all my computers and both on Windows and Mac. But only on Chrome, not in other browsers. Also, only in Snap's current "mad-clock" scheduling mode. If I run snap_slo.html which uses HTML5 animation frames Chrome runs and reacts fine all the time. Oh, cripes! I'm smelling a setup in which they force us to switch to animation frames, something I've been trying to avoid for now, because there's so much about that sucks!!

**Comment by liam4** [comment]
Citation needed? What's so bad about animation frames? I use them all the time!

**Comment by jmoenig** [comment]
* animation frames slow down Snap's regular dynamic scheduling mode significantly, most fractals render *much* much slower. It doesn't affect WARP or TURBO mode, naturally
* the browser suspends animation frames whenever the browser / browser tab is not in front. You can no longer keep a Snap project running in the background while working on something else (for example render a big fractal while reading your mail)

Play with it yourself: there's a version with animation frames online, just change ```snap.html``` in the url bar to ```snap_slo```.html

Let me know what you think!

**Comment by jmoenig** [comment]
can you reproduce the issue that Chrome often doesn't redraw the canvas while moving the mouse with the button is pressed?

**Comment by jmoenig** [comment]
worked around in f24b65f67379fd6b783b07ff220a8794a1aae79d

**Comment by gdavid04** [comment]
Cannot reproduce in Chrome 66.0.3359.181 - 64 bit - MacOS
