### ISSUE TITLE
"Extract" Command For Commands in Scripts

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#1070]
In a script I'd like to do the extract a command block from the script:

```
When %gf clicked
Say ...
Move ...
Repeat ...
...
```

So, I should be able to right click on a command block, like `move` and click "extract"
`move` would then be picked-up by the cursor and the script would become:

```
When %gf clicked
Say ...
Repeat ...
....
```

**Comment by liam4** [comment]
Oh, this sounds useful. Perhaps a setting or something so that you can shift (alt?) drag on the block to work the same way without the need of using the context menu? (Though the context menu would still be there with the extract option of course.)

**Comment by cycomachead** [comment]
Somewhere along the lines this was done. :)
