### ISSUE TITLE
Go back n layers, tiny misfeature if n > max possible

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1089]
Actually I'm not sure if it's a misfeature, maybe it's a bug, since I think it does what I want in Scratch:  If you say "go back 999 layers" the sprite goes as far back as possible.  In Snap! nothing happens.

**Comment by liam4** [comment]
That's probably just a misfeature, but it might just be better to make the number input to a dropdown and add an option "all", i.e. `go back (all v) layers`.

**Comment by jmoenig** [comment]
excellent suggestion, @liam4 !

**Comment by liam4** [comment]
Plus it wouldn't break old projects, unlike `go to [front/back v]` because of adding an input.

**Comment by jmoenig** [comment]
done!
