### ISSUE TITLE
Add ⬏ arrow to looping blocks

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1091]
Please add Scratch-style right arrow with tip upward ⬏ to repeat blocks and add a checkbox to long form dialog when C-slot is chosen.

(Yeah, you can type in the character, but it's not right adjusted and the bottom leg is too tall.)
![foo](https://cloud.githubusercontent.com/assets/3885074/12069462/e80afcd4-afe5-11e5-87e8-6b72d57da73c.png)
We've talked about this but I'm adding it to the github collection.

**Comment by jmoenig** [comment]
done!
