### ISSUE TITLE
image clipping when imported costumes are different sizes

### ISSUE THREAD

**Issue by alloplastic** [jmoenig/Snap#110]
Minor glitch... When the attached images (rename .jpg to .zip and unpack) are all dragged into the costumes pane of a sprite and then animated sequentially, the head of the character gets clipped on some frames.

I'm guessing that this is because the slicing tool I used created images of different heights.

![image_clipping_sample](https://f.cloud.github.com/assets/4890109/915000/67220f72-fe58-11e2-86de-3fdd7c81d874.jpg)

**Comment by schwonko** [comment]
issue should be fixed. it seems to me, when importing some Images of same size to build a sprite sequence, Images are clipped to its individuell real content (clipping away surrunding empty Pixels), resulting in some unwanted auto-zooming when play back the Images of the sprite. This is really ugly.

**Comment by bromagosa** [comment]
I've just tested importing these and animating them. No issue whatsoever now :)
