### ISSUE TITLE
relabel "join" to "join words"

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1104]
this was feedback on BJC: it would be great if in snap you can relabel "join" to "join words"

**Comment by jmoenig** [comment]
this is something to keep in mind for 4.1. Currently there is no way to relabel a primitive ("join") to a custom block ("join words").

**Comment by cycomachead** [comment]
I like this idea, but we should be weary of what might happen when users see relabel `join` with `join words` and `list thing` and... 

Not that this is a bad idea -- essentially this gives us automatic relabel suggestions, which we already basically have. However, we then need to be careful with things like C shaped inputs.

**Comment by brianharvey** [comment]
I'm confused.  What is the problem you're wary of?  This is just a single suggestion about one relabelling.  Of course Jens is right that this will be easier in 4.1.

**Comment by cycomachead** [comment]
> I'm confused. What is the problem you're wary of?

I'm worried that (depending on the way this is done) we end up with primitives that can be relabeled to a dozen different blocks.

Unless you're suggesting 4.1 includes the whole meta-control-snap-in-snap-shebang, it seems like this kind of relabeling would be done automatically? I'm thinking of similar to how custom blocks can currently be relabeled. 

If it's the first case, well then I guess eventually that will happen, but it seems like all this is really beyond OOP and what BYOB 3.1.

**Comment by brianharvey** [comment]
I don't think there's anything automatic about relabeling of primitives.  The equivalence classes are explicit in the code.  This would just be adding one more case.  What's special about 4.1 is partly overloading, but more immediately relevant is that we hope to have tools as primitives by then.
