### ISSUE TITLE
proxied HTTP

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1161]
I understand that there was considerable trouble with the proxied HTTP block in NYC on 3/5/16 and that Brian was able to fix things to a status of "mostly better" but that the issue is not fully resolved.

Today, Brian said: "Not resolved.  Not understood, at least not by me."

I asked for more info on Piazza as there was a post about it.

Anyone else know anything?

**Comment by maryfries** [comment]
Update from conversation with Brian:
 
different problems:
error message: 505, page not accessible.
some people get null strings back.
for some people, the block just runs forever.

other thoughts:
sometimes it works; sometimes doesn't; depends on site
perhaps www.weatherstreet.com has changed their site?
but works for some people and not others...

**Comment by cycomachead** [comment]
I don't think the proxied http block is a Snap<em>!</em> issue. What's the domain in the proxy block? 
(Both the proxy server and the regular webpage.)

**Comment by maryfries** [comment]
Another note from the Saturday PD: 
Proxied http:// works in some browsers and not in others

**Comment by eprebys** [comment]
I am not experienced enough with this stuff to really understand the bug. I can report that on Chrome Version 54.0.2840.98 (64-bit) on OSX, I am getting the following error for Proxied HTTP for all requests. I am running on my home network.

threads.js:2135 GET http://alloworigin.com/get?url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv Process.reportURL @ threads.js:2135Process.evaluateBlock @ threads.js:665Process.evaluateContext @ threads.js:634Process.runStep @ threads.js:551(anonymous function) @ threads.js:300ThreadManager.step @ threads.js:298StageMorph.step @ objects.js:5500Morph.stepFrame @ morphic.js:2734(anonymous function) @ morphic.js:2736Morph.stepFrame @ morphic.js:2735(anonymous function) @ morphic.js:2736Morph.stepFrame @ morphic.js:2735WorldMorph.doOneCycle @ morphic.js:10823loop @ snap.html:33
snap.html#:1 XMLHttpRequest cannot load http://alloworigin.com/get?url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://snap.berkeley.edu' is therefore not allowed access. The response had HTTP status code 404.


Here are the headers, as parsed by Chrome:
Request URL:http://alloworigin.com/get?url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv
Request Method:GET
Status Code:404 Not Found
Remote Address:104.24.98.48:80
Response Headers
view source
CF-Cache-Status:HIT
CF-RAY:307f110041e15576-ORD
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html
Date:Sat, 26 Nov 2016 17:30:06 GMT
Server:cloudflare-nginx
Set-Cookie:__cfduid=dc0a734a936888e2aee926a7d24ec84b21480181406; expires=Sun, 26-Nov-17 17:30:06 GMT; path=/; domain=.alloworigin.com; HttpOnly
Transfer-Encoding:chunked
Vary:Accept-Encoding
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
Connection:keep-alive
Host:alloworigin.com
Origin:http://snap.berkeley.edu
Referer:http://snap.berkeley.edu/snapsource/snap.html
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Query String Parameters
view source
view URL encoded
url:http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv



And here are the unparsed headers:
Request URL:http://alloworigin.com/get?url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv
Request Method:GET
Status Code:404 Not Found
Remote Address:104.24.98.48:80
Response Headers
view parsed
HTTP/1.1 404 Not Found
Date: Sat, 26 Nov 2016 17:30:06 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dc0a734a936888e2aee926a7d24ec84b21480181406; expires=Sun, 26-Nov-17 17:30:06 GMT; path=/; domain=.alloworigin.com; HttpOnly
Vary: Accept-Encoding
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 307f110041e15576-ORD
Content-Encoding: gzip
Request Headers
view parsed
GET /get?url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv HTTP/1.1
Host: alloworigin.com
Connection: keep-alive
Origin: http://snap.berkeley.edu
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Accept: */*
Referer: http://snap.berkeley.edu/snapsource/snap.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
Query String Parameters
view parsed
url=http://bjc.edc.org/bjc-r/cur/programming/4-internet/2-gps-data/GPS-NYC.csv
