### ISSUE TITLE
"Import tools" crashes Firefox?

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1194]
One of the teachers in our workshop reports that Import Tools crashes Firefox but not Chrome on his machine.  It happens consistently.  I'll try to find out what version he's using and follow up.

**Comment by jmoenig** [comment]
Works for me in Firefox on my Macs and even on my Windows StickPC...

**Comment by liam4** [comment]
Works for me in Firefox on my iMac 2013. I'm running Nightly 49.

**Comment by cycomachead** [comment]
Also, what does crash mean -- like the whole browser closes or the page refreshes?

**Comment by joefarebrother** [comment]
On my firefox it works with a blank project, but crashes when I have a (fairly complex) project already open.

My workaround is to only import the libraries I need without importing the entire tool library. But one time I couldn't find the block I was looking for so I opened a blank project to import the tools, then exported the blocks I wanted and imported them to my project.

**Comment by jmoenig** [comment]
Since we've eliminated the tools library for Snap5, this is one less issue to worry about :-)
