### ISSUE TITLE
Repeat until keypress with wait does not work as expected

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1195]
Here's an example of the problem:

![image](https://cloud.githubusercontent.com/assets/6549787/14922537/20e49618-0e06-11e6-8713-bf2e8b992b89.png)

If you press any key, the script does not stop because of the wait in the say block, thought that's the expected and intended behavior.

(This came up with a decryption script that was iterating through various keys; the user is supposed to press any key when they see a comprehensible translation, and this together with current key is reported back.)

Pressing **and holding** a key works, but that's not what is expected.

What we (Paul and I) think should happen is that Snap! should keep track of whether an event has occurred and then stop the script at the end of the repeat until subscript whether or not the event (e.g. key press) is still happening at that time.

**Comment by jmoenig** [comment]
Oh, wow. We need to talk. What makes you assume a predicate could be an event?
