### ISSUE TITLE
Stage size

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap#1224]
Hello,

Is it possible to recover stage size (x, and y) in variables ?
Thank you.

**Comment by joefarebrother** [comment]
I think you can use the JavaScript function block to get it

**Comment by nathalierun** [comment]
Which one ?
I am not a developer and don't know very well javascript.

**Comment by bromagosa** [comment]
These should do the trick:

![image](https://cloud.githubusercontent.com/assets/1016697/15465559/607c13dc-20d5-11e6-9825-3c64ec512348.png)

Best would be to add these as custom blocks, of course :)

**Comment by bromagosa** [comment]
Actually, I believe this is a bit more elegant, now that we have the ``(my [stage])`` block:

![image](https://cloud.githubusercontent.com/assets/1016697/15465621/c66bc7e6-20d5-11e6-866b-78154c0a9e8b.png)

**Comment by liam4** [comment]
What if you resize the stage? Resizing the stage zooms all of its contents (besides watchers, which don't behave like sprites, for whatever reason) so if perhaps you're trying to work on a layout getting the `stage.width()` won't work.

Or maybe you're trying to get the player to zoom in, in which case `stage.width()` *is* what you're looking for..

If you *really* wanted to you could always use the `JavaScript function` block to resize the stage automatically! ;)

**Comment by nathalierun** [comment]
None of those javascript functions work on my computer.

I have a macbookpro under Snow 10.6.8, with Firefox 46.0.1

**Comment by bromagosa** [comment]
That's strange, they should both work... are you sure you copied it exactly like I pasted it?

Anyway, here's another version ready for you to import into your project:

[stage width height.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/279259/stage.width.height.zip)

**Comment by nathalierun** [comment]
Hello,

Here is my implementation :
![capture du 2016-05-25 09 04 26](https://cloud.githubusercontent.com/assets/17542520/15528827/d0269dae-2258-11e6-9e73-41fd17861bca.png)

And this morning, I work on Linux (Ubuntu 14.04) with Firefox 44.0.2

But your little script works. Thanks a lot.

**Comment by bromagosa** [comment]
Notice how you're missing ``()`` after ``width`` and ``height`` :)

These parentheses are function calls, so if you don't add them you're returning the function itself, not the result of calling it.

**Comment by nathalierun** [comment]
My first trials were with () 
And it is the same...
![capture d ecran 2016-05-25 a 13 32 00](https://cloud.githubusercontent.com/assets/17542520/15535151/2534f02e-227d-11e6-8896-332241ddf318.png)

**Comment by bromagosa** [comment]
Oh, I've just spotted a second mistake, you need to unringify (right click → unringify) the green Javascript block! :)

The Javascript block is a function in itself, so it needs to be called straight away, with no surrounding rings.

**Comment by nathalierun** [comment]
It works !!!
Thanks a lot.

**Comment by kbakalar** [comment]
bromogosa's `stage width height.zip` initially returns the values of width and height from `*->stage... `, but if the stage is resized with the Resizing Buttons (SnapManual.pdf p 64) the values returned by `stage width` and `stage height` change in proportion. If  the  `*->stage... ` setting is intended to set the pixel resolution, and the resizing buttons to scale the image without changing the resolution, then this behavior is not correct.

**Comment by jmoenig** [comment]
Okay, use ```stage.dimensions``` instead

**Comment by nathalierun** [comment]
Then, I did so.
![stage2](https://cloud.githubusercontent.com/assets/17542520/21584682/76eab378-d0c8-11e6-8c54-0c8c8c1ecc72.png)

But, it does not work.
So I tried to understand why.

I tested this first :
![telechargement](https://cloud.githubusercontent.com/assets/17542520/21584749/24d7467c-d0c9-11e6-80ca-0a8d79a4177e.png)
which works correctly.

Then I did this :
![telechargement 1](https://cloud.githubusercontent.com/assets/17542520/21584756/361e0632-d0c9-11e6-88e3-6878bef86c57.png)
I tried then to understand the type of the variable a, doing this :
![telechargement 2](https://cloud.githubusercontent.com/assets/17542520/21584764/5397b1a4-d0c9-11e6-970b-951f3490a3d7.png)
And the variable a is neither a text, neither a reporter, neither nothing.

**Comment by nathalierun** [comment]
And now, I have a question.

Is there any way to fix (or modify) the stage size by a javascript function ? And how if it is ?
So the user could choose himself the dimensions stage that he wants.

I wish everybody a happy new year 2017 and a lot of energy to keep on developping Snap! ...

**Comment by brianharvey** [comment]
Load the "getters and setters for..." library and one of the options in the SETTING block is "stage size."  Similarly the SET VALUE block.  (These are in the Sensing menu.)  Note that there are minimum and maximum values outside of which the size can't be changed.

**Comment by Jonathan50** [comment]
`stage.dimensions` is an instance of `Point` instead of a string. I think you can use `stage.dimensions.x` to get the width and `stage.dimensions.y` to get the height.

**Comment by nathalierun** [comment]
@brianharvey : thanks, I got it.

**Comment by jmoenig** [comment]
we now will have reporters for this in Snap5. Thank you all, closing this....
