### ISSUE TITLE
Cursor in text not right after a minus sign

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1309]
I'm in Chrome 49.0.something, if it matters.

So, I'm typing this big comment and it has a dash in it, which I represent as two minus signs --.  (I think just one minus sign is enough to mess it up slightly, but it's plainly visible after two.)  Thereafter on the line, the vertical bar text cursor is almost but not quite a full character to the left of where the insertion point actually is.  It's very disconcerting.

I expect this is some problem about the font that Chrome is using, but I'm not sure how to test that.  I haven't done anything to change the font.

**Comment by brianharvey** [comment]
Changed the title b/c I just tried it in an input slot and the same thing happens.

**Comment by jmoenig** [comment]
Hmm.... I can't reproduce this, I can type in as many dashes / minusses as I want, but the cursor is always right...

**Comment by brianharvey** [comment]
Groan.  Just me, huh?

**Comment by bromagosa** [comment]
I think you can discard Chrome as the cause, version 49.0.2623.87 here and my cursor moves as expected too.

**Comment by jmoenig** [comment]
yep, same here with Chrome 51.0.2704.106 (64-bit)
