### ISSUE TITLE
Palette tooltips show up when not hovered over

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1311]
Sometimes Snap! gets confused about where the mouse is, and as a result, shows tooltips for custom blocks while not in the palette.  A teacher posted this movie to Piazza:
https://d1b10bmlvqabco.cloudfront.net/attach/iogthpef4ji5tp/h2tftcd9e2i5my/iqmapt7gxg01/Recording_2.mp4

I get this too, usually because I have dragged a scrollbar past the edge of the Snap! window and so Snap! thinks I still have the mouse down when I reenter the window.  Once in this situation it's kind of hard to get out again.

(By the way, for what it's worth, I don't like the tooltips.  There's a perfectly good help menu option.)

**Comment by cycomachead** [comment]
> (By the way, for what it's worth, I don't like the tooltips. There's a perfectly good help menu option.)

Don't do tooltips only show when there's no help? Or I guess that's just some convention we're following...

**Comment by cycomachead** [comment]
But otherwise, this has been there for ages; I've seen it too. I thought Nathan actually posted an issue but I can't find it.

**Comment by show0k** [comment]
For me it's one of the top annoying bug of Snap.
If an user want to inspect a big list reported by a block with a help menu, the only solution is ti save it in a variable...

**Comment by jguille2** [comment]
Hi,
@brianharvey I think this issue (video related) was fixed in  #1258.

The question about the *tooltips/help_menu* behavior is important to me too. I asked about this in #1260. I'd like to combine a good help info and (if you want) a brief popover description.

Thanks,

Joan

**Comment by jmoenig** [comment]
We've since taken out tooltips for the palette. Closing...
