### ISSUE TITLE
A sprite should be able to return the names of its costumes (as a list)

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#1321]
Why isn't "my costume names" an option? Should be easy.

<img width="312" alt="screen shot 2016-07-15 at 3 45 28 pm" src="https://cloud.githubusercontent.com/assets/2229297/16886685/be5d1d1e-4aa3-11e6-986f-4e76fa76695e.png">

**Comment by brianharvey** [comment]
I think the goal is that you should be able to say
MAP ([NAME] OF ( )) OVER (WARDROBE)
i.e. costumes will have their own set of properties, instead of treating them as properties of the sprite.  But yeah, one way or another.

**Comment by ddgarcia** [comment]
I could live with that, thanks.

**Comment by bromagosa** [comment]
@ddgarcia there is a wardrobe block in dev mode, under Looks :)

![image](https://cloud.githubusercontent.com/assets/1016697/16907755/6e4dc90c-4cc6-11e6-94a9-c12deeaa8492.png)

**Comment by cycomachead** [comment]
Yeah, but we don't have a block which is a generic `property (LIST) of (OBJECT)` block.

**Comment by brianharvey** [comment]
I think the idea is that as we expand the kinds of things that are first class, we extend the OF block to know what to show in the left pulldown when that kind of thing is dropped into the right input.

**Comment by jmoenig** [comment]
Yep, that's the idea, I agree!

**Comment by cycomachead** [comment]
> I think the idea is that as we expand the kinds of things that are first class, we extend the OF block to know what to show in the left pulldown when that kind of thing is dropped into the right input.

Yeah, I think that's come up, expect right now it's very awkward to get to that dropdown in things like a HOF or try to discover what parameters are available by just dropping in different things. (though this should probably be a separate discussion.)

**Comment by bromagosa** [comment]
Isn't this done now?

![untitled script pic](https://user-images.githubusercontent.com/1016697/50145906-e02d2500-02b2-11e9-8d3c-ff85b2932733.png)

Or, @ddgarcia, did you explicitly want to get the _names_ of the costumes?

**Comment by jmoenig** [comment]
you can use ```map``` and the ```_ of costume _``` reporter from the Pixels library with the ```name``` selector for this:
![costumes_names](https://user-images.githubusercontent.com/2596285/50157411-a15a9780-02d1-11e9-933d-cfb64e28d392.png)

**Comment by bromagosa** [comment]
Closing this then!
