### ISSUE TITLE
  Replacement role

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap#1324]

**Comment by aidiken** [comment]
![14-33 282z](https://cloud.githubusercontent.com/assets/20208703/16894168/6174b9de-4b81-11e6-8105-c230aee60a0a.png)
Do not open this role when the browser, how to change

**Comment by aidiken** [comment]
![14-33 282z](https://cloud.githubusercontent.com/assets/20208703/16894168/6174b9de-4b81-11e6-8105-c230aee60a0a.png)
Do not open this role when the browser, how to change

**Comment by jmoenig** [comment]
hmm... not sure what this was about. Closing...
