### ISSUE TITLE
Augmented Reality with Snap (request)

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#1356]
It would be great if you could do something like this in Snap!
http://ael.gatech.edu/lab/research/authoring/arspot/

**Comment by jmoenig** [comment]
Oh yes!!

**Comment by brianharvey** [comment]
Sounds like a good extension!  (Not to be built into Snap<i>!</i> itself.)

**Comment by jmoenig** [comment]
happy to report that this can now be done in the upcoming Snap5. Thanks! Closing...
