### ISSUE TITLE
set color effect doesn't work

### ISSUE THREAD

**Issue by oceank2** [jmoenig/Snap#1357]
Hi,
It seems set color effect doesn't work.
I try with different value but noting happen !
It seems  it  is the same problem with brigntness and saturation effects.
But it works well for all the other effects ( mosaic, ghost, confetti,...)
Best regards
Christophe

**Comment by oceank2** [comment]
In fact, it doen't work when the color of the sprite is black, but with a blue sprite for instance, it works !

**Comment by jmoenig** [comment]
Ah, okay, thanks we settled that!

**Comment by brianharvey** [comment]
Reopening as documentation, although I think this trips up enough people (including me sometimes) that we should think about changing the behavior (e.g., changing the color sets the hue to 50 or something).  Removing can't reproduce because it does behave just as the issue reports!

**Comment by cycomachead** [comment]
@brianharvey Is there a different between "documentation" and "help / manual" or should I consolidate them?

**Comment by brianharvey** [comment]
Umm I guess they could be consolidated.  I vote for "documentation" because in principle it also includes tutorial projects etc.
