### ISSUE TITLE
Can't write in input fields on Android

### ISSUE THREAD

**Issue by baltitenger** [jmoenig/Snap#1398]
When tried to enter some text input the keyboard shows up, but no characters appear on the screen when i type.
I have tried multiple keyboards and browsers (opera, chrome, default browser and firefox). Only firefox worked but i hate that :)
Please fix it for at least chrome.

**Comment by steveschmitt** [comment]
I have the same problem on my Android tablet, a Lenovo A10-70.  It affects the login dialog too, so it's a big problem.

I noticed that I _can_ type numbers, and that if I type a number in a field first, then I can type letters after that.  So if I want to type "hello", I have to type "4hello", then go back and delete the "4" (which is difficult on a touchscreen).

Maybe there's some weird problem with the bindings on the input boxes, or some validation code that's behind the scenes that's eating the characters.

**Comment by jmoenig** [comment]
the issue of entering text into input fields on Android has now been resolved as of https://github.com/jmoenig/Snap/tree/v5.0.6
