### ISSUE TITLE
Is it possible to know screen width and height?

### ISSUE THREAD

**Issue by introlinux** [jmoenig/Snap#1401]
I would like to adjust all elements to the size of the screen, but I would need base on the width and height variables to resize all sprites and the elements of the background.

**Comment by dekrain** [comment]
write in HTML:
```html
<canvas id="test" width="100%" height="100%"></canvas>
<script>var c = document.getElementById('test'); alert("width: "+c.width+" height: "+c.height);</script>
```

**Comment by introlinux** [comment]
And the stage? Is it possible to resize the stage using blocks?

**Comment by dekrain** [comment]
Look at the instance creation of stage handle

**Comment by jmoenig** [comment]
Snap5 gets reporters for stage dimensions and sprites' width and height. Those should address this issue. Thanks! Closing...
