### ISSUE TITLE
Call of custom variadic block with empty input list fails

### ISSUE THREAD

**Issue by MMSequeira** [jmoenig/Snap#142]
If you define the custom block
![Block definition](http://farm8.staticflickr.com/7411/9679783514_76be108815_o.png)
the call in the last "say" command of
![Script](http://farm3.staticflickr.com/2861/9679783540_274d9c7687_o.png)
will fail. Notice that this only happens for custom blocks.

The project is available at [Bug: Call to custom with empty variadic input](http://snap.berkeley.edu/snapsource/snap.html#present:Username=mmsequeira&ProjectName=Bug%3A%20Call%20to%20custom%20with%20empty%20variadic%20input).

**Comment by bromagosa** [comment]
I've just ran the project and the bug is gone after all these years. Yay! :)
