### ISSUE TITLE
Sketchpad problem

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap#1442]
Why can't board picture of the vector scratch like zoom without distortion
![0446](https://cloud.githubusercontent.com/assets/20208703/19018557/43c77a5c-8899-11e6-948e-b7473f7fdc9f.png)

**Comment by jmoenig** [comment]
you *can* import and svg as a costume: First, download the svg to your computer, then drag & drop the svg file from your computer onto Snap! Now it's an svg costume that scales losslessly.

**Comment by bromagosa** [comment]
Closing as this was a question, and got answered :)
