### ISSUE TITLE
The paint bucket bug

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap#1443]
The paint bucket board, some browsers point paint program can not move?
For example: chrome Google

![2253](https://cloud.githubusercontent.com/assets/20208703/19018605/9848a5ae-889b-11e6-8b2b-184528392f62.png)

**Comment by liam4** [comment]
The paint bucket tool works fine for me. I'm running Google Chrome 53.

**Comment by jmoenig** [comment]
This has since been fixed. Thank you! Closing...
