### ISSUE TITLE
Input Chinese solution？

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap#1445]
![2316](https://cloud.githubusercontent.com/assets/20208703/19035888/f967d108-899e-11e6-8128-5da1f1678742.png)

Solution method in say () input Chinese?

**Comment by danyoel** [comment]
It seems SNAP doesn't accept some unicode input. This is really ugly, but you can output unicode:
![image](https://cloud.githubusercontent.com/assets/9189744/19277982/80b5119c-8f90-11e6-8965-d468ceace89b.png)
![image](https://cloud.githubusercontent.com/assets/9189744/19278000/8cbebfa6-8f90-11e6-8426-d01938ec0c9e.png)

**Comment by DarDoro** [comment]
New browsers use the IME (no the plain keyboard event) to enter the ideograms . There are, at least two, pending PR to solve this problem. Look for "IME" keyword.

**Comment by jmoenig** [comment]
IME support has now been introduced with https://github.com/jmoenig/Snap/releases/tag/v5.0.6
