### ISSUE TITLE
"Change block" custom block dialog triggers improperly

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap#1523]
When editing a custom block, one can click on the HatBlock at the top to open the "Change block" dialog, which let's you give it a new category/type. This is good (if not a bit obscure), but the same behavior also triggers when clicking *any* block in the custom block's main script. 

![untitled](https://cloud.githubusercontent.com/assets/1750176/20495023/6941661e-afed-11e6-879b-fd20263765f4.png)

This may seem like a small problem, but I've seen students, especially those new to Snap, accidentally open this 5-10 times in a single hour. It happens when they try to click on the inputs of blocks to type a literal and miss (especially when trying to move the cursor to the beginning or end of the input). Seems like a strong usability issue with likely a very simple fix.

**Comment by jmoenig** [comment]
Hmm... that's actually intentional. But your observation about kids accidentally triggering the "change block" dialog makes sense. I guess this should be changed. Thanks!

**Comment by cycomachead** [comment]
I never realized what exactly was happening. This has bothered me many times before, but I always thought it was some weird user error.

**Comment by thomaswp** [comment]
Yup. Another problem case is when a student goes to grab a block to move it, but accidentally single-clicks. Any block, no matter how nested, will bring up the dialog when clicked.

**Comment by jmoenig** [comment]
Ooops, this has been fixed in the meantime. Thank you! Closing...
