### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap#1532]
In Scratch extensions are plug-ins written in JS that defining new blocks. in Snap _!_ extensions can be add-ons defined in `extensions.json` file. Example:
```JSON
{
"Test": {
  "description": "Test addon",
  "source": "test.js"
}
}
```
Loader:
```JavaScript
// gui.js
IDE_Morph.prototype.loadExtension = function(name) {
if (!this.extensions) this.extensions = JSON.parse(this.getURL('extensions.json'));
if (!(name in this.extensions)) {
throw new ReferenceError('Cannot find extension!');
}
var myself = this,
     ext = this,extensions[name],
     source = ext.source || 'err-ext.js',
     src = document.createElement('script', {src: source});
document.body.appendChild(src);
src.onload = function(){
var data = window[name];
var inst = new data(myself);
}
};
```
Code:
```JavaScript
// test.js
function Test(ide) {
   // Do something with/Add blocks...
}
```
Error:
```JavaScript
// err-ext.js
throw new ReferenceError('Cannot find source of extension!');
```

**Comment by liam4** [comment]
This sounds like a simple way to load another script into your copy of Snap*!*. But since you need to edit a file, I don't see why this is necessary – couldn't you just add the respective `<script>` into the body of your snap.html file?

```html
<!-- For example, your example, but added to the snap.html file: -->
<body>
  ...
  <script src="blocks.js"></script>
  <script src="byob.js"></script>
  ...
  <!-- Add this: -->
  <script src="test.js"></script>
</body>
```

**Comment by cycomachead** [comment]
What exactly would you want an extension to do?

The problem with extensions isn't so much _how_ to load them (or even build them), but to decide what exactly they should be capable of doing, and how they should interact with Snap<em>!</em> in a way that is safe. Ideally, we would want a way for extensions to connect with hardware -- otherwise, everything that can be done in the browser can be done via a library that loads JSFunctions.

**Comment by dekrain** [comment]
Most of all, simple way to manage blocks. Extension's class will have access to API that can e.g. add blocs .
```JavaScript
Test.prototype.init = function(api) {
api.addBlock(api.reporter, api.operators, "%n ^ %n", "pow");
}

Test.blocks = {
  pow: {
    inputChange: function(id,value,boundapi) {}, // Mutations
    call: function(a, b) { return Math.pow(a,b); }
  }
}
```
or something. It's only prototype.

**Comment by cycomachead** [comment]
Closing since we eventually got to a standard extensions model.
