### ISSUE TITLE
"http block" & protected area = NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

### ISSUE THREAD

**Issue by seteahconnoc** [jmoenig/Snap#1583]
I am testing `Snap!`'s "http block". I want to read from a file by using a PHP script on my webspace. This works well via:

`http://...mywebspace.../index.php?type=read&filename=test.txt`

(If necessary, I will send the PHP script.) Now, I protected the webspace via `.htaccess` and `.htpasswd`. When I send the http request by using a browser's address bar, I get the desired result:

`http://user:password@...mywebspace.../index.php?type=read&filename=test.txt`

Sadly, this does not work with `Snap!`'s "http block". Here, I get:

`NS_ERROR_DOM_BAD_URI: Access to restricted URI denied`

Can you help me?

**Comment by dekrain** [comment]
Maybe you should set header `Authorisation` by using `JSFunction` block.

**Comment by seteahconnoc** [comment]
@dekrain Thank you. I guess, I might need a little more help. Here is my try, which is not working by now:

For I am not quite experienced with JavaScript, I hoped, that I could avoid the "`JavaScript function` block". So, in order to set a header, I imported `Snap!`'s library `Web services access (https)`. Now I made this block:

![url_send_headers](https://cloud.githubusercontent.com/assets/23081344/21508010/8b3cfc7c-cc7d-11e6-84a2-a8e4b14462a0.png)

**Comment by dekrain** [comment]
You must encode this with `btoa` function.

**Comment by dekrain** [comment]
Second thing: use `(LIST (list [Auth...] [Basic...]))`.

**Comment by liam4** [comment]
By the way,`btoa` is a JavaScript function:

```js
// in the JavaScript console

> btoa('test:pass')
< 'dGVzdDpwYXNz'
```

You can use a JS Function block to get `btoa` in Snap<em>!</em>:

<img width="416" alt="screen shot 2016-12-27 at 5 53 33 pm" src="https://cloud.githubusercontent.com/assets/9948030/21509232/76e9fb32-cc5d-11e6-87dc-da0ba71bb0b6.png">

**Comment by cycomachead** [comment]
> Second thing: use (LIST (list [Auth...] [Basic...])).

This shouldn't be necessary. Headers is automatically a list because it's a variadic input.

**Comment by dekrain** [comment]
By the way, I did working btoa function in Snap! using JavaScript encode algorithm. It's one of my cloud project.

**Comment by dekrain** [comment]
@cycomachead ouch, now I see. The arrow after list block.

**Comment by brianharvey** [comment]
I think you guys are not getting that the OP doesn't want to have to learn JS, but is asking for a turnkey solution.  Pretend this was posted on the user forum thread instead of on github.

**Comment by seteahconnoc** [comment]
Thank you for your support. In addition to the posting of @brianharvey: As a teacher, I am aiming to use `Snap!` in an educational project (not necessarily `JavaScript` - just to stay focussed). I wanted to rebuild some of the ideas presented in `SQLsnap!` (`http://snapextensions.uni-goettingen.de/`), which is based on `Snap!`-beta-sourcecode from December 2013.

If there is a more appropriate forum, feel free to redirect me.

---

My next approach was not successfull. Any suggestions?
![btoa](https://cloud.githubusercontent.com/assets/23081344/21518665/61bb6008-cce8-11e6-9aa0-76ea01ebb8dd.png)

**Comment by cycomachead** [comment]
That looks like it should work..
I think we need more info:
Can you post the full URL? (without the password)
Are you using snap.berkeley.edu or something offline?
Does pasting the same URL work in a browser? (with embedding the password in the URL).

**Comment by seteahconnoc** [comment]
Can you post the full URL? (without the password)
You can find my website here:
`http://phagedaenic-cans.000webhostapp.com/index.php?type=read&filename=test.txt`
You can use the user `user` with the password `password`.

Are you using snap.berkeley.edu or something offline?
I am using `snap.berkeley.edu`.

Does pasting the same URL work in a browser? (with embedding the password in the URL).
This works fine:
`http://user:password@phagedaenic-cans.000webhostapp.com/index.php?type=read&filename=test.txt`
You should get a simple `hello`.
---

Of course, publishing URL and password is a serious security issue. It is just for the purpose of testing and will be deleted afterwards.

**Comment by cycomachead** [comment]
I can't reproduce the same error. Here's what I do see:

XMLHttpRequest cannot load http://phagedaenic-cans.000webhostapp.com/index.php?type=read&filename=test.txt. Origin http://snap.berkeley.edu is not allowed by Access-Control-Allow-Origin.

Take a look at enable-cors.org for info on getting around that. It seems like your URL and site should work just fine otherwise.

**Comment by seteahconnoc** [comment]
Thank you for the response. I think, it 's a newbie question, but where do you saw the error message? I just got a small, empty balloon.

---

I read the instructions on `enable-cors.org`, but I still don't know, how to solve the problem.

If my website is not password protected, I have to add the line `header("Access-Control-Allow-Origin: *");` to my PHP file to get a success.

If I use password protection via `.htaccess` and `.htpasswd`, this is not enough. So I added the line `Header set Access-Control-Allow-Origin "*"`to my `.htaccess` file - still no success. As mentioned on `enable-cors.org`, I have to reload Apache. I am not quite experienced in these things, but I don't think that I can do this while using the free services of my provider. I am only allowed to upload files.

I would be glad, if someone can help me out.

**Comment by seteahconnoc** [comment]
My problem is partly solved.

I use Debian GNU/Linux stable. When I start the chromium webbrowser via `chromium --disable-web-security --user-data-dir`, I get the expected result. Sadly, this still does not work with the iceweasel webbrowser. Of course, I intend to get a browser independent solution. Any suggestions?

**Comment by cycomachead** [comment]
To see the error message I looked in the JavaScript Console. You can usually get there by looking a menu option that says Console or developer tools.

As far as my understanding goes adding the header line to your PHP script should be enough but unfortunately I'm not super well versed in this aspect of hosting. 

I've been testing using the basic built in HTTP block. That should work with providing the password in the URL, at least once the CORS headers are working correctly. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by seteahconnoc** [comment]
Thank you very much. This is quite helpful.

Hopefully, someone can help me out with the eagerly-awaited browser independent solution. I want to use `Snap!`'s "http block" in an educational project. It would be great, if my students could use the feature without keeping an eye on the appropriate browser configuration. In addition, I think some students might get motivated in starting their own projects with free PHP webspace. Therefore, it would be nice, if the project would work just by dropping a few files on the server. I want to stay focussed on a project, that mainly uses `Snap!`.

**Comment by cycomachead** [comment]
Yeah I quite agree with you! We're working on various little projects and enhancements to this stuff over time, but some stuff like CORS is hard because it's built into every site. 

In the meantime there a couple resources you might find useful:
crossorigin.me is a proxy server that gets around most of the CORS issues. 

@bromogosa who works on Snap!, has an extension called Snapi which has a bunch of really neat enhancements for working with other web APIs. I don't have a link handy but I think there's one on the Snap homepage. Basically at some point you'll probably want to play with headers and query strings and Snapi has some blocks to deal with that as well as parsing and displaying larger JSON responses. 

I'll also mention that many other beginner-friendly languages like nodeJS, Python and Ruby have plenty of tutorials and libraries like PHP does. I've seen some courses let students pick what language they want to learn next and any of those would make a great jumping off point for dozens of simple to advanced projects.  

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by seteahconnoc** [comment]
A few days ago, I wrote:

> Hopefully, someone can help me out with the eagerly-awaited browser independent solution.

I checked out some websites regarding my topic - for instance `https://awesometoast.com/cors/`.  I think, I just have to do the appropriate configuration using the `.htaccess` file. I tried my best, but I still did not find a way to succeed.

It would be great, if someone could help me. If I could not find help here: Do you know the appropriate forum for my problem?
