### ISSUE TITLE
Color sensor issue with nested sprites

### ISSUE THREAD

**Issue by Costor** [jmoenig/Snap#1601]
When nested sprites actually overlap each other, the "touching color" color sensor gives false positives for the colors of the nested sprites.

Check this example:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=costor&ProjectName=Color%20sensing%20problem%20with%20nested%20sprites

Part1 is nested to Anchor1, and both overlap.
The sensor "touching red" will always give true for both sprites!
I think this behaviour is unexpected: We consider a nested sprite as one super-sprite, and sprites don't sense their own color. More important - this issue makes it impossible to use the touching sensor to find out whether this nested super-sprite touches another red sprite (e.g. Anchor2) - because "touching red" is always true.

Counter-Example: Part2 is nested to Achor2, but they don't overlap.
The sensor "touching red" will give false for both sprites. That is ok.

This behaviour obviously comes from the recursiveness of applying sensors to nested sprites. In case of "touching color" it should exclude the elements of the nested sprite from the test.

**Comment by bromagosa** [comment]
This seems to have been fixed over the years. Your example now works as one would expect :)
