### ISSUE TITLE
Sort history.txt most recent first?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#1632]
Mostly for @jmoenig, but would you support restructuring the file to have the most recent releases on top? That way it's easy to find what changed recently. :)

(I'll do the actual work...)

**Comment by jmoenig** [comment]
Hehe, not a bad idea :-)
OTOH I mainly keep updating that list out of nostalgic affinity, in case California falls off into the Pacific Ocean taking Github offline :-D

**Comment by cycomachead** [comment]
I personally find the history really helpful - on Snap! and other projects. It's a more "logical" organization than just the git history and provides a good starting point before jumping into debugging something. :)
