### ISSUE TITLE
It needs to be easier to import to a variable

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#1647]
Right now you have to do this through having a watcher on the stage. 

I propose the following:

* Add the import command to the _declaration_ blob of all variables (i.e. the palette or the script variables block)
* If the type of a variable is already a list, then we split the file by lines automatically.

**Comment by brianharvey** [comment]
Is there a reason we don't just have a reporter for this?  Why does the import have to have a variable at all?  (As opposed, for example, to being directly the input to a SPLIT block.)

**Comment by cycomachead** [comment]
> (As opposed, for example, to being directly the input to a SPLIT block.)

I suppose you're right this would work, but IMO, it's not great to shove tons and tons of text in an input slot - it's hard to read and takes up space in the scripting area. I guess, I wouldn't want to _encourage_ this, but it doesn't seem like a problem necessarily.

Also, and perhaps more importantly, AFAIK #20 Is still around and this would lead to wonky behavior. There's actually a bug linked to the split bock usage of pasting text into the input slot.

**Comment by brianharvey** [comment]
Huh?
![import](https://cloud.githubusercontent.com/assets/3885074/22490394/f0c9871c-e7d1-11e6-9023-43cf0272a0ad.png)

**Comment by cycomachead** [comment]
We can't do that because the web doesn't allow it. That also would break the portability of projects. The desktop app I have will work with a custom block but there's still no portability. 

I thought you meant like adding a context menu to every input. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Hmm, so, we're not allowed to have a filename embedded in the program?  It has to be from a browser open dialog?  OK, in that case, the input to the IMPORT block should be a caption to be included in the open dialog, e.g., "choose a database file."

**Comment by cycomachead** [comment]
Ah, well we can certainly build that! Well, minus the caption. You can't add a caption b/c the import dialog is attached to the window. 

![screen shot 2017-01-31 at 7 24 06 pm](https://cloud.githubusercontent.com/assets/1505907/22494252/db5d14c0-e7ea-11e6-8c53-0d7cd407d5d4.png)

However, in lots of cases, you don't want the import to be run during the execution of a program - like when building a hangman game, so I still think we should have a non-block method for importing stuff, but I could see a block being useful if you wanted to do something interactive.


BTW, try this project:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=import%20block

Using:
https://github.com/cycomachead/snap-app/releases/tag/0.0.6

**Comment by brianharvey** [comment]
I'm confused; you want me to download your repo and serve it from localhost?

Anyway, sure, importing to a variable in the GUI is good, too.  I'm not sure I like the part about "if the value is already a list, split into lines."  What if it's already a list of lists?  Should we then map-split on commas?  On spaces?  Etc.  I do agree that right-clicking in the Variables palette is a good alternative to requiring a watcher.

**Comment by cycomachead** [comment]
> I'm confused; you want me to download your repo and serve it from localhost?

it's a desktop app. If you just download it then you can double click to run snap, and then open the shared project in it. (though you'll have to save the XML first, since you can't paste in a URL of a project, yet.)

> I'm not sure I like the part about "if the value is already a list, split into lines."

I said it was optional, mostly for this reason. I guess we could try to be smarter, but IMO -- a list covers a lot of use cases without needing to make too many guesses. If we really wanted to do 2D splits, I would only do it on things you know (like CSV or TSV files).

**Comment by jguille2** [comment]
Hi @cycomachead ,

  - I'm agree to add the import and export too commands to the declaration blob of all variables. Then, we won't have to watch a var to import/export it.
  - Lists are a more complex thing (they can have different structures)... but they are important too. My teachers need to save working data. For example, in Science subject, they receive multiple data (form Arduino sensors, internet ....) and they want to save them and be able to work with other applications (spreadsheets ...). Then CSV is a powerful tool!

To work with CSV, I've made a template for our teachers, with a block "array to csv" into an example, showing how to save data into a list and export all this data into a csv file.

If you want to take a look... the template project is [http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jguille2&ProjectName=data_to_csv](http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jguille2&ProjectName=data_to_csv)

What can we do? I think we have two good options: to share this block (or another in the same way) into a Snap library or implement list exporting doing the same action (exporting a csv)

What does this "array to csv" block?
  - It reports a single string exporting the whole array
  - It builds a 2D structure . A list of lists: The items of the parent list are lines and the items of the inner lists are separated values.
  - The first inner list define the number of values (columns). If we have other lists with more items, those elements will be not considered.
  - If we have a more complex structure (inner elements were list too) they join all their data into one string.

Thanks,

Joan

**Comment by jmoenig** [comment]
Nice, Joan!

Here's a little starter project I did a while ago that parses CSV data into tables etc:
http://snap.berkeley.edu/run#cloud:Username=jens&ProjectName=Stock%20Performance

**Comment by jguille2** [comment]
Thanks @jmoenig,
Really, Snap! is great!

I will take a look at your project (I'm slower)

I only made 'array to csv' (export data) because this was the need I saw. I'll add the import option (csv to list) for other uses.

Joan

**Comment by jguille2** [comment]
I've updated [the project](http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jguille2&ProjectName=data_to_csv) with an import (csv to list) block.

Joan

**Comment by ToonTalk** [comment]
Just now I tried import on a variable watcher. Worked fine for txt but I saw the following when importing a TSV (and it had 'tsv' as a file extension):

![image](https://user-images.githubusercontent.com/2138696/49015778-fea07480-f17b-11e8-823c-737feeed901a.png)

and when I tried to import a tiny ordinary CSV file in Windows 10 I got

![image](https://user-images.githubusercontent.com/2138696/49015823-22fc5100-f17c-11e8-9ec0-94794c296e64.png)

And JSON:

![image](https://user-images.githubusercontent.com/2138696/49015934-72428180-f17c-11e8-846d-3f2f1186cf9f.png)

XML imported as plain text. Is that the intent?

**Comment by jmoenig** [comment]
Oh, wait! That shouldn't happen. I'm importing CSV files all the time. They are supposed to be imported as plain text, and then you can use the ```split (csv)``` option on them.

**Comment by ToonTalk** [comment]
And 'export' only gave me txt as an option (in the file dialog - no sub-menu in Snap!). Should I be seeing the formats mentioned in https://github.com/jmoenig/Snap/pull/1670?

**Comment by jmoenig** [comment]
nope, you can only export as text, but if you come up with your own text-based format, such as CSV, that should be fine. I'm considering adding a "encode as CSV" table option for 2D lists...

**Comment by ToonTalk** [comment]
Given the error messages when importing I assume it has something to do with how Windows associates file extension names to MIME types. Worked fine when I renamed test.csv to test.txt

**Comment by cycomachead** [comment]
Yes, it’s somewhat intentional... but obviously not quite right. (It’s an open issue, too.)


We need to check the file type otherwise  when you import a file it could turn binary data into a string of text which just looks broken and confuses students (and teachers). 

Maybe that dialog should allow you to “import anyway”. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
Import anyway sounds like a good idea to me (perhaps with the dialog emphasising need for it to be textual).

[MDN says](https://developer.mozilla.org/en-US/docs/Web/API/File/type)

> Client configuration (for instance, the Windows Registry) may result in unexpected values even for common types. **Developers are advised not to rely on this property as a sole validation scheme.** (original emphasis)

**Comment by jmoenig** [comment]
Okay, @ToonTalk , I've just patched the dev version with a tiny change that *should* make it more lenient to import other text-based formats such as JSON, XML, CSV etc. I can't really test it on my Mac because the previous non-patched version also worked flawlessly on my Mac, so I don't know whether that change did, in fact, change anything at all on a Windows PC.

I've uploaded the patch to the dev version:
https://snap.berkeley.edu/snapsource/dev/snap.html

It would be great if you give it a quick try, whether you can import CSV/AML/JSON files into a variable watcher without changing the file extension to "txr" first.

Thanks!

**Comment by ToonTalk** [comment]
Sorry but the same behaviour as before. (And nothing in the console.) I tried csv, tsv, and json.

**Comment by jmoenig** [comment]
Thanks! Hmm.... that's odd, all of these should have "text" somewhere in their MIME file type...

**Comment by jguille2** [comment]
Hi!
My feedback...

"JS mimetypes" are reporting "text/plain", "text/csv", "text/xml" and so, they are imported ok in current version (and also in dev version), because "text" is in the beginning of the string mimetype ( type.indexOf === 0 or !== -1). In linux this is running OK.

Maybe some OS associate extension to a software product... and maybe it reports "application/softname".

Note that JSON reports "application/json" and it can't be imported (nor current nor deb) with "json" extension.

**Comment by jmoenig** [comment]
Okay, all of these work on my Mac.

@ToonTalk and @jguille2 : could you try the dev version one more time (and make sure to hard-reload the page or clear the cache before)? I've now added the possibility to "Open anyway". Maybe this helps...

Thanks!

**Comment by ToonTalk** [comment]
Now I am getting the the open anyway in the dialog and its working fine. Thanks.

Here are the mimetypes on my machine:

tsv has an empty string mimetype (when I click on a TSV file it launches WordPad).

csv is "application/vnd.ms-excel" (which I assume is common for Windows machine with Excel installed)

On my system JSON also reports "application/json"

**Comment by jmoenig** [comment]
thanks, Ken, I'm glad that we've at least found a workaround for Windows machines. I think I'll package these changes into this week's maintenance release, probably sometime tomorrow.

**Comment by brianharvey** [comment]
Importing .csv files used to not work on my Mac (some time ago, I don't mean yesterday) but now does.  I hadn't tried in a while so I don't know when it changed.

I vote against scary "import anyway?" messages for known text extensions such as (especially) CSV.

**Comment by cycomachead** [comment]
Yeah. For known extensions it shouldn’t the import anyway option. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
I'm confused what is being suggested. When I try to import CSV it says "application/vnd.ms-excel" is not a known type. So either us Windows users either need import anyway or it should do the import based upon the file name and ignore its mime type.

**Comment by brianharvey** [comment]
Groan.  This is of course a misfeature of Windows; they want to make sure nobody can open a CSV in anything but Excel, even though bringing data to something other than Excel is the _whole point_ of CSV!

So, I agree, we should use the extension in the filename.

**Comment by cycomachead** [comment]
I think that mimetype comes from files saved out of excel or depending on OS settings. On Mac, CSVs default to your office apps too (but I don’t know if that changes the MIMEType). Anyway...

We should not use just the extension... because there’s too many text extensions. 

I suppose we could add a few extensions and check both, and show fewer warnings that way. 

Plus, extensions aren’t always going to exist or even match the mimetype, but I’m fine with erring on being permissive. 


Personally, I don’t think the warning is that big of a deal. We should just work on making the contents friendly and explain that’s it’s ok to just click import. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I'm not advocating for a complete list of extensions.  But CSV ... I was tempted to end that sentence with "is a special case," but CSV is so common, and so important to our (BJC and SAP) curricula, that it's more like everything else is the special case.

Anyway, local files, the only ones you import through a watcher (as opposed to the URL block), don't have mime types!  They just have extensions.

Actually, if I had my druthers, we'd just accept anything and let the user notice that the result isn't what they expected.  In particular, as a special case, I'd accept filenames with no extension.  But that's way less important than CSV files.

**Comment by jmoenig** [comment]
these local files *do* have mime types! And those work nicely on real operating system :)

But anyway, I agree with Brian. I'll make a bunch of special cases checking for files extensions that indicate text, XML, JSON, CSV. Any other extensions you suggest?

**Comment by bromagosa** [comment]
I'd add .txt to the list. I'm not sure what Windows wants to do about these but I wouldn't be surprised if it wanted to open them with Microsoft Word!

**---- THREAD HIJACKING BEGINS ----**
Sorry to hijack this thread and feel free to ignore this and go on with the issue we're discussing here, but since we're opening Pandora's box of text representations, I'd like to point out that I spent a couple of weeks implementing the ability to export lists to JSON, CSV, XML or plain text from a watcher. That has been working flawlessly in Snap4Arduino for a very long time, and I've found myself opening Snap! projects in Snap4Arduino just to be able to do exactly that.

The argument against pulling this back then (almost 2 years ago!) was that if a list contains an object (sprite, block, etc) then we don't know how to export it to text, but that's also true for regular variables and nobody has complained yet that they can't export them. OTOH, all these objects have methods to turn them into XML and back, so we could definitely 

Some extremely simple things never get done because of endless philosophical discussions :(
**---- THREAD HIJACKING ENDS ----**

**Comment by ToonTalk** [comment]
I would add TSV to the list.

BUT is this really the right way to approach this? I just read

[Detect non-printable characters in JavaScript](https://stackoverflow.com/questions/1677644/detect-non-printable-characters-in-javascript

Why not read the file and then do a test like the one suggested?

`/[\x00-\x1F]/.test(data)`

The purpose of the current filter isn't really to prevent reading binary files but reading binary files with non-printable characters.

**Comment by ToonTalk** [comment]
Regarding exporting objects as XML can one then import or drag the XML file of a single object into Snap! to recreate it?

**Comment by jmoenig** [comment]
Thanks, Ken, and Bernat. I think the purpose of the current text is to gently prevent novices from loading binary files that they can't parse into lists. I really don't mind so much whether something is printable or not, because, after all, users can program anything they want, and choose any delimiter for their own purposes, and I wouldn't want to prevent *that*. For the purpose of not confusing beginners I think a warning with the option to "load anyway" is a good compromise, and special casing a bunch of text-like filename suffixes should address the Windows issue of broken mime types. The use case is that I want kids to be able to just load CSVs.

Regarding exporting *any* list in a bunch of formats, as Bernat again suggested, I'm open to reviewing that...

**Comment by cycomachead** [comment]
> Regarding exporting objects as XML can one then import or drag the XML file of a single object into Snap! to recreate it?

For some, but not everything. And Importing a Snap! .xml file should definitely serialize the file and not display the contents, but that's a separate issue. No matter what we do, we'll want to handle Snap! files specially.

---

As far as the features: The point about extensions was that we can't rely only on them. I don't know how long the whitelist is... :)

I think Ken's point of just testing the contents makes sense. If it's text, we import it fine, and if not, then we can let people 'import anyway'. 

Also, the **original** intent of this issue is that the mechanism to import is not discoverable, so none of this even addresses that problem, though I do think we ought to solve the file types issue, too.

**Comment by cycomachead** [comment]
> I think the purpose of the current text is to gently prevent novices from loading binary files that they can't parse into lists. I really don't mind so much whether something is printable or not, because, after all, users can program anything they want, and choose any delimiter for their own purposes, and I wouldn't want to prevent _that_.

I think the point about non-printable characters, is that a binary file will be full of non-printable characters. And, I the import anyway would cover non-printable characters but I've only ever seen one data file contain non-printable characters, and that came from MioSoft. :) Which is to mostly say, I think it's not something students run into. They do however, try to import images and sounds into variables.

(which maybe if we were being diligent, we'd detect an 'image' or 'audio' mime type and add special text to the error message. That'd be the helpful thing to do.)

**Comment by ToonTalk** [comment]
---- A SECOND THREAD HIJACKING BEGINS ----
There has been plenty of criticism of how Windows handles extensions in this thread. My experience is that it works well. When installing a program it asks if I want to associate it with certain extensions. If I double-click (or click if one has enabled it) on a file without an extension association one is asked what to open it with and whether to remember the association for the future. And if I right click one menu item is "open with" where I can open it with something other than the default.

And it is the extension that determines things not which program created it so a CSV file created in WordPad will open in Excel (or OpenOffice if I preferred that).
---- THREAD HIJACKING ENDS ----

**Comment by ToonTalk** [comment]
With "open anyway" on a PNG file I see

![image](https://user-images.githubusercontent.com/2138696/49137853-8fdf2a80-f2e5-11e8-9004-9e3121d0b1bc.png)

I this so bad? Students may be curious about what is in a sound or image file.

**Comment by jmoenig** [comment]
I don't think it's so bad, a warning is enough.

Hey, I just pushed a little patch that checks for file extensions on Windows, and special cases all the types we've discussed above. Could you give it a quick try?
Thanks!

**Comment by ToonTalk** [comment]
Works fine, thanks.

**Comment by jmoenig** [comment]
Thanks for the quick test, Ken!

**Comment by cycomachead** [comment]
Yeah, the 'open anyway' should work for a png -- students can read the file byte by byte, or potentially use some JSFunctions to manipulate it, but it's also probably not what a student expects (which is to make a costume), so a warning makes sense.

**Comment by brianharvey** [comment]
> (which maybe if we were being diligent, we'd detect an 'image' or 'audio' mime type and add special text to the error message. That'd be the helpful thing to do.)

We have first class costumes and first class sounds.  We can already set a variable to a costume and the watcher does the right thing.  The _helpful_ thing to do would be to import the file as it's intended!

**Comment by cycomachead** [comment]
Yeah,  that makes sense. “Import” can create a new costume or a new sound and then assign the variable. 
that should be its own issue. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
Why not make this work for any object (e.g. sprites)?

And why not have an export menu for variable watchers for costumes, sounds, and sprites? All these things are exportable via other menus.

**Comment by brianharvey** [comment]
Uh oh, now we're going to get Jens's "Users -- give 'em an inch and they take a mile" speech.  :-)

**Comment by cycomachead** [comment]
> Why not make this work for any object (e.g. sprites)?

That's why I said XML's should be special-cased. Clearly, importing a Snap<em>!</em> XML should do the right thing and make that a Snap! object. (Sprites, blocks, and things besides the stage make sense to stand alone in a variable. Images and sounds do too, theoretically, it's just that there's an indirection from their native forms to something Snap<em>!</em> understands, so that's why the import from a variable isn't as clear.)

Also, some of this works from the 'file' menu import function -- you can import blocks or sprites that way, currently. 

I suppose the most "right" thing to do in Snap<em>!</em> would be to have import work mostly the same from any context, though that can get a little tricky.

**Comment by jmoenig** [comment]
We've made it much easier in Snap5 to import data by just dragging and dropping CSVs or JSON files into Snap. Also, we can now separately export and import lists with atomic data. I think this issue is now addressed and we can close it. Thanks!
