### ISSUE TITLE
List.prototype.becomeLinked() is inconsistent with List.prototype.becomeArray()

### ISSUE THREAD

**Issue by Costor** [jmoenig/Snap#1662]
This is just a quick notice that the method List.prototype.becomeLinked() is inconsistent with List.prototype.becomeArray() and the other List methods: 
On conversion to linked list and back the **last element of the list gets lost.** 
As .becomeLinked() actually seems not be used in Snap, this remark is just in case.

See:  http://snap.berkeley.edu/snapsource/snap.html#present:Username=costor&ProjectName=beomeLinked

.becomeLinked makes last cell with  cell.first=value, but cell.isLinked=false. This is inconsistent with use in all other methods as length(), itemsArray() etc. how the last cell is identified as it may have .content!=null.

**Comment by micahcowan** [comment]
Yeah, I noticed this too, and fixed it in pull request #1643, which also includes code changes to actually use the function. But there's some controversy over whether that change is desired. :)

One could of course just take the fix to this function from my pull request, but if we're not going to introduce code that uses it again, it's probably better to remove it entirely. There's already essentially a (working) reimplementation of it in the `.cdr()` function, which is what I based my rewrite of `.becomeLinked()` on.

**Comment by jmoenig** [comment]
I've since fixed this. Thanks, everybodx!
