### ISSUE TITLE
Variadic function input drops rings on scripting area when shrunk

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1672]
![screen shot 2017-03-01 at 1 03 06 am](https://cloud.githubusercontent.com/assets/3885074/23452933/11c95ce4-fe1b-11e6-9638-ee618ef273b3.jpg)

**Comment by cycomachead** [comment]
LOL I noticed that too. It's the same as #843 Empty rings are treated as inputs.

**Comment by jmoenig** [comment]
Oh, I've since fixed this! Closing, thanks...
