### ISSUE TITLE
Import fails on IE11

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#1684]
I get the error

![image](https://cloud.githubusercontent.com/assets/2138696/24070270/ddc3c4d8-0bf4-11e7-87a5-0b1d068ad4cf.png)

When importing the attached. Simpler projects import fine. And this imports fine in FireFox.

Windows 7
[camera and say no keys.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/852242/camera.and.say.no.keys.zip)

**Comment by jmoenig** [comment]
Oh, I think it's time to retire IE11 :-)
