### ISSUE TITLE
set pen color to <chooser> turns entire window white

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#1688]
Clicking on the color chooser in the set pen color to block turns my entire window white. Seems to only happen if tab is maximized. Windows 7.

https://snap.berkeley.edu/snapsource/snap.html#present:Username=toontalk&ProjectName=pen%20color%20bug

**Comment by ToonTalk** [comment]
Chrome Version 57.0.2987.98

**Comment by bromagosa** [comment]
Just to inform that it does work okay in Chrome 56.0.2924.87 on GNU/Linux, so it may be a platform-specific thing.

Have you tried in other browsers?

**Comment by DarDoro** [comment]
Chrome 56.0.2924.87 (64-bit) @ Win 10 works OK. Maybe some graphic card driver issue. You may try chrome://flags/ to fine tuning rendering options. For example disable GPU rendering  #disable-accelerated-2d-canvas, or  #enable-display-list-2d-canvas

**Comment by liam4** [comment]
Chrome 56.0.2924.87 (64-bit) on macOS 10.12 works fine.

**Comment by ToonTalk** [comment]
I was able to reproduce the problem with  #enable-display-list-2d-canvas but not when I disabled "Accelerated 2D canvas". I could not reproduce it in FireFox or IE11.

This still worries me because my laptop is a popular Dell model so I'd be surprised if this problem is special to my hardware.

Perhaps related to this I found in most browsers this odd behaviour of set pen color - if I place it near the bottom of the window a scroll bar appears apparently to display the color palette if I clicked on the color argument.:

![image](https://cloud.githubusercontent.com/assets/2138696/24144350/da1b6316-0e67-11e7-86be-0654ca47be03.png)

 However if I do scroll down the color palette is doesn't move like everything else:

![image](https://cloud.githubusercontent.com/assets/2138696/24144398/09ff4f70-0e68-11e7-81ae-fa9d63c99a15.png)

While if I scroll and then open the palette all is fine:

![image](https://cloud.githubusercontent.com/assets/2138696/24144511/6bb767e8-0e68-11e7-80d7-55df97c6192c.png)

**Comment by brianharvey** [comment]
Passing on message from teacher:

We are in the middle of our Create Tasks, and it appears the 
SET PEN COLOR TO (color)
no longer works - if you click the color block, everything goes crazy and the screen goes blank.  You have to reload SNAP so you lose any changes you have made to your program.

Bucky Garner
Hartselle High School

**Comment by ToonTalk** [comment]
In order to not lose work, I found that if I switched tabs and then returned Snap! was normal again.

**Comment by snorthway** [comment]
My class just started seeing this today (all using Chrome on Windows 7). Any time you use the color dropper in the costume editor, it turns the whole screen white.

![dropper](https://cloud.githubusercontent.com/assets/2825499/24294534/4ea3ba10-106d-11e7-8909-2dd1e1bc0126.PNG)

 As @ToonTalk noted you can switch tabs and come back and it will appear normal, but as soon as the mouse goes back in the window it turns white again, so that doesn't actually help in this case.

I've told them to use Firefox/IE for now.

**Comment by jmoenig** [comment]
Hmm.... The most likely explanation I can muse about is that a recent version of Chrome stopped supporting older graphics cards, which happened to me, but not in this way. Which version of Chrome are you using?

**Comment by ToonTalk** [comment]
My laptop's graphics is done by an Intel HD Graphics 4400 http://www.intel.com/content/www/us/en/support/graphics-drivers/graphics-for-4th-generation-intel-processors/intel-hd-graphics-4400.html

Not sure that qualifies as "old". As I reported earlier I'm using Chrome Version 57.0.2987.110

**Comment by jmoenig** [comment]
is anybody still experiencing this?

**Comment by ToonTalk** [comment]
Working fine today in Chrome and Windows 10.

**Comment by jmoenig** [comment]
Thanks, Ken! Closing...
