### ISSUE TITLE
Is there a reason that there is not a snap wiki on this site?

### ISSUE THREAD

**Issue by zeroturn** [jmoenig/Snap#1710]
There is a lot of really useful information buried in these open and closed issues that could be made even more useful if extracted and placed into a wiki.

Is there a reason that there is not a wiki on this site?

**Comment by brianharvey** [comment]
Lack of a round tuit.

**Comment by zeroturn** [comment]
Tell you what, if not too pricey, I'll buy one and mail it to you!  
![roundtuit](https://cloud.githubusercontent.com/assets/13770851/24666784/ea38a780-1926-11e7-91cd-256c045844d8.jpg)

**Comment by cycomachead** [comment]
In more seriousness, if someone proposes a more detailed plan for what a wiki might look like, then I think that's fine. We could try it, we just want to be clear the it will be hard to maintain.

**Comment by zeroturn** [comment]
It appears to me that this site has enough active and very knowledgeable participants that a wiki would be "relatively" self-maintaining (but then "relatively" is somewhat relative - how's that for some recursion?).  Of course, a group of this site's experts would need to moderate or supervise it in a (casual) way to insure that it stayed accurate and focused.

It seems to me that it would really have two major sections - a "user" section and a "developer" section.  The user section would discuss all things user focused.  The developer section would "pull back the curtain" for those interested in a view of Snap's entrails.  I would expect the user section to be fairly easy to maintain because Snap, as it is developed, probably does not change too much *from the user's perspective*.  That is likely not true for the developer section.  A developer section would probably require more "maintenance" because things would be changing constantly.

Insofar as the user section would go, I envision that it would adopt the user reference manual as a "skeleton", to which "flesh" would be added by way of discussion of issues (mostly closed issues) that appear on this site, as well as links to other resources (example projects, "approved/moderated" youtube videos, etc.), and anything else that users need to know.

Insofar as the developer section would go, Jens' **exceedingly concise and thorough** comments contained in his morphic.js would make for a nice "skeleton" for the developer section.  I dare not say how that might be "enhanced"!   ;-)

From my perspective, I know that I operate in two very distinct ways when I am engaged in some programming project.  If it is brand new to me, then I want a reference manual that I can peruse to bring myself up to some baseline level of competence.  However, if I am involved in a project with which I am more familiar, then, generally speaking, *I just want to get an answer to my question* so I can move on.  A wiki can really satisfy both types of inquiries.

It seems to me that there is great value in a "central repository of knowledge."  If I have to go 50 places to learn a subject, there is a high probability that there will be gaps in my education.  

Further, it seems to me that a wiki could encourage even wider participation.  I say this because, it seems to me that contributions to a site like this takes people with some *serious skills*.  Not everyone who would like to contribute possesses those serious Snap skills.  Yet, the presence of a wiki could encourage small contributions by a larger group of individuals who do not have those serious Snap skills but who do have literacy and experience with Snap that they can pass on to others who may be encountering the same issues or making the same mistakes.

A wiki seems worthwhile to me.  I think it would be worth the cost of a *round tuit*.  :-)

**Comment by brianharvey** [comment]
Thank you for not spelling "skills" with a z.  :-)

So, one reason this hasn't happened is that Jens doesn't exactly encourage new developers.  It's not like one of those cast-of-thousands things such as Linux or Hadoop or Firefox.

The user wiki will probably launch along with the forum and the social-media-like front page.  It'll live, I imagine, at snap.berkeley.edu rather than github.

**Comment by bromagosa** [comment]
Closing this as it's a question and has been answered. We now have a forum, a much more appropriate space for Q&A :)
