### ISSUE TITLE
SVG text development - questions and issues

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap#1743]
Hi. This is not a issue, but as I'm trying to develop some blocks to use SVG fonts in Snap, I'm facing some problems. I hope is ok to post them here.

I'm trying to bring SVG fonts into Snap, and learning this great tool meanwhile. You can see my progress here: http://snap.berkeley.edu/snapsource/snap.html#present:Username=davidgasku&ProjectName=svg_text3

It's very hacky at the moment.
- I create a SVG_Costume with a predefined SVG file.
- When I want to change the text, or any attribute, I get the svg, decode it, and change it, and put it back.

Some problems I'm facing:

1) I cannot set the rotationCenter correctly. It's supposed to be at costume.center() by default, but if you create several SVG's, some of them have wrong rotation centers.
2) How can I force the redraw of the sprite? I've tried this.wantsRedraw & ide.hasChangedMedia, but none works. Now I use a setSize block to force the update.
3) It seems to work in firefox, but it doesn't work very well in chrome. Maybe it is related to 2)
4) I use a flag to know if the costume is a SVG text (this.costume.isASVGText). But of course, it won't get saved into the project. Any way to create it from the user side?

If you have any idea, or some better way to do something, please share.

Thanks!

**Comment by bromagosa** [comment]
Hi @DavidGasku.

Sorry this was left unanswered. Maybe try your luck in the forum now that we have one?

Closing this as the forum is a much more appropriate space for Q&A :)
