### ISSUE TITLE
Double-clicking FILL block gets into infinite loop

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#1747]
I think this is a different issue from #1537.

If you click a FILL block twice quickly (e.g., because you get impatient), Snap<i>!</i> gets into an infinite loop.  Happens on Chome and Safari (no others tried) on Mac.

Marking as important because the infinite loop prevents saving.

**Comment by jmoenig** [comment]
I can't reproduce this anymore. Guessing that the fixes @bromagosa and I applied to FILL took care of that. Closing, thanks!
