### ISSUE TITLE
No help available for Fill.

### ISSUE THREAD

**Issue by dombogetto** [jmoenig/Snap#1749]
Tried in Edge and Chrome on Windows 10 and Chrome on Windows 7.  Does not appear when clicking help.  Other items' help appears.

**Comment by brianharvey** [comment]
Yeah, I know, a bunch of new blocks are missing help.  I'll get a round tuit when I can...

**Comment by jmoenig** [comment]
@brianharvey has since made help screen for - I believe - every block. Thanks! Closing...
