### ISSUE TITLE
Costume's Sprites cannot appear together - (Import of a .ypr)

### ISSUE THREAD

**Issue by alice77** [jmoenig/Snap#177]
Hi everyone :)

If I import a .ypr program in SNAP, I cannot see both of my 3 sprites together.

The costumes of the sprites are there (in each of the costume tab of every sprite) but I cannot put them together.

Thanks

**Comment by bromagosa** [comment]
Without the project file there isn't much we can do about this.

Closing this because it's been clearly abandoned...
