### ISSUE TITLE
"Prefer Development Release" Setting

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#1818]
Could we have a Snap<em>!</em> setting, definitely off by default, and very likely hidden, that would automatically re-direct a user to the dev branch when loading Snap<em>!</em> projects?

Essentially, once someone turns on this setting then they would always load Snap! In the new version. Obviously, we'd need a way to temporarily disable this so you can still get to regular Snap<em>!</em>, but something like a URL param like `&noDevMode` would work.

The idea here is to get us devs, and qualified TAs, interested teachers more often using the development version as a means of increased testing.

**Comment by brianharvey** [comment]
+1.

While we're at it, the "prefer no retina support" flag!

**Comment by cycomachead** [comment]
> While we're at it, the "prefer no retina support" flag!

:/ you mean to persist the setting, but yes.

**Comment by jmoenig** [comment]
I think y'all should just be using the dev version by now. There are times when the dev version will be unstable again, even experimental and non-functional. Let's not introduce settings...

**Comment by cycomachead** [comment]
It’s annoying to use the dev version when none of my bookmarks update or autocomplete. Plus I open plenty of shared project links which are in the regular version. Those are the ones I really want to automatically open in dev. 

Plenty of software, desktop, web and mobile apps, includes (hidden and not) settings for using beta releases or regular releases. I frequently make use of such functionality every day. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by merlin2v** [comment]
here is a library that activates dev mode
```
<blocks app="Snap! 4.0, http://snap.berkeley.edu" version="1">
	<block-definition s="enable Dev Mode %&apos;bool&apos;" type="command" category="control">
		<header/>
		<code/>
		<inputs>
			<input type="%b"/>
		</inputs>
		<script>
			<block s="doIfElse">
				<block s="reportNot">
					<block s="reportIsA">
						<block var="bool"/>
						<l>
							<option>Boolean</option>
						</l>
					</block>
				</block>
				<script>
					<block s="doRun">
						<block s="reportJSFunction">
							<list>
								<l>bool</l>
							</list>
							<l>throw new TypeError("Cannot read Property null as Boolean");</l>
						</block>
						<list/>
					</block>
				</script>
				<script>
					<block s="doRun">
						<block s="reportJSFunction">
							<list>
								<l>bool</l>
							</list>
							<l>world.isDevMode=bool;</l>
						</block>
						<list/>
					</block>
				</script>
			</block>
		</script>
		<scripts>
			<script x="90.45703325" y="183.83333033333338">
				<block var="bool"/>
			</script>
			<script x="254.67578325" y="34.000001999999995">
				<block var="bool"/>
			</script>
			<script x="246.218752" y="53.000001999999995">
				<block s="reportJSFunction">
					<list>
						<l>bool</l>
					</list>
					<l>throw new TypeError("Cannot read Property &apos;bool&apos; of null");</l>
				</block>
			</script>
		</scripts>
	</block-definition>
	<block-definition s="is DevMode" type="predicate" category="control">
		<header/>
		<code/>
		<inputs/>
		<script>
			<block s="doReport">
				<block s="evaluate">
					<block s="reportJSFunction">
						<list/>
						<l>return world.isDevMode;</l>
					</block>
					<list/>
				</block>
			</block>
		</script>
	</block-definition>
</blocks>
```
Don't know if this would help.

**Comment by cycomachead** [comment]
We have &devVersion=true on the community site. it could be nice to find a better way to persist that, but for now, it works!
