### ISSUE TITLE
Repeated snapshots of a project

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#1821]
I created a block that saves the current project with a unique version name (and restores the user's project name and prevents 'saving' notices and the like). Repeat forever with a wait of a minute or two is what we need for some planned learning analytics. My block can save either to the browser or the cloud.

I'm unclear how to add these features:

1. How to access these saved projects. We could mark these files as shared (though the Snap method for doing so asks for confirmation and puts up various notifications).

2. How to not bother to save if nothing has changed.

3. How to hide them from the user since they clutter up the Open dialog.

4. Or would it better if instead of using saveProject or saveProjectToCloud we create a JavaScript block that creates the XML of the current project and sends it to our own server?

**Comment by cycomachead** [comment]
I can write more later, but go for 4. Saving projects to the user's account is likely to wind up confusing. 

For 2, you can do some XML diffing, but it may be best to do this after the fact rather than before saving.
