### ISSUE TITLE
Building a new block 

### ISSUE THREAD

**Issue by JingYao0512** [jmoenig/Snap#1848]
Hi, everyone

I want to build a new block which contain reportURL and other block. 

This is a example(https://github.com/pbrown66/snap-RPi) building a new block from XML file, but I want to directly revise or add some code in Snap!. 
[snapRPi Image](https://imgur.com/lZV2SE6)

Now, I already understand how to build the block in Snap!(as following picture). However, I don't know how to include other block(reportURL) to my block.
[myBlock Image](https://imgur.com/hmwAKiQ)

I only know if you want to give block getting functional, then you should add some code into its callback in "objects.js". For example,
`SpriteMorph.prototype.motorsetLED = function(ID, state){ bla,bla,bla};`

Thank you for any help.

**Comment by brianharvey** [comment]
Your picture links don't work for me.

But maybe what you want is invoke() in threads.js?

**Comment by JingYao0512** [comment]
Hi, @brianharvey 
Sorry, I revised my link, and it can work now.
invoke() function? OK, I will try it.
thank you for your advice.

**Comment by JingYao0512** [comment]
@brianharvey 
Hello, brainharvey
Sorry, I read invoke() function, but I can't understand its function. 

I want to build a block which contain another blocks like following example(XML). 
![](https://i.imgur.com/2twsYCQ.jpg)

I can totally understand how to write the XML file for adding block, but it's needed to be loaded every time. I want to directly add block on Snap!.
