### ISSUE TITLE
Bug with pen shade 0

### ISSUE THREAD

**Issue by jdavies0** [jmoenig/Snap#1870]
Looking at the help for pen shade it describes how to do a nice blue ramp from black to the current color by ramping pen shade from 0 to 100.
Just copy the sample code found in the help for pen shade. The results are wrong, it doesn't matter what color is currently selected setting the the shade to 0 sets the pen color to red.
Easy work-around by the pen shade to start a 1 rather than 0.

**Comment by jmoenig** [comment]
Pen colors have been completely rewritten and extended for Snap5. Closing this issue. Thanks!
