### ISSUE TITLE
Library imports disappearing/appearing 

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1877]
A: Earlier today, I was caught off guard when I found LABEL in my project even though I had specifically exported and imported _only_ the two Pen blocks I needed: PEN TRAILS and SET COLOR TO RGB (so as not to clutter my project).

B: Now, I just opened that same project, and PEN TRAILS is gone: obsolete where I'd used it and no longer in the palette. But SET COLOR TO RGB is still there.

The first time (A), I was willing to believe it was user error, but this time (B), I doubt it. The project worked when I last saved it, and now it doesn't. I doubt that I accidentally deleted the block without noticing. I was testing that project constantly; I would have noticed.

I'm not 100% sure about the project window from which I exported the two Pen blocks from the library, but I think it was from the dev version of Snap. I am, however, 100% (or 99.99% ;) )  sure that the project file was created in dev mode and I just now opened it (B) in 4.0.10.2.

**Comment by maryfries** [comment]
I'm wondering if the issue is simply that PEN TRAILS won't load in 4.0.10.2 as my project is still fine in dev.

**Comment by brianharvey** [comment]
Apparently PEN TRAILS (but not SET PEN TRAILS) has been promoted to primitive in 4.1.  So the PEN TRAILS block you used in dev isn't importable to pre-dev.  Who knew?

**Comment by brianharvey** [comment]
PS @jmoenig What does it mean that the pen trails library is gone from Libraries but only the reporter is primitive?
