### ISSUE TITLE
Shift-clicking an empty list input should select the input (keyboard editing)

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/Snap#1909]
At the moment it just selects the entire block (or the space above the block), which feels wrong.

![focus-ring](https://user-images.githubusercontent.com/9948030/32301754-296ee3b6-bf57-11e7-8bac-74c8c160bcc2.png)

I shift-clicked the list icon; the whole reporter block was selected.

One could certainly argue that shift-clicking other inputs doesn't stick the keyboard editing focus ring around them. For example, at the moment shift-clicking a text or number input makes the content be focused (i.e., it lets the user start typing in it, no different from simply clicking without shift); and shift-clicking a Boolean toggle switches it, rather than focusing it. But you can't normally type in a list input, so it just feels more natural to have Snap<i>!</i> select the input, rather than the whole block, for you.

**Comment by jmoenig** [comment]
I think it's doing the right thing, selecting the block, not the input. Closing, thanks!
