### ISSUE TITLE
weird thing happening to array

### ISSUE THREAD

**Issue by merlin2v** [jmoenig/Snap#1910]
Hello, I was trying to add items from an array to a list however it seem original items are over to the list rather than a reference. In a JS function i use the following.

    return this.scripts.children[i];
![image](https://user-images.githubusercontent.com/25653109/32310318-99f37e2a-bf4e-11e7-821f-01637231d1da.png)
by doing this (without `fixLayout()` or `copy()`) the items within `this.scripts.children` "disappear". `copy()` only works for the top level (shallow copy) and moves the blocks children to the area displayed(when run by double click). _(ignore `fixLayout` it makes it worse)_.
Do you know of any way to prevent the items from being removed from the array? like a way to create a reference to the blocks?

//Edit:
to duplicate 
![image](https://user-images.githubusercontent.com/25653109/32311194-70443f82-bf54-11e7-99c0-bc0faac97bc7.png)
and then double click on:
![image](https://user-images.githubusercontent.com/25653109/32311204-82a88fe8-bf54-11e7-8675-7ca1657ab091.png)
Update: The parent of the component changes to a `CellMorph` for some reason.

**Comment by YPIMG** [comment]
You can generate a list from an array directly.
```javascript
var arr = ["things","stuff"];
return new List(arr); //List contains "things" and "stuff" at indices 1 and 2
```
As far as I know, all references are preserved; it's a perfect copy. I think you can prove/test this by doing
`var arr2 = list.asArray();`
Theoretically, it'd be identical to arr in every way except for `arr === arr2`.

**Comment by brianharvey** [comment]
Javascript arrays are not a Snap<i>!</i> data type; you can't call your dat block with one.  If you say "new List(this.scripts.children)" and do the reverse transformation inside dat: "obj.asArray" then everything should work.  But I don't see what it gains you over just copying the list in Snap<i>!</i> instead of JS.
