### ISSUE TITLE
CodeMaster – Automatic Assessment and Grading of Snap!  and App Inventor Programs

### ISSUE THREAD

**Issue by awangenh** [jmoenig/Snap#1943]
Hello,

we are excited to launch and share our _CodeMaster_, a  free web application that in a problem-based learning context allows to automatically assess and grade projects programmed with App Inventor and Snap!.

_CodeMaster_ is available in English and Brazilian Portuguese.

More information:  http://www.computacaonaescola.ufsc.br/?page_id=2523&lang=en

Or just try it out: http://apps.computacaonaescola.ufsc.br:8080

The tool has been developed by two students as part of their final undergraduate thesis in the context of our initiative Computação na Escola at the Federal University of Santa Catarina/Brazil. Based on first feedback, we are planning to continue the development of the tool as part of future student’s theses. Any suggestions are very welcome.

Best regards,

Christiane, Aldo and Jean

**Comment by awangenh** [comment]
Please let us know what you think of it. The idea is to make the life of the high/middle school programming teacher easier, and, at the same time, introduce a bit more objectivity into the assessment of coding assignments.

**Comment by jmoenig** [comment]
Hi @awangenh, I can't open the page that lets me actually try Codemaster (http://apps.computacaonaescola.ufsc.br:8080/i18n_en). It gives me a 405 error informing me that "HTTP method GET is not supported by this URL".

**Comment by ToonTalk** [comment]
Works fine for me. (I chose to be a "student."). It is cool.

**Comment by ToonTalk** [comment]
I used http://apps.computacaonaescola.ufsc.br:8080/ to try it out.

I also get Jens error with http://apps.computacaonaescola.ufsc.br:8080/i18n_en

**Comment by awangenh** [comment]
Please let us know what you think of it. The idea is to make the life of the high/middle school programming teacher easier, and, at the same time, introduce a bit more objectivity into the assessment of coding assignments.

**Comment by awangenh** [comment]
We are looking into it:

HTTP Status 405 - HTTP method GET is not supported by this URL
type Status report
message HTTP method GET is not supported by this URL
description The specified HTTP method is not allowed for the requested resource.

**Comment by ToonTalk** [comment]
Is the source code available? I'm part of a project that might want to integrate this as a component in their learning analytics work.

**Comment by jmoenig** [comment]
Great, it now works for me!

Hey, l'm somewhat baffled. CodeMaster is - somewhat to my surprise - exceptionally amazing and ... fun! I've just spent a lot of time analyzing dozens of my own projects and was pleased by the accuracy of the analyses. To be honest, "automatic assessment" is somewhat of a hot topic right now, and I've seen a lot of disappointing implementations. But *this* is something else!

In fact, I'm so fascinated by how fun it is! Can we perhaps discuss whether you'd be willing (and what it would take) to include CodeMaster in our upcoming Social Website around Snap!

**Comment by jmoenig** [comment]
Two quick remarks: I seem to be having deficits in "Synchronization" and "Parallelism". Can you tell us more about how the rubrics are defined? In my projects I often use the LAUNCH block to fork threads. Is CodeMaster checking for such explicit threads?

**Comment by cgresse** [comment]
Hi, thanks for your feedback! 
We are currently discussing the issue on licencing at our university with respect to its usage in other projects. 
But of course we would be very happy to see CodeMaster integrated in an upcoming social platform for Snap! (we will get in contact via email to discuss this suggestion).
We just published a technical report providing an overview on the rubric etc. (http://www.incod.ufsc.br/wp-content/uploads/2017/04/INCoD-RelatorioTecnicos-CodeMaster-v10E.pdf)

**Comment by jguille2** [comment]
I'm testing too...

One question @cgresse, is the Registration available? I've tried to do it and I've received the confirmation email from computacaonaescola@sistemas.ufsc.br, but I can't log in (it says my email is not registered).
Continue...
Joan

**Comment by JeanHauck** [comment]
Hi @jguille2 ,

Thanks for your feedback!
I am also working with @cgresse on CodeMaster development.
We have noticed that it was temporary unavailable. I have just tried it and seems to be working properly now.
Would you mind to try the registration from the scratch again? (ignoring the previously e-confirmation mail).

Thanks,

Jean Hauck

**Comment by jguille2** [comment]
Thanks Jean,
Now registration is ok!

I will test and keep in contact...

Joan

**Comment by bromagosa** [comment]
(trying to unclutter gh issues a little bit)

Closing this as the forum is a much more appropriate space for announcements and Q&A :)
