### ISSUE TITLE
Clean up directory - Lang files

### ISSUE THREAD

**Issue by joefarebrother** [jmoenig/Snap#197]
PLEASE can you put all the lang-xxx.js files into a new folder? This will make it SO much easier to look through the folders to find one file! It only requires one little change to the code, in gui.js:

``` js
IDE_Morph.prototype.setLanguage = function (lang, callback) {
    var translation = document.getElementById('language'),
        src = 'langs/lang-' + lang + '.js', //There that's all you need to change... just add the folder name and a slash...
        myself = this;
    SnapTranslator.unload();
    if (translation) {
        document.head.removeChild(translation);
    }
    if (lang === 'en') {
        return this.reflectLanguage('en', callback);
    }
    translation = document.createElement('script');
    translation.id = 'language';
    translation.onload = function () {
        myself.reflectLanguage(lang, callback);
    };
    document.head.appendChild(translation);
    translation.src = src;
};
```

**Comment by birbilis** [comment]
btw, to not break other forks and make it harder to merge changes manually, I think you have to use some special move (or something) command of the version control system to move those files into a new folder, not just make the folder and copy files there, then delete old ones

**Comment by birbilis** [comment]
ahem, should also merge this or mark as duplicate, hadn't noticed this one
Cleanup root source folder #823
