### ISSUE TITLE
Large amounts of text cause rendering errors

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#20]
If a comment (wrapped to a reasonably narrow line width) or block contains a large amount of text, the scripting area which contains it no longer renders its background texture. The text itself is also not rendered, nor is the background of the comment/block.

![Screen Shot 2013-04-12 at 12 44 29 PM](https://f.cloud.github.com/assets/1578238/373952/aa2a27f0-a390-11e2-9641-e04c47b1be8b.png)

![Screen Shot 2013-04-12 at 19 06 47](https://f.cloud.github.com/assets/1578238/375596/bd57af52-a3c5-11e2-8323-d0919a2bc231.png)

**Comment by lmock** [comment]
Same as #187 

but here's another instance. trying to figure out what browser this student used:

![spam4](https://cloud.githubusercontent.com/assets/5467107/12310831/7694c338-ba07-11e5-9476-6b2831ec29d8.png)
