### ISSUE TITLE
Major performance regressions when running in Microsoft Edge browser

### ISSUE THREAD

**Issue by bjr1822** [jmoenig/Snap#2001]
The following project used to run smoothly in Microsoft Edge as of last school year:
https://snap.berkeley.edu/snapsource/snap.html#present:Username=bjr1822&ProjectName=BryanReich_NursuryRhymeProject_4thGradeIntroCS

I am teaching this lesson again this year, and when I went to play back my sample project, I found that playing it in Edge is amazingly slow and choppy compared to last year. The change and rotate blocks in particular, when executing in quick succession such as in this project when the characters are tumbling down the hill, are so slow and choppy as to completely make the program nonsensical. Not sure what changed, but I'm pretty sure Edge didn't all of a sudden slow way down.
Chrome doesn't work for the same project and also has regressions, but different ones that I'll file separately.

Edge version for repro:
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

**Comment by jmoenig** [comment]
Nice project!

Hmm.... I'm pretty sure we didn't introduce any changes that would slow down anything in a particular browser. The changes we *did* add only affect clones and inheritance, which your project doesn't use. Edge, OTOH might very well have changed. I know for sure that Chrome underwent some pretty dramatic changes. You could try downloading an older release of Snap (the releases are all archived in this very Github repository, you can simply download an older one as zip-file, unzip it on your computer and open the file name ```snap.html``` in your browser - Edge - ) and try running your project in last year's version of Snap. I'd be very interested to find out more!

**Comment by brianharvey** [comment]
Jens, could it be that the scheduling change that led to removing the "prefer smooth animations" is relevant to this?

**Comment by jmoenig** [comment]
Naw, we made the switch to ```requestAnimationFrame``` more than two years ago. What *did* change was that I made *turbo* mode somewhat slower but also a lot smoother. But *turbo* isn't used in this project. Plus, it seems to be only slower in Edge. In Chrome it works fine and fast (at least when I try it myself). Bummer, it *is* such a nice project...

**Comment by bjr1822** [comment]
I downloaded the April 23rd 2017 build and tried to open the html from my computer, but it just opens blank in Edge. Nothing displays. Do I need to be hosting it on a local web server, or should it just work off the file system? It opened in Chrome ok from the file system, but when I tried to log-in to the server to pull the project down, it failed to connect, so I can't open up the project. Ideas?

**Comment by brianharvey** [comment]
Sorry, the cloud back end has a whitelist.  So, open the project in actual Snap<i>!</i>, use "Export project" in the File menu to get the project on your own computer, then you can just drag it into your local version of Snap<i>!</i>.

**Comment by bjr1822** [comment]
That will help solve my Chrome issue, but still won't unblock my debugging attempt on Edge. Do you know what is going on with Edge running the files locally?

**Comment by jmoenig** [comment]
Edge should also just work when opened locally. There's nothing Edge- or Chrome- specific in any of Snap's code. Of course you can also simply use a little Python server to locally open Snap, or open a JS console in Edge to find out why it doesn't open. I do, however, remember opening Snap in Edge on my own Windows 10 setup without any problems.

**Comment by jmoenig** [comment]
Microsoft is making a new version of Edge based on Chromium. Closing this issue. Thanks!
