### ISSUE TITLE
Snapin8r integration

### ISSUE THREAD

**Issue by kach** [jmoenig/Snap#204]
https://github.com/Hardmath123/Snapin8r

It's still in development, but I think we should integrate it so that others can test it out. I know it's minified, which you don't like, but it's easier to distribute a single snapin8r.min.js file for testing, than a bunch of (large, not that it matters) JSZip files.

**Comment by bromagosa** [comment]
Okay, it's been 6 years, but I think this shouldn't be part of vanilla Snap!. We're linking to all these projects from the Snap! site(s), but I don't think they belong into the editor itself.

**Comment by jmoenig** [comment]
You're right. Closing...
