### ISSUE TITLE
Bug when adding empty text to a custom block's name

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap#2041]
Steps to reproduce:
1- create any block with any name
2- add a word before the text by clicking the + button.
3- change from input name, to title text and leave it empty (it can be white spaces too to trigger the bug)
4- apply
The block changes to a big blank block, which name you cannot further edit

**Comment by DavidGasku** [comment]
I should mention that the intention was to add space between words or symbols in a blocks name. It would be great if this bug is fixed by adding the possibility to add white spaces as text.

![charset script pic 1](https://user-images.githubusercontent.com/5382201/36892816-3ffadd02-1e06-11e8-9539-9bde65499c61.png)

**Comment by jmoenig** [comment]
Oh my! How could this skip my attention?!
I can reproduce it, now lemme fix it.

**Comment by jmoenig** [comment]
Hmmm... the bug described here is fixed, indeed, but at the cost of having introduced another. Now, when the user edits the last remaining fragment, removes all the letter and then acknowledges the change the last fragment gets deleted which causes the custom block template in the palette to grow and become uneditable.

Leaving this open while I work on this...
