### ISSUE TITLE
Blocks not loading

### ISSUE THREAD

**Issue by Monniasza** [jmoenig/Snap#2049]
Pen blocks don't load, and all sprite scripts are gone
![issue](https://user-images.githubusercontent.com/37037712/36944146-68856e36-1f96-11e8-87ba-75949e9a2f8c.PNG)

**Comment by jmoenig** [comment]
Hmm... I've just checked and it does work for me. Can you perhaps force-relead Snap (hold down the shift key while pressing reload) and try again? Tnx!
