### ISSUE TITLE
Ability to Hide Custom Blocks

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#2068]
We should have the ability to hide custom blocks in the same way that we can hide primitives. 

This will require an adaptation to the way snap serializes the hiding, but it should be easy enough to fix. I propose adding a `hidden` attribute (boolean) to each custom block when the data is serialized.

**Comment by jmoenig** [comment]
Yes, hiding custom blocks in the palette is something we definitely want. I was thinking that we could manage the ```hidden``` flag in the custom block block definition, but then they could easily and accidentally creep into libraries. Also there's the issue of sprite-only custom blocks and - to complicate things further - inheritance. This needs some careful thought. I'm still tending towards managing block visibility as part of the definition...

**Comment by KingDavid12** [comment]
A resounding YES! to this proposal, it would be epic to be able to hide blocks that are only needed by my blocks and not the user. As for creeping into libraries, that could easily be fixed simply by having options in the context menu to show / hide all custom blocks. Those options wouldn't change them the way they do for primitives, it would be more like the way entering dev mode shows additional blocks which disappear when you leave dev mode. Of course the hidden blocks would show in the export dialog, they would, just like they should in the bock toolbar on the left (I forgot the name), have an icon to identify them as such.

**Comment by cycomachead** [comment]
I think as we add more libraries, this would be helpful. 

IMO, the first (mostly easy) approach is treat this like a primitive -- any block can be hidden by right clicking in the palette. And if you export a library with hidden blocks, it can maintain that. Unhiding them would happen in the same way it does for primitives.

**Comment by brianharvey** [comment]
Speaking of treating custom blocks like primitives, a library should be able to mark a block as primitive, and then any runtime error inside it should be ascribed to its caller (as a domain error) rather than itself.

**Comment by cycomachead** [comment]
Just gonna close this and spoil any v7 surprises than remain. You could read the code anyway! 😉
