### ISSUE TITLE
How to open a dialog?

### ISSUE THREAD

**Issue by Botcho3003** [jmoenig/Snap#2070]
(Sorry if this is not the right section, but I'm new here)
Hello. I'm making a game and I want it to create a dialog with buttons. I'm not talking about Chrome popups, but the one that opens when, for example, you open "change stage size". Javascript block is fine too. If it's possible, a way to edit its buttons and to add a text input, but just if it's possible.

**Comment by dekrain** [comment]
The Snap _!_ is created on a framework called Morphic.js. It uses it for various things, like blocks, **widgets**, sprites, etc. So, yes, you can use morphic to manage dialog box, but it requires JavaScript. The widgets are located in file `widgets.js`.

**Comment by Botcho3003** [comment]
> The Snap ! is created on a framework called Morphic.js. It uses it for various things, like blocks, widgets, sprites, etc. So, yes, you can use morphic to manage dialog box, but it requires JavaScript. The widgets are located in file widgets.js.

Thanks, but it's a bit difficult to understand. Can you give me a code of a simple dialog box so that I can work around it for my game?

**Comment by dekrain** [comment]
```javascript
var status = {
someVariable: null
};
var dbox = new DialogBoxMorph(status, onAccept);
dbox.prompt('Number prompt', 'Type here...', window.world, null, null, /* isReadOnly */false, /* isNumeric*/true);

function onAccept(info) {
this.someVariable = info;
}
```
will (hopefully) open dialog with prompt for a number

**Comment by dekrain** [comment]
Here's also a code for my "pen controller morph", which spawns a turtle and allows user to control it using buttons. https://gist.github.com/dekrain/4b71a5cd7310fc050e61031bb0aefaf6

**Comment by Botcho3003** [comment]
> ... will open dialog with prompt for a number

Thanks! It works!

**Comment by Botcho3003** [comment]
> ... will open dialog with prompt for a number
Sorry if I keep bothering you - how can I do that it reports the field in the text input?

**Comment by Botcho3003** [comment]
> The text input is created with 7-th argument of `prompt` method set to `false` or `undefined` (isNumeric).

I mean a reporter block that when executed opens the dialog and then reports the value in the text field.
And is it possible to create a message without a text input but just a text and custom buttons?

**Comment by dekrain** [comment]
Then, the reporter block has to be in sort of a busy wait to check if dialog is closed. Then, yes, it could report the content of input field.

The custom dialog can be created using some API, like `.addButton` or even `.add(morph)`.

**Comment by Botcho3003** [comment]
> Then, the reporter block has to be in sort of a busy wait to check if dialog is closed. Then, yes, it could report the content of input field.
The custom dialog can be created using some API, like `.addButton` or even `.add(morph)`.

Thanks!
