### ISSUE TITLE
SNAP listed as a "possible bulk sender"

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2073]
"These emails were blocked by our spam filtering. Microsoft has this sender listed as a possible bulk sender."

That is the reason our IT people gave me as to why I did not receive an email from SNAP to verify my new SNAP account,

I'll be glad if you can figure out a way to fix this issue because it can disrupt the momentum of people I introduce to SNAP.  It also makes me look bad by association, and believe me, I don't need any help in looking bad - I do that well enough myself!  :>)

**Comment by cycomachead** [comment]
Do you have any more info to go on? Also could you share the email domain of your school? (you can email snap-support@bjc.berkeley.edu if you'd rather not post here.) 

I'd like to look into this a little more, though I don't really understand what we can control.

**Comment by jcaldw737** [comment]
Thanks for getting back to me.  Here is what our IT people gave me as the reason I didn't receive the emails about setting up my SNAP account,

"These emails were blocked by our spam filtering. Microsoft has this sender listed as a possible bulk sender."

I just now googled "microsoft bulk sender" and got this:

https://msdn.microsoft.com/en-us/library/dn774177.aspx

Apparently postmaster@snap-cloud.cs10.org has been blacklisted.

so I googled "get off microsoft blacklist" and got some interesting stuff.

Here is my university email address - the one that I used for my SNAP account.
jerome.caldwell@uwrf.edu

If I can do anything else please let me know.  I will have two classes Fall Semester using SNAP and that will mean around 75 students setting up SNAP accounts.  I may be able to get our IT people to let the emails come through - they did let mine come through after I contacted them.

But don't you think other places are using the microsoft blacklist?

**Comment by cycomachead** [comment]
Hmm, apparently logs are only saved for the past 30 days so I can't see if there's any info on our end about why the address failed. If you, or anyone you know, signs up with a ufw.edu let me know and I'll take a second look. 

Being blacklisted is definitely not good. :/ So far, it seems like about 1/10 user signup emails get dropped. When I skim the recent errors, a lot seem to be improperly formatted emails. I'm not sure what kind of error rate to expect. Some info suggests this might be a bit high -- but we're also dealing with school systems which have whitelists and that might be part of a lower rate.

We don't use a dedicated IP address for sending emails. Right now, we're using Mailgun, which just has a pool of IPs they use. I think we could pay some money, but right now funding isn't super solid. 
I'll look into what we can (re?)configure, and if there's anything we can do to increase reliability.
