### ISSUE TITLE
"Ask _ for _" block does not report the value of fellow-clone's (script-)local variable

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap#2078]
Attempting to establish a communication between temporary (fellow-)clones via **ask _ for _** block, I made two versions of my little bubble shooter game of which only one version works (using a workaround), but I would rather not use the workaround, if possible. 

The one with workaround, which does work, is:  https://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=A_color_shooter_with_workaround

And the version that does not work: https://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=A_color_shooter_v2_doesnt_work
 
The problem is in the script you can see below in the screenshot (belonging to the "Sprite" that gets cloned):
![a_color_shooter_v2_doesnt_work - sprite - script2 error](https://user-images.githubusercontent.com/16387241/38503123-83585b8c-3c11-11e8-9af8-e21edff5d479.png)

Because of the issue above, I tried and came up with a workaround (but still I woud rather not use it):
![a_color_shooter_v2_workaround - sprite - script2](https://user-images.githubusercontent.com/16387241/38503226-d7414182-3c11-11e8-94f8-ee6a38de32c1.png)

**Comment by KingDavid12** [comment]
The error is occuring because the second input to the ask block needs to be a ring. Just right click on the variable my_last_round in the ask block and click ringify. What is happening right now is that Snap! is taking the **value** of the variable my_last_round and looking for a variable with that name.

**Comment by DyslexicAwe** [comment]
Thank you, @KingDavid12, for your help and the explanation. Sorry for not replying earlier. 
 
I hope you don't mind if I will ask a stupid question about the ask block. Why it (when it was used in my workaround) didn't require <direction> to be ringified, but it requires my variable to be ringified? Isn't <direction> a variable, too? It stores a value, just like any other variable, isn't it? (I'm just trying to make sense and learn.)

**Comment by DyslexicAwe** [comment]
Oh, I see (pun intended) now! 
Thank you, Joan. 

I would vote for the "ringified pictures" within the OF block's dropdown list because it would make anyone understand it immediately how to use the ask_for_ block, too.

**Comment by DyslexicAwe** [comment]
@KingDavid12 and @jguille2 I ringified it, but still it doesn't work as intended. Why?
![stilldoesntwork](https://user-images.githubusercontent.com/16387241/38612943-8221d4b4-3d88-11e8-9fc2-42bfeb0617ac.png)

**Comment by jguille2** [comment]
Hi @DyslexicAwe,

Yes, "my_last_round" ringified is right, but it must be a local variable (no a script variable). With _local variables_, each clone has its own copy (different values), and you can _ask_ for it.

**Comment by DyslexicAwe** [comment]
Thanks. I haven't found it written that a local variable can store multiple copies of itself, one for each clone, in the Snap! Reference Manual 4.1 - at least not written explicitly enough for me to understand.

**Comment by jguille2** [comment]
Yes. 
Local vars/blocks are only for one sprite.
And clones are sprites.

So, a clone, that is a copy of a original sprite, has the same (but its own) local vars and blocks of its origin.

**Comment by jmoenig** [comment]
Thanks for the clarification, @jguille2 . This can now be closed, I think.
