### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by RCorentin** [jmoenig/Snap#2089]
Hi, I represent a non-profit organization and we would like to use/adapt Snap for a script language like LSL or OSL (Second life’s language)

Our 2 main objectives are :
-An online version and a collaborative one ;
-An incorporate version of the application on the Second Life’s viewer.

So basically we have 3 questions :
-	How can we change the current language and incorporate directly all the code of another language ?
-	How can we add forms or change the colors of a type of blocs ?
-	We already have the code of Snap thanks to your GitHub and its work in a local test but it seems like there are a server/cloud part either for the save and for the collaborative part but we didn’t find any clue about it except in this Git repository : https://github.com/NetsBlox/collaboration
Thanks

**Comment by bromagosa** [comment]
The cloud is actually at https://github.com/bromagosa/SnapCloud :)

**Comment by brianharvey** [comment]
Our cloud server supports saving projects, but not, so far, the online collaborative editing in NetsBlox, which is an extension to Snap<i>!</i>.

About the shapes and colors of blocks, you'd have to modify code in blocks.js; we don't have a GUI for metaprogramming Snap<i>!</i> itself, although that would be an interesting project for a grad student.

About your first question, I'm not sure what you mean by "change the current language."  Do you mean that you want to replace the primitive blocks of Snap<i>!</i> with different primitives?  You can write new blocks in Snap<i>!</i> itself, and then hide our primitives.  If you want to change the _syntax_,  for example to have blocks that return numbers be shaped differently from blocks that return other types of result, that would be harder.

**Comment by gdavid04** [comment]
You can add a category with the following two lines of JavaScript:
```
SpriteMorph.prototype.categories.push(name);
SpriteMorph.prototype.blockColor.tables = new Color(r, g, b);
```
I'm currently working on an extension that allows creating custom categories.
So far you can create categories and delete them (except built-in ones).
The biggest problem for now is moving the custom blocks from the deleted category to the "other" category.
I just don't know how to access all custom blocks and modify their category.
