### ISSUE TITLE
The pen down command should immediately leave a mark

### ISSUE THREAD

**Issue by MMSequeira** [jmoenig/Snap#209]
Executing the ![down](https://f.cloud.github.com/assets/935926/1343825/8d6f87e2-3678-11e3-9a64-8c946cbe248f.png) command does not, at this point, leave any pen mark on stage:
![down - up](https://f.cloud.github.com/assets/935926/1343831/aede0d7c-3678-11e3-94f3-6e971620bb1b.png)

Moving 0 steps does not help: 
![down - move 0 - up](https://f.cloud.github.com/assets/935926/1343844/c890a4e6-3678-11e3-96fd-b5858fe4f568.png)

In order to leave a mark, one has to move at least one step:
![down - move 1 - up](https://f.cloud.github.com/assets/935926/1343849/d64b5860-3678-11e3-9ee5-1e70e91b13e0.png)

Scratch's behavior is preferable, I think: lowering the pen immediately leaves a mark. This is also closer to our intuition of what a real pen would do.

**Comment by bromagosa** [comment]
Closing because [ move (0) steps ] does leave a mark now. We don't want [ pen down ] to leave a mark because https://github.com/jmoenig/Snap/issues/209#issuecomment-26430705
