### ISSUE TITLE
Being curious - what does this mean?

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap#2147]
Upon reading the latest release's short description and its list of new features/changes/fixes by Jens [here](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/releases/tag/4.2.1.2), I am curious what does 

> scopes for "outer script variable" used in `TELL/ASK/OF` blocks

 mean and if someone can show an example of both incorrect and correct scopes for it? 
![image 2](https://user-images.githubusercontent.com/16387241/42733143-a26724a6-882c-11e8-8d72-ec7b6887edc5.png)

**Comment by jmoenig** [comment]
the inner script could not access the outer script variable "a" in this example:

![parallelism glitch script pic](https://user-images.githubusercontent.com/2596285/42738407-82b43890-8883-11e8-9e86-405008c3cfde.png)

likewise the outer script variable "flag" was unavailable in the forked processes of the clone and thus couldn't act as semaphore:

![parallelism glitch script pic 1](https://user-images.githubusercontent.com/2596285/42738419-a76b2b08-8883-11e8-9df0-02820d1cddee.png)

This is the new "Parallelism" library:

![parallelism glitch script pic 2](https://user-images.githubusercontent.com/2596285/42738431-d5db8fdc-8883-11e8-9131-5503d5fddde7.png)

Now the outer script variables scope works fine for these.

**Comment by DyslexicAwe** [comment]
So, if I understand correctily, this is needed in order to make possible for kids to use paralellization _without having to use **more than one** hat script_ (albeit I personally prefer using more than one hat script to achieve parallelization) as one user (nigeldodd) was asking for in the _Snap! user forum [here](https://scratch.mit.edu/discuss/topic/4455/?page=200#post-3140552) (to be able to keep storing all the mouse clicks' coordinates in a list, until any keyboard key is pressed) and you explained in your reply [here](https://scratch.mit.edu/discuss/topic/4455/?page=201#post-3143809) that at the time it was not possible, right?
