### ISSUE TITLE
Recognize the original among the clones?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#2157]
How could I differentiate between a clone and the original sprite? I need to do some diferent things if I click on a clone or if I click on the original sprite (that is creating the clones).

Thanks.

**Comment by jguille2** [comment]
Hi @geaplanet,

You can do different things...

Maybe the easiest is using **_my name_** attribute. Clones have no name.
Then, with something like
![clones1](https://user-images.githubusercontent.com/2926315/43361793-3f2b002a-92da-11e8-884d-1c80da26e02e.png)
only clones will say hello!

You can also use _my other clones_. If you have more than one clone (with only one clone it's not right) only the original sprite shows an empty list.

Joan

**Comment by jmoenig** [comment]
I sometimes make a predicate reporter that checks for a parent sprite:

![isclone](https://user-images.githubusercontent.com/2596285/43388661-061dab78-93ea-11e8-8001-1c5d3b9df8f3.png)

**Comment by jguille2** [comment]
Thanks Jens,
Certainly, your answer is more elegant!
The only problem is if the project uses Snap OOP features. Because then, the _original sprite_ can have an sprite parent.

Joan

**Comment by geaplanet** [comment]
Thanks both.
