### ISSUE TITLE
Could pen draw over all the things in the canvas?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#2158]
Pen draws on the stage, is there any trick to allow me to draw over all sprites in the canvas?

**Comment by jguille2** [comment]
Ups!
Maybe you can use an extra sprite for printing pentrails on the front.

Make a new sprite and uncheck the _dragabble_ checkbox. And use an script like
![pentrails](https://user-images.githubusercontent.com/2926315/43361881-54bcee28-92dd-11e8-82ff-ed694f05721a.png)

Joan

**Comment by DyslexicAwe** [comment]
Joan, I have a question which is related to this one. Is it possible to use a pen as an eraser, using the trick you showed above? Can the value of ![pen_trails pic](https://user-images.githubusercontent.com/16387241/43444040-0199f3ea-94a3-11e8-841b-4e6f82f453b2.png) be changed by changing the transparency to 100% maybe by using map_over for those elements/pixels that were "drawn" by an 'eraser' pen?

**Comment by jguille2** [comment]
Hi @DyslexicAwe,

Yes, we can change color transparency, but the result will not be an eraser tool, because pen only add color! The _compositeOperation_ is the default _source-over_

I suggest you a "hack trick" to implement an eraser tool. I use "pen size" to do it. Negative sizes turn the pen into a eraser tool (and the negative size value is the size of the eraser).

You must run the _hack_
![erasinghack](https://user-images.githubusercontent.com/2926315/43457828-5a5d1852-94c8-11e8-8263-bb43d3a763f7.png)
The code is:
```javascript
SpriteMorph.prototype.setSize = function (size) {
    // pen size
    if (!isNaN(size)) {
        this.size = Math.min(Math.max(+size, -1000), 1000);
    }
};


SpriteMorph.prototype.drawLine = function (start, dest) {
    var stagePos = this.parent.bounds.origin,
        stageScale = this.parent.scale,
        context = this.parent.penTrails().getContext('2d'),
        from = start.subtract(stagePos).divideBy(stageScale),
        to = dest.subtract(stagePos).divideBy(stageScale),
        damagedFrom = from.multiplyBy(stageScale).add(stagePos),
        damagedTo = to.multiplyBy(stageScale).add(stagePos),
        damaged = damagedFrom.rectangle(damagedTo).expandBy(
            Math.max(this.size * stageScale / 2, 1)
        ).intersect(this.parent.visibleBounds()).spread();

    if (this.isDown) {
		context.globalCompositeOperation = (this.size < 0)? 'destination-out' : 'source-over';
        context.lineWidth = Math.abs(this.size);
        context.strokeStyle = this.color.toString();
        if (this.useFlatLineEnds) {
            context.lineCap = 'butt';
            context.lineJoin = 'miter';
        } else {
            context.lineCap = 'round';
            context.lineJoin = 'round';
        }
        context.beginPath();
        context.moveTo(from.x, from.y);
        context.lineTo(to.x, to.y);
        context.stroke();
        if (this.isWarped === false) {
            this.world().broken.push(damaged);
        }
    }
};
```

Joan

**Comment by DyslexicAwe** [comment]
This deserves to be moved into a separate new issue (or question) with your answer to it (Now I am sorry I hijacked the issue by geaplanet and didn't publish my own question. Can it be done now somehow?). Thank you very much.

**Comment by brianharvey** [comment]
On my medium-time-scale list is adding support for penmode commands penpaint, penerase, and penreverse.  These are in the "anything Logo can do, we should do too" category, along with motion modes window, fence, and wrap.

**Comment by bromagosa** [comment]
We now have this functionality thanks to the "paste on" block :)
