### ISSUE TITLE
Ability to Export a list

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#218]
It would be really handy if we could export a list to a text file.
I'm not sure of the best way of handling all cases but it would be helpful for students.

**Comment by cycomachead** [comment]
@jmoenig @brianharvey 

I was working on some stuff for #983 a realized that we could basically export anything from a watcher as text, since every morph has a .toString() method.

**Comment by bromagosa** [comment]
Closing this as per https://github.com/jmoenig/Snap/commit/dab03fac5ded5518d726ff716941c6ff377f0193 and https://github.com/jmoenig/Snap/commit/a681880965e8a724e6bb7a68bb8057f518c701e7.
