### ISSUE TITLE
Costumes are barely first class

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2183]
I saw that the "is" predicate has an option for asking if something is a "costume". But I found nothing that returned costume objects. I looked in the standard libraries and finally discovered that the "pixels" library defines costume primitives. Perhaps others like me may want to program costumes but wasn't concerned with their pixels so may never discover this capability. Perhaps "current costume" in the pixel library should be in Snap! itself.

**Comment by ToonTalk** [comment]
I just noticed that "my" costumes returns a list of costumes. I had assumed that by typing "costume" into the search tool I would see all blocks related to costumes. I think search should include the menu items of blocks.

**Comment by ToonTalk** [comment]
I'm glad to see that at least the manual covers this well.

**Comment by cycomachead** [comment]
This is true of Sounds as well. At the Scratch conference, it took me a while to remember that "my" included sounds. I don't think the current location is super intuitive.

**Comment by jmoenig** [comment]
In Snap5 media is now prominently placed as first-class with many primitives allowing to access both costumes, sounds, microphone input and video. Closing. Thanks!
