### ISSUE TITLE
 CSV Format Weirdness revisited

### ISSUE THREAD

**Issue by backface** [jmoenig/Snap#2191]
I am kind of re-opening issue https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1932 about  "CSV Format Weirdness?" since it was closed but not solved (Or as it seems the merge that was supposed to solve it - https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/1950 - caused issues @jmoenig  and got reverted - https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/1993)

What's the current status or plans on CSV? core or library?

I am having problems parsing CSV file from google's spreadsheets, as this allows single quotes in unquoted strings and the current implementation of parseCSV fails in that case.

![bildschirmfoto_2018-08-17_19-32-12](https://user-images.githubusercontent.com/263257/44280196-45fd9780-a254-11e8-9d44-3464d332ef28.png)

![bildschirmfoto_2018-08-17_19-31-02](https://user-images.githubusercontent.com/263257/44280135-1ea6ca80-a254-11e8-9137-d4b996dc7327.png)

To sum up: The current implementation of CSV parsing is taken from [StackOverflow](https://stackoverflow.com/questions/8493195/how-can-i-parse-a-csv-string-with-javascript-which-contains-comma-in-data/8497474#8497474) and does not follow RFC 4180
This includes export or web publication from google spreadsheet and possibly other sources.

Workarounds or possible solutions
* A solution that seems to works for me is to replace the code in parseCSV with another snippet from the same [StackOverflow](https://stackoverflow.com/a/41563966) site. I might use that locally and include it in TurtleStitch if it seems to pass more test cases.
* The block from @jguille2 mentioned [here](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1932#issuecomment-349142033) work for me

I have a simple test example here:
https://snap.berkeley.edu/snapsource/snap.html#cloud:Username=mash&ProjectName=csv_format_weirdness

**Comment by cycomachead** [comment]
I'm definitely in favor of fixing this.

Here's one other solution, using one of the best JS libraries for dealing with CSVs:
https://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=using%20papa%20parse

If we are going to re-litigate the issue, my vote is that we make CSV processing it's own library and one which uses a known solution -- we have better things to spend time on than CSV parsers and it's pretty easy to make a nice Snap<em>!</em> library out of a good JS one.

**Comment by brianharvey** [comment]
+1.  Of course you would want to package this for users inside a split-by-csv block that checks whether the library is already loaded, and loads it if not.

The bignum library has a more complicated script-loader than yours, I think partly to do it only once and partly to deal with asynchronous loading, but I could be misremembering the latter.  Maybe we need a generic script-loading library?

**Comment by backface** [comment]
+1 for providing functional CSV parsing as a library (including bundling the necessary libraries so it also works offline)

**Comment by cycomachead** [comment]
We should absolutely remove the existing CSV option, but I think it should be more of a "deprecation". 

Whomever makes a PR adding a CSV library should make sure `csv` input option be:
`throw new Error('CSV parsing has moved to the CSV library. Please use the INSERT_CSV_SPLIT_NAME after importing the CSV library.)`

or something.

Ideally, we'd be able to dynamically import libraries for users as a part of the block migrations, but that hasn't been built yet. ;)

**Comment by cycomachead** [comment]
Also, we _really_ need libraries to include an initialization or private blocks function. :/ I hate building libraries that include useless blocks. (Useless to students and other programmers that is.

Not worth waiting on that to make these changes, but just putting it out there. :)

**Comment by brianharvey** [comment]
That should be subsumed in the general internal-definition feature, on the list.

I don't like the throw-error solution.  I think old projects should just have the "csv" replaced with a comma when loaded.

**Comment by cycomachead** [comment]
That’s an interesting option. But it would break some projects without telling people why. I guess I don’t mind it too much, but it would be nice for people to know there is a new csv library if they are using the current split block. 

I guess a ‘warning’ mechanism would be helpful here. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
In the Great Incompatible Change release there should be a warning when you _load_ a project that gets modified during loading.  So if you then edit and save the project, you don't see the message again, and you get the message when you're paying attention, not in the heat of playing a game.

**Comment by jmoenig** [comment]
Okay, revisiting this issue. Does anybody have a good CSV-parser that we can adjust for our purposes?

**Comment by KingDavid12** [comment]
@jmoenig https://github.com/mholt/PapaParse could be a possibility. Its MIT licensed, implements RFC418, and can automatically detect the delimiter for the file. I've never used it, but it's both well maintained, and looks pretty good in terms of what you need.

**Comment by cycomachead** [comment]
Yes  just use papaparse. Isn’t this the thread where I had a very simple JS function to load it? (I’m on my phone.) or if not there’s a few other examples. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by KingDavid12** [comment]
@cycomachead You do have an example using that exact library, I just that I'd bring it back to peoples' minds.

**Comment by jmoenig** [comment]
CSV and JSON support has been completely reimplemented in Snap5 to follow RFC 4180. This should be fixed now. Thanks!
