### ISSUE TITLE
How to set draggable or not draggable property by code?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#2199]
I'm almost sure I've seen this somewhere, but I've been searching for a while and I can not find it.

**Comment by brianharvey** [comment]
I still have to add per-sprite properties to the getters-and-setters library.  Soon.

**Comment by jmoenig** [comment]
There's one I made for this project I was playing with last week, feel free to reuse: https://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Hampelmann

**Comment by jmoenig** [comment]
This is now easily possible and supported in Snap5
