### ISSUE TITLE
Uninformative message when trying to save a large project

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2221]
I have a project that saves fine when it was a few MBs but once it got up to 15 BMs I consistently get

![image](https://user-images.githubusercontent.com/2138696/46482281-3549b680-c7ed-11e8-8110-028979b0575c.png)

Perhaps the message could be one that explains the project is too big for the cloud and advising to save it other ways.

**Comment by cycomachead** [comment]
Yeah, this is a bug. It's related to Snap! not properly checking the file size.

**Comment by cycomachead** [comment]
2169
