### ISSUE TITLE
can I use it like blockly?

### ISSUE THREAD

**Issue by theonlygusti** [jmoenig/Snap#2225]
Can I use the drag-and-drop block interface to let people create programs, and then transpire the programs into other languages like javascript.

**Comment by brianharvey** [comment]
Yes and no.  If the program you want to translate uses things like sprite graphics, depending on the Snap<i>!</i> runtime support, then no.  If the program just works with Javascript data types such as numbers and text, then yes, but you have to provide the translations for each Snap<i>!</i> block.  Go to File>Open>Examples>Codification to see how it works.

**Comment by brianharvey** [comment]
Thanks.  Did you look at the Codification example project?  It has translations of selected blocks into three other programming languages.
