### ISSUE TITLE
Readable variable isn't settable

### ISSUE THREAD

**Issue by kephas** [jmoenig/Snap#2234]
With these two definitions:
![let script pic](https://user-images.githubusercontent.com/762421/47536842-b6630d80-d8c2-11e8-8852-929b77e3fdf5.png)
![let script pic 1](https://user-images.githubusercontent.com/762421/47536850-bebb4880-d8c2-11e8-89f0-82e59fb9c132.png)

I can create three variables at once and they are successfully read,e.g. by **say**:
![let script pic 2](https://user-images.githubusercontent.com/762421/47536985-86683a00-d8c3-11e8-8283-25ea635d6343.png)

But I can't set them in the block, as they don't show up in the list of variables of **set**:
![capture du 2018-10-26 02-11-53](https://user-images.githubusercontent.com/762421/47537173-8ae12280-d8c4-11e8-8dfa-7e8bf0cc3f28.png)

**Comment by kephas** [comment]
The code is available in my project [let](https://snap.berkeley.edu/snapsource/snap.html#present:Username=kephasp&ProjectName=let).

**Comment by jmoenig** [comment]
Yeah, I can see what you're doing here. The reason you're not seeing the upvars in the dropdown is that they are defined inside an *input* to a parent block. I've been contemplating whether to show such variables in the drop-down - then your code would work - but my hunch is that once we give in to going meta on variables we'll end up turning Snap into a text based PL.

**Comment by jmoenig** [comment]
that said, you can make your own ```set``` block that lets you drop variable blobs in:

![set_var](https://user-images.githubusercontent.com/2596285/47553720-0dd79c80-d908-11e8-91ca-acc1d6c92bcd.png)

then you can use *that* inside your ```let``` script, and it works:

![let script pic 1](https://user-images.githubusercontent.com/2596285/47553739-1c25b880-d908-11e8-8721-15420a427346.png)

Does that help?

**Comment by kephas** [comment]
Haha, this is exactly what I was about to comment, that it could be a non-issue with this. The evaluation rules of Snap! really are powerful!

**Comment by brianharvey** [comment]
I agree, I don't see what this has to do with text vs. blocks.   Could you elaborate, Jens?

**Comment by towerofnix** [comment]
My view on this..

>The reason you're not seeing the upvars in the dropdown is that they are defined inside an _input_ to a parent block. I've been contemplating whether to show such variables in the drop-down - then your code would work - but my hunch is that once we give in to going meta on variables we'll end up turning Snap into a text based PL.

..is that if we start showing every variable in the menu (or just in general expand the scope of what variables show up in the dropdown), then we're sort of losing some of the intuitive-ity of block based languages. That is, by showing more variables, we get closer to the "text-based" concept of "show all variables that have been referenced" rather than the "block-based" concept of "show just the variables that make sense in the context". (I guess you could make an argument that those variables do (or don't) make sense in this context; shrug.)

Buuuut - I could be on a totally different thread than @jmoenig is!

**Comment by towerofnix** [comment]
Yes, I see what you mean, and agree - the whole "you could make an argument that it does make sense to show those variables". Interested in Jens's thoughts.

**Comment by jmoenig** [comment]
I'm reopening this issue. Y'all convinced me...

**Comment by jmoenig** [comment]
So, the reason I was reluctant about this is that I wanted to encourage programmers to define variables in places where they're *guaranteed* to exist, which isn't the case inside inputs that might or might not be evaluated. What convinced me was @kephas ' symmetry argument, that those - uncertain - variables are *readable* in any case. Therefore I'm marking this as a bug and I'm committing a patch to fix it. Thanks for the good discussion!

**Comment by jmoenig** [comment]
Hi @kephas I've just patched the current dev version with a fix to this. Now your ```let``` project displays those variables in the ```set``` block for me:

https://snap.berkeley.edu/snapsource/dev

Could you maybe do a quick check and see if it works as you'd expect?
Thanks!

**Comment by jguille2** [comment]
Hi,
I've tested de _dev_ version and the dropdown is running OK, showing the vars defined inside the inputs.

Joan

**Comment by kephas** [comment]
Both the SET dropdown and the keyboard interface show the variable, great!
