### ISSUE TITLE
Unclear how to tell if a sprite is showing or hidden

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2241]
If there is a way to ask a sprite if it is hidden it isn't easy to find in Snap! or in the manual.

**Comment by jguille2** [comment]
Hi @ToonTalk ,
I don't find this information either.

If you want to call this info, you can use

![callisvisible](https://user-images.githubusercontent.com/2926315/47784439-e74da300-dd05-11e8-93a8-ded2e53c0386.png)

and, of course, you can _ask_ other sprites for this info

![askisvisible](https://user-images.githubusercontent.com/2926315/47784465-fc2a3680-dd05-11e8-921a-b4df108cd889.png)

Joan

**Comment by brianharvey** [comment]
Yup, this should be in the Eisenbergification library.  I'll catch up eventually.

**Comment by jguille2** [comment]
Hi Brian,
But Eisenbergification library adds GUI and project settings.

Maybe this _visible?_ reporter can be added to the _my_ block dropdown. Current _my_ options report  rotation x and y, center x and y, dangling?... that are properties of the sprite (like this).

Joan

**Comment by brianharvey** [comment]
It was always my plan to include getters and setters for the sprite-owned things; Jens wouldn't let me do it until the OOP stuff was implemented, because that changed how sprites are organized.  But now I'll catch up, and yes, that'll include extending MY.

**Comment by jmoenig** [comment]
there is now a primitive predicate in the Looks category for this (5.0)
