### ISSUE TITLE
export issues 

### ISSUE THREAD

**Issue by Andrey-TEALS** [jmoenig/Snap#2251]
Hi everybody!

Thank you for a great product!

I trying to find a reason why students can't export projects. 
I am also open to hints what might be wrong on my end (I do not see any discussion on Internet for my issue).
Below are additional details.

I am working with remote students and when they export project into xml, import fails.
Yet, everything works on my end (as usual with developers!). I believe they use Chrome (>=58.0)

I looked inside trying to fix them by hand. File with next tags before <sprites> looks like this:
`
<costumes></costumes>
<sounds></sounds>
`

My exported file has extra list tags:

`<costumes><list id="1"></list></costumes>
<sounds><list id="2"></list></sounds>
`

I made manual change and xml file is successfully loaded. 
Unfortunately this have not fully addressed my issue as I see that export did lost some blocks (they are on student's screen shorts).

What could be wrong on my end? 

Thanks you for looking.

Andrey

**Comment by jmoenig** [comment]
Hi Audry,
bummer! I've seen this happen - but so far only very rarely. The last time I saw it was two weeks ago when someone was actually using IE. I'd love to look into this and maybe make it so that at least the projects load even when the costumes-list is missing (another possible reason might be low memory situations, although that's just a speculation that probably doesn't make much sense). Could you maybe send me one or several of the brokern XMLs (either via a Dropbox link or you can also paste them in here). That would help me address this issue a lot.
Thanks!
Jens

**Comment by jguille2** [comment]
Hi,
I only want to note, that it seems the same issue that #2224.

It was using "Save to the cloud", but the problem seems the same. Certainly, we must take care of this.

**Comment by Andrey-TEALS** [comment]
Hi, 

I agree,  #2224 do match my description. Yey! I am not alone :)
I said that students use Chrome, but looking close (after reading #2224) I see that screenshort is actually from IE. I hope that switching to Chrome would help me today.

I changed extention from XML to LOG (editor is refusing XML documents)
[PROJECT 9 11-8-2018.log](https://github.com/jmoenig/Snap/files/2565893/PROJECT.9.11-8-2018.log)

Here is original problem (I have not shared it before). This is result of pressing "Share"
![pastedimage 1](https://user-images.githubusercontent.com/44883602/48263598-a126cc80-e3f4-11e8-856c-530e96ff3518.png)

Screenshort and project file are for the same code.

I have another similar project, and I see that in both cases "loop forever" is empty. This might be a hint for a root cause?

Thank you!

**Comment by jmoenig** [comment]
So, this is good. I think the root of the problem is IE. That is very consistent with what happened in the other cases. Let me look into this. Thanks!

**Comment by cycomachead** [comment]
> One student tried to reuse prior project (from IE), it is shared successfully, but when opened has same "list" issue.

When you open the shared project, the URL will contain `#present:...`. If you change the `present` to `dl`, Snap<em>!</em> will download the XML instead of trying to load it, which should let you recover the project manually.

**Comment by jmoenig** [comment]
I'm just now preparing a patch that will let you/your students open such corrupted projects anyway, hang on for a few days at max!

**Comment by jmoenig** [comment]
thanks, @Andrey-TEALS !
BTW I did end up patching the upcoming maintenance release of Snap! with a fix that doesn't require you to edit or modify the XML files. It's already online for testing: https://snap.berkeley.edu/snapsource/dev and you should be able to load those projects that have been corrupted by IE with it. It won't complain, but if you open a JS console you'll see notificiations about the issues it encountered.
