### ISSUE TITLE
Error with JS custom reporter

### ISSUE THREAD

**Issue by rdococ** [jmoenig/Snap#2252]
I have a feeling that this *could* be a problem with my code rather than with Snap!, but I'm completely unsure. Anyways, I defined a "content of" reporter block inspired by #1888:

![content of definition](https://user-images.githubusercontent.com/3169568/48317982-853c4a00-e5f1-11e8-8588-099d14b8d310.png)

Here are the six test cases:

![content of cases](https://user-images.githubusercontent.com/3169568/48317994-a735cc80-e5f1-11e8-846e-a6ee6d056106.png)

All of the cases work fine, except for the case that is highlighted in red. I'm not sure why, but the error I'm getting is that "a variable of '' does not exist in this context". I don't know why the block would be trying to access an "empty string" variable, though.

Am I approaching the definition of the block incorrectly, or is this an actual bug of some sort?

Project link: https://snap.berkeley.edu/snapsource/snap.html#present:Username=rdococ&ProjectName=Content%20of%20reporter%20testing

**Comment by brianharvey** [comment]
Well, for one thing, since METHOD is a command, you should RUN it, not CALL it.  But the immediate problem here is that you don't want a ring around the CONTENT OF block, since it is _called_ to generate the block that you want to run.  I don't think your other tests work, either; they just don't give error messages.

**Comment by rdococ** [comment]
> Well, for one thing, since METHOD is a command, you should RUN it, not CALL it. But the immediate problem here is that you don't want a ring around the CONTENT OF block, since it is _called_ to generate the block that you want to run. I don't think your other tests work, either; they just don't give error messages.

All six cases **should** return a block to be called - that is why all of the cases with "call" blocks also have rings around the reporter itself. All of them report the content of the local method from the intended receiver (although both sprites originally had the same definition so you couldn't tell them apart; I've changed that now).

The confusion stems from the fact that I think that wrapping a ring around something, and then calling that ringed thing, should have the same result as evaluating that thing without a ring or "call" block.
