### ISSUE TITLE
Prevent Saving New Projects to Local Storage

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#2254]
The first step of deprecating local storage is to prevent people from saving new projects to local storage. 

There are two ways to do this:
* apply the setting only to users who have no local storage projects (i.e. just hide the icons)
* completely remove the local option from the save dialog.

**Comment by brianharvey** [comment]
Completely remove is the right thing.  (But keep it in the Open dialog if there are existing localstore projects.)

In addition, add a new button "Save to Disk" that replaces the Snap<i>!</i> dialog with a system open dialog, equivalent to "export project" but maybe easier for users to find.

**Comment by cycomachead** [comment]
Yeah. See the other subsequent issues. The point of removing is to actually eventually remove the code which is a maintenance burden long term. 

The save as is interesting that should be a different issue. Browsers are annoying here. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
This was done somewhere along the way, include brian's suggestion.
