### ISSUE TITLE
Load Failed: Expected "=" after attribute name

### ISSUE THREAD

**Issue by sean-morris** [jmoenig/Snap#226]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=JeromeWei&ProjectName=hangman

UserName: JeromeWei
Password: 123456

This popped up; any ideas?

**Comment by gilpin-bmchs** [comment]
I have the same issue with a student today.  All of his projects that he named without any text ex "1.1" or "2.3" are all broken now with the same error.  All other projects named with text ex: "1.1 Lab" work just fine.  Hope this helps in tracking the bug.
