### ISSUE TITLE
Editing block loses values of booleans

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2260]
When I edited 'test' to 'test edited' the number remains but the boolean is reset.

![image](https://user-images.githubusercontent.com/2138696/48345865-261e1a00-e671-11e8-9205-ce0bbe717d46.png)

Here's what remains after the edit:

![image](https://user-images.githubusercontent.com/2138696/48345884-38985380-e671-11e8-9213-5ce178e40b65.png)

**Comment by jmoenig** [comment]
Ugh. Thanks, Ken. I don't know how often I've fixed this particular thing...

**Comment by jmoenig** [comment]
Okay, turns out I only ever fixed the variadic version of this, never the plain one ;-)
Fix is coming...

**Comment by jmoenig** [comment]
fixed for the next maintenance release, upcoming tomorrow or later this week.
Already testable in dev: https://snap.berkeley.edu/snapsource/dev
Thx!
