### ISSUE TITLE
Display issues after pasting a long string into a 'set' command

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2266]
When I pasted a 100K string into a `set `command I see

![image](https://user-images.githubusercontent.com/2138696/48953190-db3bb680-ef3c-11e8-8e7e-d5d42d6dd98f.png)

When I dragged out a new block then see

![image](https://user-images.githubusercontent.com/2138696/48953242-1342f980-ef3d-11e8-860c-6f114749b9e8.png)

Saving and re-opening the project does not change the fact that the Scripts area is white for that sprite (but not other sprite's scripts area). But other than that it seems all is normal after re-opening.

**Comment by brianharvey** [comment]
So are we closing this one (because it's a duplicate)?

**Comment by ToonTalk** [comment]
Fine with me. To reproduce the problem I copied the contents of https://www.metoffice.gov.uk/pub/data/weather/uk/climate/stationdata/oxforddata.txt starting from 1853 into the input field of `set`.

**Comment by bromagosa** [comment]
@ToonTalk, as a workaround while this isn't fixed, you can use import in your variable watcher:

![imatge](https://user-images.githubusercontent.com/1016697/49009389-c47da580-f170-11e8-8133-059afe9b19ba.png)

![imatge](https://user-images.githubusercontent.com/1016697/49009439-dfe8b080-f170-11e8-8f6c-d48c59e3f18a.png)

Or the `( url [ ] )` block with some CORS proxy as an intermediary:

![untitled script pic](https://user-images.githubusercontent.com/1016697/49009531-18888a00-f171-11e8-8a06-7861ce12631b.png)

**Comment by ToonTalk** [comment]
Thanks that is helpful.
