### ISSUE TITLE
Overly complex example of using split by CSV in the manual

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2268]
The "Comma-Separated Values" section of the manual suggests one map split by CSV over split by line of the contents of a CSV file. But when I tried applying split by CSV to the contents that worked fine. It seems there is no need for all that complexity.

**Comment by jmoenig** [comment]
Yeah, that's my fault. The new simple way is only one or two weeks old, it's what I'm currently working on, so Brian didn't get a chance to update it yet ;-)

Background: We're currently working on a "Data Science + Media Computation" course and I'm shamelessly adding all the feature I need for this to Snap as we go... This is right now only half-baked, but already there's some stuff in the "Frequency Distribution Analysis" library that is great fun.

**Comment by jmoenig** [comment]
I see that @brianharvey has since rewritten the manual, including this part about csv. Thanks, closing...
