### ISSUE TITLE
Is there a way to hide the entire palette? 

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2273]
I have many Snap! iframes on web pages that contain just the blocks in the scripting area needed for an exercise. The palette area can be expanded but not shrunk beyond the display of the block categories. I'd be happy with hiding or shrinking it so much less space is taken up. Not essential but nice would be a way for a user to restore the palette. I would be happy with a little JavaScript that could accomplish any of this.

**Comment by bromagosa** [comment]
Here's an easy way to do that:

![untitled script pic](https://user-images.githubusercontent.com/1016697/49288878-3cfea200-f4a2-11e8-89bc-a3232534076e.png)

(block
[palette visibility.zip](https://github.com/jmoenig/Snap/files/2633171/palette.visibility.zip)
 attached)

**Comment by bromagosa** [comment]
closing this :)
