### ISSUE TITLE
[Request] Modified "run" block to allow running two blocks at the same time (in a single clone)

### ISSUE THREAD

**Issue by Axis-Denied** [jmoenig/Snap#2275]
If this already exists, please tell me how to do it...
A mechanism that would allow a clone to run two blocks of code in parallel would be great, and just adding more block inputs to the "run" block could help.
I have a clone that I want to spin and move to a certain x,y value at the same time, but that can't be done using broadcast _(I think)_.

Thanks for reading!

**Comment by jmoenig** [comment]
It exists: It's the "Parallelization" library (currently the bottom most one in the list)!

**Comment by Axis-Denied** [comment]
sorry about that...
_I should look harder next time..._
