### ISSUE TITLE
Preloading a Project when Starting  Snap !

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap#2284]
Hello,

It seems that loading a shared (public) project from the Snap! cloud leeds to some strange effects of the IDE, and clones :
I have two examples you can look at :
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=2018-09-21-SinusCosinus2
and 
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=2018-10-12-ICN2.AnimationDeCarres

![image](https://user-images.githubusercontent.com/17542520/49632526-7b024580-fa0f-11e8-868b-e7313393e0da.png)

**Comment by nathalierun** [comment]
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=2018-09-01-1S2-FonctionsCarteMentale.bis

**Comment by jmoenig** [comment]
Whoa! that's *interesting* and certainly a bug! Thank you, Nathalie, I have to investigate.

**Comment by nathalierun** [comment]
Strangely, this one doesn't lead to any problem
https://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=2017-12-24-JoyeuxNoel1

**Comment by jmoenig** [comment]
Hmm... there are *two* issues here, right?

(1) the palette is shown when it should'nt be
(2) the project starts even when not all assets are loaded

I've known about the second issue for some time, and have a plan how to address it, but I'm surprised about the first issue. 

Let me look into this some more.
Thanks!

**Comment by jmoenig** [comment]
I think I know the reason for the bug that shows the palette in presentation mode here: It's a glitch in my code that updates the palette whenever the ```inherit``` block gets executed. 

Now let's fix this....

**Comment by jmoenig** [comment]
Hi Nathalie, I think I found the IDE issue. I've just pushed a fix for it and it looks like it works for your project in the dev version:

https://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=nathalierun&ProjectName=2018-09-21-SinusCosinus2

The second issue will take some more effort and also some more time. But I'm working on it.
Thanks for reporting this bug!

**Comment by nathalierun** [comment]
Thank you Jens ! It works nice now...
