### ISSUE TITLE
Speed up open dialog by caching project list?

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2291]
I'm noticing that when I open an Open dialog, I spend quite a while looking at a project list that says "empty" (which it shouldn't, by the way, so as not to panic users) until it finally downloads my project list from the server.

Would it be possible to cache the project list in the client after the first Open, so that later ones would start much faster?  If necessary we could have a complicated checksum to make sure the list hasn't changed between opens, but honestly I'd rather have it slightly wrong than slow!  And unless it's a shared account, updating the cached list on "Save As," sharing, and unsharing should be enough.

**Comment by bromagosa** [comment]
How many seconds are you waiting for your project list to fill up? This has gotten considerably faster with the new cloud. It used to take about 5 secs for me to get the list, but it's now under a second.

You may be noticing a little longer delay because you have almost 4 times as many projects as I do (383 vs. 108), but there are currently only ~400 users with more than 100 projects, so only (400 / 277899) * 100 = 0.14% of our users are having to wait longer than a second to retrieve the whole thing.

Not saying it couldn't be sped up, but it's maybe not our top priority given the small percentage of users that would benefit from it and the amount of stuff that needs to be done at the moment.

**Comment by brianharvey** [comment]
I would be less concerned about it if we could stop it from saying "empty" while it's loading.  That's really scary.  Apart from that, I'm not saying it has to be first priority, but pretty often I open a different project every 10 minutes or so, and it gets annoying after a while.  But okay, we'll put it on the long term list.

Although now I think of it, I want the same feature for costumes and sounds!

**Comment by bromagosa** [comment]
Yep. We need thumbnails (and categories) for costumes. There was [a PR](https://github.com/jmoenig/Snap/pull/1666) addressing this a long time ago, but someone would need to resolve its conflicts and clean it up. I seem to remember it had a bunch of issues.

**Comment by cycomachead** [comment]
Also, caching:
We should always leverage browser caching where sensible, but remember that this can lead to stale data. @brianharvey How often are you switching projects? 

What I would propose:
* Setting cache-control headers with a reasonably short timeline (3-5 minutes?) This is fine on it's own, but I worry could lead to stale data. 
* seeing if it's easy to invalidate the cache on project save
* if not, use the last modified header (most recent project updated timestamp) to help browsers update the cache -- that's pretty easy to add from a query.

**Comment by brianharvey** [comment]
On 1/12/19 12:37 AM, Michael Ball wrote:
> @brianharvey How often are you switching projects?

I dunno, once in a while.  But the client should be able to update its 
picture of what projects I have, as I save or delete projects.

**Comment by cycomachead** [comment]
The only sensible way to do that is to make a request to server. And with the social site there’s going to be more frequent project updates (ie published status or descriptions or titles changing) that means the updates won’t just happen from one place. 

It’s possible to do, but annoying to get right. Speeding up the backend is probably much easier, at least given the linked issue above.

**Comment by brianharvey** [comment]
I don't understand "only sensible."  Hardware caches are controlled by the processor (the client), right?  Not by the memory (the server)?  And, yes, cache coherence is annoying, but the hardware people seem to think it's worth it.

**Comment by cycomachead** [comment]
I mean that maintaining a local copy of a user projects list is essentially maintaining a local copy of part of the database. It's possible to do, but I think it's a lot of work that can lead to bugs. The real challenge is reconciling updates after a delta of time has passed - you essentially have to make a request to the server to get everything that's new. And at that point there's many far simpler options we can get 

We shouldn't need to re-implement caching. Not at that level. It's also not really about the hardware level. 
There's browser caching which we can easily enable, and somewhat easily build controls over automatic cache eviction. On the server, if we need that much more speed, we could enable database level caching which is somewhat tricky but has better ways of managing evictions.

Caching is necessary, absolutely -- but web applications rarely need to reimplement client-side caching. They should take advantage of all the existing setup. Web apps rarely need to implement their own server-side caching. Eventually there will be more to do here, but right now caching is the wrong fix.

But most importantly: **We shouldn't need to cache this.** The ~2-3s are coming directly from our server. It's because the server is trying to check the XML files for project descriptions. I can get my project list to load in .5s or so by just removing the check for project descriptions.

Plus, we can compress/gzip the data to make the transit time much more minimal.

**Comment by brianharvey** [comment]
> It's also not really about the hardware level.

That was a simile.  I think that client-side caching raises exactly the same issues as processor-side caching of memory, and I point to the latter as proof that, at least sometimes, it's worth coping with those issues.

If we can get down to 1/2 second, I guess I can live with that -- provided that it doesn't say "empty" during that 1/2 second!

**Comment by cycomachead** [comment]
> I think that client-side caching raises exactly the same issues as processor-side caching of memory, and I point to the latter as proof that, at least sometimes, it's worth coping with those issues.

My point isn't that it's never worth caching, but that the effort isn't there, especially when we know we can speed things up without caching. 

But also hardware caching is solving an orders of magnitude problem. With some updates, I think we could get the loading down to much less than an order of magnitude between local data and a web request.

Also -- how do you all feel about sorting the projects list by recent first? (If we did that, we could optimize this problem even further, but that's not the reason I'm asking.)

**Comment by brianharvey** [comment]
Well, let's try your solution and see how it feels, instead of arguing in the abstract.  :)

No, recent-first would be good for the first two or three projects, and terrible for all the rest.  But I think it would be a great idea for the search bar in the Open dialog to be prepopulated with the most recent one.

**Comment by bromagosa** [comment]
> @bromagosa it's because we need to do `?updatingnotes=true` for each request.
> [bromagosa/snapCloud#125](https://github.com/bromagosa/snapCloud/issues/125) something I filed a while ago when looking into this. It makes quite a different.

The reason why we need all notes to be there in the project list even before selecting a project is that the search input looks into project notes. I don't know whether anyone else uses this (I think Jens does), but it's extremely useful to me. Lots of my projects use the first line of project notes as a sort of tagging system (I write words like graphics, fractals, game, maths, etc) so I can search for categories of projects.

If I understood correctly, you suggest running a script that reads and parses all 2.000.000 projects from disk and syncs notes into the DB? This will take an extremely long while.

Hey, I suggest moving this discussion to https://github.com/bromagosa/snapCloud/issues/125. It's not about the Snap! editor, it's about the cloud.

**Comment by brianharvey** [comment]
Fwiw, I only search titles, not notes.  Sometimes I'm confused to find something whose title doesn't match my search query.

And, I hate to sound like a broken record, but the part about not seeing "empty" is about the editor!  I would be perfectly happy never to see that, even when the list _is_ empty, if that'd make it easier.

**Comment by bromagosa** [comment]
Then we should rename this issue into "Don't show 'empty' while loading the project list". The title says "Speed up open dialog by caching project list", which is 100% a cloud job.

**Comment by bromagosa** [comment]
And, just to remind you, searching through notes is something you all emphatically made me implement! I can fish out an eternal email thread where there was a big fight over tags, notes and so on, where we all finally agreed that searching through notes would solve all the problems in the World.

**Comment by bromagosa** [comment]
That's *exactly* how it went :laughing:

I'm all for burying the hatchet of already fought battles. Let's focus on how to get project notes in sync without wasting the user's time and hopefully without having to run a script that goes over two million files.

**Comment by jmoenig** [comment]
we've been through tags and folders. Let's stop these *terrible* and often uninformed discussions getting totally out of hand here. Geez, what I'm really afaid of is that our new and shiny Snap forum ends up becoming a place like *this*. That'll really attract novices. NOT.

If you can speed up generating and transferring the project list on the server side, fine. If not, we've got other things at our hand.

**Comment by brianharvey** [comment]
I'm a little scared to suggest this, but:

1.  By default only titles are searched, and it's blindingly fast.
2.  There is a checkbox next to the search bar called "Include notes in search"
3.  When the user checks the box, s/he expects this to take a bit longer.
4.  ... and while s/he's waiting, s/he sees "Working..." not "Empty"!  :)

**Comment by jmoenig** [comment]
Okay. STOP IT. NOW!

**Comment by brianharvey** [comment]
I don't get it.  I'm the one who's up past my bedtime; it's daytime for you.

Yes, Jens, some things are more urgent than others.  But if you don't like talking about a topic, then don't!  Some of us would like to figure out the best possible design, not necessarily to be implemented today.

**Comment by jmoenig** [comment]
We're reiterating endless, *endless* discussions from long ago at every possible chance in *endless* threads. That's so inefficient and so infuriating. There's a simple engineering problem: Speed up the server side for the project list. Can someone just shut up and do it, goddammit? Instead *every* quibble about *everything* gets ridden to death in just about *every* thread.

**Comment by bromagosa** [comment]
I can do it, but unfortunately we need to discuss how. There isn't a Lua `speedup(this)` function. Let's continue [here](https://github.com/bromagosa/snapCloud/issues/125).

**Comment by jmoenig** [comment]
Oh sure. My point is, let's not - by all means - warm up the old toxic discussion about tags and folder in *this* context!

**Comment by bromagosa** [comment]
That was my point too, that's why I said

> I'm all for burying the hatchet of already fought battles. Let's focus on how to get project notes in sync (...)

Let's move on :)

**Comment by brianharvey** [comment]
Sorry, I didn't understand that we were talking about tags and folders; I thought we were talking about searching the notes.  Then Bernat reminded me.  I don't get why that's so terrible, except for the part where I don't always remember everything, which I agree is terrible, but I'm an old man.  Someday you, too, won't remember everything perfectly.

**Comment by cycomachead** [comment]
It’s not a script over two million files though, it’s only projects older than feb 2018 because since then all updates save notes to the DB. 

Anyway, even a long running script is fine — the script can just run in the background. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
I'm going to close this, in favor of discussing the specifics over on the snap cloud repo. 

But, here's a few things to note:

* Only 2.5% of projects in the past year have notes. (that's about 20K out of 800K)
* We are going to have "project collections" -- we we can style as tags or folders or whatever in the not-too-distant future. 
* As the social site becomes more prominent, that will become the best mechanism for finding, sorting, managing and what-not to your projects.

**Comment by brianharvey** [comment]
No, the second (and following) time takes as long as the first time, in 
Chrome.  (Modules box attached, to prove I flushed the cache.)  It does 
seem faster in Firefox, though.

**Comment by jmoenig** [comment]
2.5 secs the first time. Less than 2 secs the following times on Chrome for me.
No problem for me.

**Comment by cycomachead** [comment]
> You know, I'll consider this "issue" solved. Has anybody ever complained?

I mean, nothing is ever fast enough for students. 

You should notice a HUGE difference in the time it takes the request > 2s to < 0.5 in a typical case with > 100 projects where this code is running.

As far as a tangential answer -- if we had proper logging of response times we'd know if the times dropped for everyone. Unfortunately, we don't have that data. I thought we were logging some of it, but the timings don't make sense.
