### ISSUE TITLE
Costumes

### ISSUE THREAD

**Issue by tknight728** [jmoenig/Snap#2294]
There is a very big bug for when you try cloning sprites that have multiple costumes. The clone's costumes will merge if you try to move them on to each other ( I tried to change the order when this happened). Also when the costumes merge there is a second costume that shows up called Null. If you click this costume there appears a shadow that get bigger the more you move your mouse and while this is happening you cannot click on anything in the window. All you have to do to get out of it is to 
right click on the screen. The shadow will still be there but you can click on things again. After you click on another sprite the shadow will leave. Another thing that might happen will be that when you try to reload your progress the screen gets all messed up with a message saying "cannot read property 'width' of null", (image below). 

![image](https://user-images.githubusercontent.com/26363524/50291333-e8609e00-0433-11e9-9a1e-197db6a729fa.png)

**Comment by bromagosa** [comment]
I definitely can't reproduce this one. I created a sprite, drew two costumes, cloned it, then dragged a costume from one of the clones into the other, and the costume got copied correctly. I tried that several times and in different orders without running into any issues.

There must be something else to it. Can you try to pin the issue down to the minimum steps that cause it so we can reproduce it?

**Comment by jmoenig** [comment]
Internet Explorer?

Von meinem iPhone gesendet

**Comment by jguille2** [comment]
Hi @bromagosa and @jmoenig ,

I can reproduce these strange behaviors in Chrome and Firefox. We have a problem with the costumes of the "explicit clones".
To test...
- Make one or more costumes of a Sprite.
- Clone (from the corral) that Sprite.
- The new sprite (Sprite(2)) will have the same costumes. But if you try to move these costumes (change the order) you will have strange behaviors (the picture disappears, the pictures  change...)

**Comment by jmoenig** [comment]
*That* I can fix... Thank you, @jguille2 !
