### ISSUE TITLE
Bug: List blocks have disappeared under variables category

### ISSUE THREAD

**Issue by nrajpurkar** [jmoenig/Snap#2299]
Hi there,

A student of mine ran into this issue today where all the blocks except for the variables she had made disappeared. I had her resolve this by creating a new project and copying the work over. Is there a way to get them to reappear when this happens?

![image](https://user-images.githubusercontent.com/12765610/50649099-d1d93d00-0f31-11e9-96b7-a063dab35f95.png)

**Comment by brianharvey** [comment]
It's possible to hide blocks in the palette by right-clicking on them and choosing "hide."  My first guess is that the next student over did that as a practical joke, so the way to fix it is to right-click on the background of the palette and choose "show primitives."  If that doesn't work, write again.
