### ISSUE TITLE
Should closing a child table view close the parent?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2320]
When I click OK here:

![image](https://user-images.githubusercontent.com/2138696/52332483-ba600900-2a35-11e9-9812-cc099bc47a6f.png)

Both views disappear.

I might want to look at both sublists. True I can set the entire list to a global variable and then inspect sublists but is the closing of both views a good design?

**Comment by jmoenig** [comment]
Hi Ken! those two views are different kinds of views. One is the result-balloon, it is a temporary widget that - like a pop-up menu - disappears when you click elsewhere. The other is a dialog box that stays around until you close it. Did you know that you can turn the temporary result balloon of a table into a permanent dialog box simply by double-clicking on its header? That way all the views will become dialog boxes.

**Comment by ToonTalk** [comment]
Double clicking the header is very nice but not sure how I should have discovered that.

**Comment by ToonTalk** [comment]
Maybe there should be more tooltips -- e.g. like the one for creating a new turtle.

**Comment by jmoenig** [comment]
yeah, it's somewhat hidden. Although, old Smalltalkers might be checking the bubble's context menu :-)

<img width="512" alt="screen shot 2019-02-06 at 11 28 37" src="https://user-images.githubusercontent.com/2596285/52335387-946d4100-2a02-11e9-80c5-9200b11df3fb.png">
