### ISSUE TITLE
Does it make sense to have show/hide for the background?

### ISSUE THREAD

**Issue by normanbauer** [jmoenig/Snap#2325]
One of my students used the hide block for the background. This caused he stage to go dark and nothing appeared on the stage. Does this make sense?

**Comment by brianharvey** [comment]
Hahaha!  Good catch!  No, if anything, the background should disappear but the sprites remain.  Imho.

**Comment by jmoenig** [comment]
That's absolutely intentional! We added "show" and "hide" blocks to the stager 5 years ago, among other things, so scripts on the stage could control the visibility of sprites. If you only wish to "hide" the stage without all the sprites you can user the "ghost" effect on it, btw.
