### ISSUE TITLE
Paint Editor is lacking text support

### ISSUE THREAD

**Issue by MrFlash67** [jmoenig/Snap#234]
The Paint Editor is lacking a text add/edit feature. I would of thought that this would of been essential for a paint editor. Even only one font would be fine.

I have included a self-referential image from S2 below.
![screen shot 2013-11-19 at 12 32 07 pm](https://f.cloud.github.com/assets/4315979/1568131/ae6f3578-50a9-11e3-9760-a16350868bf7.png)

**Comment by euribe98** [comment]
Hello,
Was this enhancement addressed?  I don't see a text feature in the costumes editor
<img width="690" alt="screen shot 2018-04-11 at 10 56 27 am" src="https://user-images.githubusercontent.com/9489474/38634505-8978bd38-3d77-11e8-8f93-96bd3839419e.png">
