### ISSUE TITLE
Question: How is the ghost effect incremented/set?

### ISSUE THREAD

**Issue by Axis-Denied** [jmoenig/Snap#2356]
This would be extremely helpful, as I would be able to reverse the process to change the alpha value to find the original ghost value, as all of my efforts to do so often result in a value that is almost what I set it to (e.g. getting 1.000009 when the original ghost value is 1).
Come to think of it, being able to sense what value the graphic effects are would be a huge help, given that it would be something that would make a great primitive.
The reason I wanted to find this was because I wanted to animate the ghost effect, but I can't do that without a reporter that reports its current value.

**Comment by jguille2** [comment]
Hi @Axis-Denied ,

Yes, these reporters could be interesting... Maybe inside "MY" block, or into the "OF" block could be a "effects" submenu with these values.

In the meantime, you can build your workaround. The "graphicsValues" sprite property is an object with the value of all those effects. All effects except "ghost" that is related to the "alpha" value. Certainly, "alpha" is the opposite: "ghost" is "transparency" and "alpha" is "opacity" and "ghost" is (0-100) and "alpha" is (0-1).

So you can do...
![spriteEffects](https://user-images.githubusercontent.com/2926315/54446707-dd25c180-4747-11e9-931e-9c5eb2613024.png)
... and the same with the other effects ("wirl", "pixelate"...)

And, of course, you can build your own custom blocks to offer this to your students.

Joan

**Comment by Axis-Denied** [comment]
I tried your solution, and it works fine, but it starts to fall apart when animation is concerned.
(In case you didn't already know, I'm trying to use the animation library with ghost)
Whenever I attempt to animate the effect, an interesting thing occurs:
Ghost will change to zero during the entire time it is being animated. I don't know if this is because of the round block you used, but nothing seems to get it to do otherwise. I even tried to show a variable that was constantly reporting the ghost value, and it was at zero.
This could also be due to how animation works as a whole, as I believe it sets a destination and a starting point, and uses easing to go from point A to B.
Removing the round block seems to produce the same effect, and I'm not sure what the reason for this could be.
As of now, it seems as though animating ghost, unlike the other graphic effects, seems to be impossible at the moment.

**Comment by jmoenig** [comment]
(psst:)

![animate_ghost_effect](https://user-images.githubusercontent.com/2596285/55024000-41753a80-4ffe-11e9-86a2-4cbd4ebaf8a2.png)

**Comment by jmoenig** [comment]
in Snap5 there are now reporters for graphic effects, so we don't need JS funcs for this anymore. Closing
