### ISSUE TITLE
Costumes menu not opening

### ISSUE THREAD

**Issue by RobertFeyerharm** [jmoenig/Snap#2357]
The Costumes menu isn't opening on the main Snap! page.

After clicking on the Document button and then "Costumes . . ." the program hangs with the "Opening Costumes . . ." message displayed. 

After a few more clicks, I get the message:
"berkeley.edu is not responding due to a long running script." with a "Stop script" button.

**Comment by jmoenig** [comment]
this looks like a server wasn't responding. Confirming that importing costumes does work. Closing
