### ISSUE TITLE
Lego Wedo

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2363]
I am having trouble getting Lego Wedo working again. With the help in issue 1137 I did succesd a while ago.  But now I can't find the menu option mentioned here

click on the file menu, select "Import extension..."

Also the link in 1137 to a working SNAP Lego project doesn't seem to work.

Help?

**Comment by jguille2** [comment]
Hi @jcaldw737 ,

I think there are two issues here.

- First, do you remember the "https" issue? S2Bot runs an "http" server. So you must run Snap! over http. For example on [http://extensions.snap.berkeley.edu/snap.html#](http://extensions.snap.berkeley.edu/snap.html#).

- Second. What version of S2Bot are you running? I think that Picaxe people changed the "http port" i some version. Take care you are using the blocks of the right version. For example, I think you have commented an old example of #1137 and those blocks are not running ok over S2bot current version.
If you download current version, you can get the right blocks (Snap! template) from S2Bot itself.

To make the test easier, you can try [this project](http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo2_car2) and it is running OK with current S2Bot version. I just created it and I verified it.

It uses motors (Motion category), color lights (Looks), play notes (Sound) and ultrasound sensor (Sensing). It plays with a typical Wedo car (one motor and a front ultrasound sensor)
 
![wedo](https://user-images.githubusercontent.com/2926315/55020348-f146aa00-4ff6-11e9-8a0e-126f8f0db2a6.png)

Joan

**Comment by jcaldw737** [comment]
THANK YOU SO VERY MUCH for responding so quickly and with such a thorough answer.  I am really looking forward to this evening when I can make use of your much appreciated efforts!

**Comment by jguille2** [comment]
You're welcome.

We wait for your feedback.

Joan

**Comment by jguille2** [comment]
Ah @jcaldw737 , another question!!

I haven't asked you about your Wedo model!!

My example is for Wedo2 (connected by Bluetooth). If you are connecting a Wedo1 (connected by USB), the ideas are the same (-Be sure to run Snap! over http (extensions.snap.berkeley.edu) and -Take the right blocks) but the example done will not work for you.

I think the changes I've commented on http ports (between s2bot versions) are not true. I was comparing the blocks of the project you had commented (and they were for Wedo1) with the blocks I was watching (and they were for Wedo2).

Joan

**Comment by jcaldw737** [comment]
We connect via sub

**Comment by jcaldw737** [comment]
Via usb

**Comment by jguille2** [comment]
So, don't use my example (is for Wedo2).

I think you can run the other (old) example on [http://extensions.snap.berkeley.edu/snap.html](http://extensions.snap.berkeley.edu/snap.html) and it will run ok. Anyway, check the blocks (the template) that S2Bot offer you.
Any problem, post here, and I try to test it (I think I can get a Wedo1 to test).

Joan

**Comment by jcaldw737** [comment]
Sorry, but I am confused.  when I click  [http://extensions.snap.berkeley.edu/snap.html](url) , the project that comes up doesn't have any wedo blocks.  

But when I click on 
[http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo2_car2](url) I do get the wedo2 blocks.

**Comment by jcaldw737** [comment]
IT IS RUNNING! Thank you so much for all your help!

**Comment by jguille2** [comment]
Hi @jcaldw737 ,
I guess you are running the right template now over a http snap!

I just had assembled and shared [this project](http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1) to show it more easily.

Maybe you can close this issue, and also #1137.

Joan

**Comment by jcaldw737** [comment]
Got your new project! Thanks for it and all your help! I really needed it!

This issue is closed and I will also close #1137

**Comment by seteahconnoc** [comment]
Hi. I want to use a WeDo with "Snap!" via USB by using this project:

http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1

Sadly, I'm not successful. Do you have any suggestions? Do I have to do some settings in advance? Feel free to ask for further details.

Thanks in advance.

**Comment by jguille2** [comment]
Hi @seteahconnoc,
First of all, are you using and running [S2Bot software](http://www.picaxe.com/Teaching/Other-Software/Scratch-Helper-Apps)?
Check this! Running S2Bot you will see if the connection is ok (and you see sensor values in its console).
And there is another problem, we can continue this issue...
Joan
