### ISSUE TITLE
Problems with the "open" dialog after a local saving

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap#2367]
Hi,
After having saved a project in local, the "Open" menu is not running OK.

Joan

**Comment by jmoenig** [comment]
Hi Joan,
can you explain more about "local"? Is that the saving to the browser's localstorage option? Because I've taken that option out in the Snap5 version. So, you shouldn't even be able to save to "local" anymore...
Thanks!

**Comment by jguille2** [comment]
Yes, I know.
But you still can choose "computer" on the saving action (really, it does an xml export action). And then, after this "saving" (exporting), that problem appears: you "can't" open a new project from the cloud.

(Yes, "you can", because you can choose "New" and, after this, "Open" is again running ok. But it is a bug).

Why is this appearing?
Because we use "ide.source =  'local'" when we save our project on "Computer" (yes, exporting, but using the "Save as" feature, and setting projects name and also this "source" to "local").
Then, forgetting this, other code consider 'local' as deprecated, and so... this issue.

Trying to trace the proglem...

- "Open" feature calls a [ProjectDialogMorph](https://github.com/jmoenig/Snap/blob/6d2ed9752c736dab1b765be1f8b76d571678cc15/src/gui.js#L6009)
- This Dialog uses its [setSource function](https://github.com/jmoenig/Snap/blob/6d2ed9752c736dab1b765be1f8b76d571678cc15/src/gui.js#L6422)
- And this function has [the case 'local'](https://github.com/jmoenig/Snap/blob/6d2ed9752c736dab1b765be1f8b76d571678cc15/src/gui.js#L6452) and here is the problem, because it actually does nothing.

Thanks,
Joan

**Comment by jmoenig** [comment]
Thanks, Joan! I'll look into this when I'm done with the current project of adding sound volume and stereo-panning support...
