### ISSUE TITLE
snap anomalies

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2374]
I left several windows of Snap 5 Beta open for a few days, and after some time (and using/unplugging from an external monitor) two windows had weird anomalies and a third was all blank white.

![image](https://user-images.githubusercontent.com/6549787/55654138-906d5d80-57be-11e9-96c4-9dab6ff13d1d.png)

![image](https://user-images.githubusercontent.com/6549787/55654147-9cf1b600-57be-11e9-8013-58acf2250d2c.png)

**Comment by maryfries** [comment]
Here's a video; sorry it's so fast, but you get the idea...

![block-anomalies](https://user-images.githubusercontent.com/6549787/55654755-41c0c300-57c0-11e9-941e-912deab9055f.gif)

**Comment by jmoenig** [comment]
nothing new in Snap5 about the underlying Morphic framework. This looks like the usual issues you get when plugging / unplugging external monitors with different devicePixleRatios (retina / non retina), while leaving a window open. Also, there seems to be a low-memory situation on your device, so the graphics card is running low on textures. More memory - or closing some apps / tabs - should help with that.
