### ISSUE TITLE
item is not deleted of this list

### ISSUE THREAD

**Issue by introlinux** [jmoenig/Snap#2381]
I think I don't understand how "item" works in this block. This is a [little program](https://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=introlinux&ProjectName=aleatori) to random elements in a list, but I do not want to repeat an element that has already come out. I have to delete the element in the list but it doesn't work.
How to delete the item in the list?

Thanks in advance.

**Comment by introlinux** [comment]
Ok, I will need an index. I was confused by the Label block, which reported the contents of the item and printed it.

Any way, is there any block for deleting an item in a list by content?

**Comment by jguille2** [comment]
Hola Antonio!

I think you will find what you want inside the "List utilities" library.

There, we have the block "(#) for each (item) of (list)" And so, this is the same "for each" block, but there you have (#) that it is the "index" of each item.

So, you can delete a list element inside a "for each" loop with the "normal" delete command.

Joan

**Comment by bromagosa** [comment]
Modifying lists while iterating over them could potentially get you into trouble, though. You could also build your own `( index of [ item ] in [ list ] )`. Like this, for example:

![untitled script pic(3)](https://user-images.githubusercontent.com/1016697/56679293-00d41400-66c5-11e9-9cab-b58ff8b1851e.png)

Then use it in your delete block:

![untitled script pic(4)](https://user-images.githubusercontent.com/1016697/56679327-18130180-66c5-11e9-8702-b3c828b06abc.png)

**Comment by introlinux** [comment]
Great ideas! Thanks.
