### ISSUE TITLE
Resizable block/script divider (zoom blocks at any size other than 1 get cutoff)

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#239]
I LOVE zoom blocks, but at any zoom bigger than 1 cuts off all the blocks, so I'd love it if the block/script divider moved also, but short of that, allowing me to change the width of the block area manually would solve the problem. I have a 30" screen and would love to work in zoom=4! (but can't currently because all the blocks are cut off)

**Comment by cycomachead** [comment]
Fixed with 2692f1d4e5c791b9839e700a5c011ddefe63bfe5
