### ISSUE TITLE
Snap! Forum headers

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap#2411]
Hi @bromagosa and @cycomachead 

I have said several times to Bernat, but now it is becoming urgent for the next release. I think this issue is for Michael?

I think we need to change the **left header of our Forums**. We need the same header of the new site: **[Snap!], [Run Snap!], [Explore] and [Forum]**

Perhaps better integration can be done... but I think it is not necessary. But it is a requirement to be able to return to the site after a Forum navigation (current Forum Snap! logo points to the Forum itself). And I think, the same header will help navigation.

Thanks!

Joan

**Comment by cycomachead** [comment]
Yeah it's on the list. It's not as straightforward as I'd hope, though. And there's still a few bugs with the existing header that need to be worked on. 

(Closing since not directly a Snap! issue - though we need to find a place for these things. I guess the forum itself is probably best.)
