### ISSUE TITLE
Unused blocks shows tools

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2415]
If the former tools blocks are really primitives now, they should not show up in "unused blocks."

**Comment by brianharvey** [comment]
Are you in the dev version?  HOFs aren't primitives in the regular version.

Also, if you load a project made pre-5.0, the HOFs are included in the project as custom blocks.

**Comment by maryfries** [comment]
Yes, I was in 5, but it might be an older project...

Sent from my iPhone

On Jun 12, 2019, at 6:07 PM, Brian Harvey <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you in the dev version? HOFs aren't primitives in the regular version.

Also, if you load a project made pre-5.0, the HOFs are included in the project as custom blocks.
