### ISSUE TITLE
version 5 change log or features

### ISSUE THREAD

**Issue by mark-ellul** [jmoenig/Snap#2419]
Hi,

is there a page or somewhere you have documented what's new for version 5?

Regards

Mark

**Comment by bromagosa** [comment]
Here it is:

https://github.com/jmoenig/Snap/blob/master/HISTORY.md

(from [this point](https://github.com/jmoenig/Snap/blob/master/HISTORY.md#2019-01-14) upwards)

**Comment by bromagosa** [comment]
Actually, the *In development* section at the top has everything you're looking for :)

**Comment by mark-ellul** [comment]
Thanks, closing issue
