### ISSUE TITLE
put-c-slot-around-existing-code feature prevents placement where I want it

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2420]
In this code:
<img width="289" alt="Google Chrome001" src="https://user-images.githubusercontent.com/3885074/59981564-0f9e5080-95ba-11e9-9f5e-60112ded0a6e.png">
I am trying to put a (new, empty) ifelse block between the goto and the set.  I can't; either I get a white bar between penup and goto, or I get a yellow halo around the code starting with set.

Project attached.  (It's not finished yet; don't try to run it.  :-) )
[mapart.xml.zip](https://github.com/jmoenig/Snap/files/3318524/mapart.xml.zip)

**Comment by jmoenig** [comment]
Works fine for me, just hold it a little more to the right.
<img width="180" alt="drop-in" src="https://user-images.githubusercontent.com/2596285/59982180-85cca280-960e-11e9-86a5-045b2e712432.png">
