### ISSUE TITLE
Snap 5 issue with Snapp standalone creator

### ISSUE THREAD

**Issue by MaestroCaldwell** [jmoenig/Snap#2430]
Just a heads up for those who may run into this issue:
If you have coded recently with the "**go to front**" block in 4.2, the [Snapp standalone creator](http://snapp.citilab.eu) has an issue with the newly changed/updated "**go to front/back layer**" block from Snap 5. I get "a custom block definition is missing," and the rest of my code runs weird as a result (in the exe, not in Snap 5). 
I realize that cross compatibility issues are inevitable after updates, but I thought I'd say something in case others are looking.
Since I can no longer use the old block, in the meantime my workaround is to either:
-Use offline Snap 4.2 to export my xml files, or
-Or I may try to use the "go back # layers" and input a negative number to see if that works.

**Comment by bromagosa** [comment]
You should report this one to https://github.com/adrian-hintze/Snapp. They're separate projects :)

(closing because this doesn't belong to Snap! itself)
