### ISSUE TITLE
Documentation missing for "enhanced support for embedding Snap in other website, thanks, Bernat!"

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2439]
Happy to see this good news but unsure where to find out any details. I couldn't find it in the manual. Issue #719 was closed a year ago. The Stackoverflow discussion of this is 3 years old.

Perhaps the release notes could link to more information.

**Comment by jguille2** [comment]
Hi @ToonTalk,
Is not this "embed feature" self-explanatory enough?
Exploring projects (public ones or your own) you see the "Embed" button for each one. With this option you get the "embed" code, with different options.

You can take that code or learn there those different options for build your own code.

Joan

**Comment by ToonTalk** [comment]
This is very nice. I missed it because I expected there would be a way to embed a project without publishing it. Not that I'm shy about publishing things but sometimes I want to embed a tiny exercise on a page. It doesn't seem appropriate to publish it.

**Comment by jguille2** [comment]
Yes! You can embed your project without publishing it. You only have to share it (the same behavior we had (and have) with the url, to see a project).

So, go to your "my projects" page, and all your shared projects has the "Embed" button available.

Only two questions for Bernat...
- I see a little issue here. When you share/unshare a project, buttons under the project are not updated. In this case, after a "sharing", you don't see the "Embed" options until refreshing.
- And even less important... but maybe we can add "link" button. Yes, I know inside the embed code is also the link... and when "sharing" we have a popup info (with the link). But it can be useful.

Joan

**Comment by bromagosa** [comment]
I've added [an issue](https://github.com/bromagosa/SnapSite/issues/69) to address this when I get the time. Thanks for noticing!
