### ISSUE TITLE
embed feature doesn't include 'allow' options for camera, microphone, etc.

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2441]
So embedding get errors that the camera or microphone isn't allowed.

Adding allow="camera" or the like to the iframe element fixes the problem.

**Comment by bromagosa** [comment]
I believe this should go to https://github.com/bromagosa/SnapSite

**Comment by brianharvey** [comment]
This is git -- it has to have a "send this issue to a different repo" feature!  :)

**Comment by bromagosa** [comment]
There is a "transfer issue" button, but it only works between repos in the same organization / user. In the meantime, good old copy-paste works just fine :)

(closing this)
