### ISSUE TITLE
list watcher looks empty after running script (but list isn't empty)

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2446]
Project: 
[https://snap.berkeley.edu/snapsource/snap.html#present:Username=bh&ProjectName=magic%20sort](https://snap.berkeley.edu/snapsource/snap.html#present:Username=bh&ProjectName=magic%20sort)

Screenshot:
<img width="1098" alt="Google Chrome001" src="https://user-images.githubusercontent.com/3885074/60403034-94eeab80-9b4c-11e9-8b99-888be1cb70cd.png">

To duplicate:  Run script that starts with SCRIPT VARIABLES.  Note that it calls SORT.  Watcher will be correct.  Then, right click on the SORT block, choose RELABEL, choose MAGIC SORT (at the bottom of the menu of blocks).  Then run script again.  The list is correct (check by clicking on its orange blob in the palette) but the watcher has no data.  (It correctly reports the length of 100.)

Resizing the watcher doesn't fix it.  Clicking on the downarrow in its bottom right corner and choosing "1..." does fix it.  This only happens if you go through the steps as above, first with SORT then with MAGIC SORT.

**Comment by jmoenig** [comment]
Yep, I can reproduce this, thanks!

**Comment by jmoenig** [comment]
found it! pushing a fix...
