### ISSUE TITLE
making snap accept links from bjc2.edc.org

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2452]
Hi again! :)

Brian and I have uploaded a draft of the in-progress student materials to bjc2.edc.org so that Tiffany can show teachers something closer to the fall 2019 version in PD this summer and so that we can (once I finish writing up the description of the changes) can post it to Piazza for experienced BJC teachers to familiarize themselves with.

However, **Snap isn't currently opening XML files from bjc2.edc.org. Could you please add that to the whitelist?**

Thanks!

**Comment by cycomachead** [comment]
The whitelist comes from bjc2.edc.org, not Snap<em>!</em>.

The headers need to come from that server, see https://enable-cors.org/server_apache.html
There's possibly a missing htaccess file.

**Comment by cycomachead** [comment]
Oh, it's also possible that the domain needs to be added to the list of known domains in the right llab js file.

(Also, closing because it's not a Snap<em>!</em> issue).

**Comment by maryfries** [comment]
Yes! Got it fixed. Thanks!!
