### ISSUE TITLE
JavaScript version works as intended while Snap! version freezes with external dependency FunTask

### ISSUE THREAD

**Issue by sorenbug** [jmoenig/Snap#2459]
![image](https://user-images.githubusercontent.com/7751296/61573686-a817db80-aa67-11e9-898d-9c48d34605a5.png)

Calling **`λ[say]`**`.run(_ => _)` should be equivalent to the five lines from `var say` (disregarding the **`say`** vs `console.log` discrepancy) yet the Snap! version freezes. I figure it's actually some way I'm misunderstanding the differences in flow between the JS version and _Snap!_ version and not some bug with _Snap!_ though.

The project is available [here](https://snap.berkeley.edu/snapsource/snap.html#present:Username=srnb&ProjectName=lambda3).

**Comment by jmoenig** [comment]
I'm not supporting specific uses of the JS function block, and I specifically caution about using ```invoke()```

**Comment by bromagosa** [comment]
(that said, you may get user support at https://forum.snap.berkeley.edu)
