### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2462]
![image](https://user-images.githubusercontent.com/6549787/61596090-e8dd3500-abcc-11e9-958c-c2341b05b41b.png)

**Comment by bromagosa** [comment]
Hmm... we may need some more context to be able to tell what's going on.

**Comment by jmoenig** [comment]
I can't reproduce this...

**Comment by brianharvey** [comment]
I watched her do it, but neither of us knows what got her into that state.

**Comment by bromagosa** [comment]
Did she maybe log out from another tab? Did the connection drop for a bit?

**Comment by cycomachead** [comment]
Going to close if we can't reproduce, but it's possible local storage or cookies we cleared making it look like you logged out and the menu wasn't refreshed. 

But a second point is that calling logout when there's no user should probably just be a no-op and return an empty 200 response.
