### ISSUE TITLE
"current" option in costumes dropdown in custom block input isn't = to "current"

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2464]
When you use the costumes menu option, the actual input that your custom block gets isn't the costume itself, but rather the text string chosen from the menu.  I wrote a "costume named" block:
![costume-named](https://user-images.githubusercontent.com/3885074/61603391-299b7500-abf2-11e9-95d0-55580e8ecfd5.png)
Note the JOIN block.  Without it, the = test fails.  I'm assuming this is related to the fact that "current" is in italics when you choose it (although not in the dropdown when you pull it down).

P.S.  Maybe we should have made FIND FIRST error if nothing matches the predicate.  It took me a little while to figure out what was happening when I got FALSE and tried to use it later in the program.

**Comment by jmoenig** [comment]
Oh, that's a misunderstanding on your part, you always only get the strings and not what they stand for in these dropdown menus, then you pass them into blocks like ```my``` etc. to get a hold on what you want.

**Comment by brianharvey** [comment]
What??  No, read it again.  I understand perfectly well that what I get is the text.  But the specific text "current" is not equal to itself!  That's the bug.

**Comment by jmoenig** [comment]
Yes, that's right. But you pointed out yourself that that's because it's italicized and therefore should *not* be equal to a user-defined string of the same name. So if the choice is *not* equals to "current" but ```join(choice)``` *is* equals to "current" you know it's the special menu choice, which will appear translated on the outside. I agree it's not perfect for editing these menus, but it's the right solution for localizing special input options without confusing these "system texts" with user-defined names.

**Comment by brianharvey** [comment]
No, I don't buy it.  I mean, yes, for translation purposes you want to know what to translate and what not to.  That's fine.  But I'm a kid, I'm writing a custom block, it takes a costume name input, I look at the menu and the choices I see are turtle, current, alonzo, and banana.  So inside my code I do a case analysis:

if ((name) = (banana)) ...
else if ((name) = (alonzo)) ...
else if ((name) = (current)) ...
else ...

and it doesn't work.  I'm not a guy with 55 years experience debugging other people's code; I'm a kid.  It's not reasonable to expect me to think the font enters into the string comparison.  It's not reasonable to expect me to think to try applying some identity function to the string in the hope that that will lose the font information.  The = block should just compare the text, not the embellishments.  There's no reason the testing _you_ do in the translation code has to impose its need on testing _users_ do.  And, the problematic situation you're worried about is that I might have a costume whose name is "current."  Okay, let's think that through, suppose I do.  How do I write the code to distinguish these cases?  You really expect a kid to say (((name) != (current)) and ((join (name) ()) = (current)))?  That's absurd.  Ionesco-level absurd.  Again, that logic is fine for the translation software, but that's no reason to impose it on delicate little children.

**Comment by jmoenig** [comment]
Brian, I already conceded that this isn't a perfect user-facing feature the way it is now, but the alternative is not to have this feature at all. And, you know, I didn't write this for kids. The whole custom drop-down menu gimmick with its special text syntax is definitely not beginner-friendly, but a kludge to support libriaries like Hummingbird and the Finch etc. What's important to me at this time is that *that* usecase can be made to work without using JS-libraries. It's clear that what we really want for custom dropdowns is for them to be dynamic, i.e. reporters. But that's a future project.

There are other non-kid friendly parts of Snap. We can make them inaccessible or leave them in for kids to mess around and discover. I'm suggesting the latter, I'm sure you do, too :-)

**Comment by brianharvey** [comment]
OK, whatever, this one isn't worth going to the barricades over.
