### ISSUE TITLE
Is the a way to tell whether a command ring is empty or not?

### ISSUE THREAD

**Issue by Simon-Mong** [jmoenig/Snap#2466]
Hi,Dear Jens and friends here.I just run into a problem of judging a command parameter being empty or not in a custom block.Is there any way to do it?

**Comment by jmoenig** [comment]
Hi Simon, I'm afraid you currently cannot tell directly in Snap, as we're missing this kind of introspection. But, JS is your friend :-)

Here's a quick idea:

<img width="588" alt="testing for empty rings" src="https://user-images.githubusercontent.com/2596285/61887828-aa17e980-af02-11e9-84a2-f0539b0f73e8.png">

Is this what you're looking for?

**Comment by Simon-Mong** [comment]
Thank you,Jens.That's exactly what I need.

**Comment by jmoenig** [comment]
Ah, glad I could help. We need to expose more introspection in Snap! Already thinking about it...

**Comment by Simon-Mong** [comment]
Yes.You are right.

**Comment by Simon-Mong** [comment]
Ah,now I can set a default block for a ring param.
![defaultvalueforring](https://user-images.githubusercontent.com/30740101/61927055-d2a4ef80-afa5-11e9-83c3-d5895595659c.jpg)

**Comment by jmoenig** [comment]
Wow, that's really neat, Simon!

**Comment by cycomachead** [comment]
That's a cool idea! I'm gonna steal this at some point. :) 

(Closing since it's been resolved.)
