### ISSUE TITLE
Untouchable sprite with 1px dimension

### ISSUE THREAD

**Issue by DarDoro** [jmoenig/Snap#2476]
Untouchable sprite with 1px dimension.
Sprite with one of the dimension = 1px is untouchable. 
Showcase project 
https://snap.berkeley.edu/snap/snap.html#present:Username=dardoro&ProjectName=untouchables
Every sprite in this project touch each other so sensing should report "touched" for every case.

More generic problem causing this behaviour: first row and column of every sprite is ignored during touching tests.

Reported at forum https://forum.snap.berkeley.edu/t/color-touching-color/724

**Comment by jmoenig** [comment]
thanks to your merged PR we can now close this. Thank you, @DarDoro, for this good catch!
