### ISSUE TITLE
Many inappropriate blocks are listed when searching for "sq"

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2485]
5.1.0

They all contain 's'.

![image](https://user-images.githubusercontent.com/2138696/64427908-3db80a80-d0aa-11e9-8f2f-66b0688e2590.png)

**Comment by bromagosa** [comment]
What I think is going on is that the search box is looking at all but the last character. I've noticed the same thing in the open project dialog search box.

I think this may have something to do with the new input method.

**Comment by jmoenig** [comment]
Oh wow, I think you're right, Bernat and Ken. This is new and bad.
