### ISSUE TITLE
https://snap.berkeley.edu/snapsource/Backgrounds/ - 403 Forbidden

### ISSUE THREAD

**Issue by normanbauer** [jmoenig/Snap#2493]
I used to be able to access this to get a large library of backgrounds for import into Snap!.  However I get a 403 Forbidden error when I try to access it now.

**Comment by jguille2** [comment]
Yes @normanbauer,

Maybe you can do the same action from this github repo: [https://github.com/jmoenig/Snap/tree/master/Backgrounds](https://github.com/jmoenig/Snap/tree/master/Backgrounds)
Navigation is not bad here: select an image (you will see it), click to Download link (you'll get the picture url) and then you can save it or copy and paste...

Joan

**Comment by normanbauer** [comment]
That will work, but I would like my students to have a thumbnail of the background without having to guess what the background will be.  BYOB had a great selection (which is what I believe you have in git) from which you could select and have loaded. Would it be possible to have a thumbnail of the background be presented with the file name? 


-----Original Message-----

**Comment by normanbauer** [comment]
What I would like to have is download all of the jpeg files to be used by students locally. I am not github capable, so how would I download all the files to my computer in  a zip file? I still have access to BYOB, so I can get the thumbnails from it. I believe there is a 1-1 correlation between the jpeg files and the BYOB thumbnails.  I can access the .db files for the backgrounds, is there a way to display the thumbnails in BYOB?

**Comment by jguille2** [comment]
Hi @normanbauer,

Easy to download current code from github. Just go to the repo ([https://github.com/jmoenig/Snap](https://github.com/jmoenig/Snap)), click on "Clone or download" and on "Download ZIP" link. You will get all the code, with the complete "Backgorunds" folder, and you can do whatever you want.
Joan

**Comment by normanbauer** [comment]
Thank you very much, that was exactly what I desired.
