### ISSUE TITLE
Loading Costumes Causes entire app to Crash: 77.0.3865.90 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by charlieding** [jmoenig/Snap#2498]
Replicated across an entire classroom of students. Version 76.x of Chrome works just fine, but the latest Chrome update caused all the students to be unable to load costumes. 

Firefox works fine, but due to classroom tech restriction, we only have access to Chrome.

Any help?

**Comment by bromagosa** [comment]
Chrome introduced a bug in their latest release (which they promised to fix soon) that causes this freeze you're experiencing, among other issues.

We can't do anything about it until the Chrome team fixes their issue. In the meantime, we recommend using Firefox. Is downgrading Chrome a possibility for you?

Sorry about the trouble :(

**Comment by jmoenig** [comment]
learn more about the bug in Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=1001845

**Comment by bromagosa** [comment]
Closing as duplicate: https://github.com/jmoenig/Snap/issues/2491
