### ISSUE TITLE
https://snap.berkeley.edu/ security warning from FireFox

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2499]
I'm getting "Warning: Potential Security Risk Ahead" from FireFox 69.0.1 (64-bit). Chrome and Edge are OK.

![image](https://user-images.githubusercontent.com/2138696/65758988-ef7ab200-e111-11e9-9361-52a311f42edd.png)

**Comment by ToonTalk** [comment]
Error code: SEC_ERROR_UNKNOWN_ISSUER

Seems an issue with its certificate

**Comment by jmoenig** [comment]
Ooh, @cycomachead to the rescue...

**Comment by cycomachead** [comment]
This works for me... The issuer is InCommon with a root of "USERTrust RSA Certification Authority" it's the same setup that berkeley uses. Do berkeley.edu and cs.berkeley.edu work for you?

Does staging.snap.berkeley.edu work (Login is snap / snap )? That's using Let'sEncrypt.

**Comment by ToonTalk** [comment]
https://snap.berkeley.edu/ is working fine for me today as well.

staging.snap.berkeley.edu results in the same error in FireFox today. It says "Web sites prove their identity via certificates, which are valid for a set time period. The certificate for staging.snap.berkeley.edu expired on 13/07/2019."

![image](https://user-images.githubusercontent.com/2138696/65862644-98b9e600-e366-11e9-9ed7-a34359d051e8.png)

Chrome also reports the following for staging:

Your connection is not private
Attackers might be trying to steal your information from staging.snap.berkeley.edu (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by cycomachead** [comment]
Oh, whoops. My bad — staging is definitely using an old cert so nothing will work there right now. :( I should fix that, but it’s a separate issue. 

If this happens again let me know the OS versions and browser versions.

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
I've encountered this problem anew on FireFox (68.1.1) on Android 8.1 says "This connection is untrusted" for snap.berkeley.edu

More details just says that error is SEC_ERROR_UNKNOWN_ISSUER

I have to go through advanced options and yes I trust this site etc to continue.
