### ISSUE TITLE
New, Consistent, Costume/Background Bug

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2508]
If I try to open the costumes picker, even first thing when I open snap, I see one of the following:

![image](https://user-images.githubusercontent.com/6549787/66778166-ebcc8680-ee98-11e9-963b-f5470959368c.png)

![image](https://user-images.githubusercontent.com/6549787/66778397-888f2400-ee99-11e9-99a3-f96c332f8919.png)

**Comment by jmoenig** [comment]
This is a bug in recent versions of Chrome, introduced in mid-August with v76. Google has in the meantime deployed a fix (after a long discussion and intervention) to beta and Canary that is going to be in the next version of Chrome (v78) to be available within the next 7-10 days.

**Comment by jmoenig** [comment]
this is now fixed in the latest version of Chrome (78)
