### ISSUE TITLE
Snap Cloud Login Issue

### ISSUE THREAD

**Issue by YihuanDong** [jmoenig/Snap#2509]
Hi, we are running a copy of Snap on our own server at NCSU for research studies. We started to run into issues when trying to login to Snap Cloud on our Snap. This hasn't been an issue in the past until today. Our server domain "stemc.csc.ncsu.edu" is whitelisted on the Snap cloud so I don't think this is an issue related to that.

Below is the error that we're getting from the web console: 

![image](https://user-images.githubusercontent.com/8525916/66936019-058ddb00-f00b-11e9-93f8-0d6653b892ac.png)

It would be great if anyone could provide insight and give guidance on how to resolve this. Thanks.

**Comment by jmoenig** [comment]
forwarding this to snap-support....

**Comment by YihuanDong** [comment]
Thanks for your help!!!

**Comment by jmoenig** [comment]
@cycomachead, @bromagosa  I dimly remember something about this changing recently...

**Comment by cycomachead** [comment]
Replied via email but the issue is the domain cloud.snap.berkeley.edu 

I will see if I can fix the cert there, but the solution is to just use snap.berkeley.edu and everything will work the same.
