### ISSUE TITLE
Sprite is going out of stage bounds, wrapping instead of bouncing

### ISSUE THREAD

**Issue by clintron** [jmoenig/Snap#2513]
This project shows a ball sprite which uses `if on edge, bounce`.  The sprite seems to be wrapping instead of bouncing.

Also note that the x/y coordinates go outside the expected bounds of the stage.

Thanks!

https://snap.berkeley.edu/snapsource/snap.html#present:Username=therudegesture&ProjectName=out-of-bounds%20bug%20report

**Comment by jmoenig** [comment]
Oh wow, that's a bug in the version I've released earlier today. Let me investigate...
Thanks for the report!

**Comment by jmoenig** [comment]
Nope, it's not my bug, phew!

What's wrong is that the rotation center of your ball sprite is waaaaay off somewhere totally on the other side of the Earth :-)

To fix this, please edit the Sprite's ball costume, in the paint editor click on the crosshairs symbol, and then click in the center of the ball picture and drag the crosshairs to where you wish to rotate the ball (usually the middle). That's all, now your project should work fine again!

Please let me know if there is any further issue here!

**Comment by clintron** [comment]
Ahh thank you!  Sorry for the invalid report.

**Comment by jmoenig** [comment]
not a problem. Better one report to many than missing a bug or noticing it too late! See, I was totally expecting such things to happen after this week's deep changes to the underlying rendering system, so your bug report met my own fears :-)
