### ISSUE TITLE
key _ pressed? predicate anc ControlKey issues

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap#2515]
Hi!
Starting from this [forum question](https://forum.snap.berkeley.edu/t/special-key-detection/1053) I've studied our _Ctrl_ key detection and I've seen maybe it is no fully coherent.

The problem is we store multiple "special" (_ctrl_ and _shift_) key pressed together. Initially it seems right, because it's not the same a [Ctrl]+[A] (press _A_ holding _ctrl_) than [A]+[Ctrl] (_A_ and then, _ctrl_). So, it is not only a combination of states. But it's not clear because in the first case we are storing ['ctrl a'] and in the second ['a' and also 'ctrl a'] because A "fires" multiple times. (And also ['ctrl control'] in both cases, but mabe it's another matter).

And the "real problem" is "control" keyUp doesn't remove all control events. And also, some "keys pressed" are not removed.

An example:
- Press "A" and hold it
- Press "Ctrl" an hold it
- Release "A"
- Release "Ctrl"
After this, "key a pressed?" is always "true" (because the A keyUp removes "ctrl a" but not "a").

It's not a big problem, I know. Pressing again "A", the problem goes out.

I only point this to keep it present, and maybe to think about this. I know it is a delicate matter because affects the gui behavior. So I don't expect simple fixes... only keep this for a later "keysPressed" redesing.

Thanks

Joan

**Comment by DarDoro** [comment]
It's duplicate of #2253

 It's worth to note that after
- Press "Ctrl" an hold it
- Press "A" and hold it
- Release "Ctrl"
- Release "A"

"Ctrl A" is "key pressed" forever.
The same is true for "Ctrl" alone.

**Comment by jguille2** [comment]
Yes, @DarDoro, your right.

And really, it's worse the "Ctrl alone" case affecting <key [any key] pressed?>.

So, closing this to keep #2253 open.

Joan
