### ISSUE TITLE
Snap frozen using SPLIT

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2527]
![image](https://user-images.githubusercontent.com/6549787/68959057-5a07b000-079b-11ea-9ce3-10a7b9c0f88f.png)

I clicked this block and everything froze. The red button does not work.

This is replicable. Use this text: "and allows one to focus on the idea."

I know there is something wrong with that text, and I was trying to get it into unicode to find out what. (If it doesn't work for you, perhaps GH stripped out whatever weird character is causing the problem.)

**Comment by jmoenig** [comment]
I've just now fixed this, waiting for @bromagosa to deploy the patch. Sorry!
What I *was* fixing was a reported bug where people were able to edit the costume list inside a speech balloon...

**Comment by maryfries** [comment]
Ah, interesting! And in the meantime, I've discovered (independently of Snap), that there was nothing wrong with that text at all; I was just running into an excel function's character limit. ;)

**Comment by jmoenig** [comment]
naw, it's a really bad bug I've accidentally introduced, and it affects the display of list watchers. Basically everytime you try to display a list Snap! now hangs, and projects with list watchers won't load.
But, the fix is already there, just waiting to be installed....

**Comment by jmoenig** [comment]
We've just now installed the patch, everything should work again.
