### ISSUE TITLE
Reporter objects misbehaving

### ISSUE THREAD

**Issue by Wunder-Wulfe** [jmoenig/Snap#2531]
The reporter object is being used in my custom blocks by accident causing its UI to break and also annoying me sometimes as I cannot put it anywhere near my code when it is too long.
[UI Bug](https://i.gyazo.com/602f7be7ea90225c7712eabc468b6724.mp4)
[Slot Stealing](https://i.gyazo.com/cf595ba60057567a68276d783b26fb9e.mp4)

**Comment by jmoenig** [comment]
the first case looks like a low-memory situation on your computer / browser. Try completely quitting your browser and reopening it to free memory. The second case is entirely intentional. Snap's C-slots in custom blocks are designed to also accept reporters, refer to the manual for more.
