### ISSUE TITLE
Firefox Reporting Security Risk

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2546]
After Chrome and Safari both stopped working, I moved over to Firefox and got this, which Brian said to report. (Firefox is working for me so far, fortunately.)

![image](https://user-images.githubusercontent.com/6549787/71634298-ceca6880-2be8-11ea-9ed3-aa5822a9b573.png)

**Comment by bromagosa** [comment]
@cycomachead is this a certificate issue?

**Comment by cycomachead** [comment]
I can’t tell. If it were a bigger issue it would happen for everyone and the carts should be fine there. 

We need to know what advanced for more info there is.

**Comment by EvelienSnel** [comment]
The URL in the image indicates that it goes to berkeley.edu over a secure connection and then tries to load something from localhost over a non-secure connection. Is that normal?

**Comment by maryfries** [comment]
![image](https://user-images.githubusercontent.com/6549787/71742149-ccf1e680-2e2e-11ea-9f9c-fa817b76b20d.png)


---->> [about-certificate.pdf](https://github.com/jmoenig/Snap/files/4020432/about-certificate.pdf) <<----

**Comment by cycomachead** [comment]
Yeah, that's the normal certificate and everything looks good to me...

> The URL in the image indicates that it goes to berkeley.edu over a secure connection and then tries to load something from localhost over a non-secure connection. Is that normal?

In the case of what Mary's doing, yes -- and localhost should be allowed by most browsers even with http... This error seems to happen before Snap! is even loaded, I think.

**Comment by DarDoro** [comment]
![image](https://user-images.githubusercontent.com/16109071/71773273-c6f92400-2f5a-11ea-8102-90ce6e51f20b.png)

Certificate issuer is not trusted by vanilla FF. 
Setting about:config > security.enterprise_roots.enabled=true usually helped, but doesn't work for me, this time (FF 71, OS X 10.10 Yosemite).
Security exception must be accepted or certificate manually imported to system trust store.
In centrally managed environment you may be not able to do this.

**Comment by cycomachead** [comment]
I'm not sure we have the whole chain... it's definitely something that changed in FF because the cert has not changed in a wile. We may replace the certs soon, though it's a bit annoying to do so.

**Comment by DarDoro** [comment]
You can check with SSLLabs. Server sends only 1 certificate. So keystore should be rebuild with with missing InCommon CA (at least).
https://www.ssllabs.com/ssltest/analyze.html?d=snap.berkeley.edu

**Comment by cycomachead** [comment]
Yeah. I mean, the issue is the way Berkeley certs are generated. I’ll probably just replace it with let’sencrypt but the automation has not been working correctly. 

-- 
Michael Ball
From my iPhone
michaelball.co
