### ISSUE TITLE
Block inputs visually affect blocks of same type

### ISSUE THREAD

**Issue by ishanpm** [jmoenig/Snap#2548]
Certain input slots appear to be shared between blocks of the same type. This bug is purely visual and does not change the behavior of the affected blocks, but it prevents the user from seeing what the blocks' inputs are.

![snap_glitch](https://user-images.githubusercontent.com/10391397/71775790-695ddb00-2f4c-11ea-82aa-b22cf52fa043.gif)

Steps to reproduce:

- Drag two "true" blocks into the script area
- Click one to change it to "false"
- Click background of script area

Expected result: Other "true" block should still be a "true" block.  
Actual result: Other "true" block appears to be a "false" block but behaves like a "true" block.

Tested on Snap 5.4.1 with Chrome 79.0.3945.88, under Windows 10.

**Comment by jmoenig** [comment]
you beat us with this bug report. We've fixed this last night with v5.4.1. The patch has been deployed half an hour ago. Can you test again? Now this is no longer happening to me. Thanks!

**Comment by ishanpm** [comment]
Looks good now. Thanks!

**Comment by jmoenig** [comment]
thanks for the quick test @ishanpm !
