### ISSUE TITLE
Sometimes Boolean constants are too pale

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2551]
<img width="150" alt="Google Chrome001" src="https://user-images.githubusercontent.com/3885074/72233729-ef49d980-357d-11ea-83b7-752d79050ea9.png">

Hovering over the button without clicking it seems to help sometimes.

**Comment by jmoenig** [comment]
huh. Which Snap! version are you using? I (thought I) fixed that a little over a week ago...

**Comment by brianharvey** [comment]
5.4.2.  The URL was
https://snap.berkeley.edu/snapsource/snap.html#
I don't know why Chrome gave me an old one.

**Comment by jmoenig** [comment]
interesting. But can you confirm that it's fixed for you in the current version (5.4.3 ++)?

**Comment by brianharvey** [comment]
Yes, much better!  Thanks.
