### ISSUE TITLE
Snap! produces "Aw, Snap!" in Chrome Android

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2557]
Sometimes this happens while loading a project. Sometimes everything works for a few minutes. And yet I'm not doing anything different yet it crashes at different points in the execution. I did notice that it works somewhat better after a reboot.

Even with remote debugging there is no error message or clue why this is happening.

Anyone have a clue how to work around this?

Chrome 80; Android 8.1; Nexus 5

**Comment by sollyucko** [comment]
My guess would be too much memory usage.

**Comment by cycomachead** [comment]
This is a memory thing, and I'm going to close this now that Snap!6 is out, but if there's a continuing issue, we can reopen this or file a new issue.

**Comment by ToonTalk** [comment]
I did some experimentation and in 6.0 it was _much less_ frequent but did happen occasionally. Is there any way to produce an error message like "Ran out of memory, sorry"?
