### ISSUE TITLE
Problems using an apostrophe as an input name

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2559]
I created the variable:

Bob's value

![untitled script pic](https://user-images.githubusercontent.com/2138696/77061397-21136c80-6a15-11ea-9bfe-ee43e383629d.png)

And it added "value" an extra time as title text

Then clicking OK defined a block that looks like

![untitled script pic (6)](https://user-images.githubusercontent.com/2138696/77061533-5ae47300-6a15-11ea-9755-cf5e9ebc9950.png)

And then when I edit it it looks like

![untitled script pic (7)](https://user-images.githubusercontent.com/2138696/77061585-6e8fd980-6a15-11ea-94bb-fbb78276e607.png)

**Comment by jmoenig** [comment]
Hi Ken, yes that's a long standing issue, also see #1295 and even going back to #857...

**Comment by ToonTalk** [comment]
Sorry. I did search Issues first but overlooked #1295

**Comment by bromagosa** [comment]
(closing as duplicate)
