### ISSUE TITLE
Unable to Type into Number-Type Input Slots Across Browsers

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2560]
The title says it all. This happens in Chrome, Safari, or Firefox. 

OSX 10.15.3

![image](https://user-images.githubusercontent.com/6549787/77168724-b272f500-6a8e-11ea-8f84-3d490fd29b39.png)

**Comment by jmoenig** [comment]
Hi Mary,

I can't reproduce this in any of my browsers.  That error message looks suspicious to me. Snap! doesn't use any Chrome extension, what does that extension do, why did you install it? Did you knowingly install it at all?

-Jens

**Comment by maryfries** [comment]
Hi Jens,

One of them might be my password manager—not sure about the other. I only have a few extensions, and I knowingly installed them all when I set up this OS back in December. 

I am having the same problem in other browsers where I have no extensions though...

Thanks,
Mary

**Comment by maryfries** [comment]
Oh, and just like that it's working again—in all three browsers!  How strange!!

**Comment by jmoenig** [comment]
hmm... (dumb question, please don't get mad at me) ... are you sure your caps lock is off?

**Comment by jmoenig** [comment]
Oh, good. Phew!

**Comment by maryfries** [comment]
Caps lock is off now, and I haven't turned it off recently, but I have accidentally turned it on and had to turn it off again a few times lately (must be something to do with my keyboard position), so it's possible that I turned it on and off again without knowing. ;)

However, turning it on doesn't seem to recreate the issue.

It's a mystery! ;)

**Comment by maryfries** [comment]
Oh my goodness! I think I was trying to type the name of the variable in. I was trying to put text into a numbers-only input slot. Oops! The stress is getting to me. Haha!

**Comment by jmoenig** [comment]
Oh, gosh! That's entirely me these days 😁
