### ISSUE TITLE
how to put a variable on a page other than the Variables page

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2564]
How to put a variable on a page other than the Variables page?

Such as "answer" and  "mouse x" which are on the Sensing page.

Thanks in advance!

**Comment by brianharvey** [comment]
Well, first of all, those aren't variables.  For one thing, you can't set them.  Technically they are functions with no inputs.

And if you understand that, it tells you the answer to your question:  You can make a block, any color you want, that reports the value of a variable.

**Comment by jcaldw737** [comment]
Thanks so much!

How to I make a line that has a box followed by the name of the faux variable?

[If my screen capture works - like this?}

![image](https://user-images.githubusercontent.com/5361659/77580726-7e426e80-6eaa-11ea-9a36-a4acb31fcb36.png)

**Comment by brianharvey** [comment]
Oh.  Sorry, you don't.  Maybe someday.

**Comment by jcaldw737** [comment]
No problem!  SNAP has done so much to improve my teaching, I am not about to complain about this situation.
