### ISSUE TITLE
Sound Recorder Not Working

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2566]
In Chrome, I can record and playback my sound, but then the save and cancel buttons are greyed out. (I can keep working in my project, but I can't get the sound recorder popup to go away.)

In Safari, I can't record, but the save and cancel buttons do work.

In Firefox, everything behaves like it is working, but no sound is actually recorded.

**Comment by jmoenig** [comment]
Safari is known to have these issues. However, both Chrome and Firefox on my Mac running the current browser and MacOS versions record and play back sounds just fine.

**Comment by maryfries** [comment]
I did. ;)

Just to check, I opened another Snap window in Chrome, and there I'm getting the same behavior as described above for Firefox.

Sounds, in general, do work in Snap for me across browsers, and my microphone works in Skype.

**Comment by jguille2** [comment]
Hi @maryfries 
Sound recorder is working for me in Firefox and Chromium, Linux OS.

I don't guess it was a version-distro issue. Maybe is a permissions setting issue?
Have you check your browser settings?
- Usually, your browser ask you for permission every time you want to use your microphone.
- If not, there are three possibilities: your settings are blocking always micro recording, Snap! site is in the list of blocked sites for micro feature or is in the list of allowed sites (of course, this last option is not yours).

Check your settings.

Joan
