### ISSUE TITLE
No "relabel" menu item for '# for each item of ...'

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2567]
I loaded the list utilities library and wanted to change

![temp script pic (1)](https://user-images.githubusercontent.com/2138696/77980274-787cdb00-7339-11ea-8dbd-24895e7ca382.png)

to

![temp script pic](https://user-images.githubusercontent.com/2138696/77980251-6c911900-7339-11ea-8933-7314d4359a45.png)

Normally I see a 'relabel' menu item that automates this process. But not in this case.

**Comment by brianharvey** [comment]
Relabel menus can be all primitives or all custom blocks, but not mixed.  This is a known non-feature but low on the list.
