### ISSUE TITLE
Can't Download and Source Code?

### ISSUE THREAD

**Issue by Tofutush** [jmoenig/Snap#2571]
For some strange reason, I can't download the file. It goes well for a few minutes, but then it says "download fail". I tried some different browsers (not Chrome though), but it's the same. Does anyone  know how to solve this problem?
Also, I have BYOB 3.1.1 and I just want to edit the source code and (oof) I don't know where it is (haha). Could anyone tell me please?

**Comment by Tofutush** [comment]
Wait--Maybe it's because I wasn't logged in at that time?

**Comment by Tofutush** [comment]
Also, I can't get into snap.berkeley.edu. There was a ring of circles spinning, and it keeps on spinning. Will there be something wrong with mt computer?

**Comment by Tofutush** [comment]
And just to be sure, you *can* download an offline version, right? I mean, can you *only* use Snap! on the website?

**Comment by bromagosa** [comment]
You're actually on the site that hosts the source code for Snap! :)

Here are the instructions to use it offline: https://snap.berkeley.edu/offline

**Comment by Tofutush** [comment]
Well, it led me here.

**Comment by Tofutush** [comment]
Help--here I come.
I finally managed to download it. Oh man. But when I unzipped the zip, there was only three things inside: a folder called "backgrounds" which contains a bunch of backgrounds; a "gitignore" file without a name at all; and an "API.md" which claims to contain a project.
Is there something wrong? Can anyone help me please?

......Can other people see this issue? Or only two can?

**Comment by jmoenig** [comment]
the zip file of the repo has every file of the repo in it. 

1) Go to this page: https://github.com/jmoenig/Snap/releases/latest
2) download either of the archives
3) unpack them. Seriously, if you're on Windows, unpack the archive, don't just click on it.
4) open `snap.html` in a browser

**Comment by Tofutush** [comment]
Well, it's exactly what I did but all I got is this:
![1](https://user-images.githubusercontent.com/63438312/79196470-c2e67780-7e62-11ea-85a6-efe00839af4b.png)
and inside the folder:
![2](https://user-images.githubusercontent.com/63438312/79196486-c974ef00-7e62-11ea-9382-ad48fdc77cb4.png)

**Comment by bromagosa** [comment]
The fact that the zip is just 5MB totally means your download was truncated.

Please try downloading it again. It should be around 56MB.

**Comment by Tofutush** [comment]
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bernat Romagosa"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 下午3:44
收件人: "jmoenig/Snap"<Snap@noreply.github.com&gt;; 
抄送: "柠柠"<34500085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jmoenig/Snap] Can&#39;t Download and Source Code? (#2571)





 
The fact that the zip is just 5MB totally means your download was truncated.
 
Please try downloading it again. It should be around 56MB.

**Comment by Tofutush** [comment]
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jens M&amp;#xF6;nig"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 下午2:57
收件人: "jmoenig/Snap"<Snap@noreply.github.com&gt;; 
抄送: "柠柠"<34500085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jmoenig/Snap] Can&#39;t Download and Source Code? (#2571)





 
the zip file of the repo has every file of the repo in it.
  
Go to this page: https://github.com/jmoenig/Snap/releases/latest
 
download either of the archives
 
unpack them. Seriously, if you're on Windows, unpack the archive, don't just click on it.
 
open snap.html in a browser

**Comment by brianharvey** [comment]
> Seriously, if you're on Windows, unpack the archive, don't just click on it.

Okay, now I'm curious, and I don't have a Windows to try on.  What happens if you just click it?

**Comment by Tofutush** [comment]
I tried downloading again, but it's still just those three items. What could possibly be wrong?

By the way, clicking on it in Windows just shows you what's in the archive, you can't do anything with them.

**Comment by jmoenig** [comment]
This must be an issue particular to your configuration. I've just - again - verified that downloading the repo does work and that it, in fact, includes all the files. Which OS are you using? And - more important - that file list you're showing doesn't resemble what's expected to be in the archive at all. The file-symbol for zip-files looks strange to me. Is that some kind of third-party software that's handling zip-files for you? Can you try just using whatever is built-in your OS for unpacking it? As Bernat has pointed out, the size of the zip-file should be around 56 MB. If you're getting less there's something wrong with your download client. Maybe an overly aggressive "security" thingy?

**Comment by Tofutush** [comment]
I'm using a laptop, if that's what you mean. Windows 10 pro, if that's what you mean.

Well, as far as I know, I have three packing things: WinRAR (is that the default? I don't know), something called "kuaizip" (that's the one showing on the pictures, I suppose it's for zips and WinRAR is for RAR?), and one "360kuaizip" (maybe it's the same as the one above). Maybe I should use WinRAR and try to open the file?

The security is fine; I'm sure.

I don't know about all kinds of these stuff well, sorry if my explaination is not clear.

By the way, there is not much space left in the drives. Might that be a reason?

Thanks for all the help!

**Comment by jmoenig** [comment]
Drive space shouldn't be an issue on your laptop, even if it's running somewhat low, otherwise you'd be running into other issues well before trying to unzip a small archive of 56 MB 😄 

Well, I dunno, beats me, really. Are you using a current browser, such as Firefox, Chrome or the new Edge (i.e. not IE)? Can you make sure that you can download this zip file:
https://github.com/jmoenig/Snap/archive/v5.4.5.zip
and before you do anything with it check whether its size is 56 MB?

**Comment by Tofutush** [comment]
Oof. It's still the same, so I tried with Firefox, and Firefox failed.
Might there be something wrong with my laptop? Maybe it's too old?
