### ISSUE TITLE
Dropping reporter in variadic C-shaped input slot displays weirdly

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2583]
![untitled script pic (2)](https://user-images.githubusercontent.com/3885074/81494121-ff877200-925a-11ea-9100-26941a11cda3.png)

Only happens when variadic; single C-slots correctly fall back into the title line.  Fails for me in Snap<i>!</i> 5 and 6.

**Comment by 18001767679** [comment]
Aww...Isn't this what I reported in the whats this bug? topic?
