### ISSUE TITLE
Checkbox for "mouse x" watcher not behaving nicely

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2585]
Create two sprites and show the motion palette in both. In one check the box to watch "mouse x". Then go back to the other sprie and the checkbox isn't checked. But clicking on it removes the watch.

**Comment by jguille2** [comment]
Hi Ken @ToonTalk,
I see.  And the same for global variables.
I'm fixing. It's easy, but I want to check other related issues about variables on palette.
Continue...
Joan
