### ISSUE TITLE
Ghost effect not saved in projects

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2588]
I set the ghost effect, saved the project, loaded it and the effect was reset to 0.

**Comment by jmoenig** [comment]
yes, that's actually intentional, a few properties are not made persistent, such as graphic effects and some pen state (up/down), we inherited those from Scratch. Maybe it's time to revisit those decisions.

**Comment by ToonTalk** [comment]
I suspect I'm not alone in thinking that saving a project saves the entire state (at least after pressing the stop button).

I hope things like this are ending up on a list to revisit when higher priority issues have been addressed.
