### ISSUE TITLE
bug: block "costume from text" clips texts

### ISSUE THREAD

**Issue by SanderTacker** [jmoenig/Snap#2589]
The block "costumes from text" in the library "Text Costumes" clips texts after 240 pixels:

![CostumeFromText Bug](https://user-images.githubusercontent.com/43132725/82142178-c2167c00-983a-11ea-8df9-33081d47cb16.png)

The reason is that the block temporarily writes the text starting from position (**0**|0). Thus the text is clipped when the right boarder is reached. The bug can be fixed by starting at (**-240**|0). For this purpose you only have the change two lines in the block:

![CostumeFromText BugFix](https://user-images.githubusercontent.com/43132725/82142269-584aa200-983b-11ea-8ba3-dbd62ad5814c.png)

Can someone please add these changes in the next version to fix the bug?

Alex

By the way: It would be useful to add a second block to the library that has an extra alignment parameter (align=L,C,R with default L). This can be achieved by small changes:

[CustomeFromText_with_Align.zip](https://github.com/jmoenig/Snap/files/4640077/CustomeFromText_with_Align.zip)

![CostumeFromText with Align](https://user-images.githubusercontent.com/43132725/82142338-e3c43300-983b-11ea-92fb-5931e4d933bd.png)

**Comment by jmoenig** [comment]
Thanks! fixing this now for the upcoming v6 release...
