### ISSUE TITLE
mouse x and y not integers inside of an iframe

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2590]
https://snap.berkeley.edu/project?user=toontalk&project=mouse%20test

This led to a bug in my project since it was computing a list index using mouse x and y and it worked fine unless in an iframe.

Windows 10 Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by jmoenig** [comment]
thanks, Ken. There seems to be an issue with the function that determines coordinates on a canvas embedded in a web page. This is biting me in other contexts as well. Investigating...

**Comment by jmoenig** [comment]
Can you perhaps check again with the beta version? I made a few changes to how coordinates are determined in Morphic. Thanks!

**Comment by ToonTalk** [comment]
I just tried an HTML file whose entire contents are:

<iframe src="https://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=toontalk&ProjectName=mouse%20test">

and I still see fractional mouse coordinates. (All are n/9 fractions)

**Comment by jmoenig** [comment]
Oh, *now* I get it! This isn't so much about iFrames, but about whether the stage is scaled somehow. *Then* it will show fractional coordinates, because of the scaling. Duh. Thanks!
