### ISSUE TITLE
Variable watchers placement different in full-screen mode

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2592]
If I place 2 watchers in the upper corners:

![image](https://user-images.githubusercontent.com/2138696/82535904-2bb7c280-9b7a-11ea-89a4-4ba256f17c3e.png)

In full screen it looks like this:

![image](https://user-images.githubusercontent.com/2138696/82535691-d1b6fd00-9b79-11ea-8adb-a763d59849ab.png)

perhaps related to #2103

**Comment by jmoenig** [comment]
the placement is the same, but the watchers themselves don't scale up. On my list for when things settle down :-)
