### ISSUE TITLE
Adding labels to sprites

### ISSUE THREAD

**Issue by TheInfinityUser** [jmoenig/Snap#2625]
Please add an option to be able to label sprites. It helps a lot.

**Comment by jmoenig** [comment]
did you know that you can double-click on a sprite on the stage in edit mode to see which one it is in the corral? likewise you can double-click on a sprite-icon in the corral to highlight it on the stage? Does that address your issue?

**Comment by TheInfinityUser** [comment]
I don't think so. I want a label that you can enable using a script and you can use scripts to change the content, position, colour, and so on of the label and the text feature isn't applicable for this purpose.

**Comment by jmoenig** [comment]
Okay, I'm afraid I don't understand what it is you're suggesting/requesting. programmable text boxes?

**Comment by TheInfinityUser** [comment]
Exactly

**Comment by brianharvey** [comment]
This has been on my todo list since forever.  Maybe we should move it up.

**Comment by TheInfinityUser** [comment]
You can add it as an extra library.

**Comment by jmoenig** [comment]
duplicate of #2314
