### ISSUE TITLE
Run without screen refresh.

### ISSUE THREAD

**Issue by TheInfinityUser** [jmoenig/Snap#2629]
Please add a block with a Boolean input to enable and disable 'Run without screen refresh'. It could be really useful in many ways. My idea is:-
There will be a block called Enable run without screen refresh? with a Boolean input. This block will only affect the script that it is placed in.

**Comment by jmoenig** [comment]
it's called `warp`

**Comment by SchoolAshton** [comment]
you can use `PrototypeHatBlockMorph[{run without screen refresh {%'bool'}},{doRun({reportJavascriptFunction(:bool:,"this.startWarp()")},:{getVar(ReporterBlockMorph[BlockLabelMorph"bool"])}})]`
className[children],Other = Morph
{selector(inp)} = Block
:items: = list

**Comment by ego-lay-atman-bay** [comment]
You can also turn on turbo mode with code, which is basically run without screen refresh.
