### ISSUE TITLE
Confusing "length of" blocks

### ISSUE THREAD

**Issue by wmakGIT** [jmoenig/Snap#2633]
Distinguishing the two different "length of" blocks implementations are difficult for students, especially if they are insensitive to colors (e.g. red-green color blindness). I do hope there are easier ways to tell which one is which.

![image](https://user-images.githubusercontent.com/33841798/86982960-87ed9a80-c158-11ea-94df-23e19240de59.png)
![image](https://user-images.githubusercontent.com/33841798/86982970-8e7c1200-c158-11ea-8d0f-ae01ce4290e2.png)

**Comment by brianharvey** [comment]
Right, and the historical compromise in which one of them was changed to handle both kinds of input, but I can never remember which one, didn't help any.

I propose to undo the compromise, and change the names to LENGTH OF TEXT and LENGTH OF LIST.

**Comment by jmoenig** [comment]
yeah, we turned the green `length of (text)` reporter into a hyperblock in 6.0.

There sure *is* a visual way to distinguish both blocks: It's the input slot. the text one lets you type something into it, the list one is a list symbol that you cannot type into-

But I agree about renaming the green one to `length of text _`, but keep the list one the same.

Remember that renaming blocks is very hairy as it affects more than 40 translations, and those students will no longer see the renamed blocks in their own language, which is also an accessibility issue.

**Comment by jmoenig** [comment]
We could also rename the green reporter in `number of letters in _`. Would that be any better?

**Comment by wmakGIT** [comment]
For a quick fix, I would say changing the green reporter to anything that can avoid students mis-interpreting/mixing it with the other one would be great. Yes, number of letters in _ / count letters in _ should work. 

For the future ... my overall feeling is that the original intention (from a bare user's perspective) is that you want to have a generic reporter that can work with more than more data structures (overloading methods/functions). That may sound cool, but I'm unsure whether teaching method overloading to students who just learning programming would be easy.

**Comment by brianharvey** [comment]
The trouble with "number of letters in" is that it will lead people to think spaces aren't counted.  The use of "letter" in Scratch is, I'm guessing, an attempt to have it both ways, using a familiar word from the domain of natural language (in which nobody ever talks about "characters") but using it to mean the unfamiliar notion of anything that occupies space on the page.  But up to now, the degree of confusion was tolerable.  Once you start _counting_ characters, it becomes important to know just what you're really counting.  "Length" doesn't give rise to this confusion.

**Comment by jmoenig** [comment]
I've added an English translation for the green reporter: b6669cd132e7e184072898a9530914bc01bc8704
This leaves existing translations for other languages intact.

**Comment by jcaldw737** [comment]
I must begin by saying thanks again for all you have done to make my teaching life so very much better!  

What should I be doing to learn about changes like this that may affect my existing block?

**Comment by brianharvey** [comment]
Come to Snap<i>!</i>Con and hear Jens's keynote!  :)

There's probably no good way to keep up with minor releases (with numbers like 6.0.1)--sometimes there are two in the same day--but Jens announces the medium-size ones reliably in the Snap<i>!</i> forum.

**Comment by jcaldw737** [comment]
Thanks!

Sent from Yahoo Mail on Android 
 
  On Wed, Jul 29, 2020 at 0:32, Brian Harvey<notifications@github.com> wrote:   


Come to Snap!Con and hear Jens's keynote! :)

There's probably no good way to keep up with minor releases (with numbers like 6.0.1)--sometimes there are two in the same day--but Jens announces the medium-size ones reliably in the Snap! forum.
