### ISSUE TITLE
Control-f followed by typing stopped working in 6.0

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2636]
When I type control-f the text area appears and the cursor shows up in it but typing just beeps. I can click in the text area and then type a search term but this wasn't necessary previously.

Chrome Version 83.0.4103.116 (Official Build) (64-bit) - Windows 10

**Comment by jmoenig** [comment]
Oh, I see. I'm using the <control> key on my Mac and that totally works, but <command> doesn't, because it gets hijacked by the browser. Ha!, that's a bug. Thanks.

**Comment by jmoenig** [comment]
just fixed this with 0ba622c822e6e7ee99af66e1f7552ab52ef3ec78 for the next patch
