### ISSUE TITLE
iOS requires "apple-touch-icon" for favicon

### ISSUE THREAD

**Issue by R4356th** [jmoenig/Snap#2646]
iOS requires the "apple-touch-icon" type to be inside link tag for favicon. You can read about this [here](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4).

**Comment by jguille2** [comment]
Hi!
I comment this on #2647 
Joan
