### ISSUE TITLE
p tag is unnecessary

### ISSUE THREAD

**Issue by R4356th** [jmoenig/Snap#2651]
The p tag is unnecessary. You can achieve the same result by placing the text without it inside the body tag.

**Comment by jmoenig** [comment]
yeah, right. Don't be difficult, please!

**Comment by R4356th** [comment]
Okay, I am sorry about that.

**Comment by jmoenig** [comment]
hey, no worries! But please don't be disappointed if I just close this :-)

**Comment by R4356th** [comment]
Don't worry. I am not disappointed at all! I just want to help out. 😄
