### ISSUE TITLE
APL roation using "transpose" and "flip" is not working (⌽ ⍉ A)

### ISSUE THREAD

**Issue by programaths** [jmoenig/Snap#2653]
# Example project
Test project : https://snap.berkeley.edu/project?user=programaths&project=APL%20Rotation

# Expectation

In the test project, the costume is switched to a version of itself that has been transposed then flipped as in "⌽ ⍉ 2 2⍴1 2 3 4".

**Expectation**: sprite is rotated right
**Outcome**: sprite is unchanged

Note: inspired from https://www.youtube.com/watch?v=p4JavDEA-q4

# Environment

Browser: Firefox 78.02 
OS: Windows 10
Snap! Version: 6.0.0

**Comment by jmoenig** [comment]
this has now been fixed, right @brianharvey ?

**Comment by brianharvey** [comment]
Yes, fixed.
