### ISSUE TITLE
Creating clones using "broadcast" and "when I receive"  block results in unexpected number of clones

### ISSUE THREAD

**Issue by normanbauer** [jmoenig/Snap#2664]
When using a broadcast, an incorrect set of clones are created. The following example has 3 clones created and then using a broadcast to create 5 more clones. The actual number created is 23 not the expected 8. The number exiting at the end is 23 which is 4 X 5 + 3.  Where 3 = number existing before the broadcast, 5 is the intended number to create
The following is an example:

<img width="592" alt="Screen Shot 2020-07-31 at 4 40 39 PM" src="https://user-images.githubusercontent.com/16528654/89088829-313a4180-d34f-11ea-8e9c-4b3f66e9686f.png">
3 = number existing before the broadcast, 5 is the intended number to create

**Comment by brianharvey** [comment]
The three clones already created get the CLONE message too!  So the original sprite and each clone create five new clones each.  This is how it's supposed to work.  You could wrap the whole WHEN I RECEIVE script in an IF (MY PARENT) = ( ).

**Comment by normanbauer** [comment]
Yes you qre right, the parent and all its existing clones get the broadcast.  Should have seen thtat, thanks.

**Comment by normanbauer** [comment]
Your my parent should be 
<img width="195" alt="Screen Shot 2020-08-02 at 10 36 22 AM" src="https://user-images.githubusercontent.com/16528654/89128672-221cd600-d4ac-11ea-9564-91c5f94469c8.png">

Interestingly if you ujse the tell block from another sprite, you do not get the clones creating other clones.

<img width="409" alt="Screen Shot 2020-08-02 at 10 34 41 AM" src="https://user-images.githubusercontent.com/16528654/89128697-627c5400-d4ac-11ea-9367-3963c6f45e40.png">

From the parent sprite, the followin g also creates one clone, not cloning the clones.

<img width="402" alt="Screen Shot 2020-08-02 at 10 41 29 AM" src="https://user-images.githubusercontent.com/16528654/89128807-27c6eb80-d4ad-11ea-9272-79357c1b467f.png">
