### ISSUE TITLE
Unable to rename script variables within the custom block editor

### ISSUE THREAD

**Issue by ntgomes** [jmoenig/Snap#2682]
I am unable to rename a script variable when using one within a custom block editor. The web console provides some kind of null error (`cannot get property fragment of null`), which may indicate where the bug may be occurring.

**To replicate:**
1. Go to the Snap IDE: [https://snap.berkeley.edu/snap/snap.html](https://snap.berkeley.edu/snap/snap.html)
2. Make a block within any category. The custom block's name does not matter.
3. Within the block editor for that custom block, drag in a "script variable" block from the Variables menu.
4. Attempt to change the name of the script variable "a" by right clicking and selecting "rename..."
5. The name you type in as the new name doesn't matter.
6. Click OK. Nothing happens and an error is logged onto the web console.

The same issue occurs when adding multiple script variables within a "script variable" block. This issue does not occur when renaming script variables outside of the block editor (i.e. in the script area).

I suppose the easiest workaround would be to create a new local (or global) variable via the "Make a variable" button, but I think that this bug is still important to bring up.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.

**Comment by brianharvey** [comment]
The problem with "rename" in the block editor is known.  We'll get to it...

Meanwhile, to change the name of a variable in a SCRIPT VARIABLES block, click on it (not right click).  This changes only the name in the block itself, not any instances you've already pulled off.
