### ISSUE TITLE
Strange red stripes on Chromium browsers

### ISSUE THREAD

**Issue by HM100** [jmoenig/Snap#2687]
Browser: Chrome 85.0.4183.83
OS: Windows 10 (64-bit)

## Steps to reproduce
Open snap on any chromium browser preferably the ones I mentioned

Observer the upper red lines above the block inputs (Such as text and number ones)

## Expected Result:
It should not display those red lines above the inputs.

## Workaround

Use a web browser other than a chromium ones (Such as Firefox) or enable Flat design to workaround this

The following screenshot shows how the block inputs appear between GUI modes and browsers. It also happened on chromium edge and no settings were modified.
![image](https://user-images.githubusercontent.com/30199227/92393751-0bac0f00-f129-11ea-9dcd-8432983593fe.png)

Part 1 - Chrome
Part 2 - Chrome/Flat Design
Part 3 - FireFox
Part 4 - FireFox/Flat Design

**Comment by jmoenig** [comment]
What?! I don't have a Windows machine around right now. Can anybody who has one (@bromagosa , @jadga-h ) confirm this? Thanks!

**Comment by HM100** [comment]
I can reproduce this on my desktop but not on my laptop. Very weird issue

**Comment by jmoenig** [comment]
We cannot reproduce this in our Windows10/Chrome laptops. It looks like there is a rendering artifact that might me related to your computer's GPU. Hmmm....

**Comment by HM100** [comment]
> We cannot reproduce this in our Windows10/Chrome laptops. It looks like there is a rendering artifact that might be related to your computer's GPU. Hmmm....

That didn't used to happen in my desktop weeks ago and unfortunately, we can't change the GPU on my desktop right now nor I do know if that happens.

**Comment by jmoenig** [comment]
I'll test on some desktops...

**Comment by HM100** [comment]
Device Specifications:
CPU: Intel Core i7-2600 3400 MHz
GPU: Intel HD Graphics 2000
If you need device info, here there are. Note that issue is not occuring in Gecko browsers

**Comment by jmoenig** [comment]
Testing on several Windows10 Chrome & Edge Desktop machines I wasn't able to ever reproduce this behavior...

**Comment by HM100** [comment]
> Testing on several Windows10 Chrome & Edge Desktop machines I wasn't able to ever reproduce this behavior...

Very weird. It happens on my desktop device that has i7-2600 CPU + Intel HD 2000. However, it does not happen on my laptop and does not happen only on blocks but in every instance that uses blurred shadows

**Comment by jmoenig** [comment]
Yes, it's the combination of a linear color gradient with a blurred shadow that seems to overwhelm your computer :-)
We cannot reproduce it on any of ours, bummer.

**Comment by HM100** [comment]
Yeah. When Snap! was running a few months ago, it could run it with everything appearing as expected. Now the only way is to use Firefox but on my PC, it doesn't scroll as smoothly as Chrome. I would have been better if my PC had a discrete GPU on chrome since the current GPU has only 6 execution units and appears to be an issue. I'm closing this now since it might also be a chrome bug that affects older graphics cards (Not sure)

**Comment by jmoenig** [comment]
I've reopened and renamed this issue because we've gotten another report about it on Piazza.
@HM100: On the computer that this happens on, can you open up a JS console and look if there's any error message? Thanks!

**Comment by jmoenig** [comment]
Bumping this. I would really love to find out more about this issue and possibly fix it, but there's no way I - or apparently anybody from our team - can reproduce it. Could somebody who happens upon this please look at the console and let me know if there are any error messages when this happens? Thanks.

**Comment by DarDoro** [comment]
![redStripes](https://user-images.githubusercontent.com/16109071/93751725-d65df180-fbfd-11ea-89a3-9c4f186929e0.png)

It looks like blurred shadow at negative offset.
Red stripe disappears for text longer than 10 characters and for numeric input slot during drag (?????).
I see this only for one computer with integrated GPU and low resolution 1600x900.
I'l investigate it further, but maybe it is a known pattern for someone.

**Comment by jmoenig** [comment]
Thanks, @DarDoro ! I just hate how Google comes up with breaking Chrome in subtle ways *every* couple of months...

**Comment by DarDoro** [comment]
Red stripes are drawn at `blocks.js` function
```
InputSlotMorph.prototype.drawRoundBorder()
InputSlotMorph.prototype.drawRectBorder()
```

For no apparent reason shadowBlur interfere with GradientFill used to simulate 3D look of input slot.
With shadowBlur disabled it looks like expected, doesn't it?
 
![Untitled script pic (6)](https://user-images.githubusercontent.com/16109071/93789877-b0067900-fc32-11ea-8754-06e99fb4150f.png)

**Comment by jmoenig** [comment]
Well, sure, it's the shadowBlur in combination with linear gradient. But only on some computers and only on windows. This has been working fine for almost a decade. Grr....

**Comment by HM100** [comment]
A similar issue is also on the fade blocks features for the same reason DarDoro sent 
![image](https://user-images.githubusercontent.com/30199227/94088278-c110df00-fe18-11ea-9e9e-d0a8de7434b6.png)
No errors on console

**Comment by jmoenig** [comment]
is this on the same computer? Looks like your graphic card can't handle transparency, maybe it has too few colors? Can you check whether the same happens on Firefox? Thanks.

**Comment by HM100** [comment]
> is this on the same computer? Looks like your graphic card can't handle transparency, maybe it has too few colors? Can you check whether the same happens on Firefox? Thanks.

No issue on Firefox. It can handle that properly. Chrome is also able to handle this properly as long as flat design is open.

Chrome is also failing to show any shadows on most things
![image](https://user-images.githubusercontent.com/30199227/94149740-f05b3680-fe80-11ea-8a11-164468f81e63.png)

Firefox on the other hand, with the same GPU, it can display properly the shadows without a hitch:
![image](https://user-images.githubusercontent.com/30199227/94149824-0e289b80-fe81-11ea-8c05-b374360fb0b9.png)

**Comment by jmoenig** [comment]
thanks for the testing. So it's yet another stupid Chrome bug. Again.

**Comment by jmoenig** [comment]
Okay, in the latest minor release (v6.2.2) you should now be able to "turn off" those red stripes by shift-clicking on the "gears" settings button and de-checking the "Blurred shadows" option:

<img width="545" alt="unblurred shadows" src="https://user-images.githubusercontent.com/2596285/95445583-78e8d500-095f-11eb-95f2-9aefd4634418.png">

This will turn off all blurred shadows everywhere, and should also get rid of those red stripes. That setting is remembered by the browser until you change it again.

Can someone who is able to reproduce the "red stripes" confirm that this workaround addresses the issue?

**Comment by DarDoro** [comment]
Ok, red stripes disappears imediately after disabling "Blurred shadows".
Good job ;)

"Fade blocks..." still behaves weird - probably resources shortage. Even with fade=1 random blocks become pink and change color as cursor moves over them. I'm not sure if it deserves further investigation...

**Comment by jmoenig** [comment]
Thank, @DarDoro , for the quick test and confirmation!
It's only a workaround in that we simply don't use blurred shadows in that - hidden - setting. This is clearly a Chromium bug so I'm reluctant to "fix" it in Snap. But it's good to know that there is at least a workaround for the red stripes issue that we can point those to, who run into it.

**Comment by HM100** [comment]
Fade blocks appear to work again on chrome browser on my desktop:
![image](https://user-images.githubusercontent.com/30199227/95693802-dcf8eb00-0c36-11eb-9ad1-8aab9e562f4d.png)

**Comment by jmoenig** [comment]
Ha! Maybe a new Chrome solved the issue? Can you make a quick test and see of turning "Blurred shadows" on again still produces those red bars? Thank you!

**Comment by DarDoro** [comment]
Chrome v86@Win10 still no good. There is no error for input slot longer then ~100px.
Made with "script pic..."
![Untitled script pic (5)](https://user-images.githubusercontent.com/16109071/95734497-d349a480-0c83-11eb-9234-dfce860c8660.png)


Fade block now OK in booth flat and classic UI.

**Comment by jmoenig** [comment]
Thank you for the quick test! So, we still need that new hidden setting after all...

**Comment by HM100** [comment]
Latest Chrome version has solved this issue completely, Now, I'm going to close this one!

**Comment by jmoenig** [comment]
Thank you for this heads-up! I'll let others know...
