### ISSUE TITLE
NEXT COSTUME vs. NEW COSTUME

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2688]
So, let's say you've loaded the Alonzo costume, so you have (0) turtle and (1) Alonzo.  Current costume is Alonzo.  Now you say

SET COSTUME TO (NEW COSTUME .....)

doing some image manipulation on Alonzo, so he's purple or something.

Now you say NEXT COSTUME.  What actually happens is nothing, because NEXT COSTUME doesn't realize that the actual current costume is anonymous.  What should happen is that you get a fresh new unmodified Alonzo, imho.

**Comment by jmoenig** [comment]
On the contrary: Snap! *does* realize that the current costume *ist* anonymous and not part of the wardrobe. Hence there is not "next" costume to switch to, and the costume # reports zero.

**Comment by brianharvey** [comment]
Oh.  Well if costume # is 0, then NEXT COSTUME should set it to 1.

**Comment by jmoenig** [comment]
That's like saying "Oh. Well, if the day is Christmas, then the NEXT DAY should be Monday"

**Comment by brianharvey** [comment]
What I was taught was that the (whole) number after 0 is 1.

**Comment by jmoenig** [comment]
Lists in Snap! start with the index 1, an index of 0 indicates that a value is *not* an item of the list.

**Comment by brianharvey** [comment]
:-)  Cute metaphor.
