### ISSUE TITLE
"Redo" button breaks blocks in scripting area

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2689]
1. Drag, e.g., Numbers from (1) to (10) into the scripting area.
2. Put any old reporter block in the first input slot.
3. Click Undo.
4. Click Redo.
The result is a block "Numbers from to (...)" with your reporter from step 2 in what's now the only input slot.
---------------- or
1. Same as before
2. Put any old reporter block in the second input slot.
3. and 4.  Same as before.
The result is a block "Numbers from (1) to" with no second slot, and your reporter from step 2 next to it.

**Comment by brianharvey** [comment]
PS I just tried it with the + block.  I end up with "+ +" with no inputs if I fill the first input slot, or "( ) +" (no 2nd slot) if I fill the second slot.

This has to be a new bug, right?  But it's in both normal and dev versions.

**Comment by jmoenig** [comment]
fixed, at least inasmuch as it worked in v5.
