### ISSUE TITLE
issue when i try pulling down the keyboard in a chat.

### ISSUE THREAD

**Issue by haileythebug** [jmoenig/Snap#2697]
Whenever I try pulling down the keyboard in Snapchat, it slides all the way to the top of my screen so I have to leave the chat to make it go back to normal. I don't like it when It does that because sometimes I'll look back at older chats, but it keeps doing this and is bugging me. is there a way to even fix this problem?

**Comment by jmoenig** [comment]
Wait! Are you sure you're in the right place? This is the *programming language* called Snap! not Snapchat..
