### ISSUE TITLE
How do I embed a snap project using the offline version?

### ISSUE THREAD

**Issue by StickGamer** [jmoenig/Snap#2698]
I want to be able to embed projects to GameJolt and I saw a post that already got an answer for how to embed a snap project. However I'm assuming that it was for the online version and not the offline version, and I couldn't find a page that gives an answer for the offline version specifically. Can you please help? Thx.

**Comment by jmoenig** [comment]
This is a place to report bugs in the source code. Please ask questions like this in the Snap! forums: https://forum.snap.berkeley.edu You might get more competent help there. Snap! is written in JavaScript, which runs inside a web-browser. The only way to "embed" it offline is to package a project together with a browser runtime version. Snapp! does that, but I don't know whether that will let you "embed" the result into someone's website again.
