### ISSUE TITLE
Idea: (Word () of [])

### ISSUE THREAD

**Issue by scratchman92** [jmoenig/Snap#2703]
Dear jmoenig,
a (Word () of []) block would be so helpful in my projects! So please add it it would be much appreciated have a good day!
sincerely, Scratchman92

**Comment by jmoenig** [comment]
What would that block do? Would it be a reporter that answers the nth  word of a sentence? You can easily and quickly make this block yourself:

<img width="442" alt="word of" src="https://user-images.githubusercontent.com/2596285/95664947-3cc69780-0b4c-11eb-94c9-8f9f750fe466.png">

is this what you're looking for?

**Comment by scratchman92** [comment]
Thank You for the help!
