### ISSUE TITLE
suggestion: coloring to brown all variables of script like byob 3.1.1  and adding "the other" category in the gui

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2705]
![suggestion](https://user-images.githubusercontent.com/5407223/96872650-30a7d780-1474-11eb-8866-bc7f7de8fd53.gif)
![suggestion 2](https://user-images.githubusercontent.com/5407223/96873094-c6436700-1474-11eb-864c-9a6594880ffc.PNG)

1) it's for not to confuse classic variables and script variables
2) it's for regroup grey blocs in a proper category

**Comment by jguille2** [comment]
Hi @gego51,

1. A 'var reporter' called "hello" is nothing (nor script or local or global) alone. Its meaning is different in different contexts. If it's inside a script with a "script var" called "hello", it will be that script var. But if I move that outsite, it will be the sprite var (if there is one called "hello") or the global var (if there isn't a local one and there is a globa onel).
And so, inside the palette, there will be only one reporter. Then different colors can't help us here.

2. Number of categories has been commented many times. Yes, "Other" and then "List" (to fill the new space) living alone is a possibility. But I think it is a global discussion (number of primitives, navigation system...) of our GUI. We'll see...

That's all,

Joan

**Comment by gego51** [comment]
you can leave this place in case you plan to integrate new extensions in the future "and then "List" (to fill the new space) "
