### ISSUE TITLE
error of french translation

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2706]
"clean up" does not mean "erase" ("effacer" in french) but arrange ("arranger" in french)

![capture fr](https://user-images.githubusercontent.com/5407223/97206023-7fc57380-17b8-11eb-8a21-5068acd67c3c.PNG)
![eng](https://user-images.githubusercontent.com/5407223/97206027-818f3700-17b8-11eb-8a59-270e5414affa.PNG)

**Comment by gego51** [comment]
and "undrop" can be translate by "retour arrière" or "annuler"

**Comment by jmoenig** [comment]
Thank you, @gego51 ! I've just updated the French translation with your 2 suggestions. Good catch!
