### ISSUE TITLE
Project with ampersand in its name can't be opened

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2724]
This was reported on the forum.  If a project has an ampersand in its name, it should be URL-encoded but apparently isn't.

Note: This is the opposite of long-ago issue #1606.  I hope that wasn't "fixed" by introducing this bug!

**Comment by jmoenig** [comment]
This is a problem with the SnapCloud @bromagosa. Snap! encodes the url just fine:
[https://snap.berkeley.edu/snap/snap.html#present:Username=jens&ProjectName=Night%20%26%20Day](https://snap.berkeley.edu/snap/snap.html#present:Username=jens&ProjectName=Night%20%26%20Day)

**Comment by bromagosa** [comment]
Not only if you copy the URL, but also if you click on the project thumbnail:

![out](https://user-images.githubusercontent.com/1016697/100761097-c9762f00-33f2-11eb-9452-759ab50b4d3c.gif)

I would like to know how they ended up with a broken URL. Any hints?

**Comment by brianharvey** [comment]
Dunno, sorry.  Feel free to ask her.
