### ISSUE TITLE
custom categories and custom color blocks, lock and unlock scripts

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2729]
hi, 
why not create custom categories with custom color on scratch:

for exemple... javascript ,  yellow color: ffff00,
or "table, pink color: ff8888,

just left click in categories to have contexual menu "create a category"
and custm block menu, the new category is showed with primitives
 
lock scripts for avoid errors if we put a block in wrong script.

**Comment by jmoenig** [comment]
On our list
