### ISSUE TITLE
Sprite has a width of 986.182... while its costume's width is 700

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2749]
A student was working on a project and the sprite named Sprite (2) was not visible when it should be. It was created with the green flag code with the sprite named Sprite. I tried to reproduce the problem but failed.

![image](https://user-images.githubusercontent.com/2138696/102623067-e6458d00-417c-11eb-8197-45a4e95a4aed.png)

Attached is a zipped version of her project

[GuessingNumbers_version1 (2).zip](https://github.com/jmoenig/Snap/files/5716086/GuessingNumbers_version1.2.zip)

**Comment by jmoenig** [comment]
The sprite's rotation center is way outside of its bounding box, hence it's offscreen even though its "position" appears to be onstage.

**Comment by ToonTalk** [comment]
But we didn't see it before rotating it either. And how can the size be that number? If its size is 100% shouldn't it be the same as the costume width?

**Comment by jmoenig** [comment]
right, but the sprite is tilted to 150 degrees, which makes its bounding box wider than the unrotated costume.

**Comment by ToonTalk** [comment]
Ah.

So I set the heading to 90, ensured it as at the center, checked that it was shown and full size and yet I don't see this sprite displayed. And I deleted all other sprites.

Could this be relevant?

![image](https://user-images.githubusercontent.com/2138696/102687049-23665980-4227-11eb-9d1b-c03f0b806be9.png)

And this persists if go to 0 0

[Sprite not displaying.zip](https://github.com/jmoenig/Snap/files/5719187/Sprite.not.displaying.zip)

**Comment by jmoenig** [comment]
yeah, that coordinate is ... strange, you're right. Also, this project is interesting, because I'm pretty certain that your student didn't intentionally move the sprite's rotation center this far out of the visible area. I would be interested how that - obvious - mistake happened. On a more meta level I'm not really convinced that Scratch's original design decision to make rotation centers a property of each *costume* is such a great choice. I think that personally I'd have preferred making it an attribute of the *sprite* and let the programmer adjust it for each costume.

**Comment by brianharvey** [comment]
Why?  When _wouldn't_ the user adjust it to match the costume?

**Comment by jmoenig** [comment]
If, for example, - as many kids' projects I've seen do - an animation uses a number of similar costumes for a stop-motion animation, like a walking creature etc.
As I've said, I'm not really sure either way. Sometimes you want it one way, sometimes the other. It's pretty clear to me that being able - as Scratch is also - to move the rotation center out of the visible area of a sprite enables both very cool projects and likewise great confusion, as in this very case here.

**Comment by jguille2** [comment]
But Ken,
I can't reproduce your issue...

Working with your last xml project. The rotate center is not int the center of that costume. It's far away.
And going to 0,0 the position reporters reports 0 and 0.

Am I missing something?

Joan

**Comment by ToonTalk** [comment]
I don't believe my student set the rotation center - her costume came from `pen trails`.

**Comment by jguille2** [comment]
Hi Ken,

Maybe this (using pentrails) is the answer!

This action sets the rotation center in the place where your sprite is (their current situation) and the costume is where the "pen trails" is. And this action uses to create costumes with strange rotation centers. Usually I go to the center before to "take" the paintrails costume and this is clear to me.

Joan
