### ISSUE TITLE
Should snap.berkeley.edu/versions/dev/snap.html track github changes live?

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2767]
Sorry for disturbance but VERY keen to play with columns :)
Should snap.berkeley.edu/versions/dev/snap.html live track the github repo or do you have to press something at your end every now and then to update it?
Please ignore this if busy :)

**Comment by jmoenig** [comment]
Haha, naw, it's not yet automatic. But I think we'll be releasing this patch shortly, anyway. Either today or tomorrow morning. I'm giving a talk about it on Friday, so I need it to be "live" :-D

**Comment by jmoenig** [comment]
Hi @cymplecy, incidentally @bromagosa has put the dev version up live, so you can now already play with the `column` reporter....

**Comment by bromagosa** [comment]
But to answer your first question, I've done that for MicroBlocks and our life is much easier now. We should to the same for Snap! someday... When Things Slow Down :tm:

**Comment by jmoenig** [comment]
I'm sorry, @cymplecy, but we're taking the experimental `column` and `width` reporters out again, in favor of a more general new experimental fast `rotate` primitive. These experimental features may change and even be taken out again as we research them :-)

**Comment by cymplecy** [comment]
Boo!!!
I'm going to put my lawyers onto you.... oh wait...... that's not going work is it? :)

No problem - it worked well :)

I'm just after a syntactically simple method of accessing columns.  I got VERY excited to see it as a primitive as I didn't seem to get any traction from Brian, when I raised it on the forum, to add it to the List library

**Comment by jmoenig** [comment]
well, so the new idea is that you can use `rotate` instead and then the items of the rotated lists ARE the columns you wish to access, and you can do so using ITEM OF which already is hyperized.

**Comment by cymplecy** [comment]
Well - that's the complete opposite of simple column access :)
Plus overhead to rotate a large list would be huge (unless your just meaning to change the view of the list?)
But I'll wait to see it in action :)

**Comment by brianharvey** [comment]
By ROTATE do you mean TRANSPOSE?  I'd love a fast TRANSPOSE, but I agree with Simon that COLUMN is cognitively easier.  I mean, we already have ITEM (LIST (LIST col)) OF to extract a column, so the point of adding _anything_ is cognitive load, right?  And, if I'm right that you mean TRANSPOSE, please don't call it ROTATE, which already means something -- turning 1 2 3 4 5 into 3 4 5 1 2 for example.
