### ISSUE TITLE
Cursor starts blinking sequence being invisible for 2 steps (~1s)

### ISSUE THREAD

**Issue by DarDoro** [jmoenig/Snap#2768]
The keyboard cursor starts blinking seq being invisible for 2 steps (~1s at least).
Steps to reproduce:
1. Move the cursor away (click on script area)
2. Click on the sprite label input field,  BEYOND the last letter.

Nothing happens for at least 1s.
Expected behavior: cursor appears immediately.

The same, for file Save/Open dialogs.

Chrome.87@Win10

**Comment by cymplecy** [comment]
Confirmed the same on mine (also Win10/Chrome)
Same behaviour on File Save dialog

I think its always done this - I've just lived with it :)

**Comment by DarDoro** [comment]
All these little, low priority, imperfections are like a grain of sand inside the boot, that scratches until bleeding as you walk longer.
This one and the inability to select the entire lines with <Shift><down> are most annoying for me.

**Comment by jmoenig** [comment]
Oh good, finally something that's easy to fix :-D
thank you!
