### ISSUE TITLE
missing block

### ISSUE THREAD

**Issue by tillkast** [jmoenig/Snap#2769]
where can I find block 'SCHOW PICTURE' in current version ?

Best regards,
Till

**Comment by TheMapotakes** [comment]
Okay

**Comment by jmoenig** [comment]
Hi @tillkast , you can just use the "switch to costume" block now.
Here's a short video outlining the changes in Snap!: https://www.youtube.com/watch?v=yCeIGtDh9jI&feature=youtu.be

**Comment by tillkast** [comment]
Hallo Jens.
Herzlichen Dank für deine schnelle Antwort.
In dem verlinkten youtube-video finde ich da leider keinen Tip.

Wenn ich switch to costume nutze, muß das Bild ja als Köstüm gespeichert sein.
Der Vorteil von SHOW PICTURE ist für mich, dass ich die pixel-Tabelle eines Bildes mehrfach manipulieren kann (ohne das Bild zu speichern) und mit SHOW PICTURE dann die manipulierte pixel-Tabelle anzeigen kann.
Ich kann also mehrere pixel-Tabellen im script haben, und je nach Bedarf dann diese pixel-Tabellen einfach anzeigen (ohne dass diese als Kostüm gespeichert sind).

Schöne Grüsse nach Walldorf,
Till

**Comment by tillkast** [comment]
Hallo Jens,
jetzt hab ichs geschnallt, was du meinst:

mit switch to costume kann die pixel-tabelle als new costume mitgegeben werden.

Alles klar und schöne Grüsse,
Till

**Comment by tillkast** [comment]
Hallo Jens,
jetzt könnte ich noch einen Tip gebrauchen, wie ich ein Kostüm ‚verschicken‘ kann.

Hintergrund:
Ich möchte ein Nachricht(text) in der Pixeltabelle eines Bildes(in der Saturation-Spalte) verschlüsseln und diese verschlüsselte Pixeltabelle an einen Empfänger schicken, der sie dann entschlüsseln kann.
Aktuell habe ich das codieren und decodieren innneralb meines scripts bereits realisiert.
Wie bekomme ich aber das verschlüsselte Bild an einen anderen Empfänger verschickt (ohne die explizite pixel-tabelle zu verschicken)?
Das verschlüsselte Bild kann ich zwar als sprite exportieren, dann wird es aber beim Empfänger auch wieder als sprite importiert(und nicht als Kostüm, um daraus dann die pixel auszulesen).

Schöne Grüsse,
Till

**Comment by jmoenig** [comment]
Hallo Till,
kannst du denn nicht anstelle der Sprite nur das Kostüm exportieren? Dazu kannst du es zunächst zur Liste der Kostüme hinzufügen, etwa so:

![export_costume](https://user-images.githubusercontent.com/2596285/107933635-48edb600-6f7f-11eb-8c5a-79ce866567a5.png)

Anschließend kannst du dann in den Kostümreiter wechseln, und es dort im Kostüm-Kontextmenü (Rechtsklick...) als PNG exportieren, welches du dann weitergeben kannst.

Lass mich wissen, falls das nicht funktioniert.

**Comment by tillkast** [comment]
Hallo Jens,

herzlichen Dank für deinen Tip:
ein neues Kostüm aus dem script heraus hinzuzufügen, das hat mir gefehlt.
Jetzt ist alles paletti, ich kann damit das neue (modifizierte) Kostüm exportieren und im neuen script dann wieder importieren.

Es ist schon sehr beeindruckend, welche Funktionen in snap! vorhanden sind.

Ich unterrichte jetzt snap! im 4.Jahr und es ist eine tolle ‚Einstiegsdroge‘ für die Programmierung.

Dickes Kompliment dafür!

Schöne Grüsse,
Till

**Comment by TheMapotakes** [comment]
l
