### ISSUE TITLE
bug when i use data of sound block

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2776]
when i use  ((samples) of sound (sound)) with function for to reduce table of my sound
![Capture](https://user-images.githubusercontent.com/5407223/107130913-72994400-68d2-11eb-9207-c44760660552.PNG)
, the primitive block keep the reduction of table, and i must restart snap for to restore the data of primitive block

**Comment by jguille2** [comment]
Hi Jeremy,

Maybe the forum is a better place for this...

You are mapping over "samples of sound", and then you get "numbers" (not lists). And so, you can't use your "hache" function there.

Joan

**Comment by gego51** [comment]
my function 'hache'  or cut work great with tables, or lists inside list, the probleme is the table of the primitive block, after to use the script for cut the list, the value of primitive samples is definitively reduced, but it shouldn't normaly, it's a bug

**Comment by gego51** [comment]
![un](https://user-images.githubusercontent.com/5407223/107142450-495ad100-692f-11eb-8717-54d24af1d50e.PNG)
![2](https://user-images.githubusercontent.com/5407223/107142453-4e1f8500-692f-11eb-9c0c-583584df2b0a.PNG)
![3](https://user-images.githubusercontent.com/5407223/107142455-5081df00-692f-11eb-9ee3-451afb9b366e.PNG)

**Comment by gego51** [comment]
here, there are a bug
![sss](https://user-images.githubusercontent.com/5407223/107142676-d81c1d80-6930-11eb-8de6-0f8db2bb293b.PNG)
![ttt](https://user-images.githubusercontent.com/5407223/107142678-dbafa480-6930-11eb-8a70-d1b6d5967f13.PNG)
![uuu](https://user-images.githubusercontent.com/5407223/107142682-deaa9500-6930-11eb-802d-8e0a353a7e3f.PNG)

**Comment by jguille2** [comment]
Hi Jeremy,

I think the key is the number of channels of different samples.

If you play with a stereo file, samples are a list of lists. But if you play with mono files, then samples is a single list.
If this is the case, then, your map is wrong.

Maybe it's not the case... but your examples make me wonder in this way.

Joan

**Comment by gego51** [comment]
all my sounds are stereo,
in my last example, my sounds was deleted but i have not remove sound, and my script of 'hache' block souldn't modify my sounds

**Comment by jguille2** [comment]
I'm sorry, but I don't see any bug there.

"my sounds" is a list. And this list is writable. You can add, delete... items of this list.

So, your "hache" block is cutting that list. 

Yes! And it will cut any writable list, even if this list is a list of numbers, of sounds, sprites, a list of lists...

Joan

**Comment by gego51** [comment]
i have change my block since, he should cut a copy of list stored in a variable named 'list', not cut data of (my (sound))
![image](https://user-images.githubusercontent.com/5407223/107156367-2d325080-697e-11eb-9e6b-48e9feb65657.png)
