### ISSUE TITLE
just one question

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2778]
can we import a script file (three.min.js) as raw on a custom block with javascript block and use in snap?

**Comment by jguille2** [comment]
Hi Jeremy,

Maybe the forum is a better place for questions.

And maybe this forum post is useful for you:
https://forum.snap.berkeley.edu/t/running-a-web-page-in-snap/5326/10

Joan

**Comment by gego51** [comment]
hi,ok, 
thanks
