### ISSUE TITLE
bug with list (lists inside list) input in javascript block

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2779]
I try to use "return list[0];" with input ((pixel)of costume(myimage)), but he wont work, that is a bug?
![3d texture picture block script pic](https://user-images.githubusercontent.com/5407223/107628826-7d046680-6c61-11eb-9b27-0ab0aa4e032a.png)

i'll try to make a pen stamp block with 4 position point using data of pixels picture for to texture 3d forms in Snap

https://snap.berkeley.edu/project?user=gego51&project=3d%20texture%20picture%20block

**Comment by jmoenig** [comment]
a Snap list isn't a JS array. Why do you need to use JS for this? If you must use something like

    `list.at(index)``

where `index`  starts at 1.

**Comment by gego51** [comment]
thanks
I try to made a stamp picure block with quicky execution, I have made my block with snap blocks, but its to slow,

**Comment by gego51** [comment]
Thanks, my block work, you can try it https://snap.berkeley.edu/project?user=gego51&project=3d%20texture%20picture%20block
