### ISSUE TITLE
Snap Media Storage optimizations

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#278]
Currently, when saved to disk, Snap stores media (Sounds, Images/Costumes) for each sprite. In many projects this could lead to a lot of duplication of resources.

Instead, what if Snap used 1 section in each project file for <media> where all images and sounds were stored. Each sprite's media objects would point to an item in the media section. (That could be determined based either on image name, or a hash). This way two or more sprites could reference the same file without duplicating code. 

Optionally, we could apply gzip compression to objects to further reduce file sizes.

**Comment by cycomachead** [comment]
@jmoenig 

Realized this has been here for a while...

My old description is somewhat weird. Here's a better description:

 I've noticed that in some projects students tend to duplicate the same costume across multiple sprites. The `<media>` section could check for duplicates of any serialized data, and then when it assigns id's to that data, two different sprites could share the same serialization. I suppose than when loaded into Snap<em>!</em> we'd need to take care to duplicate the data so that they become separate objects in memory, but that seems possible.

**Comment by jmoenig** [comment]
Yes, we could canonicalize media, that looks like a reasonable optimization at first glance. I've been resisting this because I also want to make media more first class, and - more importantly - because media will be shared among "breeds" of sprites in the new objects system that features inheritance.

**Comment by cycomachead** [comment]
I think it would be possible to do this only for the serialized, XML version. As long as the base64 is equivalent, we could save a lot of disk space in some projects. The in-memory, running Snap<em>!</em> use would be separate from these changes.

**Comment by jmoenig** [comment]
Ah, good point, yes.
