### ISSUE TITLE
Transpose of producing un-expected result

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2780]
Using published dev version https://snap.berkeley.edu/versions/dev/snap.html - so ignore if still playing around

![image](https://user-images.githubusercontent.com/2357428/107642387-ba222600-6c6c-11eb-8701-5b749b6e525f.png)

The my projects table is 533 x ( 8 or 9 depending on age of files) for me with 2 element lists in each non-blank cell

I was expecting test to be 9 x 533 with each cell still being a 2 element list but its  2 x 10 with 533 element lists

Bug or expected behaviour?

**Comment by jmoenig** [comment]
expected behavior, because now you no longer have a 2-dimensional table, but a 3-dimensional one, in which case we're doing the official right thing in mathematics. I dunno anything about this, but @brianharvey will be able to explain about transposing 3D matrices.

If you want those 2-item lists to be unaffected, you'll have to somehow make them "atomic" first. One way to do that is to convert them to a text first, using, e.g. the "lines", "csv" or "json" options in the new "length" block, and then to split them back into lists using split (duh!) in the transpose.

All of this is still very experimental...

**Comment by jmoenig** [comment]
hm... of course, converting the 3rd dimension to something like "csv" will require a HOF or nested loops, and that, in turn will slow everything down to a level where it'll be faster to simply write your own quick "2D-transpose" function using MAP:

<img width="689" alt="2D-transpose" src="https://user-images.githubusercontent.com/2596285/107656190-3411d980-6c84-11eb-92de-d3fc8aa9d89c.png">

**Comment by brianharvey** [comment]
Oy.  In the library there's a version of deep map that takes a predicate that reports True for whatever you consider to be atomic.  I use that for cases like this.  Maybe we need to JSify that?  More discussion needed...

**Comment by cymplecy** [comment]
Where can I find info on the maths behind transposing 3D matrices  - my google foo is getting me nowhere :(

But maybe restrict it to a 2D transpose and have a library block that does a deep transpose?  Or have transpose and deep transpose in this block?  Just my thoughts

**Comment by jmoenig** [comment]
Oh, yeah, this is totally biting me in my test cases right now. Took me over 20 minutes even to realize why my code wasn't doing what I expected it to do. Wow.

**Comment by cymplecy** [comment]
Just seen latest change from transpose to columns .... I don't think that is quite the right word (and would clash with my great wish for a library (or relabel primitive ) _column of_ block
Is there any real practical use case for >2D transpose?

**Comment by cymplecy** [comment]
How about _swap_?  Does that clash with any existing or proposed block?

**Comment by jmoenig** [comment]
*columns* would be the word for 2D transpose, what you (and I usually) want. *transpose* would be the matrix-transpose that also does the right thing for dimensions greater than 2.

**Comment by cymplecy** [comment]
columns <> transpose in any language that I know of :)
AFAICS the operation being performed that is currently called `columns of` is a shallow matrix transpose 

TBF  `item 2 of(columns of myTable)` does make sense but I think that is just an accidental by-product :)

Are there other snap blocks that only make sense if you combine them? :) 

Also, as you know, I'm trying to get a simple, explicit `column of` block and having a `columns of` block that does a transpose will just cause confusion - and I'm trying to make things as simple for snappers to access columns as it is to access rows

**Comment by cymplecy** [comment]
Previous reply deleted - I'm having a longer think :)

**Comment by cymplecy** [comment]
`item 2 of(columns of myTable)` makes perfect sense :)
