### ISSUE TITLE
Compiled MAP gives wrong answer with a variable in the function

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2784]
![apl-library-speedup script pic (3)](https://user-images.githubusercontent.com/3885074/107894473-936e2480-6ee4-11eb-86b2-46233cfd560f.png)

![apl-library-speedup script pic (1)](https://user-images.githubusercontent.com/3885074/107894358-37a39b80-6ee4-11eb-94ad-0933eda5ed34.png)

![apl-library-speedup script pic (2)](https://user-images.githubusercontent.com/3885074/107894368-3f634000-6ee4-11eb-905d-0b75e957b32b.png)

It works if you put the ringed = directly in the MAP instead of using the variable.

**Comment by jmoenig** [comment]
hmm... given how the compiler works going meta can't work, because it's not using the Snap process to evaluate a block. I guess the right thing would be to throw an error. Let me check...

**Comment by brianharvey** [comment]
Oh.  But it works ... oh, is the problem about "meta"-ness finding the right evaluation environment?  I'm trying to understand why it works fine if I put a block in the CALL rather than a variable whose value is the block.

**Comment by jmoenig** [comment]
CALL pushes frames onto the *Snap!* stack, wheres *compile* evaluates things in JS only. That's also the issue behind the variable discrepancies. So in this case CALL does the right thing but the compiled version of MAP "overtakes" it. But there might be a solution for this, I'm working on something...

**Comment by jmoenig** [comment]
My idea is to simply compile *call* into *invoke()*. Dirty trick, but it might work....
