### ISSUE TITLE
Reporter with grey ring not showing up in result pic

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [jmoenig/Snap#2789]
This
![untitled script pic (10)](https://user-images.githubusercontent.com/70973578/109206618-b4990580-776d-11eb-8509-920d3cb4bf92.png)
is fine, but this
![untitled script pic (11)](https://user-images.githubusercontent.com/70973578/109206666-c2e72180-776d-11eb-84a1-ab8023b25419.png)
is not fine. I tested it out multiple times, and, it's a little confusing. This
![untitled script pic (16)](https://user-images.githubusercontent.com/70973578/109206999-34bf6b00-776e-11eb-9199-29d4f2b4da3a.png)
doesn't show the call block
![untitled script pic (15)](https://user-images.githubusercontent.com/70973578/109207019-3e48d300-776e-11eb-9b1c-6d52bc8c7e54.png)
but this
![untitled script pic (17)](https://user-images.githubusercontent.com/70973578/109207073-53256680-776e-11eb-9ea1-b8afc3248f66.png)
does.

This only works when there's an error.

**Comment by sathvikrias** [comment]
I don't understand, everything looks fine.

**Comment by jmoenig** [comment]
What's your question, @ego-lay-atman-bay ?

**Comment by ego-lay-atman-bay** [comment]
> What's your question, @ego-lay-atman-bay ?

when I do a result pic on this
![untitled script pic (4)](https://user-images.githubusercontent.com/70973578/109327269-c33ef580-781d-11eb-9759-a7154cce5dc9.png)
it results with
![untitled script pic (3)](https://user-images.githubusercontent.com/70973578/109327290-c934d680-781d-11eb-85b9-2b858a74a0aa.png)
this is obviously a bug.

**Comment by jmoenig** [comment]
Eh? what are you trying to do? make pictures of errors that we catch?
