### ISSUE TITLE
Table view missing a column (sometimes)

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2790]
Attached is a list whose elements are lists that are sometimes 1, 2, or 3 long.

When I look at elements 30 to 40 all is well:
![image](https://user-images.githubusercontent.com/2138696/109286533-50556f00-785d-11eb-875a-41f6036ad2e0.png)

But when I look at 20 to 40 it doesn't display the C column:
![image](https://user-images.githubusercontent.com/2138696/109286591-64996c00-785d-11eb-8209-02c63143225b.png)

Notice that the right side of element 16 is displayed differently (which should be displayed as element 6 of the first image)

Double clicking on 20 to 40 displays only 2 columns while 30 to 40 has 3 columns.

Here's the list:

[temp.zip](https://github.com/jmoenig/Snap/files/6048862/temp.zip)

**Comment by cymplecy** [comment]
I think this explains what is going on

**Comment by ToonTalk** [comment]
Thanks. That does explain this.

I suggest that if one double clicks on such a value that it scan the entire list since this would be in response to a user action and I'm guessing that it would be fast enough to still feel very responsive.

**Comment by jmoenig** [comment]
that's right, when creating the list watcher I'm only scanning the first 10 rows of the list. The reason we're not scanning the whole table is mostly because if it's made up of very large linked lists this can get pretty slow at some point.
