### ISSUE TITLE
New "length" block appears twice in search

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2797]
![image](https://user-images.githubusercontent.com/2138696/110316040-1c403200-8045-11eb-85a5-e4fa1dc66031.png)

**Comment by jmoenig** [comment]
Ugh. I see, the old block is still in the blocks dictionary, but it gets auto-morphed into the new one, so we end up with twice the same block in the results. Will fix for next release. Good catch, thanks, Ken!
