### ISSUE TITLE
Saved project truncated a list

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2798]
I have a global variable whose value was list of 3 lists of 2 elements. And I noticed that after exporting and then importing the project the list was just 2 lists of 2. I repeated this a few times and then I set a couple unrelated global variables to 0 and the problem went away. This project is 30MBs of list data in about 30 global variables.

Before "fixing" the problem, I did look at the project XML and sure enough that list had only 2 elements.

Also I did put a break on VariableFrame.prototype.toXML and saw that it produced the correct 3-element XML but somehow it was truncated later.

I'm not completely sure but I think the 30 other lists were all fine.

This was in 6.6.0.

**Comment by jmoenig** [comment]
hmm... there haven't been any changes to the serializer for a long time. Things like these have been surfacing in situations where browser memory is getting very low, especially with such big projects. It would be great to be able to reproduce this, so we can find out if, in fact, it is due to low memory or caused by something else.

**Comment by ToonTalk** [comment]
I found a version that reproduces this problem. 'all content codes' is 2 long. Click on 'Create content codes' and after a few seconds it is 3 long. Export and import and it is back to 2 long.

[whatsapp.zip](https://github.com/jmoenig/Snap/files/6107943/whatsapp.zip)

**Comment by ToonTalk** [comment]
In Chrome (Windows 10) the tab is 1.2GB

**Comment by jmoenig** [comment]
thanks, looking into this now...

**Comment by jmoenig** [comment]
Okay, I think I found the problem! Let me try to fix it...

**Comment by jmoenig** [comment]
hmm... the problem is a hybrid list where parts are linked and others aren't.... This is pretty ugly.

**Comment by jmoenig** [comment]
okay, so here's the issue: in your list all but the last items are linked, and the last one is an arrayed one. We don't have a way to serialize a hybrid list preserving a heterogeneous internal structure. I can "fix" it by turning it into an arrayed one internally and then saving it and setting the "linked" flag. Next time you load it it would be uniformly linked. I guess that would be okay, perhaps even right, and perhaps less bad than loosing items along the way. But officially such structures aren't yet supported for save / load.

**Comment by jmoenig** [comment]
really, this whole linked-list business is needlessly slow, a memory hog, and a pain to maintain, plus there's hardly anything to be learned from it, not even algorithm efficiency, because the alternative is so much faster in every case. Sigh,

**Comment by jmoenig** [comment]
I'm "fixing" this the way I outlined above: If a list starts out being linked, I'm saving the whole list as being uniformly linked. That way at least all the items get saved and restored, even though the internal structure doesn't persist.

**Comment by ToonTalk** [comment]
Very glad to hear it's fixed. Thanks.

The list in question was created by using the "add" block to add a list of a key and counter on an initially empty list. Then to update the count "replace item 2" was called. So I'm unclear how it can be a combination of linked list and array internal structures.

And this problem went away when I reset other variables. Or was it one of those variables that caused a different list to be truncated?

**Comment by jmoenig** [comment]
you were also using Brian's old sort block, and *that* may have been the culprit, because it would answer a linked list. It might make sense to maybe update some of the libraries used for newer versions. That might also make the project faster.

**Comment by brianharvey** [comment]
The list library now uses your internal JS sort in the sort block.

About "hardly anything to be learned from it," that's not true if you're interested in recursive functions.

I'd like to believe that if we gave linked lists the same TLC you've given arrays, performance would be much better.  But it may be that that would require the sort of aggressive compilation that mature Lisp systems use, and that's way beyond my level of expertise.

Actually, I bet we could optimize a common use case of linked lists, namely ones that don't have two different heads merging into the same tail, by representing them as a pointer to a JS array plus a starting array index value.  Let me think more about that...

**Comment by ToonTalk** [comment]
Having imported the list library long ago I was using the old one. I can't think of a way that projects would be able to refer to the latest version of a library but I wonder if there is some way of supporting developers by suggesting that one may wish to upgrade.

For example, if one grabs a copy of the "sort" block a message appears saying this block has been upgraded (or even more importantly the subject of a bug fix) in the current version of the library.

Note there is an asymmetry here with respect to library blocks implemented in Snap! versus JavaScript. If the JavaScript is part of the Snap! source (or as I do it comes from JS file loaded upon demand) then it'll be upgraded automatically.

One idea is that when one imports a library there is a checkbox enabling autoloading of the current version upon startup. The project would record the version number of those libraries that are to be kept current and imports if needed.

**Comment by ToonTalk** [comment]
P.S. I like how the new "sort" block has a Snap! implementation as a "comment". A convention I think I'll try copying.

**Comment by ToonTalk** [comment]
Or maybe we need a "load library" block that does nothing if the up-to-date library is already loaded

**Comment by jmoenig** [comment]
only the HOFs running atomically by JIT compiling the function inputs have a lightening bolt symbol, those are actually dangerous, because depending on which function you input they can crash Snap. Regular MAP - the primitive version - is safe to use, because it can be stopped by the user and it will yield and doesn't ever completely block Snap.

**Comment by brianharvey** [comment]
Umm some library blocks have lightning bolts, namely the ones implemented by JS code in Snap! that isn't user-visible ordinarily.  SORT is an example; it surfaces the reportAtomicSort primitive.  Also the ones that are implemented using compiled HOFs get lightning bolts, e.g., ASSOC.
