### ISSUE TITLE
UI element to insert a slot into a "multiple inputs" input?

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/Snap#2804]
When editing a list of data (or say, list of reporters), it'd be nice to have an option to add a new slot between existing ones. I'm not sure if this might already be an option, but I couldn't find anything like it :P

Mostly inspired by stuff like the custom pipe operator in Jens's 2018 *Reinventing on Purpose* talk: https://www.youtube.com/watch?v=X_vP0P6LBJM

<img width="254" alt="Pipe operator block with multiple ringified reporters" src="https://user-images.githubusercontent.com/9948030/111039390-3cd10900-8404-11eb-930a-3d1b73c24c86.png">

It'd be nice if you could stick a new operand between existing ones, without having to add a slot at the end and move all the blocks you want to come after over. Same with editing a data list: copy-pasting a bunch of data is not accessible or fun! :P

I'm not too sure what the UI for this would look like, though. Probably a button between existing slots, ala the block editor prototype screen? But those would be distracting to always have visible, so maybe there could be a "+" button next to the arrow heads which would make insert points visible. Or maybe an option in the context menu for the block with multiple inputs. Or some other option I didn't think of! :)

**Comment by towerofnix** [comment]
Funnily enough the best workarounds for this are the ones which take inspiration from Scratch's own custom procedures - make control structures like "pipe" into multi-block custom *stack* blocks, not reporters, and that lets you get all the dragging and reordering options of stack blocks :)

I can make a demo script of that if anyone's curious, though it's only tangential, since the option to insert things in multi-inputs would still be handy.

**Comment by brianharvey** [comment]
If you want to do sequential programming, there's no need for PIPE at all!

I like the idea of plus signs that appear when you hover between two input slots, as in "plain prototype labels" mode.  That would be great for all variadic inputs.

This is one of those perennial ideas that we all want, but need some more relaxed time to get around to.

PS Hi, haven't heard from you in a while!

**Comment by towerofnix** [comment]
> If you want to do sequential programming, there's no need for PIPE at all!

Yes, I suppose this is true! :)

More pertinently, the current way to construct a list of data for storage in one variable (and still have access to insert, etc) would probably use CALL, something like this:

![set a list to CALL with a series of stack blocks sequentially creating a list](https://user-images.githubusercontent.com/9948030/111051854-761d6f00-842c-11eb-81a2-85deac9e597a.png)

(Oops, sorry this image is abhorrently large, lol.)

Sort of a way to encapsulate the construction of a list within one plain CALL operation, rather than include those blocks with the rest of the script (which would function equivalently).

> PS Hi, haven't heard from you in a while!

Hi! Good to say hello again! :)
