### ISSUE TITLE
No typechecking for variables used in loops

### ISSUE THREAD

**Issue by manzanillo** [jmoenig/Snap#2809]
Hi there,
if we use a string as an input in a `repeat ()` statement, we will get an infinite loop. I prepared a project to illustrate this here:
https://snap.berkeley.edu/snap/snap.html#present:Username=seegerer&ProjectName=wiederhole%20string%20mal&editMode=true

While I know that this not how a `repeat ()` statement is supposed to be used, but it might confuse learners, who might experience this while learning to code with Snap!

I suggest to add a check to the `repeat ()` statement that checks whether the literal can be parsed as an integer.

**Comment by jmoenig** [comment]
hmm... my policy is to not assert any data types in general, the only exception we negotiated are the list category blocks. Sure, error messages or nops can help, and for sure we'd like to avoid unstoppable loops from occurring, but this isn't what's happening here, right? The loop keeps running but can be stopped by the user at any time.

Still, you're right about catching this if possible. I'd suggest expanding the termination check in the `doRepeat` method to `NaN` number-cast counters. Does that make sense?

Oh, I see you've already filed a PR, that's perfect, thank you!!

**Comment by jmoenig** [comment]
Haha! just looked through your PR and found that your suggestion is the same. Looking forward to your updated PR ;-)
Thanks for catching this!
