### ISSUE TITLE
Duplicating a block (sometimes) doesn't keep the duplicate grabbed, with strange sequelae

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2816]
So, I start here:
<img width="401" alt="Google Chrome002" src="https://user-images.githubusercontent.com/3885074/112071993-26c2f700-8b2e-11eb-92a7-2adfdddd5668.png">
Then I grab the `y-7` block, but it doesn't stay attached to my cursor:
<img width="401" alt="Google Chrome003" src="https://user-images.githubusercontent.com/3885074/112072120-625dc100-8b2e-11eb-81e0-86a9d334e2d5.png">
And when I click (anywhere, I think) again, the duplicate bumps the entire haloed expression out of its slot, which I guess isn't that surprising:
<img width="434" alt="Google Chrome004" src="https://user-images.githubusercontent.com/3885074/112072326-d009ed00-8b2e-11eb-99f9-457d2a2a0abd.png">
(Not surprising because the duplicate is still above that halo, even if my mouse isn't.)

Here's the project:
https://snap.berkeley.edu/snap/snap.html#present:Username=bh&ProjectName=X%20Y%20T%20world

**Comment by jmoenig** [comment]
I can't reproduce this in any of the browsers I'm using: Chrome, Safari, Firefox, Edge. There is no way I can get the duplicated block *not* to be where the mouse pointer is. Which OS/browser versions are you using? Also, do you have browser extension installed that tamper with default settings or disable certain things?

**Comment by brianharvey** [comment]
Chrome 88.0.4324.146 
MacOS 10.13.4 (17E202)

<img width="1243" alt="Google Chrome002" src="https://user-images.githubusercontent.com/3885074/112121944-053d2c00-8b7d-11eb-8421-2fff37ddf7d4.png">
<img width="1246" alt="Google Chrome003" src="https://user-images.githubusercontent.com/3885074/112121968-0c643a00-8b7d-11eb-83f9-53247284801b.png">
