### ISSUE TITLE
New and Better Paint Editor

### ISSUE THREAD

**Issue by Barthdry** [jmoenig/Snap#2818]
I know this maybe tough but i have now seen scratch costume editor more comfortable to use then the snaps editor and also it has a vector editor which is nice. I hope you may improve the performance of the paint editor otherwise we maybe needed to import things from outside which i don't like much.
It is not as comfortable as scratch costume editor and also it opens in a new windows which i don't like. Also the Layout maybe improved

**Comment by brianharvey** [comment]
Yes, we know.  There are a bunch of open issues about the paint editor and a complete rewrite is planned.  So, don't feel insulted, but I'm closing this because it doesn't tell us anything we don't know.  :)
