### ISSUE TITLE
VariableFrame is not defined

### ISSUE THREAD

**Issue by videotoaster** [jmoenig/Snap#2823]
I'm attempting to place a Snap fork on my website.
However, upon uploading all of the files, I'm encountering this error.
```
Uncaught ReferenceError: VariableFrame is not defined
    at IDE_Morph.init (gui.js?version=2021-04-09:230)
    at new IDE_Morph (gui.js?version=2021-04-09:212)
    at window.onload (snap.html:33)
```
I am certain that every file exists in the `src` directory.

**Comment by jmoenig** [comment]
I dunno what to respond to this issue, obviously Snap works, so it must be an issue with your fork. Closing.
