### ISSUE TITLE
Snap lists and Javascript lists are not the same.

### ISSUE THREAD

**Issue by ErickDaGamer** [jmoenig/Snap#2846]
I'm trying to make a statistics blocks library in Snap to find the mode of a list. Unfortunately, I'm having trouble making the mode (most occurring numbers) block because the list cannot be accessed by the Javascript function. Here's my code:
```
var nd = []
for(var i=0;i<od.length;i++) {
    nd.push(od[i])
} //In an attempt to translate the list. Doesn't work.
//Credit to Scott Sauyet for this script (https://codereview.stackexchange.com/users/13443/scott-sauyet)
return nd.reduce(function(current, item) {
    var val = current.numMapping[item] = (current.numMapping[item] || 0) + 1;
    if (val > current.greatestFreq) {
        current.greatestFreq = val;
        current.mode = item;
    }
    return current;
}, {mode: null, greatestFreq: -Infinity, numMapping: {}}).mode;
```
The reason it's returning nothing when I run it in Snap is because the function never returns since ND doesn't have any elements,  therefore it never enters the nd.reduce() function. I don't know how to fix this. If this isn't fixable, I'll try to make it myself with Snap blocks.

**Comment by RubenVerg** [comment]
You can use `list.toArray()` to get an (JS) Array from a (Snap!) List and `new List(array)` for the opposite.

**Comment by ErickDaGamer** [comment]
Oh ok thanks!

**Comment by ErickDaGamer** [comment]
Snap says that od.toArray() is not a function (od is the input Snap list)

**Comment by DarDoro** [comment]
There is no list.toArray().
The API is in lists.js file.
>  conversion:
>     -----------
>     asArray()               - answer me as JavaScript array, convert to arrayed
>     itemsArray()            - answer a JavaScript array shallow copy of myself
> ...
>  // List instance creation:
> function List(array)

last = new List([ 1,2,3]);
arr = new List([ 1,2,3]).asArray();

This should be not posted as an Issue!

**Comment by RubenVerg** [comment]
Yeah sorry I misremembered the function name.
