### ISSUE TITLE
Script pic doesn't work correctly, nor does project summary.

### ISSUE THREAD

**Issue by ErickDaGamer** [jmoenig/Snap#2848]
Whenever I try to take a picture of a script pic, Snap! cuts the image so that only the top left part shows up. It also happens when I try to export a summary.
![Custom blocks script pic](https://user-images.githubusercontent.com/59941851/121788218-6f63dc80-cb80-11eb-87e2-b5317af03ffe.png)

**Comment by jmoenig** [comment]
hmm.... I just tried both and it works for me, also in different block zoom levels. Which OS and browser versions are you on?

**Comment by ErickDaGamer** [comment]
It's working now for some reason. I think it broke but after I came back to the website, it worked. Anyway, here's my browser and OS information:

OS Name: Microsoft Windows 10 Enterprise (Windows think I'm running this because I bought Windows 10 Pro but now Windows is running under enterprise without a valid license key since the license key is for Pro)
Version: 10.0.19042 Build 19042

Browser: Chrome
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
