### ISSUE TITLE
What about having a Bagpack for Snap?

### ISSUE THREAD

**Issue by Barthdry** [jmoenig/Snap#2849]
I am asking the exact same backpack as in Scratch. But i am not asking rigidly for it to make cloud storage perhaps it can store it to the local directory perhaps or maybe even simpler way to do it.
I am not asking for you guys to reply Smerge is the best way to do it. I know it is possible but a few work is required

**Comment by cycomachead** [comment]
It’s on our long term list of ideas to provide something similar. We definitely want it too.
