### ISSUE TITLE
Error not reported on click of unselected sprite

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2850]
If you click on the green sprite, nothing happens. If you switch to that sprite (you see the red glow) and then back again and then click on it, the error message is displayed. It is also displayed when full screen presentation mode.

https://snap.berkeley.edu/snap/snap.html#present:Username=toontalk&ProjectName=no%20error%20reporting&editMode

**Comment by jmoenig** [comment]
hmm..., when I click on the green sprite there is an error reported in a bubble next to its icon in the corral (if it's not selected), and next to the variable-setter block if it is selected. In presentation mode the error message is shown onstage for me.

**Comment by jguille2** [comment]
Yes Jens!
And this is great (the message in the corral).
But Ken is right: that message does not appear at the beginning! You have to select that sprite and, after this, if you select another sprite, then you get the corral message. At the beginning nothing happens.

Joan

**Comment by jmoenig** [comment]
By golly, you're right!
