### ISSUE TITLE
Colors and Crayons lib not showing correctly on my local running latest git download version

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2854]
Please ignore if its just some issue on my local version

![image](https://user-images.githubusercontent.com/2357428/124264172-0f7fa680-db2c-11eb-8888-6c59a7ca21f4.png)

**Comment by jmoenig** [comment]
but... that's the right version! If you scroll down you'll see more blocks... right?

**Comment by cymplecy** [comment]
What an idiot!
