### ISSUE TITLE
Parameters and values end up on different lines sometimes

### ISSUE THREAD

**Issue by pamelafox** [jmoenig/Snap#2870]
The parameters can sometimes end up on the line before the value, which makes a block hard to visually parse. Here are a few examples:

<img width="913" alt="Screen Shot 2021-07-30 at 7 51 23 AM" src="https://user-images.githubusercontent.com/297042/127677917-982ff8a3-b8a5-43a8-82b5-3655bfe29589.png">

![untitled script pic(43)](https://user-images.githubusercontent.com/297042/127677809-b8b88d11-5812-4a82-8743-93d128c3790b.png)

@cycomachead thought that there was something built that prevented this, but maybe that was never merged or there's been a regression? I think it would help improve readability if Snap automatically ensured params/values were on same horizontal line.

Thanks!

**Comment by brianharvey** [comment]
<img width="572" alt="Screen Shot 2021-07-30 at 8 55 52 AM" src="https://user-images.githubusercontent.com/3885074/127680263-4da8eefd-9dee-4aa9-979a-882f00c33405.png">

**Comment by jmoenig** [comment]
thanks, Brian, beat me to answering it :)

**Comment by cycomachead** [comment]
I think what we really want (and what we don’t have) is the “prefer breaks here” control. Though this is still helpful! I think I just didn’t look to the very last time in the list earlier. 😅
