### ISSUE TITLE
Bignum library broken in 6.9.0

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2871]
![image](https://user-images.githubusercontent.com/2138696/127745938-13fce51e-099f-4be5-a30d-11854b74d4b6.png)
 
Despite release notes:

fixed bignums library and and made colors library faster, thanks, Brian!

**Comment by brianharvey** [comment]
Works in dev version 7.0, right?

**Comment by ToonTalk** [comment]
Right. But that may be a while, right?

**Comment by cycomachead** [comment]
@brianharvey this was the issue. 

Ken, we are going to release a 6.9.1 with a fix for this soon.

**Comment by brianharvey** [comment]
I swear I fixed this once already!  The problem isn't in the JS code, it's that the Snap! code surrounding it got messed up -- looks like someone dropped the JS Function block into the wrong place.  Should I file a PR for this?  That would put it in v7, right?  So I'll just email it to you... :)

**Comment by cycomachead** [comment]
@ToonTalk Can you double check with a project here and please confirm the new library is working for you:
http://snap.berkeley.edu/versions/michael-dev/snap.html
This is 6.9.1

**Comment by ToonTalk** [comment]
Library seems fine but when I encountered the problem I switched to the dev version so my project is v7 only and I can't test it.

**Comment by cycomachead** [comment]
No worries. Thanks for checking!

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
Just a note 6.9.1 is now out and on snap.berkeley.edu. :)
