### ISSUE TITLE
CorsProxy is disbled in 2020

### ISSUE THREAD

**Issue by TheMapotakes** [jmoenig/Snap#2877]
This time, CorsProxy is an block the sever url: www.corsproxy.com has be shutdown in 2020 end of life is no longer supported in JS blocks, TheMapotakes project of BrowserLock in Snap!

And now we see an url:
https://snap.berkeley.edu/snap/snap.html#present:Username=themapotakes&ProjectName=JS%20blocks&editMode&noRun

**Comment by cycomachead** [comment]
Using a proxy is outside the scope of what Snap! Can provide. But if you find a different proxy service it should work in place of Cors proxy.

**Comment by TheMapotakes** [comment]
Is CorsProxy died?
