### ISSUE TITLE
New Project doesn't work if a block dialog is open

### ISSUE THREAD

**Issue by thomaswp** [jmoenig/Snap#2890]
Creating a new project when the new block dialog or a block editor dialog is open will fail to reset the script area.

To reproduce:
* Add blocks to the script area
* Open the block dialog (e.g. with the [+] button)
* Go to File -> New Project

**Actual behavior**: The stage resets, but the script area is not reset.

**Expected behavior**: The script area also resets.

![new proj bug](https://user-images.githubusercontent.com/1750176/132369221-5d4a9498-433f-42bf-93f4-11f2655f75d0.gif)

**Comment by jmoenig** [comment]
Thanks, @thomaswp ! If I'm not mistaken I've already fixed this bug for the upcoming v7 release. Let me check....
Yep! it's fixed in the version in this repo already.
