### ISSUE TITLE
[feature request]add "and wait" option behind relabel to send command

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2892]
In my Mayflower project, I'm using clones quite a lot and using send to target specific clones with messages

I'm having to write my own handlers to wait till the send broadcast is completed so I'm wondering if we could have send and wait option built in but hidden behind relabel?

**Comment by jmoenig** [comment]
Hi Simon! Events are a low-floor way to fork parallel / async threads. If you're just using single sends to specific other sprites wouldn't TELL / RUN (OF) let you synchronize them in order?

**Comment by cymplecy** [comment]
I only get off the floor if I have too :)

So I started off using broadcast and waits (with thread safe scripts flag set) with the sprites/clones containing the executing scripts and then needed to narrow them down to target individual clones/sprites 

At that point I simply switched to using send and added simple wait handling using a sprite local wait variable.  Very pleased with myself for inventing it :)

But, I will try standing up and using tell instead from now on :)

Cancel my request :)



Broadcasting and letting the receiver deal with stuff has the low-floor advantage of easy coding inside the receiving sprite as opposed to the sometimes complicated way of accessing sprite internal objects and values

**Comment by cymplecy** [comment]
Following this experiment with great interest :)

![image](https://user-images.githubusercontent.com/2357428/135238953-b3bd8253-4b9f-457d-9c87-acdffe178dbd.png)

**Comment by cymplecy** [comment]
![image](https://user-images.githubusercontent.com/2357428/135743250-e7f4fd4b-74d9-45b0-937d-a2796461260c.png)

If one of the receive variations ends up being kept in v7, I'd like to re-instate my FR :)
