### ISSUE TITLE
Maybe remove reference to the receiving object in the new message upvar?

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2898]
With the old global message reporter, if we use send message instead of broadcast, the message gets turned into a list with the 2nd item being the intended receiver

I'm wondering if this is needed any more with the upvar message reporter?

It would let receiving scripts look cleaner and be simpler to understand and use
e.g this

![image](https://user-images.githubusercontent.com/2357428/138238340-415ca158-61f8-4d3d-9116-b8c9d03a0c34.png)

instead of this

![image](https://user-images.githubusercontent.com/2357428/138238377-764811c8-13e0-492c-b0a7-bc0d9d75ab4e.png)

I've had a long think about this and I can't come up with a scenario where a receiving sprite or sprite clone would need to have confirmation that it was the intended receiver

And if someone did need this, then they could simply encode the message at the send end
![image](https://user-images.githubusercontent.com/2357428/138243750-c3925cdb-68e2-4daf-abc4-1a4f01f23edc.png)

**Comment by jmoenig** [comment]
BUT - beware, we've been discussing this among the devs and we're going to play with it in the dev version, but we might decide to roll it back for the v7 release if we find that it breaks too many existing curriculum materials.

**Comment by cymplecy** [comment]
I know the rules :)

But you could leave the send and wait in..... :)
