### ISSUE TITLE
Please add 2 input types

### ISSUE THREAD

**Issue by SchoolAshton** [jmoenig/Snap#2919]
please add the unevaleuated code and unevaleuated multiline block input types
```
'%smlt:{
type: 'text entry',
tags:'static'
},
'scode':{
type: 'text entry',
tags:'monospace static'
}
```
for custom blocks.

**Comment by WarpedWartWars** [comment]
Is this what you mean?
```
'%mltUE':{
    type: 'text entry',
    tags: 'unevaluated'
},
'%codeUE':{
    type: 'text entry',
    tags: 'monospace unevaluated'
},
```

**Comment by jmoenig** [comment]
why?

**Comment by SchoolAshton** [comment]
because I need it

**Comment by jmoenig** [comment]
folks, I appreciate your enthusiasm and your contributions, but let's not spam this repo with the kind of things you discuss in the forums. Thank you.

**Comment by brianharvey** [comment]
You do understand that custom blocks can already have these input types, right?  That's what the gear-ish icon in the bottom right of the dialog is for.

**Comment by SchoolAshton** [comment]
not these

**Comment by brianharvey** [comment]
<img width="742" alt="Screen Shot 2021-11-25 at 11 24 47 PM" src="https://user-images.githubusercontent.com/3885074/143542746-0246687b-3c24-4aec-81cc-6a8d9d211255.png">

**Comment by jmoenig** [comment]
Yeah, Brian, but they want those to be *unevaluated*, which they can't, and I won't agree to.
Also, I don't want to encourage these kinds of "issues" here, they are okay-ish (sorta) in the forums, but not in this repo. Here be the pros who formulate whole sentences.

**Comment by brianharvey** [comment]
Ah, okay.  Sorry.
