### ISSUE TITLE
[minor]my custom category library blocks not showing in my fork

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2920]
I have created them in a custom category and I can load them in fine but the custom category ones don't appear in the preview

![image](https://user-images.githubusercontent.com/2357428/144010687-49559cc8-2a99-4753-807b-4569abbf62b4.png)

![image](https://user-images.githubusercontent.com/2357428/144010896-f746dabb-8e4f-4d3b-98b6-83bb43ff645a.png)

Just passing on in case minor issue rather than design decision

**Comment by jmoenig** [comment]
Thanks! Fixing now...
