### ISSUE TITLE
Save as not working as expected

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2922]
I opened a project...

<img width="612" alt="Screen Shot 2021-12-05 at 10 17 37 PM" src="https://user-images.githubusercontent.com/6549787/144781665-7245fdd3-8e4b-4b57-9d30-3f9109765d2c.png">

Saved it with a new name...

<img width="612" alt="Screen Shot 2021-12-05 at 10 17 55 PM" src="https://user-images.githubusercontent.com/6549787/144781706-eaa8473d-9edc-4826-a416-a4ce7b3d5d67.png">

But the new file has the same old name and so I can't tell them apart...

<img width="612" alt="Screen Shot 2021-12-05 at 10 18 14 PM" src="https://user-images.githubusercontent.com/6549787/144781738-dd1f7663-c58b-4c94-930f-72261a39e63f.png">

**Comment by jmoenig** [comment]
Hi Mary, that's strange. Looks like what you're finding is the *old* project, not the copy with the new name. Can you find the new project elsewhere, i.e. in your account page? Maybe it just takes a little while to update the backend server.

**Comment by maryfries** [comment]
Both projects have the same name there too. 

![image](https://user-images.githubusercontent.com/6549787/145497407-6af90f42-6630-4485-b882-95effaacc432.png)

And they appear to be separate files with the same name. It seems that I can edit one without changing the other.

**Comment by cycomachead** [comment]
I think something is really broken here. It should not be possible to have two projects with the same name. :(

The cloud should update pretty quickly.

**Comment by jmoenig** [comment]
I've looked into this, and will be pushing a fix within the next days. I don't think both projects have the same name, but that the one which is supposed to have parentheses has one or more a trailing blanks in the title.

**Comment by cycomachead** [comment]
Yeah, I suspected it might be trailing blanks. Well, we should just fix this on the backend too. But editing the project name within Snap! always calling trim() would be good

**Comment by maryfries** [comment]
It is likely that I was trying to use parentheses in these titles as that used to work.

**Comment by jmoenig** [comment]
this has been resolved, I think.
