### ISSUE TITLE
A MORPH GOT STUCK TO THE HAND OBJECT

### ISSUE THREAD

**Issue by SchoolAshton** [jmoenig/Snap#2923]
[img](https://preview.redd.it/xbgpdajxbv381.png?width=1366&format=png&auto=webp&s=db1b8e22d0fa42781fd71e3979ce4145491fc446)

**Comment by jmoenig** [comment]
I believe you, but It'd be nice if you'd be a little more specific about it, so I can investigate.

**Comment by WarpedWartWars** [comment]
... And anyway, I don't think you're supposed to report issues in dev mode.

**Comment by SchoolAshton** [comment]
I messed with a glitched block. :(
