### ISSUE TITLE
Window focus

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2926]
Until today, I was able to close a Snap tab just like any other tab. Starting today (in dev), when I close a snap tab, Chrome asks if I'm sure, closes the window, and then _changes the focus to another window_, so I have to go back and find the window I had open again. (It's driving me a little nuts, and I imagine that it will bother students who have the curriculum open in a second tab and have other windows open too.)

**Comment by WarpedWartWars** [comment]
This might be a Chrome issue. Can you see if any other browsers do this?

**Comment by jmoenig** [comment]
this has nothing to do with Snap, and nothing has been changed for that closing pop-up for a dozen years. See, this is exactly what I'm afraid of, announcing an update triggers the expectation that the brightness of the Moon has been altered by something in a new Snap! release (that hasn't even happened yet) ;D
