### ISSUE TITLE
Two empty rings aren't equal

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2932]
![untitled script pic](https://user-images.githubusercontent.com/2138696/145707372-bac61daf-37cb-4702-a97f-2b923ece00af.png)

But this works

![untitled script pic (28)](https://user-images.githubusercontent.com/2138696/145707374-8315d6f2-2139-4d1d-85e5-1ff286f83b45.png)

which I can use but what I really want to say is

![untitled script pic (29)](https://user-images.githubusercontent.com/2138696/145707395-56aefa2e-6432-4ace-b732-0926152834d4.png)

Version 7

**Comment by ToonTalk** [comment]
Not sure what this should do

![untitled script pic (30)](https://user-images.githubusercontent.com/2138696/145707476-ac041c52-eec2-42b6-ba31-caa3b4d95486.png)

**Comment by jmoenig** [comment]
yep, that's a bug, thank you!
