### ISSUE TITLE
Split changes predicate to a reporter

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2933]
This is expected:
![untitled script pic (31)](https://user-images.githubusercontent.com/2138696/145708029-9f6e6ac2-e1de-4975-8fe4-c2ab3aa11ada.png)

But not this:
![untitled script pic (32)](https://user-images.githubusercontent.com/2138696/145708033-a0c0e7c3-aa04-4c78-9710-e450a532cf88.png)
![untitled script pic (33)](https://user-images.githubusercontent.com/2138696/145708036-89ed3176-cfb9-4fc6-85ba-a36cf3d5a9bf.png)

In my mind predicates are a subset of reporters but this shows Snap! thinks otherwise:
![untitled script pic (34)](https://user-images.githubusercontent.com/2138696/145708078-649ffa6b-20a4-4889-9573-9656651ff56c.png)

**Comment by WarpedWartWars** [comment]
The second and third ones are because it's ringified.
![untitled script pic - 2021-12-12T140008 414](https://user-images.githubusercontent.com/91039320/145729367-fcc83bad-cfef-49b0-9dfa-7e18ab7f3b65.png)
