### ISSUE TITLE
definition of receiving a ring of a ring

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2934]
I expected this to work:

![untitled script pic](https://user-images.githubusercontent.com/2138696/145721530-c0942082-3f4c-4cd4-946e-296ac18c5f49.png)

since 

![untitled script pic (35)](https://user-images.githubusercontent.com/2138696/145721552-58bd1168-029c-492d-b7b8-ef5576d1dad5.png)

and

![untitled script pic (36)](https://user-images.githubusercontent.com/2138696/145721600-6ebf4d91-8062-4702-b725-01697d30d163.png)

But is behaving as if it is receiving a ring of a ring

![untitled script pic (37)](https://user-images.githubusercontent.com/2138696/145721631-435c5df5-259a-4623-852e-3ef92fa2429a.png)

Perhaps related to https://github.com/jmoenig/Snap/issues/2836

**Comment by WarpedWartWars** [comment]
It's trying to get the definition of the ITEM 1 OF ... block.

**Comment by jmoenig** [comment]
Ken, you need to be careful about which block is ringified

**Comment by ToonTalk** [comment]
I don't understand. Look at the second image.

**Comment by ToonTalk** [comment]
By the way I just noticed that results in talk balloons don't use the Fade Blocks setting

**Comment by ToonTalk** [comment]
OK I see this now but how can one get the `definition of` something that is being reported?

If I'm walking through the structure reported by definition of then how can I find the definition of sub-expressions?

I guess I want a `definition of` that doesn't have an enforced ring around its input.

**Comment by jmoenig** [comment]
you can right-click and select "unringify"

**Comment by ToonTalk** [comment]
I found a workaround as
![untitled script pic](https://user-images.githubusercontent.com/2138696/145782921-2d60a5d2-00a5-4d74-8021-326b7b788e5c.png)

before I learned about unringify

I tried what I thought was intuitive which is to drag out the empty ring from a fresh copy of `definition of` - is it clear that it should produce a copy of the ring (at least when it is empty)?
