### ISSUE TITLE
Broadcasts not being received (sometimes!)

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2937]
Trying big Mayflower project in Snap!7 and some broadcasts don't seem to be being received (the project uses a lot of broadcasts)

So in this example - the here1 broadcast seems not to be received (its not in the log)

![image](https://user-images.githubusercontent.com/2357428/145810174-9f656095-1d73-49eb-8110-234aa03b5b47.png)

![image](https://user-images.githubusercontent.com/2357428/145810222-ccd5ece1-dd65-44e6-b221-ed4989b25188.png)

But if I remove the previous broadcast - then it does appear in the log 

![image](https://user-images.githubusercontent.com/2357428/145810485-8969eb32-d153-4b41-a7bd-fe0786126cbf.png)

![image](https://user-images.githubusercontent.com/2357428/145810557-1d8fb6f5-c5c2-4edc-b428-2c0ce5badd84.png)

I'll try and make a smaller project that exhibits the same issue

**Comment by cymplecy** [comment]
![image](https://user-images.githubusercontent.com/2357428/145812700-dcecf0e2-db08-415f-a2d2-7b983487f5b5.png)

**Comment by cymplecy** [comment]
Adding wait to my example cures the example :)
![image](https://user-images.githubusercontent.com/2357428/145814518-6a6ca314-8f6f-455b-ab4f-6665aac80602.png)
![image](https://user-images.githubusercontent.com/2357428/145814822-0ec5956f-d104-4318-b24d-0cf1a2e4015b.png)

but I am losing a real broadcast  so will try and narrow that one down :)

**Comment by jmoenig** [comment]
that's an expected race condition when you reenter an already running script. The "any message" hat block starts to run, then, before it gets a chance to run the "add" it again gets triggered with a new message, since it is the very *same* script.

**Comment by cymplecy** [comment]
Yes - I realised that in my edited 2nd post :)

My real lost broadcast is from a callback in the original MQTT library so probably an issue with the library - seeing if I can find out why

**Comment by jguille2** [comment]
Only a comment...
In your example, I think "broadcast and wait" is the solution.

Joan

**Comment by cymplecy** [comment]
Example is a bad example of my issue :)
I will raise another separate issue if / when I can narrow it down to something simple to demonstrate

**Comment by cymplecy** [comment]
Whole issue sorted - no missing broadcasts now - (needed a tweak to the library I was using)
