### ISSUE TITLE
Dropping a file of blocks when stage covers the window reveals palette categories

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2941]
I went to full size and dropped a blocks file and this is what resulted.
![image](https://user-images.githubusercontent.com/2138696/146232672-8bab564b-fe9d-43dc-9b35-9411cd1a5a55.png)

The category buttons don't seem to do anything.

Exiting full size and re-entering full size removes the palette categories.

**Comment by jmoenig** [comment]
thanks for reporting this!
