### ISSUE TITLE
size of Stage missing

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2943]
![untitled script pic (41)](https://user-images.githubusercontent.com/2138696/146250940-1aa65022-73e5-4ee7-9b66-e7ff5e7e7835.png)

height and width works

**Comment by jmoenig** [comment]
it's because the stage doesn't have a size.

**Comment by ToonTalk** [comment]
It does in the getter and setter library
![untitled script pic](https://user-images.githubusercontent.com/2138696/146323177-a73a3bc0-8841-4318-940f-145a4417718f.png)

**Comment by jmoenig** [comment]
yeah, those are the stage *dimensions*, the width and height of the stage. The *size* of a sprite is a single number representing its scale relative to the costume within the current stage scale as a percentage.

**Comment by cycomachead** [comment]
Should it not always just report 1 then?

-- 
Michael Ball
From my iPhone
michaelball.co
