### ISSUE TITLE
Progressive web app caching interfering with debugging

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2946]
Running Snap! only on localhost it seemed as if it was losing some changes I made today. And yet the source files looked fine. In Chrome's dev tab called "Application" I see it had cached a localhost version of a Snap! PWA. Deleting it fixed my problems. But I worry this will reappear.

PWAs are great but is there a way for them to not cache any localhost files? Perhaps sw.js should use absolute URLs instead of the relative ones it currently lists.

Note I didn't install the PWA. I.e. I did not click on this:
![image](https://user-images.githubusercontent.com/2138696/146398291-223c06d9-40bb-430f-8c3b-075b664eafe1.png)

I don't know how I activated the PWA caching.

**Comment by cycomachead** [comment]
The caching seems to be on by default. In development you seem to need to hard refresh more. :/ maybe we can add an exception for localhost?

**Comment by cycomachead** [comment]
The alternative is to keep incrementing the version number in sw.js

**Comment by DarDoro** [comment]
There are extension to block SW registration for selected site (Chrome, Firefox).
The simplest one
https://chrome.google.com/webstore/detail/block-service-workers/ceokjgeibfjfcboemhdpkdalankbmnej
https://github.com/clod81/block_service_workers
