### ISSUE TITLE
When adding a category with the color white, the text becomes hard to read

### ISSUE THREAD

**Issue by DXLB-Dichter** [jmoenig/Snap#2947]
**How To Replicate**

1. Click New Category
2. Set color to white (or any very light color)

**Solution**
Set text color to black. 

![Screenshot 2021-12-16 13 40 50](https://user-images.githubusercontent.com/80650273/146437721-62d6ce6d-0eab-4f2c-a87c-bc8b50c58b0d.png)

**Comment by jmoenig** [comment]
C'mon, plz don't spam this repo, I work here.
