### ISSUE TITLE
Error while hiding block, SpriteMorph.prototype.changeBlockVisibility error, "ide" not set

### ISSUE THREAD

**Issue by DarDoro** [jmoenig/Snap#2953]
Error while hiding block ( described https://forum.snap.berkeley.edu/t/hiding-blocks-programmatically-rises-an-error-in-snap-7/9646)
![2219bc2f70830eed3f1b71702d36fc6ca023c4a1_2_690x116](https://user-images.githubusercontent.com/16109071/147795615-673bdd0e-7bb5-4412-8ad7-9f1dd3fd108c.png)

**Comment by jmoenig** [comment]
thanks! Also thanks, @zakkolar for providing the fix in 859f1efa33671bc0aac6fff9b6be5f1cd8021880
