### ISSUE TITLE
PWA caching not working due to query part of URLs

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2957]
When I tried the Snap! PWA offline I got errors such as

snap.html:17 GET https://snap.berkeley.edu/snap/src/morphic.js?version=2021-12-10 net::ERR_FAILED

The solution is to pass in an option to ignore the part of the URL after the ? as follows:

`caches.match(e.request, {'ignoreSearch': true}).then(function(response) {`

**Comment by jmoenig** [comment]
Ooh, I never knew. Thanks, Ken, will add this for the next patch!
