### ISSUE TITLE
Will tags be mutated in-place in the future?

### ISSUE THREAD

**Issue by emixa-d** [jmoenig/Snap#2966]
A few days ago, Snap! (7.0.3) failed to build in Guix (see https://issues.guix.gnu.org/53326#0). The cause was that the v7.0.3 tag used to point to some commit (I'm not sure which exactly, but I guess d9ce299bf12a30b7bca12ad8bd4bc8db7bfbb1e9) but now it points to another commit (14f468ccac47164eeda24a6b4cecf4311f57340b).

Guix then bailed out because the hash changed -- it verifies the hash for ensuring no MITM happens and for reproducibility (to make sure that if you choose some version of Guix, then that version will always produce the exact same Snap!).

This was not a large problem, because we could update Snap! to 7.0.5.

Anyways, while I would recommend to never change what a tag refers to, Guix can deal with upstreams changing tags (by referring to the commit directly instead of via a tag), but there appears to be a slight preference for tags (for transparency reasons), so I'd like to know if this will happen in the future, such that the package definition in Guix can be modified appropriately if necessary.

**Comment by jmoenig** [comment]
yeah, that was an exception.
