### ISSUE TITLE
pick random 20 to 10 never picks endpoints

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2972]
This isn't exactly advertised to work, but since NUMBERS FROM 20 TO 10 does work, it's not an unreasonable thing for users to try.  The result is always in [11,19].

Suggested fix:
```
if (floor > ceil) {
    floor = +max;
    ceil = +min;
}
```
before the existing IF.

**Comment by jmoenig** [comment]
excellent catch, thank you!
