### ISSUE TITLE
result pictures taller than 16,384 pixels don't render properly

### ISSUE THREAD

**Issue by 1e1001** [jmoenig/Snap#2973]
the cutoff is exactly at 16,384 pixels vertically
14-bit integers?
![image](https://user-images.githubusercontent.com/22437115/151718398-c3632327-eb73-4c99-8b97-04e7e6d8084d.png)

**Comment by cycomachead** [comment]
This is a built in limitation of the JS Canvas API. It hasn’t changed in a decade and I don’t expect it to change anytime soon. 

Unfortunately working around this is a pretty significant amount of effort. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by 1e1001** [comment]
ah that makes sense, i probably shouldn't be rendering 21k-tall previews anyways

i also find it interesting that it still renders parts of the blocks past the cutoff though
