### ISSUE TITLE
Blockify fails to provide any feedback

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2977]
Import the following and click to blockify

[data.csv](https://github.com/jmoenig/Snap/files/8010208/data.csv)

It appears as if nothing happens but if you move the mouse and click the blockify blocks appear.

**Comment by jmoenig** [comment]
it's just that the gargantuan size of the second list item exhausts Chrome's memory, Ken. Other browsers such as Safari show it.

**Comment by ToonTalk** [comment]
Right. But couldn't the thing being dragged be clipped like it is after it is dropped?
