### ISSUE TITLE
A perhaps surprising behavior of =

### ISSUE THREAD

**Issue by gigamonkey** [jmoenig/Snap#2998]
Is this in fact the desired behavior?

![image](https://user-images.githubusercontent.com/250053/156935991-dc586c28-8941-4ac9-80d3-e521366b3dae.png)

(I was looking at `snapEquals` in `threads.js` (as a nice bite-sized bit of code to understand) and noticed that this would happen. Without looking at the code I would have expected this to evaluate to `true` as it seems pretty picky to consider those different values because of the presence of a space.

On the other hand, even if you said that that expression should be `true`, it's less clear to me whether this is desired or not:

![image](https://user-images.githubusercontent.com/250053/156936164-137012c9-1fe2-4b85-9a73-3215c03e5e9b.png)

Given that there's no special syntax for literal strings (with quotes or whatnot) if you actually wanted to have string values that differ only in trailing or leading space you have to treat these as different.

Anyway, if either or both of these are not the desired behavior, I'd be happy to cook up a revised `snapEquals` and submit a PR.

**Comment by brianharvey** [comment]
No, this is the intended behavior.  Spaces count.

If you take one of the arithmetic operators, with round input slots, you'll note that it won't let you type a space into it.  A space makes the string not be a number.

But if you want to live in an environment in which spaces aren't so important, check out the word and sentence library, which makes Snap<i>!</i> behave like Logo, so "hello␢␢␢␢␢world" is two words rather than 15 characters.

**Comment by jmoenig** [comment]
roping in @brianharvey as I don't have a strong opinion about this. My personal hunch would be to be waaay more strict and less permissive, also about case sensitivity, but we seem to have inherited this from Scratch/LOGO. Oh, I see, Brian has already chimed in...

**Comment by brianharvey** [comment]
&lt;flame>Case sensitivity is a terrible idea, one of many terrible ideas for which we have Thompson and Ritchie to thank.  Case is a _decoration!_  To think abc and ABC are two different objects is like thinking that abc and **abc** are two different objects.  And to set up conventions in which foo, Foo, and FOO are different kinds of objects is just asking for bugs.  Especially when your programming language is embedded in a natural language in which first letters of sentences are capitalized.&lt;/flame>

**Comment by gigamonkey** [comment]
> Case sensitivity is a terrible idea

Indeed. Just earlier today I was enjoying your old school Lisper rant^Wdiscourse here: https://github.com/jmoenig/Snap/issues/2895#issuecomment-933760979

> P.S. Our handling of numbers and strings is partly inherited from Scratch but partly not, so I'm sure you can find inconsistencies. That's on my very very long term list of things to worry about someday.

Yeah, for instance, despite not being able to type spaces into the round holes you can still jam a string in there:

![image](https://user-images.githubusercontent.com/250053/156944911-0e21c891-1649-4a75-8bf4-6e9474008d24.png)

Also this fun one lets you see through to the underlying Javascript:

![image](https://user-images.githubusercontent.com/250053/156944963-f9817357-e030-4c8a-bf99-c306d30c2546.png)

Anyway, thank you for humoring my questions as I tour through the code.

P.S. would you like me to close out issues like this to indicate I have no further questions on this topic and so it doesn't clutter up your issue tracker? Or do you have some process for closing out issues that I should let you do?

**Comment by brianharvey** [comment]
It's fine for you to close your issue.  Our "process" for closing issues is like good old fashioned garbage collection: every so often someone, often Michael, can't stand it any more and closes 40 issues at once.

**Comment by gigamonkey** [comment]
👍🏻
