### ISSUE TITLE
Incorrect hovered state in "About" dialog

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#30]
1. Open the about dialog (Snap! logo → About…)
2. Click the "Modules…" button
3. **Without moving the mouse**, click the "Back…" button
4. Click the "Credits…" or "License…" button

The "Back…" button looks like the mouse is hovered over it, even though it is not.

![Screen Shot 2013-04-12 at 19 00 33](https://f.cloud.github.com/assets/1578238/375580/cef48934-a3c4-11e2-921c-9cec989d4684.png)

**Comment by bromagosa** [comment]
This was coincidentally fixed by the modules dialog getting longer, so you no longer can click on "Back" without moving your mouse :laughing:

Closing it now.
