### ISSUE TITLE
Should rings be consider reporters?

### ISSUE THREAD

**Issue by gigamonkey** [jmoenig/Snap#3002]
I was surprised by this:

![image](https://user-images.githubusercontent.com/250053/157717257-2cfee67b-ebcb-4b47-927c-20b008d36a3b.png)

On the other hand:

![image](https://user-images.githubusercontent.com/250053/157717806-2a576be7-bd50-4825-80b2-cdea4dfac43a.png)

When I have a few minutes I'll dig into the code to try and understand this better unless someone tells me this is expected behavior.

**Comment by gigamonkey** [comment]
Ah. 

![image](https://user-images.githubusercontent.com/250053/157723422-ca23cd4c-7dd0-4b3d-98ac-52cb49ebe8fb.png)

![image](https://user-images.githubusercontent.com/250053/157723495-96367b4a-36c9-4ddd-8e3b-53b31b73ad22.png)

![image](https://user-images.githubusercontent.com/250053/157723543-2cad3cfa-0f21-4271-ac5f-52c7301496bf.png)

Where `IDENTITY` is this:

![image](https://user-images.githubusercontent.com/250053/157723198-dc087a1f-c404-41a7-9556-f215bf3df194.png)

Is there a built in version of IDENTITY or some other way to make a reporter ring that reports a constant value?

**Comment by jmoenig** [comment]
That's the intended behavior, it reports the *type* of the block inside the ring, its syntax.

**Comment by gigamonkey** [comment]
Yeah, it makes sense now. The thing that I was missing was how (mostly for testing) to make a reporter ring that always reports the same value since I can't just type a value in the hole of the ring.

**Comment by cycomachead** [comment]
![untitled script pic](https://user-images.githubusercontent.com/1505907/157746280-a74160b5-5723-4ba0-bc37-d7d52a7612b8.png)

This is usually what I do. :)

**Comment by cycomachead** [comment]
> But (I just realized this second) it's not as useful as it could be because its input slot is restricted to Number type.

Well, in that case doesn't JOIN work for text things? I've seldom found a need for a ID reporter where I am passing in literal values, but I guess it can come up.

**Comment by brianharvey** [comment]
Yes, but using JOIN to mean "identity function" isn't very intuitive.  And if the input isn't Text or Number, JOIN turns it into (for a user) gibberish.
