### ISSUE TITLE
Snap Project Not Opening

### ISSUE THREAD

**Issue by sifata3** [jmoenig/Snap#3010]
I was working on a project for school earlier today and when I come home and try to open the project it gives me the error "Load Failed: Error: Expected to close I" Please reach back to me as soon as possible as this is an important project I have been working on for weeks.

**Comment by jmoenig** [comment]
can you try recovering an earlier version? I've just released a patch that addresses a recent project-loading issue, but your case seems different, it looks like your browser was either crashing or in a low-memory situation when it was trying to save the project, so parts of it got lost.

**Comment by sifata3** [comment]
I attempted to recover it and it let me however It didn’t let me save that
version so I couldn’t continue working on that version of the project.
