### ISSUE TITLE
numbers from help seems out of date?

### ISSUE THREAD

**Issue by gigamonkey** [jmoenig/Snap#3011]
According to the help for `numbers from` the range must be ascending.

![image](https://user-images.githubusercontent.com/250053/158730092-308b4c81-6f33-4c3d-b03c-7a246a3c192c.png)

Yet this works?

![image](https://user-images.githubusercontent.com/250053/158730180-81e33cfb-0b4c-4b7f-8a3a-466fd77e1982.png)

Is the help wrong or should I really not depend on this working?

**Comment by brianharvey** [comment]
Oops, the help is wrong.  I'll fix it.  (Although I want to replace the word "to" in the title text with a pulldown choice of to/upto.)

**Comment by jmoenig** [comment]
fixed with https://github.com/jmoenig/Snap/commit/6366eccfcf009f6b8bb66cb925c64d3e6262b2f8
