### ISSUE TITLE
Join is adding a "0" instead of "1"

### ISSUE THREAD

**Issue by ferdithedev** [jmoenig/Snap#3031]
I have a variable, called output, with the value of "1000000000000000" (it's 16 characters long). When I now want to add a "1" with the join command (join output  "1") it is adding a "0" so the new value isn't "10000000000000001" but it's "10000000000000000"
![snap1](https://user-images.githubusercontent.com/69450649/162330781-f0d01262-1454-4d9a-94ae-ab24ecf2cc60.png)
![snap2](https://user-images.githubusercontent.com/69450649/162330803-1d2a3c7d-ab2b-498a-b6e6-a34a4af51ddd.png)
.

**Comment by brianharvey** [comment]
Yeah, we shouldn't do text-to-number conversion until the user actually does arithmetic on the value.

(Probably the actual stored number is the value you want, and the rounding is happening only when it's displayed in a watcher on stage, for what it's worth.)

But meanwhile, as a workaround, import the Bignums library, turn on bignums, and Snap! will then give you all the digits you want.

**Comment by cymplecy** [comment]
As Brian has said - its a display watcher issue (if number isn't too big and stays as an integer)

![image](https://user-images.githubusercontent.com/2357428/162400415-58363c59-2505-4ab9-a3b6-c05a2971939b.png)

As a workaround for longer binary numbers, I've sometimes added a "x" to the beginning and then stripped it back off later
![image](https://user-images.githubusercontent.com/2357428/162401210-210801f0-8092-4427-b194-71940f50864d.png)

**Comment by ferdithedev** [comment]
Okay, thank you that helped a lot

**Comment by ferdithedev** [comment]
So sorry for asking again but how would I make a block like "join input list" because when i'm doing this with a loop that goes through the list of single digits and i want to join them again to a singe variable the same problem happens again.

**Comment by cymplecy** [comment]
Could you explain a bit more what your problem is.  What are you trying to
acheive in the end?

Also, your might be better off asking this on the forum if you just want to
ask general questions.

**Comment by cymplecy** [comment]
I've just realised what your asking :)

If you drop a list over a join block, get it to turn red before releasing
your mouse button and it will automatically become a join input list block
:)

**Comment by ferdithedev** [comment]
Thank you
