### ISSUE TITLE
[FR]Could copy to clipboard be added to the right-click menu?

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3037]
as well as the export option?

![image](https://user-images.githubusercontent.com/2357428/162986206-7b799161-8804-4d5b-a467-638c1c9d610d.png)

**Comment by jmoenig** [comment]
problem with this is that the Clipboard API is still very much in flux, and not - uniformly - supported across browsers https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility
