### ISSUE TITLE
is identical too help has a green `false`

### ISSUE THREAD

**Issue by gigamonkey** [jmoenig/Snap#3038]
The help for `IS IDENTICAL TO` shows the false case with a green false:

![image](https://user-images.githubusercontent.com/250053/163030794-13cf0427-3f90-477a-b61c-31671f63982c.png)

Seems like it should show it like this:

![image](https://user-images.githubusercontent.com/250053/163030710-9afbefe8-2863-4036-845a-3a81d07ba8f7.png)

**Comment by WarpedWartWars** [comment]
I can fix that.

**Comment by brianharvey** [comment]
Sure, whenever you're ready.  Thanks!

**Comment by WarpedWartWars** [comment]
Working on it right now.
