### ISSUE TITLE
New ask/menu features

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3040]
Just a quick suggestion/FR
I think we could do with a method to set the answer to null 
Or even better, set it any value

I've done it before when required using JS but I feel it would be very useful with the new facilities to have it done natively

https://forum.snap.berkeley.edu/t/solved-any-way-of-setting-the-value-the-answer-sensing-block-reports/5486/2

**Comment by jmoenig** [comment]
beats me why you need that - instead of just using a variable - but there you go: ASKing <nothing> (or a falsy value) now also  clears the "answer". Does that help?
