### ISSUE TITLE
src_load not working properly in Chrome 101.0.4951.41 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3043]
This problem does not arise in Edge or FireFox.

src_load does work for https://snap.berkeley.edu/ and the domain if it is cloned (and it works fine for localhost) It does not work for https://ecraft2learn.github.io/ai/ (It probably won't work for https://microworld.edc.org which is on SnapExtensions.urls)

To reproduce enable JavaScript and run

src_load on, for example, https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.3.0/lodash.js (from an MDN example of loading a script)

net::ERR_FAILED shows up in the Network tab of dev tools

Here is the stack trace:
(anonymous) @ https://snap.berkeley.edu/snap/src/extensions.js?version=2022-02-08:1026
Process.reportApplyExtension @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:866
Process.doApplyExtension @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:858
Process.evaluateBlock @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:840
Process.evaluateContext @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:794
Process.runStep @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:693
(anonymous) @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:367
ThreadManager.step @ https://snap.berkeley.edu/snap/src/threads.js?version=2022-03-16:365
StageMorph.step @ https://snap.berkeley.edu/snap/src/objects.js?version=2022-03-16:8485
Morph.stepFrame @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:3225
(anonymous) @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:3226
Morph.stepFrame @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:3226
(anonymous) @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:3226
Morph.stepFrame @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:3226
WorldMorph.doOneCycle @ https://snap.berkeley.edu/snap/src/morphic.js?version=2022-01-28:12046
loop @ https://snap.berkeley.edu/snap/snap.html:52

**Comment by DarDoro** [comment]
Works for me with JS enabled to bypass URL whitelist
Chrome 101.0.4951.54@Win10/64
COORS headers seems to be OK.

I've seen cookies accumulate to the point where they block the request because the data becomes malformed/big and the server is unable to parse it.
