### ISSUE TITLE
FLATTEN should only flatten one layer, not all the way to atoms.

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3052]
I was reminded by this discussion:
https://forum.snap.berkeley.edu/t/how-to-resample-a-list-quickly/11236
following a request by Mark Guzdial.

**Comment by jmoenig** [comment]
I disagree strongly. Flat means flat.

**Comment by brianharvey** [comment]
Hmm, to my surprise everyone seems to agree with you.  But in that case FLATMAP can't just be (FLATTEN (MAP ...)).  You learn something every day.  I guess I could get used to (APPEND INPUT LIST: ...) if that worked on atoms, or SENTENCE (which does just what I want) if it were primitive.
