### ISSUE TITLE
Continuation looks weird when displayed with SAY

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3060]

**Comment by brianharvey** [comment]
![untitled script pic](https://user-images.githubusercontent.com/3885074/172574062-78e1fe51-91d3-4224-8edd-74f3e460f5f0.png)
<img width="196" alt="Screen Shot 2022-06-08 at 1 48 04 AM" src="https://user-images.githubusercontent.com/3885074/172574093-9fc89917-71ad-47f4-81dd-24cc37afe889.png">
I know that the expression is an error but I was trying to make a point to a forum kid...

This happens both in dev and in the official version.

**Comment by WarpedWartWars** [comment]
I think it's the variadic input that's the problem:
cont of
![untitled script pic - 2022-06-08T143800 214](https://user-images.githubusercontent.com/91039320/172722107-b2190dbd-efa7-44de-a3a0-83e0ab5230c6.png)
is
![untitled script pic - 2022-06-08T143853 762](https://user-images.githubusercontent.com/91039320/172722122-5db5803b-5b1e-48cf-ab02-85115dff7e87.png)
cont of
![untitled script pic - 2022-06-08T143827 722](https://user-images.githubusercontent.com/91039320/172722130-76ab8023-6364-47a1-a145-1ba8e1be6ff5.png)
is
![untitled script pic - 2022-06-08T143847 552](https://user-images.githubusercontent.com/91039320/172722143-17c9f4a0-f807-400d-925a-8892176edf1e.png)
cont of
![untitled script pic - 2022-06-08T143909 529](https://user-images.githubusercontent.com/91039320/172722153-58807017-ad47-4903-a2cc-6bfe47c0808f.png)
is
![untitled script pic - 2022-06-08T143912 280](https://user-images.githubusercontent.com/91039320/172722162-220df22a-6866-4980-916e-5dc4d38aeacc.png)

**Comment by brianharvey** [comment]
Right, it works with - instead of +.  But in my example the + block isn't missing; it's just white on white.

**Comment by WarpedWartWars** [comment]
That's because the speech bubble itself is white. Try dragging it out of the bubble.

**Comment by jmoenig** [comment]
this looks like a bug, thanks, @brianharvey ! I should probably fix it...

**Comment by jmoenig** [comment]
hmm... on further investigation it turns out that it's more of a misfeature than a bug, because the continuation is the *slots* and not the *block*. Huh, need to rethink continuations at some point...
