### ISSUE TITLE
DEFINITION OF BLOCK error with reporter reporting constant text

### ISSUE THREAD

**Issue by WarpedWartWars** [jmoenig/Snap#3061]
I think these should explain:

![untitled script pic - 2022-06-13T104752 194](https://user-images.githubusercontent.com/91039320/173413791-896b9653-978a-46ae-becb-bff6204e18e8.png)
![untitled script pic - 2022-06-13T104755 619](https://user-images.githubusercontent.com/91039320/173413800-d7ab0cfa-af15-4b5b-9e53-25d1456318da.png)

This is using the feature from the latest commit (Jun 02).

**Comment by jmoenig** [comment]
excellent catch, thank you!

**Comment by WarpedWartWars** [comment]
Wouldn't this:
![untitled script pic(4)](https://user-images.githubusercontent.com/91039320/174916138-5145104b-6af7-4152-aa1d-de296d3c8f5b.png)
make more sense?

**Comment by jmoenig** [comment]
naw, constants are better modeled as variables. I'm not a fan of reified literals.
