### ISSUE TITLE
[dev]prompt errors out if supplied with a number

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3065]
I was wanting to put current value of a variable as the title in the menu but it errors out due to the translate primitive if it is numeric

![image](https://user-images.githubusercontent.com/2357428/178119079-f04ff831-da20-43c1-8224-49a057260911.png)

As well as this, I think it should handle any other type accepted as a value in the prompt options

**Comment by cymplecy** [comment]
submenu has the same issue
![image](https://user-images.githubusercontent.com/2357428/178119277-17363712-1075-429d-a1d7-f0a9689c8000.png)

**Comment by jmoenig** [comment]
Ooh, excellent catch, thank you, Simon!
