### ISSUE TITLE
Playing a lot of Music can cause console to be spammed up and will prevent further music from being played

### ISSUE THREAD

**Issue by HM100** [jmoenig/Snap#3075]
I have created a game project and after a few use of the game, console gets logged with this:
```
[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
```

Can something be done so as this not to happen. This appears in later chrome versions see [this bug](https://crbug.com/1144736#c27) for more. You can check out [this project](https://snap.berkeley.edu/project?user=hm100&project=Pastry%20Planet%20Iris%20X%E1%B5%89%C2%B2) for more. Before that bug begins, music will start to cut out a bit before it completely stops out. I'm unable to check Firefox but it happens in Chrome and it is irritating.

**Comment by HM100** [comment]
This bug also affects a few other projects

**Comment by HM100** [comment]
This bug affects two blocks:
![image](https://user-images.githubusercontent.com/30199227/180868755-f5d8c676-37a4-4a51-8b4e-4bfaca0f846b.png)

**Comment by HM100** [comment]
Any ETA

**Comment by HM100** [comment]
Still happens. Is there any ETA for fix? As this issue makes projects with sound to gradually have degraded music until it eventually stops having any sound heard
![image](https://user-images.githubusercontent.com/30199227/220472693-808f6fdc-e41d-45df-96ff-0ea126429ec9.png)

**Comment by pessoacasual12** [comment]
I use sound effects in my game and this happens as well. The sounds get more and more cut until eventually it doesn't play sounds anymore.

**Comment by HM100** [comment]
In Chrome, I no longer get that error in console but sounds still cut until they don't play anymore
