### ISSUE TITLE
Option-drag to duplicate

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3077]
Feature request: Could option-dragging an object (a block, script, variable, etc.) drag off a _copy_ of the original rather than the original? That's fairly common across apps and would be discoverable for folks who use it elsewhere. It would be quicker than using the drop-down. Thanks!

**Comment by cymplecy** [comment]
"option-dragging"?  Do you mean something like holding down control and dragging?

"That's fairly common across apps"  Could you give an example - I've been programming for 45 years and never heard of this? :)

**Comment by ego-lay-atman-bay** [comment]
I have a suggestion for this, maybe use alt+click and drag to duplicate the blocks under it, and shift+alt+click and drag will duplicate only the block under the mouse (similar to how scratch addons Duplicate script with Alt key addon does it).

**Comment by cycomachead** [comment]
Jens and I were discussing this -- we're both a little hesitant to keep adding hidden keyboard shortcuts, and features at the moment.

I agree with the desire though. It's useful on a Mac, though I am really not sure how universal it is outside of power users. That said, what we were thinking about is that a 'Curriculum Developers' or 'Power Users' extension or some sort would be a useful thing to have, that could allow these enhancements.
