### ISSUE TITLE
Unused blocks not working?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3080]
I'm not able to get "unused blocks" in the File menu to work with the Colors and Crayons library.

**Comment by brianharvey** [comment]
In what way is it failing to work?  Presenting too many blocks, or not enough, or what?

**Comment by ego-lay-atman-bay** [comment]
a similar issue, not sure if it's related, is that the checkboxes in the unused blocks menu don't reflect if the block is checked or not. They only change when you select all or none, not when you click on the checkbox. This is just a visual bug, as when you click a checkbox, it is unchecked internally.

**Comment by maryfries** [comment]
@brian It's not working in that the unused blocks don't get removed. Michael and I think it's that there are too many dependencies so you can't automatically remove any blocks once they are added.
