### ISSUE TITLE
adding intermediate arguments to JOIN?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3081]
Has the ability to add blocks in the middle of a string of inputs been removed? Dan was presenting today and couldn't figure out how to do it, and we both remember seeing the feature in the past. 🙃

**Comment by DarDoro** [comment]
Place the cursor over the slot
![insdel](https://user-images.githubusercontent.com/16109071/181840109-6e002915-dcb4-4226-9e35-1cf548311347.png)

**Comment by maryfries** [comment]
Thanks! We tried so many things, but we didn't try that! 🤦‍♂️

**Comment by maryfries** [comment]
Could we change the menu options to "insert a slot before" and "delete this slot"?

To the point that raised this issue, could this menu also appear when you click _between_ slots (which is the intuitive place to click and what both of our brains were determined to do)?
