### ISSUE TITLE
shouldn't get error message after clicking stop sign

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3082]
Here's the error message I got:
<img width="778" alt="Screen Shot 2022-07-30 at 11 29 00 AM" src="https://user-images.githubusercontent.com/3885074/181936921-09fa94e3-27f6-43bf-8a92-e34e51e16635.png">

I was debugging a procedure that wasn't working by putting a pause in:
![untitled script pic](https://user-images.githubusercontent.com/3885074/181936945-ca4b1873-8b9c-4233-845c-3c17a85a4db9.png)

The second SET (BLOCKS) was just there for debugging and isn't meant to be part of the finished procedure.  With it there, since it changed the value of BLOCKS, the REPORT isn't expected to work.  I just made a watcher for BLOCKS to see what value I got, then I clicked the stop sign.

So I shouldn't get an error message, even though there would be an error if the procedure continued.

Here's the project:

https://snap.berkeley.edu/versions/dev/snap.html#present:Username=bh&ProjectName=callers-test

**Comment by jmoenig** [comment]
stopping everything doesn't *immediately* stop everything, only after completing the current atom. First, paused threads resume, then the "when I am stopped" scripts run, and last blocks that are directly clicked in the scripting area still try to display their result bubble. So, yes, there can be the occasional error message popping up, especially for paused processes. In that case, pressing STOP again removes those.
