### ISSUE TITLE
"reporter didn't reporter" when changing a custom block from command to reporter

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3083]
I was trying to write a custom reporter, but forgot to push the Reporter button, so it created a command.  But I dragged a REPORT block into it, so its definition was correct.  Then I tested it, and nothing happened, and that's when I noticed that I'd made it a command instead of a reporter.  So I edited the block and changed it to a reporter.

From then on, when I tested it, I got a "reporter didn't report" error.  For a long time I thought there was a bug in my code, or maybe a bug in SPLIT BY BLOCKS, but eventually, because I'm a wizard rather than a real kid, I thought to throw away the REPORT block from the definition and drag in a new one, and that fixed it.

So, this all happened because I didn't make the reporter a reporter in the first place.  But that shouldn't have poisoned the REPORT block, which should start working once I made my reporter a reporter.

**Comment by jmoenig** [comment]
confirmed! That's a bug that needs to be adressed. Thanks!
