### ISSUE TITLE
context doesn't work as I expect

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3085]
Here's my procedure:
![split-by-block-test script pic](https://user-images.githubusercontent.com/3885074/182001926-f12b5ee3-2ad5-406f-bc42-76186479f382.png)

Inside ` I end up in effect doing 
![split-by-block-test script pic (1)](https://user-images.githubusercontent.com/3885074/182001989-d8e8306e-a338-45d0-a632-f69353af9a6c.png)
where CALLER is the context input (THIS SCRIPT) from ORDINALS.

The context displays as 
![split-by-block-test script pic (2)](https://user-images.githubusercontent.com/3885074/182002061-9225301f-4231-4a14-b736-d1e21b276bb9.png)
with the body of ORDINALS in it.

Shouldn't I be able to get NUM out of that context?  The error is
<img width="410" alt="Screen Shot 2022-07-30 at 3 23 09 PM" src="https://user-images.githubusercontent.com/3885074/182002112-431d2f58-14e4-4183-8d50-16a16b95bb84.png">

**Comment by jmoenig** [comment]
@brianharvey this is the fix we've come up with this morning (my time). It makes sense to me, i.e. I can formulate an understanding why it should work and what it does (differently), and it also passes my other test cases, so I feel confident enough to push it at this time. Please give it a banging yourself, though, it would be so great if this got you (one step) farther... Thanks!

(also feel free to reopen this issue if it doesn't)
