### ISSUE TITLE
alphabetizing custom categories means that category numbers can change

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3086]
This is undesirable, right?

**Comment by jmoenig** [comment]
nah, that's to be expected. If you're into meta-programming you can't rely on the order of things to stay the same, especially if you're mutating those things, inserting and removing things. Note: you now have a way to always check the current categories in your system (in their order):

![my_categories](https://user-images.githubusercontent.com/2596285/182022160-c3bf026e-14be-495a-a137-548df3e4f7ec.png)
