### ISSUE TITLE
defining a block with multiple inputs in a row

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3088]
What am I doing wrong?

![split-by-block-test script pic](https://user-images.githubusercontent.com/3885074/182008364-71e4a7d9-feec-4b7c-8ed2-ae7fdae94fa3.png)

![split-by-block-test script pic (1)](https://user-images.githubusercontent.com/3885074/182008380-fde943da-eb6c-40c9-88c5-25be3ea00fba.png)

![split-by-block-test script pic (2)](https://user-images.githubusercontent.com/3885074/182008412-c92a5639-07aa-4782-a213-c4007797c51e.png)

Even if I'm confused about how to do it, either the block should have two inputs or I should get an error message about the number of inputs in the definition not matching the number in the label, right?

**Comment by jmoenig** [comment]
Ha! that's a bug. Thanks!

**Comment by jmoenig** [comment]
@brianharvey same here, I've just pushed a fix that *appears* to fix this while passing all my other tests. But please do run yours and let me know of any hiccups. Thanks!

**Comment by brianharvey** [comment]
The block is now defined correctly, but won't run:

<img width="1339" alt="Screen Shot 2022-07-31 at 10 23 26 AM" src="https://user-images.githubusercontent.com/3885074/182038457-c1677fd9-359d-44d5-8f71-855cad95f617.png">

**Comment by jmoenig** [comment]
Ah, haha! So I think this is actually the other bug about the context of `this script` that didn't get fixed (and even broken). lemme try to refine the fix...

**Comment by jmoenig** [comment]
okay, can you try again? Make sure to flush your cache. Tnx!

**Comment by brianharvey** [comment]
Yay!  It works!
