### ISSUE TITLE
make sure to always trim variable names

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3099]
![image](https://user-images.githubusercontent.com/2138696/183250501-a0c9e4ac-4ffe-43ca-82d8-ff2ffca46e91.png)

I did this by importing 'data.csv', deleting it, and then importing 'data (6).csv' (file name created by Windows). If I only import  'data (6).csv' all is fine.

**Comment by jmoenig** [comment]
I bet your "data" variable (the one you see in the palette) isn't named "data" but "data " or something else that Windows did to it.

**Comment by ToonTalk** [comment]
Yup. You're right, it is 'data '. But why isn't the name 'data (6)'?

**Comment by cymplecy** [comment]
https://forum.snap.berkeley.edu/t/minor-imported-exported-variable-value-name-not-fully-utilised/9993
