### ISSUE TITLE
One can add a project to old SnapCon collections but not 2022

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3106]
![image](https://user-images.githubusercontent.com/2138696/184892103-3a111fa5-975d-4445-ae2c-f7f5cfeb8934.png)

Also this is an odd list

**Comment by brianharvey** [comment]
Added toontalk to people who can add to 2022.

As for the "odd list," the owner of a collection can mark it as open to anyone, and the list you're seeing is the open-to-anyone collections plus the ones you own plus the ones that have explicitly invited you.

For the "when things slow down™" list:  Maybe if nobody's looked at a collection in a while it should be removed from the open-to-anyone list so as not to have that list be cluttered.
