### ISSUE TITLE
Taking screenshot on Mac changes size of small stage from 1/2 to 1/4 size

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3111]
This happens after taking a region screenshot (command-shift-4) while the Snap<i>!</i> window is active, even if the screenshot is of a screen region not in the browser window.  Command-shift-3 doesn't do this.  Control-N for new project fixes it.

To clarify, it's not just that the stage is 1/4 size at the moment I took the picture below; it's that pushing the fullsize/halfsize button from then on toggles between full size and quarter size.

<img width="1384" alt="Screen Shot 2022-09-01 at 1 09 44 PM" src="https://user-images.githubusercontent.com/3885074/188003061-b0b7994b-41d6-4e4e-ba6c-1960221ab56d.png">

PS It has an Update (Chrome) button in this picture, but I just updated (Version 104.0.5112.101) and it still happens.  MacOS 12.4.

**Comment by jmoenig** [comment]
Hmm... I can't reproduce this. Maybe you have some additional key-bindings?
