### ISSUE TITLE
Call acts as identity when ring was created by join

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3113]
![untitled script pic (8)](https://user-images.githubusercontent.com/2138696/188533354-356d798a-7d19-4109-aa5e-81daccd06c7e.png)
![untitled script pic (56)](https://user-images.githubusercontent.com/2138696/188533367-216ff981-d3ec-49ef-8328-8fc85fa7e5fa.png)

**Comment by ToonTalk** [comment]
Perhaps related to https://github.com/jmoenig/Snap/issues/3053

**Comment by ToonTalk** [comment]
But this works:

![untitled script pic (57)](https://user-images.githubusercontent.com/2138696/188533886-b9f14fb5-de40-47bd-93ea-0769f36441b1.png)

**Comment by ToonTalk** [comment]
I guess one needs a way to invoke `call `without a ring around it.

It is very odd that one needs to introduce a variable to get around this problem.

**Comment by ToonTalk** [comment]
Perhaps if one drags the ring out of `call `a new ring shouldn't automatically appear.

**Comment by brianharvey** [comment]
This is what UNRINGIFY is for.

The automatic provision of a ring is the rule so that relatively naive users can use and write higher order functions.  If you're doing metaprogramming, you're by definition not a naive user and it's okay to make you unringify functions that you've created dynamically from code.

**Comment by ToonTalk** [comment]
Makes sense. So is it the case that to programmatically unringify one needs to introduce a variable for the ring?

Automatic ring provision is good but should it happen again when the user explicitly removes the ring from `call`?
