### ISSUE TITLE
Bitwise operators unexpectedly returning negative numbers

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3122]
I'm (trying) implementing the MD5 hash algorithm in Snap! and I've hit a snag

![untitled script pic (34)](https://user-images.githubusercontent.com/2357428/192499534-ae7fcf84-d88e-4586-86dc-4f5881e73b64.png)

Although 0x80000000 is normally considered to be positive in Snap!

![MD5 script pic (1)](https://user-images.githubusercontent.com/2357428/192500549-24c4fde8-5948-4636-ba74-eaa0ebdfc5d8.png)

 I suspect the AND function is treating the leading 1 of the result as a two's complement flag and returning a negative value
 
It would be very nice if it didn't :)

**Comment by brianharvey** [comment]
Of course it's only the display that's questionable; the actual value returned is correct.

I believe both of these displays are as close to correct as Javascript allows.  The trouble is that Javascript _arithmetic_ doesn't include integer type at all; all numbers are 64-bit floats.  Bitwise operators, on the other hand, work on 32-bit integers.  And in fixed-width integer arithmetic, numbers with the sign bit on are negative.  What it says in the textbooks is that bit _n_ (counting from the right) has the value 2^_n_ except that bit 31 has the value -(2^31).
So the bitwise operator is correctly reporting a negative number.

64-bit floats, though, can represent exact integers up to 2^53.  So it correctly reports that that bit pattern is a positive number.

W3schools:

> JavaScript stores numbers as 64 bits floating point numbers, but all bitwise operations are performed on 32 bits binary numbers.

> Before a bitwise operation is performed, JavaScript converts numbers to 32 bits signed integers.

> After the bitwise operation is performed, the result is converted back to 64 bits JavaScript numbers.

One could make a case for using 64-bit-wide bitwise operators to match the 64 bits of numbers.

One could also make a case for providing arbitrary-width exact integers...

**Comment by cymplecy** [comment]
I think that bit operators should be able to handle 32 bits without unexpected results going from Snap! to the engine room and back again :)

In an ideal world I think Snap! bitwise operators should deal with numbers approaching the 56 bit limit integers that Snap! normally copes with.

But at a minimum, it would be nice to see it deal with 32 bits.

I think its easy to achieve using Snap! but maybe should be done in the primitive?
 
AND example

![ANDmod](https://user-images.githubusercontent.com/2357428/192715515-bec947cd-a5a1-4ff0-a30a-0fa1dc7550e5.png)

And also, I think the unsigned right shift needs a little mod to prevent it giving unexpected results

![unsignedRightShiftMod](https://user-images.githubusercontent.com/2357428/192715848-b2596311-5033-4b93-9b70-409865377da8.png)

And, thinking about it, maybe the names of the right shifts need to changing to make them more Snap!ish

I think that users would expect the standard right-shift to be the unsigned version

I'd vote for not even having the signed version as I don't think it's appropriate for Snap!

**Comment by jmoenig** [comment]
Thanks for this discussion, I'm closing this issue, because Snap! is just deferring the bitwise operations to JS
