### ISSUE TITLE
Telling another sprite to report behaves badly

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3126]
![image](https://user-images.githubusercontent.com/2138696/195757427-32fcdae1-6e7f-406c-bf4c-70e38e65b342.png)

**Comment by jmoenig** [comment]
this is the correct and intended behavior though. `report` terminates the script. Using `tell` only binds the execution context, i.e. the environment in which variables are looked up, to another sprite, but it is *not* something that controls *threads*.

**Comment by ToonTalk** [comment]
But then why this?
![image](https://user-images.githubusercontent.com/2138696/195776695-52bdc292-fa9f-4363-a1b2-645b2b7aa60b.png)

**Comment by jmoenig** [comment]
because in this case `report` only returns from the procedure

**Comment by cycomachead** [comment]
FWIW, this isn't specific to `tell`, but all lambdas.

**Comment by ToonTalk** [comment]
So `report `in this context is like
![untitled script pic](https://user-images.githubusercontent.com/2138696/195784500-b3218b3c-4f26-4013-9ea7-04058a5cf9e7.png)

I find this surprising since all other languages `return` just terminates the procedure it is in. Which is what it does in my second example.
