### ISSUE TITLE
Dutch translation 

### ISSUE THREAD

**Issue by HansAusHolland** [jmoenig/Snap#3139]
The split by block in Dutch should be "woord" instead of "Wort". I also would suggest to keep "cr" instead "regelterugloop", which in my opinion is ugly. 
<img width="431" alt="Scherm­afbeelding 2022-11-06 om 11 30 21" src="https://user-images.githubusercontent.com/21287856/200175236-fc5ecb64-66e6-4eb9-ab12-8429c164e2ba.png">

**Comment by jmoenig** [comment]
I agree, Hans, thank you! I'll change it now...
