### ISSUE TITLE
"when I receive [green flag]" triggers on (almost) all messages 

### ISSUE THREAD

**Issue by lantti** [jmoenig/Snap#3151]
The "when I receive"-block is behaving somewhat unexpectedly when set to trigger on the green flag. In addition to triggering on the green flag, it also triggers on any other message except` __clone__init__`. This seems to be happening because the event to listen to, set by the green flag icon on the menu, is` ['__shout__go__'] `and  SpriteMorph.prototype.allHatBlocksFor() (according to my understanding) interprets event arrays as wildcards. I ran into this when switching scenes and using the "when I receive"-block to pass some extra data with the green flag to the next scene. An easy workaround seems to be setting a new message for the "when I receive"-block with bare `__shout__go__`, this way it doesn't get wrapped in an array and seems to work just fine.

A small script to demonstrate the issue:
https://snap.berkeley.edu/project?username=lantti&projectname=when%20I%20receive%20green%20flag

**Comment by jmoenig** [comment]
thank you, good catch and excellent problem analysis! Amazing that this bug has gone unnoticed so long :)
