### ISSUE TITLE
THIS SCRIPT doesn't capture variables in rings

### ISSUE THREAD

**Issue by Jonathan50** [jmoenig/Snap#3154]
Given this:
![untitled script pic (3)](https://user-images.githubusercontent.com/13597222/209750006-9607cfe3-851b-4c47-ab2e-3a9339058852.png)
this works as expected:
![untitled script pic (2)](https://user-images.githubusercontent.com/13597222/209750015-1250a88c-3d30-4b98-8e27-84a45ca12510.png)
![untitled script pic (1)](https://user-images.githubusercontent.com/13597222/209750019-55cc1165-645f-4908-8059-68060757668e.png)
as does this:
![untitled script pic (4)](https://user-images.githubusercontent.com/13597222/209750149-201e7479-2cd8-4503-a2c6-e86464f761a0.png)

However, this should be equivalent but doesn't work:
![untitled script pic (5)](https://user-images.githubusercontent.com/13597222/209750358-948a7605-b5e2-40eb-b731-f9d23ab7bf84.png)
nor does this:
![untitled script pic (6)](https://user-images.githubusercontent.com/13597222/209750421-f637d946-c362-43ad-a7a0-6284b60a3dd3.png)

That's not a useful example, but QUASIQUOTE does the same thing as this macro and also suffers from this problem. This isn't a big problem because QUASIQUOTE or something similar is unlikely to be used in a ring.

(THIS SCRIPT does display the ring, however.) https://snap.berkeley.edu/snap/snap.html#present:Username=jonathan50&ProjectName=macro%20test

**Comment by jmoenig** [comment]
Thanks! Took me a while to get around to this. Fixing now...
