### ISSUE TITLE
Unidentified External error

### ISSUE THREAD

**Issue by ahmadkcobn** [jmoenig/Snap#3174]
When script/projects are run, users are getting the following error message:
Unidentified External error
Failed to open MIDI output device Microsoft MIDI Mapper:
Unidentified External error.
![BYOB error](https://user-images.githubusercontent.com/124145337/216049949-df05b0a4-9a52-4592-acd9-35236b81b273.jpg)

If anybody can point to the right direction? how can we resolve this in SNAP. 

[Flappy Bird Game - Catch Up Template.zip](https://github.com/jmoenig/Snap/files/10557193/Flappy.Bird.Game.-.Catch.Up.Template.zip)

**Comment by jmoenig** [comment]
Hi, sorry you seem to be encountering an issue with the old BYOB version that has been replaced / superseded by Snap! for over a decade. I'd love to look into this but my laptop won't even let me install BYOB anymore. Any chance I can convince you to switch to Snap!?

**Comment by ahmadkcobn** [comment]
Hi jmoenig,
thanks for rapid response, really appreciate it. Suggestion to move to Snap is already under consideration and still going through talks. Is there any solution to resolve this for now?

**Comment by jmoenig** [comment]
I really have no idea about this error. It seems to be related to the part of BYOB that was the old Scratch v1.4 code base. I don't see your project using MIDI at all when I opened the project in Snap to glance over the scripts. Maybe try not using any sound output? I'm really sorry, I did love my old BYOB application and I'm really sad that I can't even run it on this shiny new Mac anymore.

Glad to hear you're considering moving to Snap! This should be really easy for you and for your students, you can even directly open the BYOB projects in Snap and continue working on them. Also, we and the community will be able to help you much better with any issues you might encounter. If you're worried about having (your school and students) to be online: Did you know that you can install Snap! locally on a laptop so you don't need to go online?

**Comment by cymplecy** [comment]
JFI I opened the project in  BYOB on my Win11 machine and it doesn't give me any errors when I run it

I even tried to provoke an issue my recording/playing sound and that worked fine as well
![image](https://user-images.githubusercontent.com/2357428/216059114-0cd6436e-3cf8-4c8d-be28-2281b7784dd4.png)

**Comment by ahmadkcobn** [comment]
Thanks for confirming there isn't any issue with the project or script. As mentioned before, we will be moving to Snip very soon. Is there MSI version available for it? ( i think i will have to PM jmoenig for this).

**Comment by ego-lay-atman-bay** [comment]
There is no MSI for snap. If you go onto snap in chrome (idk about
Firefox), there should be an option somewhere on the URL bar that will
allow you to install snap. This will add a desktop shortcut, and you'l be
able to run it offline.
