### ISSUE TITLE
Blocks do not return to original colours after pausing

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3176]
and then single stepping and inspecting
Only way to clear that I've found is to save/reload
![image](https://user-images.githubusercontent.com/2357428/216556691-1c2aa739-adc1-43e5-af73-09744b265920.png)

**Comment by cymplecy** [comment]
Smallest example - seems to be the launch that provokes the issue
Also, clicking on the sprite isn't working for me - even after save and reload

![singlebug script pic](https://user-images.githubusercontent.com/2357428/216562451-92865c19-09f4-406b-a38a-4cdf877f6478.png)

**Comment by cymplecy** [comment]
And even after clear cache - close tab - open new tab on click isn't working

![image](https://user-images.githubusercontent.com/2357428/216568549-604f534c-1dbe-4013-b95c-a42da2e2014c.png)

**Comment by cymplecy** [comment]
And even after whole browser close and re-open on 8.1.1 on mouse click not working 

V7 still works

**Comment by cymplecy** [comment]
I changed the hat block to when I am pressed and that worked and then afterwards on click also works again

**Comment by jmoenig** [comment]
weird, but I can't reproduce with your exact scripts in Chrome on my Mac - it works as I would expect it to, including returning to the original colors and working again and again and again....

**Comment by cymplecy** [comment]
:(
This is my sequence to provoke it
![snap](https://user-images.githubusercontent.com/2357428/216650045-111e873d-244d-40a3-8bf6-0eada3fb6552.gif)

**Comment by cymplecy** [comment]
Lets wait until the documentation for the new debugging facilities comes out and see what happens on other peoples machines when they try it out

**Comment by jmoenig** [comment]
Thanks, @cymplecy . We were able to reproduce the issue that the hat block didn't trigger. Turns out I introduced that bug yesterday morning as I was fixing something else. We couldn't reproduce the coloring issue, which might be browser-cache related. In any case, I've released a patch (8.1.2) which - I hope! - fixes this. Could you do one of your quick tests, and let me know, if this is now resolved for you? Thanks for all your reports!

**Comment by cymplecy** [comment]
Fixed for me in 8.1.2 :)

**Comment by jmoenig** [comment]
thanks!

**Comment by 18001767679** [comment]
i also got a simillar problem 3 days before:if you hover onto something when visual stepping and then turn off stepping when still hovering then the highlight wont dissappear
