### ISSUE TITLE
Blockify uses empty slots instead of zero

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3180]
![image](https://user-images.githubusercontent.com/2138696/219102859-4c8fc5db-a664-4608-90c5-765d51ea9096.png)

**Comment by ToonTalk** [comment]
Right. I think my objection is aesthetic and pedagogic. Everyone understands a zero but not everyone reading a script knows that empty slots behave like zero.

**Comment by jmoenig** [comment]
fixed, thank you, Ken!
