### ISSUE TITLE
Hidden variables don't get exported with blocks

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [jmoenig/Snap#3186]
I was trying to use the new `__module__...` variable thing, and it worked, as long as the variable was shown. When I hid the variable, I could no longer export it with the blocks, even though it shows up in the export blocks dialog.

<img src="https://user-images.githubusercontent.com/70973578/220229910-19a2bd79-dac0-4ec4-a627-9c07a14c4eff.png" width="30%" ></img>
turns into that when imported into a new project
<img src="https://user-images.githubusercontent.com/70973578/220229992-ff52e152-e913-49f6-a15b-0cdedaaa14c1.png" width="30%"></img>

I did also make sure to disable all my userscripts, so that's not the issue.

**Comment by jmoenig** [comment]
Good catch, thank you!

**Comment by jmoenig** [comment]
forgot to call with the "include hidden" parameter, duh :)

fixed in dev, please give it a try: https://snap.berkeley.edu/versions/dev
tnx

**Comment by jmoenig** [comment]
yeah, I think this works now, it was the same function call. Thanks!

**Comment by ego-lay-atman-bay** [comment]
I just tested it out, and exporting the blocks from the export dialog exports the hidden variable, but when I tried exporting a script pic, the variable also got exported. I also tried doing a scripts pic, and that didn't export the variable.
