### ISSUE TITLE
Searching in stage results in error

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [jmoenig/Snap#3190]
@loucheman on the forums found an issue with searching blocks in the stage not working. I looked in the console and found this error
<img src="https://cdn.forum.snap.berkeley.edu/original/3X/0/3/0322145dbae5f3635416d690abfe6c073317c73c.png">

https://forum.snap.berkeley.edu/t/the-and-and-or-blocks-dont-show-up-in-search-anymore/13779/9

**Comment by jmoenig** [comment]
Thanks! investigating...
