### ISSUE TITLE
App warning dialog does not show up (if project was created by different app)

### ISSUE THREAD

**Issue by backface** [jmoenig/Snap#3191]
The warning (inform dialog) on loading a project that was created by a different app does not show up (For instance TurtleStich vs Snap). As far as I see, for now, the if condition/app check actually works, but the inform dialog (silently) does not show up:
 
https://github.com/jmoenig/Snap/blob/4ac4ab31da62fb0d46aaafd59510c9b928d9b190/src/store.js#L336

**Comment by jmoenig** [comment]
Thank you, Michael, great catch! Will fix asap.
