### ISSUE TITLE
Altering blocks in the palette does not update the scrollbar

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#32]
When a block is altered within the palette, e.g., when an input is added to a ring, the palette does not update its horizontal scrollbar.

![Screen Shot 2013-04-12 at 19 12 57](https://f.cloud.github.com/assets/1578238/375623/8e47d9d4-a3c6-11e2-8d64-a54cec872f7b.png)

**Comment by bromagosa** [comment]
Closing as we can resize the palette manually since many versions ago, and we're not expanding arrowheads on variadic blocks in the palette anymore.
