### ISSUE TITLE
sci snap error with the create costume block

### ISSUE THREAD

**Issue by sudo-000** [jmoenig/Snap#3219]
![image](https://github.com/jmoenig/Snap/assets/107282563/0d2ac9e0-280c-4b93-9a03-4dd218faf5de)
Please fix ASAP

**Comment by ego-lay-atman-bay** [comment]
You need to load the scisnap extension first.

**Comment by sudo-000** [comment]
just need to add this block at the start of my program and everything is solved!

**Comment by sudo-000** [comment]
Thanks for your help : )

**Comment by cymplecy** [comment]
I'd always recommend bringing up such an issue on the forum

Doing it here is best reserved once an issue is a proven and repeatable bug

And maybe don't say "fix it ASAP" next time :)
