### ISSUE TITLE
Tune scope midi file loading issue

### ISSUE THREAD

**Issue by sudo-000** [jmoenig/Snap#3220]
![image](https://github.com/jmoenig/Snap/assets/107282563/b70c4a77-1c57-4a45-9f2d-b62f1fa79eb3)
Why this doesn't work? Is it a bug of the tune scope extension?

**Comment by ego-lay-atman-bay** [comment]
This kind of thing goes on the forum, since it's a bug with the block code, nothing to do with the internals of snap.

**Comment by sudo-000** [comment]
This is a built-in extension, not my own. 
so...

**Comment by cymplecy** [comment]
As @ego-lay-atman-bay says, the forum is the place to start asking about possible bugs and issues.

**Comment by DarDoro** [comment]
It seems that Tunescope expects a format 0 MIDI file, and converts only first available track.
https://support.apple.com/pl-pl/guide/logicpro/lgcpdf6a3851/mac
`Format 0 files contain all data in one track.`
You should reference your MIDI file, so TS team can look at the issue.
Or convert your file to Format 0 and check results.

**Comment by sudo-000** [comment]
My midi is in format 1............................
Maybe add a format 1 support in the future? 
PLZ?
