### ISSUE TITLE
how can i revover my project when i used "split" saving by mistake?

### ISSUE THREAD

**Issue by n0name-o0o0** [jmoenig/Snap#3230]
![IMG_20230703_135515_882](https://github.com/jmoenig/Snap/assets/89623512/0e64088a-7e4a-43cb-b647-9df8ba365bee)
to make saving quicker ,i used this option,but next time i opened the save file,it went all bad
![IMG_20230703_135650_140~2](https://github.com/jmoenig/Snap/assets/89623512/02150b64-cb7b-44c6-8919-6dde6f814117)
After this,i tried import by"open" the "no-media" project and
![IMG_20230703_135831_829](https://github.com/jmoenig/Snap/assets/89623512/03056f74-46d5-47fb-8ec2-e73e422c67d5)
Clicked on 'yes' and then
![IMG_20230703_135836_931](https://github.com/jmoenig/Snap/assets/89623512/8997887e-cd38-46d6-9017-4b534568dd14)
what can i do to deal with it?

**Comment by jmoenig** [comment]
sorry, but you'll need to recover an earlier version that hasn't been split.
