### ISSUE TITLE
Old Projects Using Old Usage of the Ask Block Don't Function Properly

### ISSUE THREAD

**Issue by joecooldoo** [jmoenig/Snap#3232]
Ever since the ASK _ AND WAIT block was changed so that if you run it without providing an input it would stop any other ASK _ AND WAIT block, several projects break because some use a custom text engine to show the message and use a blank ask box, and others just use it as a "press enter to continue" kind of thing. But now that it has been changed to its current functionality a bunch of other projects now use the new feature as well.

**Comment by jmoenig** [comment]
yeah, well, I've been expecting some off-label use-cases to break when I changed the semantics.

**Comment by brianharvey** [comment]
I don't think it's fair to brush this use case off as "off-label."  Not saying you have to (or can!) do anything about it, but was there ever any documentation ruling out an empty question?  I could see it if there were a more primitive "wait for user input" that didn't take a prompt, and ASK AND WAIT were a special case of that, so we had an official correct way to wait for user input without prompting it.  As it is, wasn't this already an established use case in Scratch?

**Comment by joecooldoo** [comment]
I think a blank ASK block should only work if there is no currently running instance of ASK.

> PS: Nice icon!
Who, me? This is my original pfp from a few years ago.

**Comment by brianharvey** [comment]
> I think a blank ASK block should only work if there is no currently running instance of ASK.

Alternatively, use some other notation for stopping pending ASKs, such as
ASK (* stop all *) AND WAIT
But maybe it's too late for that?  In which case I endorse @joecooldoo's idea.

> Who, me?

No, Jens's steampunk hat! :)

**Comment by brianharvey** [comment]
@jmoenig This is another example of the small things I was talking about the other day.  I'm reopening this in the hope that it'll be fixed, preferably before people get used to the new current behavior.

**Comment by jmoenig** [comment]
Folks, please stop annoying me with this already. Snap changes, and this particular feature has been around for a year, and - contrary to some others - it has been communicated rather well. Remember when typing `print "hello world"` stopped working in Python? Right.

And the comment about "little things", Brian, is not fair in this context. ASK has taken a *huge* step forward with this menu behavior, and it is used by many, many projects (have you paid attention yesterday at the conference?). Yes, some very old projects that use ASK in - I repeat - an *off-label* way should be adjusted. I'm closing this for good.
