### ISSUE TITLE
where is run w/ continuation in 9.0.1?

### ISSUE THREAD

**Issue by JiafengLiao** [jmoenig/Snap#3237]
I didn't find the block 
![image](https://github.com/jmoenig/Snap/assets/15614871/3cda4857-9c94-4776-a7bd-e5c52ba2d4c0)

**Comment by jmoenig** [comment]
`call/cc` and `run/cc` have been deprecated in v9, they still work for existing projects, but for new ones we now have replaced them with true first-class continuations:

<img width="146" alt="this continuation" src="https://github.com/jmoenig/Snap/assets/2596285/db74bd7d-ce7e-40c5-aadf-c5e6f4ce9dcd">

You can use `this continuation` together with `call` and `run` pretty much exactly like you used to use `call/cc` and `run/cc`, here's an example for how to build the `catch/throw` control structure:

<img width="525" alt="catch throw" src="https://github.com/jmoenig/Snap/assets/2596285/53d615c2-8d73-49f0-be80-775f2389c5b2">

Does that make sense to you?

**Comment by JiafengLiao** [comment]
It make sense for sure. Thank you for the explanation! Great piece of art!

**Comment by JiafengLiao** [comment]
Is "join input list" deprecated as well btw?

**Comment by jmoenig** [comment]
`join` works the same as before, you can drop a reporter on the arrow heads:

<img width="260" alt="join_variadic" src="https://github.com/jmoenig/Snap/assets/2596285/5d258473-bdd1-4b53-a69b-109d5ba6d8a6">

and it will turn the `join` block into `join input list`:

![join_input_list](https://github.com/jmoenig/Snap/assets/2596285/b588a31e-e0ea-4fa3-be2b-f337f5d10218)

in v9 you can now tell whether a variadic input accepts reporter drops on the arrows for the variadic case if it displays the vertical ellipsis.

**Comment by JiafengLiao** [comment]
Thanks! It works! Will keep on digging

**Comment by jmoenig** [comment]
sure, and please don't hesitate to ask if there's anything that raises a question!
