### ISSUE TITLE
Report Block inside If Statement exits top level script

### ISSUE THREAD

**Issue by gustav-langer** [jmoenig/Snap#3252]
When a report block inside an if block is called, it will act almost like a [stop this script].
This works inside a custom command block and inside a ring executed by either call or run, but not in a custom reporter block.
![this works](https://github.com/jmoenig/Snap/assets/95526386/7240e656-72a3-4646-91ea-ba1ef0ddecbd) ![image](https://github.com/jmoenig/Snap/assets/95526386/e11b1255-c8e0-4211-8276-bd16a18b27f8)
![image](https://github.com/jmoenig/Snap/assets/95526386/3c5a2b58-e82c-4001-a6f5-9af80aa7b12a)
![image](https://github.com/jmoenig/Snap/assets/95526386/f6a2cba4-7f35-4bae-b483-ca9e8b019192)  

![image](https://github.com/jmoenig/Snap/assets/95526386/8b91268a-bab9-4384-a21a-9ce64c7b0c75) ![image](https://github.com/jmoenig/Snap/assets/95526386/f6923455-b8bb-4bb1-b2dd-354632050f81)

It also doesn't work in if-else blocks.
![image](https://github.com/jmoenig/Snap/assets/95526386/258aadf8-281f-4a9e-b633-40a1b5be6528) ![image](https://github.com/jmoenig/Snap/assets/95526386/16ea3985-e3b8-404d-ab0b-89334ca80dd5)

The bug will always stop the entire script.
![image](https://github.com/jmoenig/Snap/assets/95526386/49a1c959-ddf2-40de-b342-a7a10477e3ac) ![image](https://github.com/jmoenig/Snap/assets/95526386/dd93f923-48f1-432d-8416-39803e4be4f3) ![image](https://github.com/jmoenig/Snap/assets/95526386/7af5ab43-8c6f-4418-927b-f7ecffbec95f)

I tested it on versions 8.1.6 and 9.0.5 (because these happened to be the versions I had on my computer) and the bug only occurs in 9.0.5, so it's probably caused by the new variadic IF or the changes made for the THIS block to work.

**Comment by jmoenig** [comment]
thank you! I can reproduce and confirm this to be a bug. A quick investigation lets me agree with your assessment that this is likely caused by the recent changes to variadic conditional IF.

**Comment by jmoenig** [comment]
I've just patched Snap v9.0.6 with a fix for this, my own test cases - and the ones you reported - all seem to pass now. Can you please confirm? Again, thank you for this very attentive and thoughtful bug report!

**Comment by gustav-langer** [comment]
Seems to be fixed now. Thanks!
