### ISSUE TITLE
[Feature] discord embeds?

### ISSUE THREAD

**Issue by walksanatora** [jmoenig/Snap#3254]
was sharing a project in my APCSP class discord that i made in my spare time and there was no embed which made me sad

**Comment by ego-lay-atman-bay** [comment]
I'm pretty sure they're talking about just general social media previews, which includes the forum and discord. I agree, this would be great (and if I recall correctly, this has been suggested on the forum at some point before). The only things we need is the title and description of the project (and maybe also the thumbnail).

**Comment by cycomachead** [comment]
This would be great to have, I agree. It belongs as an issue in snap-cloud/snapCloud (not Snap! itself), but someday it will happen...
