### ISSUE TITLE
relabel  the block ,langues will change

### ISSUE THREAD

**Issue by moodykeke** [jmoenig/Snap#3263]
When in a non-default language (English) environment, choosing to relabel or switch the block status will change the language back to the default (English).
![bug](https://github.com/jmoenig/Snap/assets/32347947/bf4cec40-cb32-4d07-b75d-c6a881bfb331)

**Comment by moodykeke** [comment]
v9.0.8

**Comment by jmoenig** [comment]
Good catch, thanks!
