### ISSUE TITLE
List/Table View menu option on reporters should be switched

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3265]
Hi! I think the list vs. table view options in the drop-down menu on reporter bubbles should be switched. When you are viewing a table, it should offer list view, and when you are viewing a list, it should offer table view. Right? Thanks!

![Screen Shot 2023-10-31 at 2 07 28 PM](https://github.com/jmoenig/Snap/assets/6549787/7059ad94-f66e-41dd-aa6a-619c410d5bb7)
![Screen Shot 2023-10-31 at 2 06 52 PM](https://github.com/jmoenig/Snap/assets/6549787/783179ca-6761-4e50-93a7-d2da3802b03d)

**Comment by ego-lay-atman-bay** [comment]
> When you are viewing a table, it should offer list view, and when you are viewing a list, it should offer table view. Right?
That's what it does...? I'm confused as to what you're asking for.
