### ISSUE TITLE
Menu items to arrange custom blocks.

### ISSUE THREAD

**Issue by Simon-Mong** [jmoenig/Snap#3266]
![image](https://github.com/jmoenig/Snap/assets/30740101/65c55f43-39c5-4185-84f6-8659d344093b)
HI, my dear friends. The custom block cagegories are really cool. But when I devided my blocks into different categories I found I need two menu items "move up" and  "move down" to arrange the blocks. I added them and they do help. Do you think it is necessary to add them in here?

**Comment by jmoenig** [comment]
This is beautiful, Simon! For v10 I'm working on letting users fully customize the palette, even letting you mix primitives and custom blocks and arrange them freely. But in the meantime your "move up/down" menu items are wonderful! If you would like to send me PR I'd love to have a look and perhaps even integrate it into the next patch / minor update. Thanks!

**Comment by Simon-Mong** [comment]
CustomCommandBlockMorph.prototype.goUp = function () {
    var idx, stage, ide, method, cat, temp, t_idx, 
        rcvr = this.scriptTarget();
    if (this.isPrototype) {
        return null; // under construction...
    }
    method = this.isGlobal? this.definition
            : rcvr.getLocalMethod(this.blockSpec);
    if (method.isGlobal) {
        stage = rcvr.parentThatIsA(StageMorph);
        idx = stage.globalBlocks.indexOf(method);
        if (idx > 0) {
			cat = stage.globalBlocks[idx].category;
            for( t_idx = idx - 1; t_idx > -1; t_idx-- ) {
				if ( stage.globalBlocks[t_idx].category == cat ) {
					break;
				}
			};
            if (t_idx > -1) {		
			    temp = stage.globalBlocks[t_idx];
                stage.globalBlocks[t_idx] = stage.globalBlocks[idx];
			    stage.globalBlocks[idx] = temp;
			}
        }
    } else {
        idx = rcvr.customBlocks.indexOf(method);
        if (idx > 0) {
			cat = stage.customBlocks[idx].category;
            for( t_idx = idx - 1; t_idx > -1; t_idx-- ) {
				if ( stage.customBlocks[t_idx].category == cat ) {
					break;
				}
			};
            if (t_idx > -1) {		
			    temp = stage.customBlocks[t_idx];
                stage.customBlocks[t_idx] = stage.customBlocks[idx];
			    stage.customBlocks[idx] = temp;
			}
        }
	}
    ide = rcvr.parentThatIsA(IDE_Morph);
    if (ide) {
        ide.flushPaletteCache();
        ide.categories.refreshEmpty();
        ide.refreshPalette();
    }    
};

CustomCommandBlockMorph.prototype.goDown = function () {
    var idx, stage, ide, method, cat, temp, t_idx, 
        rcvr = this.scriptTarget();
    if (this.isPrototype) {
        return null; // under construction...
    }
    method = this.isGlobal? this.definition
            : rcvr.getLocalMethod(this.blockSpec);
    if (method.isGlobal) {
        stage = rcvr.parentThatIsA(StageMorph);
        idx = stage.globalBlocks.indexOf(method);
        if (idx > 0) {
			cat = stage.globalBlocks[idx].category;
            for( t_idx = idx + 1; t_idx < stage.globalBlocks.length; t_idx++ ) {
				if ( stage.globalBlocks[t_idx].category == cat ) {
					break;
				}
			};
            if (t_idx < stage.globalBlocks.length) {		
			    temp = stage.globalBlocks[t_idx];
                stage.globalBlocks[t_idx] = stage.globalBlocks[idx];
			    stage.globalBlocks[idx] = temp;
			}
        }
    } else {
        idx = rcvr.customBlocks.indexOf(method);
        if (idx > 0) {
			cat = stage.customBlocks[idx].category;
            for( t_idx = idx + 1; t_idx < stage.customBlocks.length; t_idx++ ) {
				if ( stage.customBlocks[t_idx].category == cat ) {
					break;
				}
			};
            if (t_idx < stage.customBlocks.length) {		
			    temp = stage.customBlocks[t_idx];
                stage.customBlocks[t_idx] = stage.customBlocks[idx];
			    stage.customBlocks[idx] = temp;
			}
        }
	}
    ide = rcvr.parentThatIsA(IDE_Morph);
    if (ide) {
        ide.flushPaletteCache();
        ide.categories.refreshEmpty();
        ide.refreshPalette();
    }    
};

Hi Jens. v10 sounds exciting. These two functions works well for my custom blocks. I will try more libraries to see if there would be exceptions.

**Comment by jmoenig** [comment]
Thanks, @Simon-Mong ! I have slightly reformulated your code - but kept the algorithm you suggest - and integrated this feature into my dev branch: https://github.com/jmoenig/Snap/commit/6f1487d747765b954cfd0cb86f66ba8768547cd0
I'm closing this issue now. For the final v10 I'm planning to add even more ways for users to arrange, cluster and mix blocks in their projects' palettes, so it's very likely that this code is going to - even drastically - change along the way. But for now it's nice that we have this capability in dev. Thank you!

Oh, and yesterday i've also made it so that if you import a block or script into a project that already has a custom block version of, the existing definition gets overwritten (this has always been the case) but the *order* of custom blocks (their position in the palette) stays the same.

Again thank you!
