### ISSUE TITLE
Javascript Function Block seemingly can't access `List()` function! 

### ISSUE THREAD

**Issue by ErrorBot1122** [jmoenig/Snap#3268]
I'm trying to make a simple list sorting `JS function` (bc Snap doesn't have one) and realized that I needed to convert my `JS Array` Back into a `Snap List` after sorting OR it will just return the stringified version of the list! Went back into the source code and found a function called `List()` to convert it back into a Snap list BUT when I tried to use it returned **nothing**!
<br/>

![NO SORT](https://github.com/jmoenig/Snap/assets/65428515/4f3b2b81-568d-463b-b28a-d1a99cc5f545)
<br/>

Am I just tripping here or is there no access to the functions in the `JS Blocks`?

**Comment by ego-lay-atman-bay** [comment]
There is a snap block for sorting in the list utilities library.

Also, you have to di `new List(["list"])`

**Comment by cycomachead** [comment]
The `new` is what's missing here. Lego batman is right.

As for the sort block itself. 
The goal has always been to keep the default set of blocks fairly constrained....though they've grown a lot recently. 
However, there is a sort block in the "List Utilities" library.
