### ISSUE TITLE
Colors: We need "set pen saturation to (num)"

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#327]
How can I programmatically choose "pink" (red+white) or "grey"?
I'm playing with 'set pen color to (num)' and 'set pen shade to (num)' and without a 'set pen saturation to (num)', I can't programmatically get a shade of grey or white or pink.  It is the case that I can select some of those colors with 'set pen color to (color-picker)' since it shows the fully-saturated slice of the outside of the HLS color space (allowing me to get 'white' and 'pink' but not 'grey')

**Comment by bromagosa** [comment]
Fixed in dev now:

![imatge](https://user-images.githubusercontent.com/1016697/51082968-939e0380-1711-11e9-91b1-927804ef7019.png)
