### ISSUE TITLE
Service worker, wrong URI to resources

### ISSUE THREAD

**Issue by DarDoro** [jmoenig/Snap#3270]
The service worker "sw.js" fails to cache some resources and sometimes breaks the update of the Snap! version.

`"Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed`

Misspelled or wrong URI

_libraries/word-sentence.xml => libraries/word_sentence.xml
libraries/variadic-reporters.xml = >_

**Comment by jmoenig** [comment]
Thank you, Dariusz, good catch!
