### ISSUE TITLE
[Bug]: LIBRARIES file is looking for wrong Words, sentences library file

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [jmoenig/Snap#3273]
https://forum.snap.berkeley.edu/t/words-sentences-library-won-t-load/15459

I looked at the LIBRARIES file, and it's looking for ` word-sentence.xml`, but the file is actually named `word_sentence.xml`

**Comment by brianharvey** [comment]
On it!

**Comment by jmoenig** [comment]
yes, @DarDoro has been notifying us about this, thanks

**Comment by jmoenig** [comment]
fixed with https://github.com/jmoenig/Snap/commit/c3e8e30ce93e4c32c1d120517bc5102df2ab269f
