### ISSUE TITLE
Cannot use tell block to call a private method defined in another sprite

### ISSUE THREAD

**Issue by sudo-000** [jmoenig/Snap#3282]
![image](https://github.com/jmoenig/Snap/assets/107282563/f10232cc-3960-469c-a678-5ff85fd76c8a)

I have multiple clones of the same sprite, each has their own private Set Value block that doesn't bother other sprites. 
I want to run the Set Value block in each of them by Tell... but snap don't wanna let me do it.

**Comment by jmoenig** [comment]
That's a feature, because global custom blocks are available to every sprite.
