### ISSUE TITLE
may you please have Snap! not compile broken functions

### ISSUE THREAD

**Issue by Askofep-1** [jmoenig/Snap#3292]
[sus.xml.zip](https://github.com/jmoenig/Snap/files/13932612/sus.xml.zip)
this file only contains an xml file
open in snap and you will get an error

**Comment by jmoenig** [comment]
Please don't spam this repo with blurbs on unused or experimental features

**Comment by Askofep-1** [comment]
open please

**Comment by Askofep-1** [comment]
please unclose this
