### ISSUE TITLE
Video breaks if you resize the stage after clicking the video reporter block.

### ISSUE THREAD

**Issue by samankittani** [jmoenig/Snap#3296]
If you click on the `video` block, video begins to show behind the stage. Then, if you resize the stage, the video breaks and the `get motion from _________` returns an error. It is fixed if you use the stop all block and reinitialize the video by clicking the `video` reporter block. I included screenshots for reference and recreation.

![Screenshot from 2024-01-16 14-34-37](https://github.com/jmoenig/Snap/assets/87401990/f3093242-84f9-466d-b4d1-a12e6eb31fb8)
![Screenshot from 2024-01-16 14-35-06](https://github.com/jmoenig/Snap/assets/87401990/c0251375-218b-4177-b176-c2d23ddb84d9)
![Screenshot from 2024-01-16 14-35-24](https://github.com/jmoenig/Snap/assets/87401990/bcfc35b1-ff81-407b-9be7-c0e0c5290c98)
![Screenshot from 2024-01-16 14-35-35](https://github.com/jmoenig/Snap/assets/87401990/ceca2b14-d1c1-49cb-a39b-90d378388746)
![Screenshot from 2024-01-16 14-35-44](https://github.com/jmoenig/Snap/assets/87401990/041a7ac8-6766-4fdf-9bb4-12b3c9328da4)
![Screenshot from 2024-01-16 14-35-55](https://github.com/jmoenig/Snap/assets/87401990/476befca-1d52-4d02-8a97-72d96eeebe3d)
![Screenshot from 2024-01-16 14-36-01](https://github.com/jmoenig/Snap/assets/87401990/85b3996e-868e-4623-8d88-64a7e120808f)
![Screenshot from 2024-01-16 14-36-17](https://github.com/jmoenig/Snap/assets/87401990/97fc9817-d2b4-4f72-bfbf-e364ca3842dd)
![Screenshot from 2024-01-16 14-36-24](https://github.com/jmoenig/Snap/assets/87401990/85d34723-5f3c-4a87-b540-49ff50c0b193)

**Comment by jmoenig** [comment]
Thanks! Huh, things I never thought if trying 😁 .
Probably we should stop the video before applying different stage dimensions, what do you think?

**Comment by samankittani** [comment]
Works!, Thanks:)
