### ISSUE TITLE
When running snap from local filesystem, keyboard input does not work

### ISSUE THREAD

**Issue by pnkfelix** [jmoenig/Snap#3311]
I'm on a Mac

I saved the Snap!%209.2.6.html that you get after doing "Run Snap" on the website locally to my desktop.

Then I loaded it later, and most things worked, except every time I wanted to interact with anything that took keyboard input, it failed to register my keyboard presses.

This included numeric input boxes on the "move (10) steps" block, and also the "Export Project As ..." dialog box.

I have seen this on Safari, Firefox, and Chrome.

----

I do note that when I git clone the repo and load the index.html from there into the same browser, the keyboard input works. Not quite sure yet what difference there might be here.

**Comment by cymplecy** [comment]
"I saved the Snap!%209.2.6.html that you get after doing "Run Snap" on the website locally to my desktop."
That's not a valid method of downloading Snap! to run locally (as you've found out)

**Comment by pnkfelix** [comment]
Ah, you are right; I had misremembered the contents of https://snap.berkeley.edu/offline

**Comment by pnkfelix** [comment]
(it is sort of unfortunate how many things *do work* when you download Snap in the manner I described... I had "tested" my method, and since I saw some basic interactions working (dragging a sprite, dragging a move block, clicking the move block and seeing the sprite move), I assumed that I had something that was working...)
