### ISSUE TITLE
Rejoining colour picker is failing

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3322]
Encounted a problem when running my old Snap! to OpenSCAD project and eventually traced it down to this
Split seems to work fine
![untitled script pic - 2024-03-01T134926 077](https://github.com/jmoenig/Snap/assets/2357428/a509ad27-0905-4e8f-b503-9cc90284250c)
But when re-joined - colour isn't original one

![untitled script pic - 2024-03-01T134931 694](https://github.com/jmoenig/Snap/assets/2357428/36f21be4-f35e-4567-8692-79ada03567c4)

as shown below
![untitled script pic - 2024-03-01T134937 895](https://github.com/jmoenig/Snap/assets/2357428/95789961-e2e9-4b59-9f3b-b25f07e7f8ca)

Issue doesn't occur if I do the same using V8 https://snap.berkeley.edu/versions/v8/snap.html
![untitled script pic - 2024-03-01T135457 453](https://github.com/jmoenig/Snap/assets/2357428/faaad816-907c-47ad-b92c-43433475291e)

**Comment by cymplecy** [comment]
If I've used git bisect correctly :) then it points me to this commit as the first time it changes behaviour
https://github.com/jmoenig/Snap/commit/59ff5d6621403c207cfb0197db31327cbc2d6ef0

**Comment by jmoenig** [comment]
thank you, Simon! This should be fixed now.
