### ISSUE TITLE
Request:Large Project Optimisation

### ISSUE THREAD

**Issue by n0name-o0o0** [jmoenig/Snap#3333]
hi, developer of Snap!
is it that the problem:
I tried to open and edit my project which have a large audio file,total is about **5M**.. I edited and saved,and then next time I open it,the browser crushed
maybe one of therereseon is computer's super low Ram but...
I opened a **30x larger** project in Scratch3 Turbowap and PenguinMod it **doesn't** happen.

my suggestions:

1. give a way to load audio media files later using a URL(load audio via URL)

2. change a better format of project file

please it will really help
love u devteam <3

**Comment by n0name-o0o0** [comment]
@jmoenig so added what?

**Comment by jmoenig** [comment]
not going to happen, that's what. You can make large projects and import all your songs and photos, but then you need to save them locally on your computer, not in the free Snap cloud. If something "crashes" (or "crushed", or whatever you try to express) that's an issue on your computer. I have many extremely large projects locally on mine that work and load fine.
