### ISSUE TITLE
Custom blocks with % causes issues

### ISSUE THREAD

**Issue by bruh-9000** [jmoenig/Snap#3339]
- When creating a custom block, if you enter in something such as "%15" as the block, it will convert it to 15 and an input. My best guess is that this is because of how Blockly works with inputs, and this might be a feature but I'm not sure.
- If you rename an input to start with %, it will end up removing the % from the input name and causing issues, when you reopen the block it will remove the %
- If you edit a label to start with %, it will convert to an input

**Comment by cymplecy** [comment]
You are much better bringing up issues like this on the Snap! forum
https://forum.snap.berkeley.edu

Best to keep this issue tracker clear for severe issues requiring urgent action

But even then, try and raise them on the forum first :)

**Comment by ego-lay-atman-bay** [comment]
One thing to note, this has absolutely nothing to do with blockly, as snap does not use blockly, that's scratch.

**Comment by jmoenig** [comment]
This is a longstanding known issue, the percent notation goes back to BYOB and predates the current GUI. Closing...
