### ISSUE TITLE
Copying Reporter Output

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3370]
Hi all! Could we please add a feature for copying the output of a reporter? For example, you could right-click the block and one of the menu options could be "Copy output".

We're leading a teacher PD in Cleveland this week, we are working on [BJC Sparks 1.2](http://localhost/bjc-r/sparks/student-pages/U1/L2/01-super-short-story-builder.html?topic=sparks%2F1-functions-data.topic&course=sparks.html) with a number of primary school teachers (and other non-CS teachers), and some teachers wanted to be able to copy the output of their "super short story" and use it elsewhere. For example, teachers might have students building a sentence for as a paragraph starter in Snap and then pasting that into Word to elaborate the story as part of a writing lesson.

I imagine this has been debated and there is a reason we don't have this feature (in fact, I think I may have even requested it myself in the past), but I want to make the case again. Being able to access the output of a block (whether text, image, sound, CSV, etc.) is a natural instinct, and it helps non-CS teachers integrate CS experiences into their existing lessons.

Could we please revisit the issue of having copyable block output? I'm happy to brainstorm solutions if there is an implementation barrier (eg, there could be a pop-up for something like "you can't copy CSV output" if some outputs won't work). Thanks!

**Comment by ego-lay-atman-bay** [comment]
This was actually already added in v10.
![markup_1000429962](https://github.com/jmoenig/Snap/assets/70973578/64d6ccb2-ea89-4a57-92b1-bb6c6c3867c7)

**Comment by maryfries** [comment]
YAY!!! I just told them. We are all excited!! Thanks!
