### ISSUE TITLE
Add the ability to change octaves in the piano keyboard

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [jmoenig/Snap#3378]
It would be really great to be able to change octaves in the piano keyboard. It would make choosing a note even easier (because currently you have to type in the number for the note in a different octave).

![image](https://github.com/user-attachments/assets/b038d885-50ec-4407-af23-7d2fb0869547)
![image](https://github.com/user-attachments/assets/9b0b5009-a0c4-4492-9f13-82ae67450274)

I have already modified the piano keyboard in [my fork](https://ego-lay-atman-bay.github.io/Snap/snap.html) to add this (that's how I got the screenshots), which I find helpful. I'm not creating a pull request yet, because Snap 10 is currently in the release candidate stage, and I think that it would be better to discuss it first.

Here's my piano keyboard modification if you want to take a look at it.
https://github.com/ego-lay-atman-bay/Snap/tree/piano-keyboard-octaves

**Comment by jmoenig** [comment]
very nice!
Can you make it so that it always shows 2 octaves instead of only one?

**Comment by ego-lay-atman-bay** [comment]
I'll see what I can do.

**Comment by ego-lay-atman-bay** [comment]
Adding the second octave wasn't nearly as hard as I thought it would be (due to how I coded it). However, there is still a small difference, there is no third C key on the far right (but I personally think the keyboard looks better without it).
![image](https://github.com/user-attachments/assets/a85aa6e5-572f-4a4a-8d50-515b17991a39)
![image](https://github.com/user-attachments/assets/c4d16db1-070d-4273-9df6-b1d6d4ed8e79)

**Comment by ego-lay-atman-bay** [comment]
Do you want me to create a pull request?

**Comment by jmoenig** [comment]
this is all very nice, thank you!
Yes, please create a pull request into the master branch. I'll try to get it into v10!
(it would be even the most awesome thing if you could include the 3rd C key on the far right, but if that's too difficult, don't worry about it)

**Comment by ego-lay-atman-bay** [comment]
Alright, I added the third C key, which wasn't hard at all.
![image](https://github.com/user-attachments/assets/a376ba87-5173-4b18-9aab-4122dda7cb23)

I also submitted a pull request: https://github.com/jmoenig/Snap/pull/3380
