### ISSUE TITLE
Reporter and Predicate Custom Blocks have no Min Width

### ISSUE THREAD

**Issue by dragazo** [jmoenig/Snap#3385]
It looks like when rendering custom blocks, commands have a sensible minimum width, but reporters and predicates do not, which can lead to very weird-looking blocks. This is tested in the latest Snap! release (10.0.0) by creating a custom block with no text parts but a single C-ring input parameter.

Commands look ok:
![untitled script pic](https://github.com/user-attachments/assets/8fe7d618-ba47-4d1a-a511-279f9fc66cea)
![untitled script pic (5)](https://github.com/user-attachments/assets/5825a325-de40-4772-bc66-702b8c121398)

Reporters do not: 
![untitled script pic (1)](https://github.com/user-attachments/assets/1f18ee3f-b37f-4085-b872-b8f769fe2d5b)
![untitled script pic (4)](https://github.com/user-attachments/assets/31247903-a2ed-438b-80e6-fc9209fca382)

Predicates are probably the worst offender:
![untitled script pic (2)](https://github.com/user-attachments/assets/a8a08154-f5e2-400b-8469-027457e1720c)
![untitled script pic (3)](https://github.com/user-attachments/assets/460bf526-3ee5-423d-88e0-23a29b47adb1)

When text is added, the added width corrects the issue. But even without text there should probably be some minimum width that at least allows for the puzzle piece wedges of C-ring inputs to be rendered correctly.

**Comment by jmoenig** [comment]
Reporters and predicates do, in fact, have a minimum width, and it is observed when they are rendered. C-slots, however, override certain layout rules, assuming that there will also be label text. Unlabelled blocks are not a supported modality, what do you need them for, if not your own programming language?

**Comment by dragazo** [comment]
I don't have an intended use case for these blocks, but we should still be able to render them well. Since this isn't an issue for commands blocks specifically, the code for doing this correctly must already exist somewhere and just isn't being applied to reporters/predicates.

**Comment by brianharvey** [comment]
I have no concern with the width in these pictures, but imho the _height_ of the predicate block's C-slot is inadequate; the TURN blocks seem just to be sitting next to the predicate block, rather than attached.  But I agree that this isn't a high priority.
