### ISSUE TITLE
Command blocks occasionally reporting

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3387]
PD observation: Command blocks are occasionally reporting (10.0.0). I've seen that once earlier this month (July), but we caught it on [video](https://berkeley.zoom.us/rec/share/SVM7p10PNkK8M89FjgefoXSI34tYoTn1g_597uGr4PlfOwuqz_EnfcKHzzmUlLxN.p62GInGrO1khHZne?startTime=1721833207000) (Password: X?P^!m3b) during the PD (around 00:55:00).

**Comment by maryfries** [comment]
I've seen it happen in other projects, but [here](https://snap.berkeley.edu/snap/snap.html#present:Username=hclarkson&ProjectName=BJCMS%20-%20Song%20Mystery%20hc) is the project at that point in the video.

**Comment by brianharvey** [comment]
Always sound blocks?

**Comment by ego-lay-atman-bay** [comment]
No, it's just visual stepping reporting the value of an input in a custom block that is being used.
![image](https://github.com/user-attachments/assets/c8238538-489b-4584-b3f9-0f9f3df9f5a3)

![image](https://github.com/user-attachments/assets/4acb20b9-09e5-4578-b43d-a79fc9e041b1)

![image](https://github.com/user-attachments/assets/dd9f22bd-1bfa-4c40-85c6-3d9fa3ebcb5b)

![image](https://github.com/user-attachments/assets/b18da593-7d13-48b7-8e9a-5a68793d7dbb)

**Comment by maryfries** [comment]
Interesting. I'll let you know if I run into it without visible stepping on.

**Comment by jmoenig** [comment]
@ego-lay-atman-bay is right about this. In visible stepping mode all evaluations of input slots inside a script which the user directly clicked to run are displayed as little result balloons. This behavior has been contributed by @jedi-force last year for v9 for better stepping-debugging purposes, and overall we've been getting enthusiastic reports about it.
