### ISSUE TITLE
Arrays bereak Snap!

### ISSUE THREAD

**Issue by YeesterPlus** [jmoenig/Snap#3390]
try reporting an Array object with no elements

**Comment by ego-lay-atman-bay** [comment]
Like this?
![untitled script pic (22)](https://github.com/user-attachments/assets/e1c543cb-0cce-4630-9785-9e218692c400)

**Comment by YeesterPlus** [comment]
Javascript arrays break them

**Comment by ego-lay-atman-bay** [comment]
> Javascript arrays break them

Snap uses a custom list object, which can be made with `new List([elements])`. I think maybe you just think that they're broken, when in reality, snap just doesn't use javascript arrays by themselves.
