### ISSUE TITLE
If I create a variable this happen

### ISSUE THREAD

**Issue by GamerCreeperNoob** [jmoenig/Snap#3405]
![IMG_0702](https://github.com/user-attachments/assets/a42e0f61-1fff-40e0-b893-a4fe24f48f90)

**Comment by jmoenig** [comment]
Gosh, you're right! Thank you, will have to fix tonight

**Comment by RayTheNoob** [comment]
Checking `Extension Blocks` in the settings menu also seems to cause this.

![extensionblocks](https://github.com/user-attachments/assets/9fd937e0-7dd8-424e-bfe4-4e03721b22e0)

![extensionblock2](https://github.com/user-attachments/assets/bb05b25a-49c1-47a5-9112-608e032893bd)

**Comment by ego-lay-atman-bay** [comment]
Same with javascript extensions

**Comment by jmoenig** [comment]
fixed in v10.4.4, thanks!
