### ISSUE TITLE
Can't send green flag to scene (from forum)

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3407]
![error](https://github.com/user-attachments/assets/bca7958e-bc50-495d-8a22-0acb5754d0ff)

**Comment by jmoenig** [comment]
Ah, yes, indeed! This is coming from the changed result format of input groups (reporting a table instead of a flat list). Perhaps that wasn't such a good idea after all^^. This is probably going to pop up in other blocks as well, will fix, thank you!

**Comment by jmoenig** [comment]
fixed in v10.1.5
