### ISSUE TITLE
Why is version 10.1.9 back?

### ISSUE THREAD

**Issue by GamerCreeperNoob** [jmoenig/Snap#3415]
I opened snap! And version 10.1.9 is back?!?!?!

**Comment by GamerCreeperNoob** [comment]
I forget to say: before the version was 10.2.0

**Comment by cymplecy** [comment]
See https://forum.snap.berkeley.edu/t/snapblocks-part-2/16544/133

**Comment by GamerCreeperNoob** [comment]
10.2.1 is here!
