### ISSUE TITLE
Update lang-zh_CN.js

### ISSUE THREAD

**Issue by moodykeke** [jmoenig/Snap#3421]
[lang-zh_CN.zip](https://github.com/user-attachments/files/18051511/lang-zh_CN.zip)
Fixed partial translations to add translations for imported libraries.
Thanks!
说明：
修正部分翻译，增加导入库的翻译。

**Comment by jmoenig** [comment]
thank you! Is this different from your pull-request https://github.com/jmoenig/Snap/pull/3422 ?

**Comment by moodykeke** [comment]
It is no different from pull-request #3422. During the pull process, the network is always unresponsive, so another copy is sent. It was later found that the network was restored.
Thanks!

**Comment by jmoenig** [comment]
got it, thank you!
