### ISSUE TITLE
Read-Only is missing for boolean slots

### ISSUE THREAD

**Issue by GamerCreeperNoob** [jmoenig/Snap#3426]
Read-only is missing in boolean slots

**Comment by ego-lay-atman-bay** [comment]
No, they're not, because there's no such thing as a readonly boolean input. The closest thing is static boolean inputs.

**Comment by GamerCreeperNoob** [comment]
But the

**Comment by GamerCreeperNoob** [comment]
Oops. But the true or false boolean block, slot 1 is read-only!

**Comment by ego-lay-atman-bay** [comment]
It's actually static

**Comment by GamerCreeperNoob** [comment]
Sorry.

**Comment by GamerCreeperNoob** [comment]
Ok, I test it, you are right! Sorry for issue!
