### ISSUE TITLE
Encoding error for french

### ISSUE THREAD

**Issue by gaetanc** [jmoenig/Snap#345]
When we use accent and we save the project all the accent are wrongly encoded. It result by barbarian caracters instead of accent.

An example "scène" is encoded like that 
![image](https://f.cloud.github.com/assets/2857661/2372017/2e6bc41c-a834-11e3-9c76-c46f506e20e7.png)

It happen in any place where we can have text. 

I don't know where can be the problem. Have you some idea about the location of this problem?

**Comment by jmoenig** [comment]
I've just again tried this with the new backend and cannot reproduce it any longer. Looks like our new backend fixed this, yay, @bromagosa and @cycomachead !
