### ISSUE TITLE
Download Snap Source link

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#347]
Depending on what we do (re #346) we could change the zip file URL to point to the most recent version on github. All we need to do is use this:
`https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/archive/master.zip`
It will always be updated. :)

**Comment by hotsphink** [comment]
Sorry for the +1 comment, but I just started looking at snap and quickly found the "Download Source" link in the UI, which was good, but then it unpacked a bunch of OSX-specific junk files, which made it look pretty half-baked. My immediate thought was "why isn't this on github or somewhere?" It took me some time to discover that it *is* on github. Cloning the github repo makes far more sense for my usage than downloading a zip file snapshot. From the point of view of a potential contributor, the current setup feels a little sketchy. I would recommend at the least getting rid of the osx droppings and making README.md and/or readme.txt point to the github page.

**Comment by cycomachead** [comment]
Closing since this now points to the latest GitHub release.

**Comment by brianharvey** [comment]
The repo has a .gitignore that includes .DS_Store; what is the "OSX-specific junk" in the repo?

**Comment by marwahaha** [comment]
I'd guess that removing `.DS_Store` from the `.gitignore` would increase the chance of someone checking-in "OSX-specific junk"....

**Comment by jmoenig** [comment]
I think he was talking not about the github repo but about the zip file we used to have. When you make a zip file on a Mac it does not play well on Windows computers, and often creates some folders and files that look like OSX junk when you unpack it. I think it was just that and that @hotsphink was probably even right about it...
