### ISSUE TITLE
for loop did unexpected thing (based on other languages), counts down. Can we re-introduce for i = START to END by STEP

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#389]
I guess I should have remembered that for counts down, but I didn't, and it caused some trouble recently.  I was trying to write "index of (last occurring) <predicate> in <list>" which set the index to 0, then iterated:
for i = 1 to (length-of(list))
  if (call predicate on (item (i) of list))
    set index to i
return index

thinking, naively, that when the list is empty, the for loop wouldn't execute (ala every other language we know of), but got caught that the predicate executes TWICE (i = 1, then i = 0).  

So as much as I like the "smart for", it causes problems for people who know what they're doing. I'd much rather have (as an addition) the for that has the explicit STEP. And yes, I could build it myself, but it would be nice if it loaded with TOOLS.

dan

**Comment by bromagosa** [comment]
> @brianharvey You can close those.

Can we close this, then?

**Comment by brianharvey** [comment]
Ah, see, @jmoenig, I'm not the only one wanting UP TO.

@bromagosa, when Jens reads this comment, then _he_ can close it. :)

**Comment by jmoenig** [comment]
I will :-) Thanks!

**Comment by jmoenig** [comment]
You really want *FOR pro* with three unevaluated inputs:

<img width="426" alt="FOR pro" src="https://user-images.githubusercontent.com/2596285/59148014-f8c8fd00-8a02-11e9-96e5-877153e3d702.png">

**Comment by brianharvey** [comment]
If you're going to do that, you want the START input to be type Any, not type Number!

**Comment by cycomachead** [comment]
Why? Start only gets evaluated once - so there’s not really a need for it to be unevaluated. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I didn't say "Any (unevaluated)," just "Any."

FOR I = (a) TO <I = (z)> STEP [I = (UNICODE ((UNICODE OF (I))+1) AS LETTER)]

I'm sure there are more interesting examples too.

**Comment by cycomachead** [comment]
Ah, I guess so -- that seems interesting, but personally FOR EACH with a stream sounds much more clear/easier to understand what's being returned.
