### ISSUE TITLE
Some instances of custom blocks show help tooltip

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#39]
When a custom block with a help comment is dragged out of the palette, hovering over the block instance shows the help tooltip where the block prototype is in the palette.

![Screen Shot 2013-04-13 at 09 50 47](https://f.cloud.github.com/assets/1578238/376573/2c3bf95c-a441-11e2-95a2-1884df3eaa2f.png)

**Comment by bromagosa** [comment]
This was fixed long ago, it seems. We're not showing these speech bubbles anymore now.
