### ISSUE TITLE
Is saving to localStorage obsolete?

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#435]
@brianharvey wrote:

> I'd be interested in discussion about whether the "localstore" option (using overgrown cookies) is obsolete now that cloud storage works and we have export as a fallback.

I think it is, but I think we should develop some mechanism for autosaving cloud projects locally (using the FileSystem API, if it's available, and falling back onto localStorage).

**Comment by cycomachead** [comment]
Closing this, as a result of many other discussions.

Local storage has a problem that on some school computers, programs like DeepFreeze may "reset" browser settings and data often which cause students to lose work. These programs, do not erase normal user files, so when offline use is needed, exporting is a better scenario. 

In the intervening 4 years, we still have no direct access to the file system, but exporting a file has improved a lot. 

So we are going to let users move their projects from local storage to their local machines or to the cloud, then remove the feature entirely.
