### ISSUE TITLE
De-duplicate URL Anchors (#open / #cloud)

### ISSUE THREAD

**Issue by nathan** [jmoenig/Snap#45]
#open: should support the Username=<em>username</em>&ProjectName=<em>project name</em> format, so users can link to their projects in editing mode rather than presentation mode.

**Comment by cycomachead** [comment]
there's `#cloud` now, but all the URL anchors need refactoring.

**Comment by bromagosa** [comment]
Was this issue about supporting linking a project in edit mode? Because we've had this for years now (`&editMode` flag).

If so, this can be closed.

**Comment by jmoenig** [comment]
Yeah, I think we can closer this now. Thanks!

**Comment by cycomachead** [comment]
No, this was about having multiple URL anchors that do the same action - but I don’t know if we can easily just remove them. I think open and cloud are still synonymous actions.  

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by bromagosa** [comment]
Oh, right. We can't remove them because people have been using them for a long time now. So it can be closed anyway :)
