### ISSUE TITLE
Dragged blocks from palette are stacked on original blocks in palette if you follow specific steps

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#456]
![stackedblock](https://cloud.githubusercontent.com/assets/7092949/3098954/f9c3e840-e5f3-11e3-822d-cd8b05b853f2.png)

This works with for example "say", "think" or any "loop" block too...

<b>edit:</b> I changed title from "Copied blocks..." to "Dragged blocks..."

**Comment by bromagosa** [comment]
This has been fixed at some point during these last 5 years.
