### ISSUE TITLE
Passing function into "number" input type should try parse value to number

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#458]
I came across this problem:

![parsetonumber](https://cloud.githubusercontent.com/assets/7092949/3103366/6a458068-e655-11e3-8093-c26be0f49d1b.png)

Because passing function into "number" input type doesn't parse it's returned value to number, you can <b>NOT</b> be sure that value is used as number everywhere. It is confusing especially if you passed through condition <code>"is %value a number?"</code>

![parsetonumber2](https://cloud.githubusercontent.com/assets/7092949/3103420/3dc194d6-e656-11e3-8007-3133acacf443.png)

**Comment by bromagosa** [comment]
Closing because this now reports false:
![imatge](https://user-images.githubusercontent.com/1016697/51083989-2c894a80-1723-11e9-9270-7f9a081309a6.png)
