### ISSUE TITLE
Importing Text files with different extensions

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#512]
_Snap!_ complains that it only knows who to support text files even if the file being imported is plain text, just with a different encoding. 

I just tried to import a `.json` file and _Snap!_ wouldn't let me. Of course, renaming a file to `.txt` works, but it seems like an unnecessary solution to the problem.

I thought this had come up before, but I didn't see anything...

**Comment by bromagosa** [comment]
Closing since .txt, .json and .csv work now. We also have "import anyway" so other cases are equally covered.
