### ISSUE TITLE
Nesting a sprite within itself should be disallowed.

### ISSUE THREAD

**Issue by xtitter** [jmoenig/Snap#514]
When she opens a project.  The resulting XML (from export project) is quite bare.

She has spent many hours on the project, and it was working without any errors just before this error.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=lroszko&ProjectName=big%20project    

(I added the %20 to the url above, but I don't think that is causing the problem.  She gave me http://shoutkey.com/occupy which has a space in the url, weirdly).

Any thoughts?  I'm going to share this issue URL with her (Lynda Roszko), so she can hopefully answer questions as necessary.

**Comment by bromagosa** [comment]
This is now implemented. You can't nest a Sprite via UI nor programmatically.
