### ISSUE TITLE
(Minor) Block context menus should have `add comment` function

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#520]
Sometimes I know precisely where I'd like to attach a comment. It'd be great if I can do that by right-clicking a block and have the comment immediately attached to that block.

**Comment by cycomachead** [comment]
Wooohoooo! It only took 6 years!!
https://github.com/jmoenig/Snap/commit/d05b9467006f9714de73175329e272930a925474

**Comment by jmoenig** [comment]
and I didn't even have to write it myself, b/c then it would've taken even longer 😂
