### ISSUE TITLE
Self-hosted Snap! cloud

### ISSUE THREAD

**Issue by Gubolin** [jmoenig/Snap#535]
I would like to host the Snap! cloud by myself. How can I do so?

**Comment by brollb** [comment]
In case anyone is still looking to host their own Snap! deployment, they could check out https://github.com/c2stem/snap-cloud.

**Comment by KingDavid12** [comment]
@brollb Is this implementation for the new cloud (dev version) or the old cloud?

**Comment by brollb** [comment]
Unfortunately, it is the old cloud. Do you know if there is an implementation of the new cloud available? Are you hosting your repo online somewhere?

**Comment by brollb** [comment]
Nevermind. I found it: https://github.com/bromagosa/snapCloud

**Comment by KingDavid12** [comment]
@brollb That's not my implementation, but it is the implementation I based mine on.

**Comment by cycomachead** [comment]
That’s the new cloud, yep. Feel free to host it yourself, though it would be interesting to hear specific use cases.

**Comment by bromagosa** [comment]
And take in account it's still in active development. Remember to keep your fork in sync :)
