### ISSUE TITLE
"Unshare" button replaces "Save" and "Open" buttons in dialog windows

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#560]
In GIF I mixed up two ways how to replace "Open" or "Save" buttons with "Unshare" button. Also "Unshare" button is clickable and asks user if he wants to unshare for example offline (browser) project. Duration: 0:37
![unshare_button](https://cloud.githubusercontent.com/assets/7092949/3859832/32a29d3e-1f1d-11e4-8b77-20ab762e7dcd.gif)

<b>EDIT:</b> changing language or zooming blocks shows "Unshare" button too. Its problem of dialog windows but I think that this can be fixed.

**Comment by bromagosa** [comment]
This has been magically fixed :)
