### ISSUE TITLE
Import issues with Firefox

### ISSUE THREAD

**Issue by julius90** [jmoenig/Snap#577]
I have a problem with the import of a self-made projekt in Firefox. It contains new created blocks with 50+ commands inside. If I want to import the xml-file I've got an script error in snap/morphic.js:1138. This problem occurs only in Firefox. I've tested it with Chrome, Opera and Internet Explorer and it works without any issues.
Maybe there are too many commands in the new created blocks but I'm very surprised that only in Firefox it doesn't work. The file is 1,75 MB large.
I hope that somebody can help me.

**Comment by bromagosa** [comment]
Closing cos OP could actually load the project in the end, and Firefox has changed so much in 4 years that this is most probably obsolete anyway.
