### ISSUE TITLE
Renaming a project is confusing

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#607]
It seems very confusing to rename a project when all I want to do is export an XML. (I actually couldn't find a way to do it without first saving to local storage or the cloud...)

Intuitively, I would just try clicking on the project title to rename it. (However, I think that might conflict with how Snap<i>!</i> saves files...?)

**Comment by bromagosa** [comment]
This is now a Snap! site / backend issue, and already implemented there :)
