### ISSUE TITLE
Attempt to hide variable reporter disallow user to show palette menu

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#646]
1. create variable via "Make a variable" button
2. right click on variable reporter -> choose 'hide'
3. right click onto palette -> menu with "find blocks..." and "hide primitives" should appear, but doesn't

![variablepalettemenu](https://cloud.githubusercontent.com/assets/7092949/5101446/08164c40-6fb9-11e4-8c54-87f1a9ccff07.gif)

**Comment by bromagosa** [comment]
Well, there's no "hide" option in vars context menu anymore, so this bug is gone :)
