### ISSUE TITLE
Duplicated comment can hang anywhere in Snap and comments aren't transferable to another sprite

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#670]
1) hang everywhere
2) visible in presentation mode

gif duration: 26 sec
![comment](https://cloud.githubusercontent.com/assets/7092949/5388840/c1075696-80f2-11e4-977e-9588abfc6264.gif)

3) comments can't be transfered to another sprite (it does not matter if it's original or duplicate). Because we can copy text content in Snap!, I would like to transfer comments -- as I can do with blocks

**Comment by jmoenig** [comment]
Jeez! How could I not notice this for so long!
This needs to be fixed... NOW :-)
