### ISSUE TITLE
'Obsolete!' reporter, which does NOT return value, freezes Snap!

### ISSUE THREAD

**Issue by studej** [jmoenig/Snap#679]
![obsolete_freeze](https://cloud.githubusercontent.com/assets/7092949/5561904/7167ade2-8dfa-11e4-8f3c-09b0bb1a7a88.png)

I think that it should return at least nothing (<code>''</code>), because we have cases when some reporter reports this (e.g. <code>answer</code> reporter reports <code>''</code>) and no problems appear.

I fixed it, but it is dirty fix (that's why I didn't create pull request) to just find a problem
In <code>threads.js</code> I added new process:

```
Process.prototype.reportNothing = function () {
    return '';
};
```

and then in <code>store.js</code> I changed piece of code which begins with line 1014
from:

```
var block = isReporter ? new ReporterBlockMorph()
            : new CommandBlockMorph();
block.selector = 'nop';
```

to:

```
var block;
if(isReporter){
    block = new ReporterBlockMorph();
    block.selector = 'reportNothing';
}
else{
    block = new CommandBlockMorph();
    block.selector = 'nop';
}
```

**Comment by bromagosa** [comment]
Not an issue anymore:

![imatge](https://user-images.githubusercontent.com/1016697/51084009-72dea980-1723-11e9-8df2-f6923ce0da5d.png)
![imatge](https://user-images.githubusercontent.com/1016697/51084013-7d00a800-1723-11e9-8dc5-bada87e2c002.png)
