### ISSUE TITLE
list watcher containing costumes, bug

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap#682]
When you create a list variable and store costumes in it using the "wardrobe" block, the watcher doesn't show the images when you open the project.
That 's what you get
![bug](https://cloud.githubusercontent.com/assets/8059587/5577324/860de634-9017-11e4-9ee9-2aa116e2b7a4.jpg)
when you should get this.
![correct](https://cloud.githubusercontent.com/assets/8059587/5577328/99a810ca-9017-11e4-986c-acd72371206c.jpg)
The problem appears only in the watcher. Everything else works ok(e.g. speech bubbles).

P.S 1: The "wardrobe" and especially the "javascript fucntion" blocks are amazing.
P.S 2: Happy New Year to all.

**Comment by cycomachead** [comment]
Just saw this, but this is a known issue with the wardrobe block, which is partially why it's still in dev mode. :)

**Comment by jmoenig** [comment]
Oh my Gosh, how could I forget all about this. This needs to be fixed for 5.0. Self-assigning this to make it a priority.
