### ISSUE TITLE
keypress UTF-8 support

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#683]
Hi, I was trying make a simple typing game in spanish, but I found I can't use 'ñ' key or 'áéíóú' keys with the block "when key __ pressed". I tried to export and download the XML project with another key, then I replace the line with the key and wrote 'ñ'. It opens well in Snap! Even 'ñ' appears in the block, but it doesn't work when I press the 'ñ' key  :-/

Any idea to solve this issue? 
It would be great if there was a way in javascript to detect the key you want to use in the block.

Thanks in advance.

**Comment by geaplanet** [comment]
In the "say" blocks I can't use 'áéíóú' either.

**Comment by studej** [comment]
<quote>
In the "say" blocks I can't use 'áéíóú' either.
</quote>
I can

**Comment by geaplanet** [comment]
What could be the problem then?

**Comment by studej** [comment]
1) Snap, and Scratch too, does not support those letters in "when key __ pressed" block.
2) I don't know why you can use it in "say" block :(, it works for me even with chosen english language

**Comment by geaplanet** [comment]
Sorry, it was only a browser problem. I had an old version (27) of Firefox. With the new versions the say block goes well and with Chrome too.

**Comment by geaplanet** [comment]
Sorry, I rectify what I say before.
- As say studej, "when key __pressed" block does not support those letters.
- Say block works with those letters in Chromium, BUT not in Firefox neither in others browsers like midori or xxxterm even based in webkit as chromium.

**Comment by studej** [comment]
Did you updated Firefox browser? Because I know that in this browser 'áéíóú' works perfecly.

**Comment by Gubolin** [comment]
This is somehow related to #387 and partially solved in #631. The `any key` hat combined with the `keys pressed` reporter responds to nearly any key.

**Comment by geaplanet** [comment]
My system: Ubuntu 14.04 64bits, Firefox 34, Chrome 39.

I'll give a try what gubolin says about pressed keys.

Thanks.

**Comment by introlinux** [comment]
At the end what happened with this old issue? Is the "last key pressed" block (commented by @Gubolin) in Snap or any other solution?

**Comment by cycomachead** [comment]
Support for this will be improved with the 'any key pressed' and key reporter coming in v7.
