### ISSUE TITLE
Run onload

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#684]
Is there any way to run a project directly without loading Snap interface?

**Comment by bb010g** [comment]
A node.js path would be nice. Package that with [node-webkit](https://github.com/rogerwang/node-webkit) and you're set for standalone Snap.

**Comment by cycomachead** [comment]
I think the problem is likely the `file:///` urls which are burdened by security issues. 

Node-webkit is probably going to be the best way to package things offline

**Comment by jmoenig** [comment]
no, seriously. use #run: and then the raw project data (not the filename or path). That totally works offline.

**Comment by geaplanet** [comment]
What do you mean with "the raw project data"? Could you give an example?
Thanks.

**Comment by Gubolin** [comment]
You can get the raw project data when you export your project.

Apart from that, #575 "Distribute offline versions of Snap! for desktop and mobile" is related. In this pull request I added a node-webkit build script. A minification is included, you can let the script build a modified version of Snap! that is smaller in size and runs your project instantly in a presentation-like mode.

**Comment by geaplanet** [comment]
Wow! Gubolin, it sounds really interesting.

**Comment by jmoenig** [comment]
yes, @Gubolin , this *is* really cool. At some - not too distant - point I want to meet you in person and discuss how we can unify your impressive pioneering developments with similar parallel ones (e.g. by @bromagosa at the CitiLab). Let's make that a New Year's intention :-)

**Comment by brianharvey** [comment]
> I want to meet you in person
+1!  Is there a European Scratch Conference this year?

**Comment by bromagosa** [comment]
I've had an idea lingering in my head for a while, and the more I see how
much Snap is being used worldwide the less crazy it seems... what do you
guys think about a SnapConf in 2015? Is it too soon?

**Comment by brianharvey** [comment]
> SnapConf in 2015
I'm in!  :-)  One issue is that much of our team consists of starving students, or even more starving high school teachers, and so we'd have to think about fundraising for travel scholarships.
We should probably take this discussion to the forum.

**Comment by jmoenig** [comment]
Joek is trying to organize a European Scratch Conference in Amsterdam in August this year (2015), he's asked me to "be on the team" and he's currenty trying to secure some funds. We should know more by the end of Jan.

**Comment by cycomachead** [comment]
> I'm in! :-) One issue is that much of our team consists of starving students, or even more starving high school teachers, and so we'd have to think about fundraising for travel scholarships.
> We should probably take this discussion to the forum.

It's come up amongst others doing BJC work as well. I think it would be amazing to get people together!

**Comment by introlinux** [comment]
I'm trying what @jmoenig  says, but I get this: http://goo.gl/fJDFaf
prueba.xml is the file exported (raw data in xml), it's in the same folder where Snap is.
What's wrong?

**Comment by introlinux** [comment]
I'm very interested in this topic, is it possible run a game directly bypassing the Snap environment or not?

**Comment by jmoenig** [comment]
You can currently directly run a project that's been shared in the cloud, but the user can still switch to edit mode and also hit the stop button. Very soon, however, we'll have options that allow you to run a Snap project in a "locked" mode. Hang on!

**Comment by introlinux** [comment]
Thanks, @jmoenig, for your answer. Is there any plan for doing that offline too, as @geaplanet said at the beginnig of the thread?

**Comment by jmoenig** [comment]
offline is currently a technical problem with HTML5 (not just in this respect), so it's not on my list of short-term expectations.

**Comment by introlinux** [comment]
:_-(
Ok, is there any alternative? Would be possible prepare a web server locally for loding games in a PC without internet?

**Comment by bromagosa** [comment]
@introlinux either that, or using nw.js to run Snap! as a desktop app.

Also, I'm currently tutoring a student who's building a "Snap! bundler" as a final project for his bachellor's degree that will allow you to turn any Snap! project into a standalone desktop app. So far it's looking quite good, and we should have results to show before this summer! :)

**Comment by introlinux** [comment]
@bromagosa it would be terrific. I'll be tunned, where can we see news of that proyect? here in github?
On the other hand, I'm not sure that using nw.js solve the problem, we don't want to run Snap offline or as an application only (that's easy, you download sources, run the snap.html and that's all) but that Snap accept a local file as a parameter to directly execute a game in presentation mode.

Is there any information on what features should have a server for running Snap?

**Comment by bromagosa** [comment]
@introlinux you can load a file by using ```#run:``` as @jmoenig said. Just point to the relative path of that file, like ```#run:examples/vee.xml```. Anyway, I'm afraid that won't work if you just "run" the ```snap.html``` file, you'll need either to serve it somehow or use nw.js...

That project is not yet published, but I'll let you know when it is :)

**Comment by introlinux** [comment]
@bromagosa, your clue solved my problem. I run "python -m SimpleHTTPServer" in the Snap folder as @geaplanet commented, then I launched firefox with http://localhost:8000/snap.html#run:mygame.xml
And it worked. I'm stupid, I was launching snap.html locally.

**Comment by nathalierun** [comment]
Hello,

I have the same sort of problem. I want to make a demo of edgy with a project already insode like that :

**Comment by introlinux** [comment]
@nathalierun Wow! What's atlas.xml? O_O?
I can say you what I did to see your proyect atlas.xml offline:
- I downloaded edgy zip from [github](https://github.com/snapapps/edgy)
- I decompresed the file in a folder.
- I downloaded the [atlas.xml file](http://www.snap-apps.org/uploads/4/8/6/0/48600729/atlas.xml) into edgy folder.
- In the edgy folder I opened a terminal and run: python -m SimpleHTTPServer
- Then, I opened Firefox/Chrome with this URL: http://localhost:8000/edgy.html#run:atlas.xml

**Comment by nathalierun** [comment]
Fantastic !
Thank you very much.

2016-06-13 18:08 GMT+04:00 Antonio Sánchez <notifications@github.com>:

**Comment by bromagosa** [comment]
This was solved a long time ago by the Snapp! project packager, and more recently with the offline version.
