### ISSUE TITLE
Minor: Relabeling Blocks Improvements

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#699]
Would the following relabeling updates be considered useful:
- allowing `round` and the `sqrt`blocks to be relabeled with each other

These new two are a bit unconventional, but I think it would be really helpful to be able to:
- `letter of` <--> `item of`
- and `length of` (word) <--> `length of` (list)

I have a pull-request ready if this sounds like a good idea.

**Comment by studej** [comment]
And what about relabeling all hat blocks? Currently you can relabel only `when flag is clicked` with `when I am clicked` (why?)

**Comment by cycomachead** [comment]
Hat blocks would be good to add as well and would be very doable.

**Comment by brianharvey** [comment]
I'm not exactly *against* this idea, but I'd rather add 'round' to the pulldown in the sqrt block, and make the two length blocks be synonyms with the union of the two domains.  Letter vs. item seems less useful to me, but I don't hate it.  (I bet Jens will, though.)  Hat blocks, maybe.

**Comment by cycomachead** [comment]
Round to the pull down makes sense to me as well. 

> make the two length blocks be synonyms with the union of the two domain

They do work like that now (at leas the green one accepts lists), the problem is that it gets confusing as to what's a list and a sentence. 

The letter and item of blocks are handy for when students switch implementations from using strings to lists and vice versa which does happen.

**Comment by cycomachead** [comment]
The big cases of this one have been addressed.
