### ISSUE TITLE
Snap! Can't Open Files / Saving Issues to XML

### ISSUE THREAD

**Issue by lmock** [jmoenig/Snap#749]
Lots of students are having issues exporting their projects to XML files on multiple browsers (chrome, firefox, IE). And some can't even open their projects on other browsers (i.e. Firefox, IE, Safari). Here's one --

http://snap.berkeley.edu/snapsource/snap.html#present:Username=junlee1204&ProjectName=project

I've tried to save it as an XML and got this issue --

![capture](https://cloud.githubusercontent.com/assets/5467107/6768184/e5a9b338-d019-11e4-8b21-d29368a7f390.JPG)

**Comment by lmock** [comment]
Here's another one:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=ypkao&ProjectName=StayingAfloat_YipingKao_JoanaSean.xml

**Comment by lmock** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=hberris&ProjectName=Midterm%20Project%20Final%20

**Comment by lmock** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cs10project&ProjectName=color%20to%20sound

**Comment by lmock** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=addison&ProjectName=CS10%20Project

**Comment by jmoenig** [comment]
Okay, this is a serious issue.

I *was* able to export each of these project using Firefox, and to reopen and play it it Chrome. Interestingly "save to disk" often did not save the complete project in Firefox - apparently the damn thing just yields when it isn't supposed to (i.e. in the middle of a function, geez) - so I had to use "export", and *that* worked.

These projects are rather large:

* "project" - 21.7 MB
* "CS10 Project" - 22.2 MB
* "midterm project 1" -  33.8 MB

even

* "Color to sound" - 6.9 MB
* "Staying Afloat" - 4.9 MB

And they do import and implement zillions of blocks each and thus have zillions of scripts, many of which are extremely large and long (spanning several screens for a single script).

All of this is just an observation, though, and doesn't mean to put any blame on the students. We've got to get saving to work better, even for giant projects such as many of these are.

I noticed that saving to the cloud apparently worked in all cases. So maybe we can just add an option to download a project directly from the cloud to disk (a download link url)...

**Comment by cycomachead** [comment]
> I noticed that saving to the cloud apparently worked in all cases. So maybe we can just add an option to download a project directly from the cloud to disk (a download link url)...

This would be really beneficial as a work around, since getting files from a server has no problem.

Some of these crashed the web process when I opened in Safari which was unexpected, but that may be related to other issues.

**Comment by bromagosa** [comment]
okay... so I've tested my solution with large projects and it still doesn't work in Chrome :(

**Comment by jmoenig** [comment]
Bummer. I hate Chrome...

**Comment by cycomachead** [comment]
Has anyone tried a solution with the `Blob()` API?

**Comment by Logalicioustuff** [comment]
May sound dumb, but what exactly is the "Save to Disk" option support to do? I only use Safari and it only opens it as the XML in the same window, although the "Export Project" does the same, so probley not intended. :-)

**Comment by jmoenig** [comment]
"Save to Disk" *should* work on all browsers, but is currently unsupported by Safari and - I believe - IE.

**Comment by cycomachead** [comment]
When it works, the save to disk option creates a project XML in the browser's Downloads folder, without ever showing the XML or requiring additional clicks.

Here's where it's currently supported: http://caniuse.com/#feat=download

**Comment by 2002R** [comment]
hello there
I'm facing the similar problem in importing,  and exporting I did it using Baidu browser! can't I do both operations with one browser??
