### ISSUE TITLE
Is flicker-free pen clear/redraw possible? (Ugly event queue hackery)

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap#774]
Trying to draw a characters animated limbs with pen draw commands.
So I have to do a 'clear' every frame.

But that (usually) produces flicker, due to lack of synchronization with frame buffer swap (if there even IS one).

Oddly enough, I was able to hack the event queue, and somehow sending TWO redraws from two different 'forever' loops produces a smooth, non-flicker animation.... but I don't know why!

I experimented quite a bit with order of 'broadcasts', calling from Sprites versus Stage.
Can't document all the variants, but maybe you could play with the code inside the 'redraw' Sprite of this project, and tell me what's going on.

This link should draw smoothy (though maybe not on your machine?)... but if you swap the order of commands a bit, you'll get flicker from the repeated pen 'clear' command...

http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=ayeager

Or tell me the proper way to sync pen clear/redraw with frame buffer?

Thanks!

**Comment by jmoenig** [comment]
This is an interesting issue, in which receiving a "broadcast" in Snap behaves slightly different than in Scratch. 

In Scratch clearing the pen trails and *broadcasting* "redraw" within the same atom would also trigger and perform the *"When I receive 'redraw'"* scripts within that same atom (display frame). As a result, however, the *"When I receive 'redraw'"* scripts would never light up in the scripting pane (try it!), and you wouldn't be able to ever see them running, even though they running all the time. I consider this to be a bug / design fault in Scratch's scheduler.

In Snap, *receiving* a broadcast happens at the *next* atom (display frame). That way, the receiving script gets a chance to "light up", and hence the flicker you observe.

If you want to force something to happen at the exact same time or within the exact same display frame you cannot use broadcast in Snap, but you *can* use ```RUN``` and directly invoke the redraw scripts in other sprites.

l've slightly edited your project to demonstrate how you can do this:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=ayeager

**Comment by deader69** [comment]
Awesome! 
Need more time to ponder all this, will have probably a few follow-up questions... if you can keep this topic 'open'.
Maybe incorporate this info in the manual, and/or examples/tutorials? This project itself might become a good demo eventually... I'm thinking of turning this into a dancing-guy app, where the user can slide the hands/body/feel around, record keyframes, then 'dance' by 'gliding' the body parts from one keyframe to the next.

For now I'll just say Thanks!
