### ISSUE TITLE
Virtual keyboard doesn't work on Android

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap#81]

**Comment by ToonTalk** [comment]
I discovered today that [this patch](https://gist.github.com/swiperthefox/48996720c0e82b3d02560188a4b5006f) for enabling IME (e.g. Chinese input) also fixed the problem with input in Snap! on Android. See pull #2322 for details.

**Comment by jmoenig** [comment]
Thanks, @ToonTalk , that's a very valuable argument. I'll look into this issue next week when 5.0 is out. Supporting all languages for input is really important.

**Comment by jmoenig** [comment]
the issue of entering text into input fields on Android has now been resolved as of https://github.com/jmoenig/Snap/tree/v5.0.6
Thanks, everybody, who was involved in addressing this issue!
