### ISSUE TITLE
<touching [aColor]?> is really slow

### ISSUE THREAD

**Issue by bromagosa** [jmoenig/Snap#846]
Here's a minimal example:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=touching%20color%20performance

Now that clones are fast (yay!) we were trying to translate an old Scratch project that has 50 clones representing bacteria, and we need to check for color collisions. This block is way too slow though, rendering the program unusable.

See it here (unfinished): http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=infection

Maybe @nathan, aka The Optimizer, can shed some light here? I've tried applying some of your suggestions in code related to color collisions, and performance improved just very slightly...

**Comment by ddgarcia** [comment]
My memory was that Jens' mentioned touch color was slow but touch sprite was fast, so if there was any way to recode it that way, you'd see a performance jump.  (This was relevant for my conversion of Scratch's "Marble Racer" -- one of my favorite projects -- to Snap!)

**Comment by bromagosa** [comment]
Hi Dan! You're right, but in this case we really need to test for colors, as they define whether a bacteria is sane or sick...

Besides, since we're working with clones, there is no way to check whether a particular clone is touching another one (or is there? that'd fix it...).

**Comment by jmoenig** [comment]
Color touching is expensive and problematic - among other things because of anti-aliasing. The idea is to replace it with nested sprites and sprite collision detection. That's also the approach we're exploring for GP.

Clones cannot (at this time) sense collision with their own likes. However, *other* sprites *can* sense collision with any clone of a breed by checking for the original (cloned) sprite name.

**Comment by liam4** [comment]
I wonder if in Snap! 4.1 we'll get something like..

```
([clones v] touching (object))
([sprites v] touching (object))
([clones and sprites v] touching (object))
```

**Comment by brianharvey** [comment]
Hi, fancy meeting you here!  :-)

No, in 4.1 clones are no different from other sprites, except that they have a nonempty PARENT attribute.  So you could

KEEP ITEMS SUCH THAT <<ASK __ <TOUCHING? (object)> AND <(ATTRIBUTE PARENT __) IS A [SPRITE]>> FROM (SPRITES)

**Comment by SMSARVER** [comment]
Thank you so much! I was making a platformer with the color block and it lagged so much. I tried using the touching sprite block and everything worked so much faster!

**Comment by bromagosa** [comment]
Nice to see this fixed 4 years later! :smiley:
