### ISSUE TITLE
Logging in to Cloud while displaying the Cloud projects dialog should refresh it.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#861]
Snap<i>!</i> will warn you if you aren't logged in when trying to save a file, but then when you successfully log in -- the Cloud tab of the Open/Save dialog doesn't get refreshed. The user has to click to another tab, then back to the Cloud to see projects.

**Comment by jmoenig** [comment]
right. You can also just click on the cloud tab again (no need to first tab to another source).

**Comment by cycomachead** [comment]
> You can also just click on the cloud tab again (no need to first tab to another source).

Hmm, I thought I tried that before and didn't see an update.
