### ISSUE TITLE
Saving a Project when opened from a shared URL is confusing.

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#862]
When you save a project that already has a name the only info shown is the word "Saved".

This is confusing because it's not clear where the project is being saved - it could be either to the cloud or to the user's local storage.

Secondly, the sharable URL stays in the menu bar -- this is a little weird because it's no longer accurate to the project being worked on.

What I'd like to improve:
1. The message should be "Saved `project name` to the `location`."
2. When a shared project is saved, the cloud user should be compared to the url, and if they don't match, the URL should be removed. Similarly, if the project is being shared to local storage, the the URL should be removed.

**Comment by jmoenig** [comment]
Those are good suggestions, I agree.

**Comment by cycomachead** [comment]
I just implicitly fixed the URL issue with 6.9.1 -- the confusion is pretty much gone because, hey, you're always saving to cloud. 😁
