### ISSUE TITLE
Color and Shade problem - When changing shade to 0, resets color to 0

### ISSUE THREAD

**Issue by millike** [jmoenig/Snap#877]
I was working with color and shade trying to explain how the numbers work to teachers for bjc. 
![colorworks](https://cloud.githubusercontent.com/assets/5317373/8780029/7730cb8e-2ed4-11e5-8605-0d86ca48fc9e.png)
That's an example of my code to make the color number change so they understand how to numbers work. I also made other picture examples so they understand the shade. 
![image](https://cloud.githubusercontent.com/assets/5317373/8780078/be675a0e-2ed4-11e5-8fce-5651606b4ecd.png)
![image](https://cloud.githubusercontent.com/assets/5317373/8780086/c3852a5c-2ed4-11e5-8140-9ead84eabeed.png)
![image](https://cloud.githubusercontent.com/assets/5317373/8780093/c8ada9f0-2ed4-11e5-9cfc-67b9ca8c8592.png)
![image](https://cloud.githubusercontent.com/assets/5317373/8780095/cbe8d68a-2ed4-11e5-9dbf-dad28532724f.png)
Each time the shade is changed by 25 so they can see how the shade works. 
I was going to create an exercise for the teachers to do - I wanted them to print each color as an ombre. First line, ombre (simple only in four steps) of dark red (black) to bright red. Second line, the orange..etc. But, when I to try make it do that, it messes up and only uses the color red. 
![image](https://cloud.githubusercontent.com/assets/5317373/8780350/6ed8bb02-2ed6-11e5-860a-e035039b1b3f.png)
I tried hard coding this as well...
![image](https://cloud.githubusercontent.com/assets/5317373/8780383/97faf0b8-2ed6-11e5-94b4-a39646b55805.png)
But I got the same problem
![image](https://cloud.githubusercontent.com/assets/5317373/8780389/a3b56e6a-2ed6-11e5-8943-54b1867cba54.png)
My guess is when the shade is reset to 0 in the loop (in order to start with the darker color and increase shade to the lighter color for each row), the set shade to 0 also reset the color to 0..? But I could be wrong.

**Comment by jmoenig** [comment]
yep, that's a bug. In my code it says:

```javascript
    hsv[1] = 1; // we gotta fix this at some time
```

Let me see whether we can just remove that line...

**Comment by jmoenig** [comment]
this has been fixed since for the upcoming Snap5. Closing thanks!
