### ISSUE TITLE
Allow users to query the state of many things (pen state, show/hidden, layers)

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#884]
I realized when I wanted to write a stateless "Draw Square" routine (remembers current pen state, puts pen down, moves in a square, and puts pen back in the state it started), that I had no way to query the current pen state.  I think we should provide watcher variables for every piece of internal state of Snap!

**Comment by jmoenig** [comment]
yep, that's right. Anything, really, getting and setting... coming in 4.1!

**Comment by bromagosa** [comment]
As a workaround, you can always do that by using Javascript:

![image](https://cloud.githubusercontent.com/assets/1016697/8871446/a52baf80-31f5-11e5-9965-2df0e5a0d614.png)

Then you could wrap those in reporter blocks to make them friendlier.

**Comment by bromagosa** [comment]
@brianharvey, doesn't your Eisenbergification library take care of this?

**Comment by brianharvey** [comment]
It will, when I update it to include sprite-specific things.  Jens wouldn't let me do that until OOP was done because it changed lots of sprite data structures.  Thanks for reminding me!

**Comment by ddgarcia** [comment]
Thanks, Brian. I seem to remember that there was a discussion about where it should go. The advantage of putting it under "my" is that it's all in one place and doesn't need to be loaded with a library, but it's in sensing where people probably won't look for it. The advantage of a library called "Pen getters" is that new green blocks appear where people would normally be looking for them. The third idea is not to have them in a library but in vanilla snap, but that means there's more blocks to load at default runtime, etc.

**Comment by jmoenig** [comment]
happy to say it only took n years :-)
