### ISSUE TITLE
Deleting a variadic rigned input leaves an extra ring lying around

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#885]
This is probably related (internally) to #843 

If you have a variadic input that is a ringed input type, and you have an empty ring, removing an input slot pops out that ring and leaves it on the scriping area. 

Obviously, the default Snap<i>!</i> behavior to pop out exisiting content when removing inputs makes sense, but it would be handy if empty rings were treated differently when the input type is a ring. 
(I suppose you could also technically make it so that only reporter rings aren't kept if the input type is a reporter, but rings are so easy to make that it's not a big deal if an empty reporter ring disappears when the input type is variadiac predcate rings)

**Comment by jmoenig** [comment]
yeah, it's hard to tell whether the ring is the "original" slot or something the user put there...

**Comment by cycomachead** [comment]
From playing around with things, my intuition is that empty rings would just be automatically removed from the stage when popped out, at least as long as the input type is a ring. This could also apply to changing block specs like #843 mentions. In the empty ring case, I don't expect any users would notice a difference in behavior.

**Comment by jmoenig** [comment]
this has since been fixed. Thanks! Closing...
