### ISSUE TITLE
Pen Color Help Screen is Incorrect

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#897]
When I use "set pen color to" the following numbers give the respective colors

130 gives red
70 gives blue
30 gives green

which is not what I read to be the case in the help on that block.
Also is there a number that will make the pen black?

**Comment by jmoenig** [comment]
works for me, see

  http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=Colors

setting the pen shade to 0 will make any hue black.

**Comment by jcaldw737** [comment]
Thanks so much for your rapid and thorough response at such a late  hour too!
Below is a link to the problem I am having.  When I execute the blocks on this project I don't get the colors I am expecting from the help on two of them and from experience with BYOB on the other.
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jcaldw126&ProjectName=Pen%20color%20question

**Comment by cycomachead** [comment]
For @brianharvey 

Looking at this again, the Colors in Snap<em>!</em> are fine, but the help screen is definitely wrong.

Colors in Snap<em>!</em> go from 0-100, but the help screen is old, from BYOB.

Tag #893 Because really RGB is better :P Also #332

**Comment by jcaldw737** [comment]
Thanks for the explanation, it really helps!

**Comment by cycomachead** [comment]
I'll leave this open until we fix the help screen. :)

**Comment by ToonTalk** [comment]
I could find no documentation for pen color numbers in SnapManual.pdf - I searched for the word 'color'.

**Comment by brianharvey** [comment]
Our color numbers are 1/2 the corresponding Scratch color number (0-100 instead of 0-200).  We're talking about this on another thread; it'll all get settled one way or another soon I hope.

**Comment by jmoenig** [comment]
colors and their help screens have since been redone. Thank! Closing...
