### ISSUE TITLE
tamil language use throws error

### ISSUE THREAD

**Issue by K0T3R** [jmoenig/Snap#953]
If I use snap to switch language to "Tamil". I get the following error:

Load failed:TypeError: Cannot read property 'add' of undefined.

![image](https://cloud.githubusercontent.com/assets/7160418/10120036/4a103940-645e-11e5-903d-98c55d80724c.png)

Thanks for the great software!

**Comment by cycomachead** [comment]
Can you try on a new project / Snap<i>!</i> window?

If you saved that project, can you re-open it and see if there's an error? I think this error is unrelated to switching the language.

**Comment by K0T3R** [comment]
I tried switching the language and then opening the project. Same error.

No error if I do not switch the language.

Please tell me if I can do anything in my end to help reproduce this bug.

**Comment by cycomachead** [comment]
@K0T3R Has this happened again?

Can you share the project if you still have it?

**Comment by K0T3R** [comment]
Hi Michael,

Yes - I still see this issue today :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=k0ush1k&ProjectName=tutorial

Steps to reproduce:
Open the project, go to development mode and change language to Tamil.

Thanks
Koushik

**Comment by cycomachead** [comment]
Weird, I do see it now. I'll try to take a look, but this seems odd.

**Comment by Barthdry** [comment]
Any way can you check the New tamil specification or new tamil language
