### ISSUE TITLE
Pen color is red for all negative values + pen shade doesn't exceed 50%

### ISSUE THREAD

**Issue by Zro617** [jmoenig/Snap#991]
Here's what happens when pen color changes by a negative amount:
![snap_color_issue1](https://cloud.githubusercontent.com/assets/11638093/10839189/b9366b78-7e9e-11e5-8bc6-1f131c4786d1.png)
As you can see, it's just red everywhere. In Scratch, the hue cycle would simply wrap back to violet, blue, cyan, and so on.
Here's what happens when pen color changes by a positive amount:
![snap_color_issue2](https://cloud.githubusercontent.com/assets/11638093/10839190/b93aa0b2-7e9e-11e5-91d6-df0179ba815e.png)
The pen color changes as one would expect. Though as you may also notice, pen shade doesn't seem to change anymore after about halfway.

**Comment by jmoenig** [comment]
fixed in Snap5
